### ISSUE TITLE
After updating H5utils when trying import meep I get Import error

### ISSUE THREAD

**Issue by emtiyl** [NanoComp/meep#1015]
https://github.com/NanoComp/meep/issues/739#issuecomment-466576634

I update H5utils using conda update -c chogan h5utils this command .

after updating when I try to use import meep as mp
I'm getting an error 
![image](https://user-images.githubusercontent.com/31549451/64617437-24cf9200-d3e7-11e9-85ee-be2e25ed8581.png)

**Comment by ChristopherHogan** [comment]
The `chogan` channel is no longer supported. Please use the `simpetus` channel for nightly builds, as described in the [docs](https://meep.readthedocs.io/en/latest/Installation/#nightly-builds).

**Comment by emtiyl** [comment]
![image](https://user-images.githubusercontent.com/31549451/64694366-2dd16980-d4a2-11e9-809c-97c94d0a9ca6.png)
After using simpetus I'm getting invalid colormap file error.

**Comment by tseberso** [comment]
Having same errors

**Comment by ChristopherHogan** [comment]
This will be fixed once conda-forge/h5utils-feedstock#14 is merged.

**Comment by ChristopherHogan** [comment]
The h5utils conda package has been updated. This should be resolved.

**Comment by junyi-lee** [comment]
I tried updating h5utils on both conda-forge and simpetus but still got the invalid colormap error (meep imports fine though). 

$ h5topng -t 0:332 -R -Zc dkbluered -v -a yarg -A eps-000000.00.h5 ez.h5
Using colormap "dkbluered" in file "/home/xxx/miniconda3/envs/meep/share/h5utils/colormaps/".
h5topng error: invalid colormap file

However the files are in the directory:
~/miniconda3/envs/meep/share/h5utils/colormaps$ ls
BrBG  autumn   bone       cool    dkbluered  gray   hot  inferno  lines  prism   summer  viridis  yarg
RdBu  bluered  colorcube  copper  flag       green  hsv  jet      pink   spring  vga     winter   yellow

The conda list is as follows:
![CondaList](https://user-images.githubusercontent.com/52336033/70154057-d6324b00-16ea-11ea-8ae5-2378436a2214.png)

and which gives
$ which h5topng
/home/xxx/miniconda3/envs/meep/bin/h5topng
