### ISSUE TITLE
get_field_point for 2d cell with non-zero kz and special_kz=True

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#1018]
(re: @stevengj's question in #1010:[comment](https://github.com/NanoComp/meep/pull/1010#issuecomment-528522428)).

When calling `get_field_point` in the case of a 2d cell with non-zero k<sub>z</sub> and `special_kz=True`, the ratio of the fields at any two points *outside* the cell along a line in the *z* direction should be defined by their relative phase difference exp(ik<sub>z</sub>*d*) where *d* is the separation distance.

However, as demonstrated in the following example, the value returned by `get_field_point` for two *different* points separated in *z* is the *same*. This is unexpected.

```py
import meep as mp
import math

resolution = 30 # pixels/um                                                                          

cell_size = mp.Vector3(14,14)

pml_layers = [mp.PML(thickness=2)]

geometry = [mp.Block(center=mp.Vector3(),
                     size=mp.Vector3(mp.inf,1,mp.inf),
                     material=mp.Medium(epsilon=12))]

fsrc = 0.3  # frequency of eigenmode source                                                          
bnum = 1    # band number of eigenmode                                                               
kz = 0.2    # fixed out-of-plane wavevector component                                                

sources = [mp.EigenModeSource(src=mp.ContinuousSource(fsrc),
                              center=mp.Vector3(),
                              size=mp.Vector3(y=14),
                              eig_band=bnum,
                              eig_parity=mp.EVEN_Y,
                              eig_match_freq=True)]

sim = mp.Simulation(cell_size=cell_size,
                    resolution=resolution,
                    boundary_layers=pml_layers,
                    sources=sources,
                    geometry=geometry,
                    symmetries=[mp.Mirror(mp.Y)],
                    k_point=mp.Vector3(z=kz),
                    special_kz=True)

sim.run(until=50)

d = 3.5
ez1 = sim.get_field_point(mp.Ez, mp.Vector3(2.3,-5.7,4.8))
ez2 = sim.get_field_point(mp.Ez, mp.Vector3(2.3,-5.7,4.8+d))

print("field:, {}, {}".format(ez1.real,ez2.real))
print("phase:, {}, {}".format(ez2.real/ez1.real,math.cos(2*math.pi*kz*d)))
```

```
Using MPI version 3.1, 1 processes
-----------
Initializing structure...
Halving computational cell along direction y
time for choose_chunkdivision = 0.000809389 s
Working in 2D dimensions.
Computational cell is 14 x 14 x 0 with resolution 30
     block, center = (0,0,0)
          size (1e+20,1,1e+20)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (12,12,12)
time for set_epsilon = 0.114979 s
-----------
MPB solved for omega_1(1.03923,0,0) = 0.320023 after 17 iters
MPB solved for omega_1(0.967463,0,0) = 0.30002 after 8 iters
MPB solved for omega_1(0.967391,0,0) = 0.3 after 4 iters
MPB solved for omega_1(0.967391,0,0) = 0.3 after 1 iters
run 0 finished at t = 50.0 (3000 timesteps)
field:, -0.00029456639310736254, -0.00029456639310736254
phase:, 1.0, -0.30901699437494756
```

In fact, `get_field_point` *always* returns `-0.00029456` regardless of its *z*-component. This would indicate that the *z*-component of `k_point` is just being ignored.

**Addendum**: results for `special_kz=False` (i.e., 3d cell) are exactly as expected.

**Comment by stevengj** [comment]
Yes, `get_field_point` should definitely be fixed.   There is probably also a similar problem in get_array_slice and similar (due to `loop_in_chunks`)

**Comment by stevengj** [comment]
In particular, for `get_field_point` we need to update `locate_point_in_user_volume`

**Comment by stevengj** [comment]
A basic problem here is that if the volume is 2d (`D2`), then the C++ code normally does not even *look* at the z component of a `vec`.  (The good news is that the `vec` class initializes the other components to zero, so it should be safe to look at them.)   In particular, the Python and Scheme front ends do not even *pass* the z component to C++ if it is a 2d cell.

**Comment by stevengj** [comment]
I'm guessing that, for the same reason, if you ask for a 3d slice of a 2d simulation, it just gives you a 2d slice.
