### ISSUE TITLE
Disabling subpixel averaging doesn't always work.

### ISSUE THREAD

**Issue by kitchenknif** [NanoComp/meep#1023]
Setting `eps_averaging=False` when initializing a Simulation object doesn't always prevent meep from running subpixel averaging. 

e.g. 

```
import meep as mp

resolution = 100  # pixels/um

fcen = 1.5
df = 1

sx = 1.3
sy = 1.3
sz = 0.8
cell_size = mp.Vector3(sx, sy, sz)

Background = mp.Medium(index=1.)
GaP = mp.Medium(epsilon=10.)

def material_function(vec):
    if vec.x * vec.y * vec.z > 0:
        return GaP
    return Background

boundary_layers = [mp.PML(0.1)]

source = [mp.Source(mp.GaussianSource(fcen, fwidth=df), component=mp.Ex,
                             center=mp.Vector3(0, 0, 0),
                             amplitude=1)]

sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size,
                    boundary_layers=boundary_layers,
                    material_function=material_function,
                    dimensions=3,
                    sources=source,
                    split_chunks_evenly=False,
                    eps_averaging=False,
                    )

sim.run(until_after_sources=[10])
```

Runs subpixel averaging (though not always - which on its own is already strange).

Is this expected behavior? 
Running meep built with commits up to 19f81a1

**Comment by oskooi** [comment]
Rest assured that subpixel smoothing is being turned off. See this [FAQ](https://meep.readthedocs.io/en/latest/FAQ/#why-doesnt-turning-off-subpixel-averaging-work
) for why it might appear that this is not the case.

Also, note that even when subpixel smoothing is disabled, Meep requires some non-trivial time to initialize the grid which can be relatively long (i.e., minutes) for a 3d cell with large resolution.
