### ISSUE TITLE
What exactly 'k_point' is in Meep?

### ISSUE THREAD

**Issue by mucahitdemir** [NanoComp/meep#1036]
Hello!
**In the project 'Angular Reflectance Spectrum of a Planar Interface' in Meep**
here is the project code;
https://meep.readthedocs.io/en/latest/Python_Tutorials/Basics/#angular-reflectance-spectrum-of-a-planar-interface
We could not understand what 'k_point' is and the purpose of them?
Here is the User Interface explanation which, still, we did not understand.
Thanks in advance.
![Screen Shot 2019-10-14 at 14 45 36](https://user-images.githubusercontent.com/43001724/66749024-672a3a00-ee91-11e9-86ac-4162fcb69a71.png)

**Comment by oskooi** [comment]
See the FAQ [How does the `k_point` define the phase relation between adjacent unit cells?](https://meep.readthedocs.io/en/latest/FAQ/#how-does-k_point-define-the-phase-relation-between-adjacent-unit-cells).

**Comment by mucahitdemir** [comment]
Hello! thanks!
