### ISSUE TITLE
Memory not freed up by Simulation

### ISSUE THREAD

**Issue by jeinarsson** [NanoComp/meep#1038]
Hi, I'm running many Meep simulations in a binary, serially, and am seeing memory leakage. A small example:
```
import os
import psutil
import meep as mp

def evaluate():
  # Code from examples/straight-waveguide.py, with resolution = 30.
  cell = mp.Vector3(16,8,0)
  geometry = [mp.Block(mp.Vector3(mp.inf,1,mp.inf),
                       center=mp.Vector3(),
                       material=mp.Medium(epsilon=12))]
  sources = [mp.Source(mp.ContinuousSource(frequency=0.15),
                       component=mp.Ez,
                       center=mp.Vector3(-7,0))]
  pml_layers = [mp.PML(1.0)]
  resolution = 30
  sim = mp.Simulation(cell_size=cell,
                      boundary_layers=pml_layers,
                      geometry=geometry,
                      sources=sources,
                      resolution=resolution)
  sim.run(until=1)

mp.quiet(True)
process = psutil.Process(os.getpid())
while True:
  evaluate()
  print(process.memory_info())
```

(Sample) Output:
```
pmem(rss=55906304, vms=2243817472, shared=17506304, text=47247360, lib=0, data=54673408, dirty=0)
pmem(rss=58003456, vms=2243817472, shared=17506304, text=47247360, lib=0, data=56770560, dirty=0)
pmem(rss=60100608, vms=2243817472, shared=17506304, text=47247360, lib=0, data=58867712, dirty=0)
pmem(rss=62197760, vms=2243817472, shared=17506304, text=47247360, lib=0, data=60964864, dirty=0)
pmem(rss=65789952, vms=2243817472, shared=18935808, text=47247360, lib=0, data=63062016, dirty=0)
pmem(rss=67887104, vms=2243817472, shared=18935808, text=47247360, lib=0, data=65159168, dirty=0)
pmem(rss=69984256, vms=2243817472, shared=18935808, text=47247360, lib=0, data=67256320, dirty=0)
...
```
I'm on Python 3.6, Meep 1.11.0, MPB 1.9.0, all compiled from source.

I ran the following C++ code, adapted from tests/bench.cpp:
```
#include <stdio.h>
#include <stdlib.h>
#include <meep.hpp>
using namespace meep;

double one(const vec &) { return 1.0; }
void evaluate(const double xmax, const double ymax, const double zmax, double eps(const vec &)) {
  const double a = 10.0;
  grid_volume gv = vol3d(xmax, ymax, zmax, a);
  structure s(gv, one);
  fields f(&s);
  f.add_point_source(Ez, 0.8, 0.6, 0.0, 4.0, vec(xmax * .5, ymax * .5, zmax * .5));
  f.step();
}

int main(int argc, char **argv) {
  initialize mpi(argc, argv);
  quiet = true;
  while(true) {
    evaluate(10.0, 10.0, 10.0, one);
    master_printf(".");
  }
  return 0;
}
```
Which does not seem to leak memory (as monitored by `top`).

I do not have any SWIG experience, and don't have an understanding of how the SWIG wrapped objects are destroyed once the reference counter goes to 0. Is there some cleanup method I could call to ensure that all fields etc are deallocated, for example?

Many thanks. Would be helpful even just to know if this is reproducible for y'all.

**Comment by oskooi** [comment]
I was not able to identify any memory leaks. I tried two test cases and monitored the memory usage with `top -p <process id>` from the shell rather than `psutil` from within Python as you did. I ran [examples/binary_grating_oblique.py](https://github.com/NanoComp/meep/blob/master/python/examples/binary_grating_oblique.py) using a single process. As soon as the program terminated, the memory was released.

I also ran a slightly modified version of your test script involving a longer runtime and the results were the same (i.e., no memory leak).

```py
import meep as mp

def evaluate():
  # Code from examples/straight-waveguide.py, with resolution = 30.                                                                                                  
  cell = mp.Vector3(16,8,0)
  geometry = [mp.Block(mp.Vector3(mp.inf,1,mp.inf),
                       center=mp.Vector3(),
                       material=mp.Medium(epsilon=12))]
  sources = [mp.Source(mp.ContinuousSource(frequency=0.15),
                       component=mp.Ez,
                       center=mp.Vector3(-7,0))]
  pml_layers = [mp.PML(1.0)]
  resolution = 30
  sim = mp.Simulation(cell_size=cell,
                      boundary_layers=pml_layers,
                      geometry=geometry,
                      sources=sources,
                      resolution=resolution)
  sim.run(until=1000)

evaluate()
```

Is it possible that what you are observing is somehow related to the `psutil` module?

**Comment by jeinarsson** [comment]
Thanks for your reply!

Just to clarify: When the program terminates, the memory is recovered (because this is part of the OS's responsibility.) I am talking about running many simulation instances after each other, in the same program execution. Note the `while True:` loop in my example above (both Python and C++). I see the same memory usage with `top`, `pmap` and `psutil`, so I believe the numbers are correct. I chose to put the `psutil` example here simply because it makes the measurement self-contained in the example.

Could you verify whether you see memory usage increasing indefinitely for the non-terminating Python program above? As measured with `top`, for example.

**Comment by oskooi** [comment]
Yes, I was able to reproduce the memory leak you reported using `top` and the following script:

```py
import meep as mp
import time

def evaluate():
  # Code from examples/straight-waveguide.py, with resolution = 30.                                                                                               
  cell = mp.Vector3(16,8,0)
  geometry = [mp.Block(mp.Vector3(mp.inf,1,mp.inf),
                       center=mp.Vector3(),
                       material=mp.Medium(epsilon=12))]
  sources = [mp.Source(mp.ContinuousSource(frequency=0.15),
                       component=mp.Ez,
                       center=mp.Vector3(-7,0))]
  pml_layers = [mp.PML(1.0)]
  resolution = 30
  sim = mp.Simulation(cell_size=cell,
                      boundary_layers=pml_layers,
                      geometry=geometry,
                      sources=sources,
                      resolution=resolution)
  sim.run(until=100)

while True:
  evaluate()
  time.sleep(10)
```

`top` reveals that the `VIRT`, `RES`, and `SHR` fields are non-zero constant values throughout the entire duration of the simulation even as the `%CPU` switches from `0` to `100`.  It seems that the `Simulation` object is indeed not being freed from memory when out of scope. Clearing the `Simulation` object manually by placing `sim.reset_meep()` or `del sim` right after the line `sim.run(...)` inside `evaluate` also does nothing.

**Comment by jeinarsson** [comment]
Thanks for verifying!

`reset_meep` sets the internal variables, like `fields`, to None, reducing their refcount to 0. That should in principle be equivalent to that `sim` goes out of scope at each return of the `evaluate` function in this example. So that `reset_meep` does nothing seems logical (I also tried this..).

However -- and this is where I did not get further -- it seems some allocation in those objects do not get freed, and the main suspect would be `fields`. (I base this suspicion on that larger simulations leak more memory..) At the same time, the C++ example indicates that the destructor of the C++ `fields` does clean up properly, which leads me to suspect the SWIG-wrapped Python `fields`. I was hoping that someone with more SWIG experience might weigh in.

**Comment by jeinarsson** [comment]
I did a simple printf-debug, and `fields::~fields` does get called once per simulation, so that does not seem to be the issue in itself.

**Comment by jeinarsson** [comment]
Here's a more minimal example:
```python
import meep as mp
def evaluate():
  cell = mp.Vector3(16,8,0)
  geometry = [mp.Block(mp.Vector3(mp.inf,1,mp.inf),
                       center=mp.Vector3(),
                       material=mp.Medium(epsilon=12))]
  resolution = 50
  sim = mp.Simulation(cell_size=cell,
                      geometry=geometry,
                      resolution=resolution)
  sim.init_sim()  # if this is commented out, no memory is leaking.


mp.quiet(True)
while True:
  evaluate()
```

**Comment by jeinarsson** [comment]
It seems `structure::~structure` is never called, because meep.i dumps
`meep::structure *create_structure_and_set_materials` verbatim into the python extension code, so no one owns the returned pointer, and it is never freed. If it weren't for the `%inline %{..}%` block, I believe a solution would be to add a `%newobject` directive ([doc](http://www.swig.org/Doc2.0/Customization.html#Customization_ownership)).

**Comment by jeinarsson** [comment]
The problem is fixed by inserting 
```
%newobject create_structure_and_set_materials;
```
before the inline declaration in meep.i.

**Comment by jeinarsson** [comment]
Let me know what you think! Thanks

**Comment by jeinarsson** [comment]
FYI I'm seeing some more memory leaks in a more complicated model, will get back once I have a better minimal example. The above patch fixes the example at the beginning of this thread.

**Comment by jeinarsson** [comment]
It seems that using a material function makes another leak:

```python
import meep as mp
import numpy as np

MATERIAL = mp.Medium(epsilon=12.25)
def geometry_func(r):
  return MATERIAL

def evaluate():
  cell = mp.Vector3(16,8,0)
  geometry = [mp.Block(mp.Vector3(mp.inf,1.,mp.inf),
                       center=mp.Vector3(),
                       material=geometry_func)]  # If material=MATERIAL, no memory is leaking.
  resolution = 50
  sim = mp.Simulation(cell_size=cell,
                      geometry=geometry,
                      resolution=resolution)
  sim._init_structure()  # if this is commented out, no memory is leaking.


def main():
  while True:
    evaluate()

if __name__ == "__main__":
  main()
```

**Comment by jeinarsson** [comment]
This one was harder to track down.

The offending allocation is
```cpp
sl->items = new susceptibility_struct[length];
```
in `py_list_to_susceptibility_list` in typemap_utils.cpp.

I'll see if I can figure out the correct fix. Any input welcome. Happy friday.

**Comment by jeinarsson** [comment]
This seems a little involved. There is some kind of garbage collection in place for susceptibilities, but materials with user defined functions are excluded. However, `py_list_to_susceptibility_list` does allocate susceptibilities for user defined functions, when called through `geom_epsilon::get_material_pt`.

Would appreciate if anyone has visibility into the flow of allocations here, for the correct fix.

Have a great weekend.

**Comment by jeinarsson** [comment]
I'm happy to close this issue with #1039 and #1041.

I believe I still see some more, smaller, leaks when running simulations with DFT fluxes (add a source, a dft flux, and sim.run(until=1) to the above example), but would have to do a bit more work to diagnose carefully. Will open a new issue if/when I get there. 

Thanks for your work & responses.
