### ISSUE TITLE
Calculating Radar Cross Section(RCS) of 3D shapes using MEEP

### ISSUE THREAD

**Issue by khashabri** [NanoComp/meep#1040]
Hello guys,
I'm very new to the MEEP and currently struggling with calculating the RCS of different 3D shapes. 
For instance, let's consider a 3D sphere, could someone please help me with how to calculate the RCS of it and also modify the code for more complicated objects? For a sphere, I should expect a result as in the following:
![RCS_Sphere](https://user-images.githubusercontent.com/50481847/67081785-2172b780-f198-11e9-8023-4d8966236110.png)

**Comment by stevengj** [comment]
The meep-discuss mailing list is a better place for this kind of usage question.

The short answer is use a DFT flux box to calculate the net inward power flowing into the object — this is the absorbed power.  Then use the same flux box but with subtracted fields (as in the reflection tutorial) to calculate the scattered power.  Then the cross section is absorbed+scattered power divided by incident intensity. 

See also #980

**Comment by khashabri** [comment]
Alright! I've posted a more [detailed issue](https://www.mail-archive.com/meep-discuss@ab-initio.mit.edu/msg06415.html) on this topic in the mailing list. Unfortunately, for the RCS-subject, there are literally no resources in MEEP to look at. A tutorial or a detailed commented post — which is what I am trying to construct — would be highly demanded by people who are researching in this area.
