### ISSUE TITLE
Problem with load_minus_flux_data in parallel simulations

### ISSUE THREAD

**Issue by ovidiopr** [NanoComp/meep#1044]
Hi,

I am finding that parallel simulations with Python interface give wrong results when I use the function 'load_minus_flux_data'. I have found a [closed issue about this problem](https://github.com/NanoComp/meep/issues/463) but the bug persists for release [v1.11.0](https://github.com/NanoComp/meep/releases/tag/v1.11.0).

If necessary, I can provide my simulation code but the bug can be reproduced with the original code reported on issue 463. Only a small change is required, on lines 60, from:
```python
coeffs, vgrp, kpoints = sim.get_eigenmode_coefficients(refl_flux,[1],eig_parity=mp.ODD_Z+mp.EVEN_Y)
```
to:
```python
coeffs, vgrp, kpoints, kdom = sim.get_eigenmode_coefficients(refl_flux,[1],eig_parity=mp.ODD_Z+mp.EVEN_Y)
```
and line 101, from:
```python
coeffs, vgrp, kpoints = sim.get_eigenmode_coefficients(refl_flux,[1],eig_parity=mp.ODD_Z+mp.EVEN_Y)
```
to:
```python
coeffs, vgrp, kpoints, kdom = sim.get_eigenmode_coefficients(refl_flux,[1],eig_parity=mp.ODD_Z+mp.EVEN_Y)
```

Thank you and best regards,

Ovidio

[serial.txt](https://github.com/NanoComp/meep/files/3779139/serial.txt)
[mpi.txt](https://github.com/NanoComp/meep/files/3779140/mpi.txt)

**Comment by ovidiopr** [comment]
Hi Again,

I ran the second script of [issue 463](https://github.com/NanoComp/meep/issues/463) and this is what I get:
`Using MPI version 3.1, 1 processes
-----------
...
data:, 39.28950110, 39.31156477, 0.00000000, -0.00000000

Elapsed run time = 27.4320 s`
and for the parallel simulation:
`Using MPI version 3.1, 4 processes
-----------
...
data:, 39.28950110, 39.31156477, 0.00018202, 21.66404309

Elapsed run time = 10.4703 s`

Best regards,

Ovidio

**Comment by oskooi** [comment]
Actually, this is not a bug: as @stevengj noted in #463:[comment](https://github.com/NanoComp/meep/issues/463#issuecomment-412982282), the normalization and real runs must have the *same* cell dimensions. In this example, if you replace `sx = dpml+2*Lw+dpml` (in the second run) with `sx = dpml+Lw+dpml`, the results are as expected.
