### ISSUE TITLE
package not found on Window system Conda.

### ISSUE THREAD

**Issue by vishalvashistha87** [NanoComp/meep#1089]
Hi, 
I try to install this package on my window based system. I have preinstalled Conda but Conda could not found this package. Could you please check why it's happening? Here is the screenshots of error from my system. 
Thanks in advance. 
<img width="547" alt="Capture" src="https://user-images.githubusercontent.com/13811787/71667418-afa91380-2d6d-11ea-8fd2-2b4ab1c2e5fd.PNG">

**Comment by oskooi** [comment]
It could be that there is something potentially wrong with the Anaconda/Miniconda installation in Windows. As a workaround, have you tried installing the Windows Subsystem for Linux as described in [Installation/Windows](https://meep.readthedocs.io/en/latest/Installation/#installation-on-windows)?

**Comment by ChristopherHogan** [comment]
Meep conda packages are currently only available for Linux and MacOS.

**Comment by stevengj** [comment]
Duplicate of #385
