### ISSUE TITLE
Focused Gaussian Beam

### ISSUE THREAD

**Issue by pierreluc-plt** [NanoComp/meep#1093]
Hi, 
How would you you generate a focused gaussian beam? I am trying to get a beam that starts at w(z)>w0 and that focuses with waist w0 at distance f from the source. The picture below illustrates what I mean. The part that I am interested in is the beam on the right side of the lens.  

![image](https://user-images.githubusercontent.com/40267882/71980751-d1cbe700-31ee-11ea-92f5-5733cad4e8e4.png)

It is similar to issue 971 (https://github.com/NanoComp/meep/issues/971) but the source of the beam is at the waist. 

Thanks!

**Comment by oskooi** [comment]
This is described in https://meep.readthedocs.io/en/latest/FAQ/#how-do-i-create-a-focused-beam-with-a-gaussian-envelope.

**Comment by stevengj** [comment]
The [FAQ](https://meep.readthedocs.io/en/latest/FAQ/#how-do-i-create-a-focused-beam-with-a-gaussian-envelope) basically says how to create a Gaussian beam in the paraxial approximation given a source plane at the beam waist.  It would be nice to have a more general Gaussian beam source (non paraxial, not necessarily located at the beam waist).

Closing this issue in favor of #1094, which describes a way to implement a more general Gaussian source.
