### ISSUE TITLE
Assigning permittivities pixel-by-pixel

### ISSUE THREAD

**Issue by zhaonat** [NanoComp/meep#1096]
Suppose I have a specification for the permittivity distribution on the rectangular yee's lattice (i.e. it comes from some a frequency domain adjoint solver). Is it possible to recreate the structure pixel-by-pixel in meep? (i.e. can I somehow have pixel-by-pixel control of the Yee lattice in meep somehow rather than specifying blocks or discs, etc. etc.)

**Comment by stevengj** [comment]
In principle, yes.  If you define a material function, with subpixel averaging disabled, it will be called for each point in the Yee grid, so you "just" need to return whatever value you want at each point.   Implementing this (given e.g. arrays of values on the Yee grid) requires some care, as you would need to make sure you understand how Meep defines its Yee grid.   (We are thinking of providing a higher-level API to expose the Yee grid coordinates.)

In C++, you have direct access to the stored ε values via the `chi1inv` field of the `structure_chunk` objects within the `structure` object, but of course mucking with Meep internals like this requires a fair amount of understanding as well.

**Comment by zhaonat** [comment]
Thanks Steven! Aside from these options, which requires some care, then the only other option that does roughly the same thing (i.e. using the python api) would I guess be the meep.adjoint ParametrizedDielectric (with a FiniteElementBasis)?

**Comment by stevengj** [comment]
The `ParametrizedDielectric` is still ultimately evaluated only on the Yee grid, so it is just a form of material function.

**Comment by oskooi** [comment]
Importing the material geometry as a bitmap image is possible using the [`MaterialGrid`](https://meep.readthedocs.io/en/latest/Python_User_Interface/#materialgrid) feature which was released in [version 1.15 (July 2020)](https://github.com/NanoComp/meep/releases/tag/v1.15.0).
