### ISSUE TITLE
Ring Resonator in Cylindrical Coordinates AttributeError Meep

### ISSUE THREAD

**Issue by BaileyM25** [NanoComp/meep#1097]
AttributeError: module 'meep' has no attribute 'CYLINDRICAL'

I was given this error, very confused as I am following the instructions for this example.

**Comment by danielwboyce** [comment]
That sounds like Meep might not have been properly installed. What operating system are you using? Can you give some more details on how you were trying to install it (build from source, using a Conda package, etc.)?

**Comment by BaileyM25** [comment]
I am pretty new to this but I am pretty sure I used a Conda package. I actually am pretty sure I did many different ways of trying to install it. However for more detail, I started the process with this video: https://www.youtube.com/watch?v=pxIJTGiBdWs

**Comment by danielwboyce** [comment]
The video follows roughly the same process described in the [installation procedure in our documentation](https://meep.readthedocs.io/en/latest/Installation/#conda-packages) for a conda package. The only difference is that the current syntax for creating the environment is

```conda create -n YOUR_ENVIRONMENT_NAME -c conda-forge pymeep```

Using a conda package is probably the easiest way to install for a beginner, though, so good choice! Just to make sure, are you installing in Ubuntu or another flavor of Linux? If you are working with Windows or macOS the installation will be different; native compilation on Windows isn't supported (with a potential workaround if you install the Windows subsystem for Linux) and there are different hoops to jump through for macOS.

Also, can you show the script you're using to test? Where the 'CYLINDRICAL' reference is failing? There's a chance you have installed Meep correctly but something is just going wrong with your program.

**Comment by BaileyM25** [comment]
For this issue, I am in Ubuntu and working with Spyder.


```

> #!/usr/bin/env python3
> # -*- coding: utf-8 -*-
> import meep as mp
> """
> Ring Resonator in Cylindrical Coordinates Tutorial
> @author: bailey
> """
> 
> 
> # defining the parameters 
> n = 3.4
> w = 1
> r = 1
> pad = 4
> dpml = 2
> 
> 
> # Define the dimensions and size of the computational cell
> 
> sr = r + w + pad + dpml
> dimensions = mp.CYLINDRICAL
> cell = mp.Vector3(sr, 0, 0)
> 
> 
> m = 3
> 
> 
> geometry = [mp.Block(center=mp.Vector3(r + (w / 2)),
>             size=mp.Vector3(w, 1e20, 1e20), 
>             material=mp.Medium(index=n))]
> 
> pml_layers = [mp.PML(dpml)]
> resolution = 10
> 
> fcen = 0.15 #center frequency
> df = 0.1
> sources = [mp.Source(src=mp.GaussianSource(fcen, fwidth=df),
>                      component=mp.Ez,
>                      center=mp.Vector3(r + 0.1))]
> 
> 
> sim = mp.Simulation(cell_size=cell,
>                     geometry=geometry,
>                     boundary_layers=pml_layers,
>                     resolution=resolution,
>                     sources=sources,
>                     dimensions=dimensions,
>                     m=m)
> 
> sim.run(mp.after_sources(mp.Harminv(mp.Ez, mp.Vector3(r + 0.1), fcen, df)),
>         until_after_sources=200)
>                     

```

**Comment by danielwboyce** [comment]
That should work, since it's just the [tutorial](https://meep.readthedocs.io/en/latest/Python_Tutorials/Cylindrical_Coordinates/#modes-of-a-ring-resonator) from the documentation. Are you launching Spyder in the `conda` environment where you've installed `pymeep`?

**Comment by BaileyM25** [comment]
I believe so? I use the terminal provided with Ubuntu and just type Spyder and it launches up with no issues. I used this same terminal for the entire installation process.

**Comment by BaileyM25** [comment]
![Screenshot from 2020-01-13 11-02-24](https://user-images.githubusercontent.com/43218505/72302218-836f7b80-3626-11ea-8e07-650789b8da5a.png)

**Comment by danielwboyce** [comment]
It looks like you're not launching Spyder from the base conda environment. If you followed the instructions from the Your Tube video you linked, you didn't install Meep there, so you'll need to launch Spyder from the environment where Meep is installed. You'll want to do

```conda activate ENVIRONMENT_NAME```

for that environment. That'll change `(base)` next to your username in the terminal window to `(ENVIRONMENT_NAME)`. Then you can launch Spyder from that environment (you may need to reinstall depending on Anaconda was initially configured). Launching Spyder in that environment should let you run the tutorial properly.

If in the future you want to avoid needing to relaunch Spyder to connect your runtime to a different Python interpreter, there are some other (free) IDE options that let you dynamically change your Python/Conda virtual environment without relaunching. I like PyCharm, which has a nice community version.

**Comment by BaileyM25** [comment]
ooooooh! I think I understand, I am going to retry and see what it does.

**Comment by BaileyM25** [comment]
![Screenshot from 2020-01-13 16-54-53](https://user-images.githubusercontent.com/43218505/72317846-c8f86c80-3657-11ea-9cc2-f642c6d28e23.png)


This is the error I am now getting. I got everything installed to (mp) but now it is saying it cannot be found.

**Comment by js1990** [comment]
Did you manage to figure this one out?
