### ISSUE TITLE
Prism Geometry missing blocks

### ISSUE THREAD

**Issue by pstrk** [NanoComp/meep#1098]
Using pymeep I tried to create a linear taper structure based on a prism object. When reducing the taper tip width below a certain threshold part of the taper prism seems to disappear. It seems the threshold depends on the length of the taper. The error might be related to the aspect ratio of the vertex? 

With a wider tip everything looks fine (tip width 0.1):
![prismbug-wide-tip-crop](https://user-images.githubusercontent.com/34421515/72083587-5b200e00-3302-11ea-9894-4c74f0624c08.png)

With a finer tip the issue arises (tip width 0.05):
![prismbug-fine-tip-crop](https://user-images.githubusercontent.com/34421515/72083591-5ce9d180-3302-11ea-8d86-3c6847069024.png)

The following code was used to generate this examples:
```python
import meep as mp
import matplotlib.pyplot as plt

sx = 40
tip_width = 0.1 # 0.05
wg_width = 1
cell_size = (sx, 5, 0)
resolution = 100
Si = mp.Medium(index=3.5)
geometry = []

vertices = [mp.Vector3(-sx * 0.5, wg_width * 0.5),
            mp.Vector3(-sx * 0.5 + 3, wg_width * 0.5),
            mp.Vector3(sx * 0.5, tip_width * 0.5),
            mp.Vector3(sx * 0.5, -tip_width * 0.5),
            mp.Vector3(-sx * 0.5 + 3, -wg_width * 0.5),
            mp.Vector3(-sx * 0.5, -wg_width * 0.5),
            ]

geometry.append(mp.Prism(material=Si, vertices=vertices, height=mp.inf))

sim = mp.Simulation(cell_size=cell_size,
                    geometry=geometry,
                    resolution=resolution)
sim.eps_averaging = False
plt.figure()
sim.plot2D(output_plane=mp.Volume(center=(0, 0, 0), size=(sx, 5, 0)))
plt.show()
```

I am not sure, but this might be related to #864. I am using the latest stable release of pymeep (Conda package).

**Comment by smartalecH** [comment]
Have you tried the nightly build of the conda package? We recently updated libctl with a more robust polygon method that hasn't transitioned to a "stable" release yet.

This is what I get when I build everything from source with bleeding-edge:

![taper](https://user-images.githubusercontent.com/24902086/72086021-43ca2c00-32d4-11ea-8070-00df49e2eb45.png)

**Comment by pstrk** [comment]
Thanks for your quick response. It does indeed work nicely with the newest nightly build.
