### ISSUE TITLE
module 'meep' has no attribute 'CYLINDRICAL'

### ISSUE THREAD

**Issue by BaileyM25** [NanoComp/meep#1101]
Hello, I am trying to run one of the tutorials in the meep documentation however it for some reason is not reading CYLINDRICAL correctly. 

AttributeError: module 'meep' has no attribute 'CYLINDRICAL'

I am using Ubuntu outside of Windows and installed meep via a tutorial on Youtube (https://www.youtube.com/watch?v=pxIJTGiBdWs) and tried it the conda way. In the beginning I was receiving 'meep' module not found. I fixed that by going to the env that I created in the terminal and did 'pip3 install meep' 

 I cannot for the life of me figure out this current issue though. 

Edit: I wanted to show more pictures to hopefully explain better.

![Screenshot from 2020-01-14 17-56-12](https://user-images.githubusercontent.com/43218505/72412212-0b8a7980-372a-11ea-9006-f73f10429d27.png)

![Screenshot from 2020-01-14 17-55-21](https://user-images.githubusercontent.com/43218505/72412227-10e7c400-372a-11ea-8760-07a62a7d87dc.png)

![Screenshot from 2020-01-14 17-56-26](https://user-images.githubusercontent.com/43218505/72412240-16dda500-372a-11ea-9f2f-4c736650e12d.png)

![Screenshot from 2020-01-14 17-57-12](https://user-images.githubusercontent.com/43218505/72412250-1c3aef80-372a-11ea-836d-75771187a6ed.png)

**Comment by danielwboyce** [comment]
Wait, are you trying to run `meep` in Google Colab or through Ubuntu? That is, are the Conda environments you're trying to install `pymeep` hosted by Colab or your local Ubuntu machine? Running Conda packages in Colab can be much more of an art than a science; personally I've never been able to get any Conda packages to stably run in Colab. Issue #460 touches on this.

**Comment by stevengj** [comment]
Don't paste screenshots into error reports.  Screenshots are hard to read, cannot be copy-pasted, and cannot be searched.  Paste [quoted text](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code).

Did you try one of the tutorial examples, e.g. `meep/python/examples/ring-cyl.py`?

**Comment by BaileyM25** [comment]
I have figured it out but forgot to close the post. When I originally did the installation, I had no idea what was going on and had things installed everywhere. Mixing pip installs and conda installs. I just had to reinstall with using 1 as constant. And apologies for the screenshots, was trying to show file system as well. Will not do that next time.

**Comment by lamph123** [comment]
> I have figured it out but forgot to close the post. When I originally did the installation, I had no idea what was going on and had things installed everywhere. Mixing pip installs and conda installs. I just had to reinstall with using 1 as constant. And apologies for the screenshots, was trying to show file system as well. Will not do that next time.

How did you solve your problem? Could you share it with me? Thanks!

**Comment by KPK101** [comment]
Hi,
I installed meep in python using pip( I'm guessing this isn't enough) and I face a similar error: " module 'meep' has no attribute 'Vector3'. It would be helpful is you could share how to resolve this.
