### ISSUE TITLE
Calculating eigenmode coefficient scaling

### ISSUE THREAD

**Issue by smartalecH** [NanoComp/meep#1107]
As described in the docs, the eigenmode coefficients are scaled by a normalization constant, `Cm`:
```
Cm=vm*As
```
where `vm` is the group velocity and `As` is the mode volume.

In theory, if I wanted to calculate this (i.e. for adjoint sims), I should be able to use the group velocity returned by `get_eigenmode_coefficients` and a brute force calculation of the mode volume. I can't seem to reconcile results, however, with what the internals of `get_eigenmode_coefficients`:

https://github.com/NanoComp/meep/blob/93be1abd83e507d4f8becba8bef0da002526b947/src/mpb.cpp#L811

I'm assuming my calculation of the mode volume is different from meep's. Is there a routine (maybe through swig) that can calculate this given a volume object? It's also possible that meep does some additional normalization on the group velocity that I'm not aware of...

Currently, I'm doing the brute force mode-mode overlap integral and am getting matching results. It would be nice to skip this step, however, and just use quantities from the API.

**Comment by stevengj** [comment]
I'm not sure what "mode volume" you are referring to.  I thought the eigenmode coefficients were scaled so that |coefficient|² is power?

**Comment by smartalecH** [comment]
Sorry for the ambiguity. By "mode volume" I actually meant the cross-sectional surface area of the mode monitor. Taken from the [docs](https://meep.readthedocs.io/en/latest/Mode_Decomposition/) describing the inner product of any two eigenmode coefficients:

> The normalization constant Cm is a matter of convention, but in MPB it is taken to be the group velocity of the mode, vm, times the area AS of the cross-sectional surface S.

As you mention, the eigenmode coefficients are supposed to be scaled so that |coefficient|² is power. Formally, the final equation should be

![Screen Shot 2020-01-27 at 7 50 51 PM](https://user-images.githubusercontent.com/24902086/73226512-5f3f8e80-413e-11ea-953d-5f14e1b79770.png)

Is there an easy way to calculate As? I tried pulling the dimensions from the volume object and calculating the area that way, but was unable to produce the correct results.

In a seemingly unrelated issue, I believe there is a bug within the actual codebase that implements the above equation. After doing some print statements, I found that the line that is supposed to normalize out the Poynting flux (S), always assumes S=1 (at least in 2D cartesian coordinates). Is this expected?

https://github.com/NanoComp/meep/blob/e0d1c5ab5578834b6aedf53dd73b4daf04c13248/src/mpb.cpp#L813

**Comment by stevengj** [comment]
MPB normalized the modes so that the integral of epsilon |E|^2 is 1, so to get to unit power you just need to scale by vg.

**Comment by smartalecH** [comment]
Hmm the group velocities returned by `get_eigenmode_coefficients()` don't match the corresponding inner product.

I'll try to produce a WME that doesn't require manual `master_printf` statements. Unfortunately `Simulation.fields.get_mode_mode_overlap()` doesn't have a working typemap.

**Comment by stevengj** [comment]
Actually it looks like [`get_eigenmode` renormalizes the mode](https://github.com/NanoComp/meep/blob/e0d1c5ab5578834b6aedf53dd73b4daf04c13248/src/mpb.cpp#L581-L589) so that it has unit power.
