### ISSUE TITLE
Issues with Creating a Video of Simulation

### ISSUE THREAD

**Issue by BaileyM25** [NanoComp/meep#1111]
I am running into issues trying to animate the simulation of a Straight Waveguide using MEEP.

First, I created an mp4 file and get Broken Pipe Error but from looking deeper into fixing the issue, I was told it was better to ignore the issue.

//pipe error in visualization.py
"BrokenPipeError: [Errno 32] Broken pipe"

//creates video file
`filename = "Videos/straight_waveguide.mp4"`
`Animate.to_mp4(10,filename)`

Then, when I try to play the recently created file, I get a ValueError that states I must pass embed = True.

//value error in display.py
"ValueError: To embed videos, you must pass embed=True (this may make your notebook files huge)
Consider passing Video(url='...')"

//trying to play file
`embed = True`
`from IPython.display import Video`

`Video(filename)`

**Comment by smartalecH** [comment]
Are you using the example Jupyter notebook? Are you runnning it in Jupyter, or are you trying to run it in iPython?

> but from looking deeper into fixing the issue, I was told it was better to ignore the issue.

You probably don't want to "ignore the issue". If the pipe breaks it's not going to write any data to the mp4.

Have you tried playing the mp4 locally on your machine to make sure there's something there?

**Comment by BaileyM25** [comment]
I am using the example in Jupyter notebook, yes. I have tried opening the file and it just opens with nothing.

**Comment by smartalecH** [comment]
Seems like you need to fix that broken pipe. Unfortunately, that is a very system dependent problem. Did you build from source, or from a conda package? What platform are you on? Are you sure you have ffmpeg installed?

You can get more debugging information by printing out the error messages stored in the pip:
https://github.com/NanoComp/meep/blob/e0d1c5ab5578834b6aedf53dd73b4daf04c13248/python/visualization.py#L903-L905

Use something like:
```python
proc = Popen(command, stdin=PIPE, stdout=PIPE, stderr=PIPE)
print(proc.stderr)
for i in range(len(self._saved_frames)): 
     proc.stdin.write(self._saved_frames[i]) 
```

**Comment by BaileyM25** [comment]
I built it from a conda package, I am using Ubunutu, the version of ffmpeg version 4.2 installed.

When I try that command, I get Popen is not defined. I tried to change the directory to where I have the code itself to see if that would help and then I get 'Animate' is not defined.


`filename` = `"miniconda3/envs/mp3/bin/CylindricalRingResonator/straight_waveguide.mp4"`
`Animate.to_mp4(10,filename)`

**Comment by ptang314** [comment]
How did you fix the pipe error?  I'm running into the same problem with the same install as you.

**Comment by BaileyM25** [comment]
Unfortunately, I was not able to properly fix the issue. I had to move on.

**Comment by knifelees3** [comment]
Hey, I have met the same problem, But I finally fixxed it in a very simple way. Maybe my problem is not acutally the same, 
The original code is
`filename = "Videos/straight_waveguide.mp4"`
and I found that I need change it into
`filename = "straight_waveguide.mp4"`
or I should create the folder “Videos”, Otherwise, I will meet the same probelm you mentioned above.

So the problem is that the folder doesn't exist and you need create it. This is my problem and perhaps your problem is more difficult?

**Comment by doswellf** [comment]
This is too late but also removed media/ and was able to generate the mp4
