### ISSUE TITLE
The MPI problem

### ISSUE THREAD

**Issue by chenyudong92** [NanoComp/meep#1114]
Hi, all

I want to run the meep at the TACC super computer center, but they using the **CRAY_MPI** to complie their parallel program. Whatever, the MPI meep complied by **MPICH**. What could I do to pair the **MPICH** to **CRAY_MPI**.

**Comment by stevengj** [comment]
You can pass `MPICXX=... MPICC=...` to the `configure` script to compile with a different MPI.

**Comment by chenyudong92** [comment]
Hi, Johnson

Thanks your help. But, I not familiar with Linux script. Did you means I can use anaconda to download the Python version meep and use the configure script to compile it?

By the way, could you send me a example of configure script with I can follow.

Thanks a lot!!

Sincerely,
Yudong Chen
M.S. of Electrical Engineering at SMU
Ph.D. Student of Electrical Engineering at UTA
Office at 2nd floor of NanoFab at UTA
________________________________
发件人: Steven G. Johnson <notifications@github.com>
发送时间: Wednesday, February 12, 2020 7:09:11 AM
收件人: NanoComp/meep <meep@noreply.github.com>
抄送: Chen, Yudong <yudong.chen@mavs.uta.edu>; Author <author@noreply.github.com>
主题: Re: [NanoComp/meep] The MPI problem (#1114)


You can pass MPICXX=... MPICC=... to the configure script to compile with a different MPI.

―

**Comment by danielwboyce** [comment]
No, to compile with a different MPI you'll have to build from source. We have details on building from source in [our documentation](https://meep.readthedocs.io/en/latest/Build_From_Source/), but that only has information specific to Meep. There are lots of guides on the Internet on building from source code that can give you some introductory information on what that means.

**Comment by stevengj** [comment]
Seems like this can be closed; it's not really a problem in Meep, just a matter of applying the right build techniques.
