### ISSUE TITLE
MPI_Barrier() function called after MPI_FINALIZE was invoked.

### ISSUE THREAD

**Issue by RJTK** [NanoComp/meep#112]
I am running an mpi enabled version of meep with the Python interface.  I have built and installed from source, and all the tests are passing.

The code

    def test000(self):
        cell = mp.Vector3(16, 16, 0)
        geometry = [mp.Block(mp.Vector3(12, 1, 1e20),
                             center=mp.Vector3(-2.5, -3.5),
                             material=mp.Medium(epsilon=12)),
                    mp.Block(mp.Vector3(1, 12, 1e20),
                             center=mp.Vector3(3.5, 2),
                             material=mp.Medium(epsilon=12))]
        pml_layers = [mp.PML(1.0)]
        resolution = 10

        sources = [mp.Source(mp.ContinuousSource(wavelength=2*(11 ** 0.5),
                                                 width=20),
                             component=mp.Ez,
                             center=mp.Vector3(-7, -3.5),
                             size=mp.Vector3(0, 1))]

        sim = mp.Simulation(cell_size=cell,
                            boundary_layers=pml_layers,
                            geometry=geometry,
                            sources=sources,
                            resolution=resolution)

        sim.run(mp.at_beginning(mp.output_epsilon),
                mp.to_appended("ez", mp.at_every(0.6, mp.output_efield_z)),
                until=200)
        return

works without issue when using the non mpi enabled version of meep.  However, with mpi I have the following error:

```
Compilation started at Mon Oct 16 18:52:53

nosetests -v test_basics\:TutorialBentWaveguide.test000

**
** successfully loaded python MPI module (mpi4py)
**
test000 (test_basics.TutorialBentWaveguide) ... time for set_epsilon = 0.428574 s
Working in 2D dimensions.
Computational cell is 16 x 16 x 0 with resolution 10
     block, center = (-2.5,-3.5,0)
          size (12,1,1e+20)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (12,12,12)
     block, center = (3.5,2,0)
          size (1,12,1e+20)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (12,12,12)
time for set_epsilon = 0.0348468 s
-----------
creating output file "./nosetests-eps-000000.00.h5"...
creating output file "./nosetests-ez.h5"...

Field time usage:
    connnecting chunks: 0.00792003 s
         time stepping: 0.491834 s
         communicating: 0.0852661 s
     outputting fields: 1.30064 s
    Fourier transforming: 0.00029254 s
       everything else: 0.0530965 s

ok

----------------------------------------------------------------------
Ran 1 test in 2.413s

OK
*** The MPI_Barrier() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[(null):29473] Local abort after MPI_FINALIZE completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!

Compilation exited abnormally with code 1 at Mon Oct 16 18:52:56

```

The function causing this problem is `mp.to_appended` -- replacing it with `mp.at_end(mp.output_efield_z))` does not result in any errors.

The file created by `mp.to_appended` is `nosetests-ez.h5`, but it is corrupted.

```
$ h5debug nosetests-ez.h5 
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 0:
  #000: H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1085 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: H5Fsuper.c line 277 in H5F_super_read(): file signature not found
    major: File accessibilty
    minor: Not an HDF5 file
cannot open file
```

It seems the program is being interrupted while writing to the .h5 file?

**Comment by stevengj** [comment]
That's weird.  The mpi4py documentation says that it only calls `MPI_Finalize` when the program exits:
>`MPI_Finalize()` is registered (by using Python C/API function `Py_AtExit()`) for being automatically called when Python processes exit
which should be after HDF5 closes the file.

**Comment by RJTK** [comment]
The above seems like it might be due to Nose, there is no error if I just paste the code into the interpreter.  However, h5debug says the same thing about the output file -- it is corrupted.

**Comment by RJTK** [comment]
The error

```
*** The MPI_Barrier() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[(null):878] Local abort after MPI_FINALIZE completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```
occurs when python exits, nothing to do with Nose.

**Comment by stevengj** [comment]
@ChristopherHogan, are we sure that the `to_appended` file is being closed when `run` finishes?

**Comment by ChristopherHogan** [comment]
The corrupted h5 file looks like the issue we had before the file was getting closed properly, which has been fixed.  I am unable to reproduce this on the latest master branch.
```bash
(mp3) chris@ubuntu:python (master)*$ h5debug issue-112-ez.h5 
Reading signature at address 0 (rel)
File Super Block...
File name (as opened):                             issue-112-ez.h5
File name (after resolving symlinks):              issue-112-ez.h5
File access flags                                  0x00000000
File open reference count:                         1
Address of super block:                            0 (abs)
Size of userblock:                                 0 bytes
Superblock version number:                         0
Free list version number:                          0
Root group symbol table entry version number:      0
Shared header version number:                      0
Size of file offsets (haddr_t type):               8 bytes
Size of file lengths (hsize_t type):               8 bytes
Symbol table leaf node 1/2 rank:                   4
Symbol table internal node 1/2 rank:               16
File status flags:                                 0x00
Superblock extension address:                      UNDEF (rel)
Shared object header message table address:        UNDEF (rel)
Shared object header message version number:       0
Number of shared object header message indexes:    0
Address of driver information block:               UNDEF (rel)
Root group symbol table entry:                     
   Name offset into private heap:                  0
   Object header address:                          96
   Cache info type:                                Symbol Table
   Cached entry information:                      
      B-tree address:                              136
      Heap address:                                680
```

**Comment by ChristopherHogan** [comment]
I should also mention that instead of using nose (which isn't 100% supported just yet) I ran your test function as `main` via `mpirun -n 2 python issue-112.py`.
```python
def test000():
...
if __name__ == '__main__':
    test000()
```
