### ISSUE TITLE
Unable to display the figure of the adjoint example-CrossRouter.py

### ISSUE THREAD

**Issue by tsehso** [NanoComp/meep#1124]
Hi All,

I'm trying to familiar with how to use adjoint solver on Meep and have met some problems when running the example script of CrossRouter.py.

After several tries, I still couldn't work out how to remove the below warning and thought this might be the reason why the figure of this example couldn't be displayed. 

Visualization.py:347: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if options['fill_color'] != 'none': # first copy: faces, no edges

Any help would be very appreciated. 

Thanks in advance.

**Comment by smartalecH** [comment]
We're working on a significant update to the adjoint solver that will hopefully be released soon.

**Comment by stevengj** [comment]
We now have a new API with new examples.  #1167
