### ISSUE TITLE
The problem of the amp_fun

### ISSUE THREAD

**Issue by chenyudong92** [NanoComp/meep#1128]
Hi,

Where I can find more detail to explain how the amp_fun function works for generate oblique plane wave？

Because, the example is not work good enough, if I want to change the source center position at x-axis. Like the following script:

[Gaussian-beam-with-angle.txt](https://github.com/NanoComp/meep/files/4217120/Gaussian-beam-with-angle.txt)

**Comment by chenyudong92** [comment]
## generate a titled Gaussian beam profile by defining the amplitude function of the source
#%%
import meep as mp
import math
import cmath        #complex number math
import numpy as np
import matplotlib.pyplot as plt
#%%
resolution = 40 # pixels/μm

cell_size = mp.Vector3(20,20,0)

pml_layers = [mp.PML(thickness=1.0)]

ng=1

fcen = 1/1.45 # center frequency of CW source (wavelength is 1 μm)

tilt_angle = math.radians(0) # angle of tilted beam
k = mp.Vector3(y=1).rotate(mp.Vector3(z=1),tilt_angle).scale(fcen*ng)

sigma = 2 # beam width

def gaussian_beam(sigma, k, x0):
    def _gaussian_beam(x):
        return cmath.exp(1j*2*math.pi*k.dot(x-x0)-(x-x0).dot(x-x0)/(2*sigma**2)) #a.dot(b)=np.dot(a,b), inner produce
    return _gaussian_beam


src_pt = mp.Vector3(3,9,0)# I move the x-axis of the source center


sources = [mp.Source(mp.ContinuousSource(fcen, fwidth=0.2*fcen),
                     component=mp.Ez,
                     center=src_pt,
                     size=mp.Vector3(10,0,0),
                     amp_func=gaussian_beam(sigma,k,src_pt)
                     )]

sim = mp.Simulation(cell_size=cell_size,
                    sources=sources,
                    k_point=k,
                    boundary_layers=pml_layers,
                    resolution=resolution)
f = plt.figure(dpi=120)
sim.plot2D(ax=f.gca())
plt.show()
#%%
non_pml_vol = mp.Volume(center=mp.Vector3(), size=cell_size)
sim.run(until=50)

ez_data = sim.get_array(vol=non_pml_vol, component=mp.Ez)

plt.figure()
plt.imshow(np.flipud(np.transpose(np.real(ez_data))), interpolation='spline36', cmap='RdBu')
plt.axis('off')
plt.show()
#%%

**Comment by smartalecH** [comment]
```python
import meep as mp
import numpy as np
from matplotlib import pyplot as plt

resolution = 10 # pixels/μm

sx = 14
sy = 10
sz = 0
cell_size = mp.Vector3(sx,sy,sz)

pml_layers = [mp.PML(thickness=2)]

# rotation angle (in degrees) of planewave, counter clockwise (CCW) around z-axis
rot_angle = np.radians(0)

fsrc = 1.0 # frequency of planewave (wavelength = 1/fsrc)

n = 1.5  # refractive index of homogeneous material
default_material = mp.Medium(index=n)

rot_angle = 30*np.pi/180
k_point = mp.Vector3(fsrc*n).rotate(mp.Vector3(z=1), rot_angle)

# beam waist
w = 0.6

def amp_func(pt):
    return 1/ np.sqrt(np.pi*w**2) * np.exp(-pt.y ** 2 / w ** 2)

sources = [mp.EigenModeSource(src=mp.GaussianSource(fsrc,fwidth=0.1*fsrc),
                              center=mp.Vector3(),
                              size=mp.Vector3(y=sy),
                              direction=mp.NO_DIRECTION,
                              eig_kpoint=k_point,
                              eig_band=1,
                              eig_parity=mp.EVEN_Y+mp.ODD_Z,
                              amp_func=amp_func,
                              eig_match_freq=True)]

sim = mp.Simulation(cell_size=cell_size,
                    resolution=resolution,
                    boundary_layers=pml_layers,
                    sources=sources,
                    default_material=default_material)

sim.run(until=60)

# plot the intenisty
f = lambda x: np.abs(x) ** 2
field_parameters = {'post_process':f}
sim.plot2D(fields=mp.Ez,field_parameters=field_parameters)
plt.savefig('gaussian_beam.png')
plt.show()
```

![gaussian_beam](https://user-images.githubusercontent.com/24902086/74873181-b5ae8000-532c-11ea-9013-1d15e760b3f1.png)
