### ISSUE TITLE
rename omega parameters to frequency

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#1131]
#919 introduced an `omega` parameter for the frequency for various Python and C functions such as `get_epsilon_point`, `get_array`, `output_epsilon`, etc. Since `omega` does *not* refer to the angular frequency (which contains a 2π factor), it should be renamed to `frequency`. This is consistent with other Meep functions which have a frequency argument. However, to maintain backwards compatibility, `omega` should continue to be supported for those functions which currently have an `omega` parameter (but still removed from the documentation).

**Comment by stevengj** [comment]
(I think the only way to implement this is to support both arguments, and give a deprecation warning if `omega` is passed.)
