### ISSUE TITLE
Feature request: savefield_and_continue

### ISSUE THREAD

**Issue by zhetaoj** [NanoComp/meep#1137]
Large simulation running on cluster times out after reaching the maximum time limit. It would be very helpful to add a run function to output the field distribution and/or to load it back and continue the simulation in a second run. This would also allow the user to check the result before determining whether a longer simulation is needed.

**Comment by oskooi** [comment]
The [checkpointing feature](https://meep.readthedocs.io/en/latest/Python_User_Interface/#load-and-dump-simulation-state) was added by #1715 and #1738.
