### ISSUE TITLE
Custom sources use different is_integrated convention

### ISSUE THREAD

**Issue by smartalecH** [NanoComp/meep#1143]
It seems that the `custom_time_src` has a different integrated current convention than the other time sources.

Specifically, the following lines show that the `current` function only acts as an integrated current source when `is_integrated` is set to `true`. Otherwise, it just returns a call to the `dipole` function.

https://github.com/NanoComp/meep/blob/5f2d84f11569fc1a0cf6ef3c563205d305d450b5/src/meep.hpp#L931-L936

This is different from the default, which *always* assumes that a call to the `current` function wants an integrated current source:

https://github.com/NanoComp/meep/blob/5f2d84f11569fc1a0cf6ef3c563205d305d450b5/src/meep.hpp#L850-L855

This is an important distinction since meep uses a combination of integrated and non-integrated sources for different field components.

https://github.com/NanoComp/meep/blob/5f2d84f11569fc1a0cf6ef3c563205d305d450b5/src/meep.hpp#L818-L819

 If the user specifies a custom function, however, then either *all* the sources must be integrated, or *none* of the sources are integrated. This seems problematic, especially for time-dependent adjoint sources.

Am I misinterpreting something?

**Comment by stevengj** [comment]
I think the principle is that, if the user supplies a function `f(t)`, we should use that directly.   If they specified a non-integrated current source, then `f(t)` is the current.  If they specified an integrated source, then `f(t)` is the dipole moment.

Since the `is_integrated` flag is per-source, what the user does with a custom source doesn't affect anything else, I think.

**Comment by stevengj** [comment]
The documentation here seems correct for `CustomSource`:

```
is_integrated [boolean] — If True, the source is the integral of the current (the dipole moment) which is guaranteed to be zero after the current turns off. In practice, there is little difference between integrated and non-integrated sources except for planewaves extending into PML. Default is False.
```
