### ISSUE TITLE
Simple Install Guide for MEEP on Ubuntu?

### ISSUE THREAD

**Issue by mgs85-dot** [NanoComp/meep#1155]
I have used MEEP for many years, but recently my computer died and when I try to reinstall MEEP I keep running into problems. I want to install it in the Ubuntu app for windows. Using the simple get-install command seemed to work, but I get an error related to Guile which has been reported before which requires version 2.011. Is there no way that the repository version on Ubuntu can be adjusted to make installation less painful for us not blessed with good programming skills (this bug has been around for several years now)? Someone suggested before that the install instructions should make this bug clear (I wasted much time on this).  I have followed the build from source instructions on the MEEP page (pasting exactly what is written) but get errors relating to the HDF5 libraries when installing h5utils (can't seem to find HDF5 libraries). I found some reference to this on another forum (stack exchange) but this didn't work either. I have also tried to follow instructions from Filipe D., John W. and others on forums, but even though I pasted commands in 1 by 1 can't seem to get MEEP to install.

Could someone makeup an idiot's guide to installing MEEP from source on ubuntu (literary what you have to type in line by line, in the correct order including all commands for downloading, cloning, unzipping etc. I am no expert on linux or programming) and put it on the MEEP official page? I'm sure it would help others too instead of having to trawl through forum after forum trying to take account of all these incompatibilities and bugs.

Many thanks for your help.

**Comment by oskooi** [comment]
Have you tried the [build script for Ubuntu 16.04/18.04](https://meep.readthedocs.io/en/latest/Build_From_Source/#ubuntu-1604-and-1804) from the manual? Rather than building from source, a much simpler approach is to install the [Conda package](https://meep.readthedocs.io/en/latest/Installation/#conda-packages). The entire installation involves copying/pasting just five lines into the shell terminal.

**Comment by mgs85-dot** [comment]
Hi oskooi, thanks for the suggestions. I have been trying the build script you refer to. For some reason it fails when I run as a script, so I have been inputting the lines manually. I adjusted the lines are directed for Ubuntu 18.04 (the version I have).

I forgot to say, I am not interested in the python version of MEEP. I just want MEEP and MPB

When I run the section starting sudo apt-get -y install, I noticed for Guile that it mentions Unpacking guile-2.0 (2.0.13+1-5ubuntu0.1). It is my understanding that this version of Guile won't work with MEEP (need 2.0.11 or earlier). See https://github.com/FilipDominec/python-meep-install/issues/7 

When I get to h5utils, after running the sh autogen line I also get an error saying:

configure: WARNING: can't find libdf (HDF4): won't be able to compile h5fromh4 or h4fromh5
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking hdf.h usability... no
checking hdf.h presence... no
checking for hdf.h... no
checking hdf/hdf.h usability... no
checking hdf/hdf.h presence... no
checking for hdf/hdf.h... no
checking for H5Fopen in -lhdf5... no
configure: error: hdf5 libraries are required for compilation

I also tried the conda method you pointed out. Will this work for ubuntu on windows? I get an error ERROR: could not open HSTS store at '/home/mgs85/.wget-hsts'. HSTS will be disabled

 Thanks very much for your help

**Comment by mgs85-dot** [comment]
Hi Ardavan, following your instructions on this post https://www.mail-archive.com/meep-discuss@ab-initio.mit.edu/msg05819.html but taking care to make the changes for ubuntu 18.04 mentioned here https://meep.readthedocs.io/en/latest/Build_From_Source/#ubuntu-1604-and-1804 seems to have worked for me. MEEP now running. Thanks for your help

**Comment by oskooi** [comment]
Ok. I highly recommend switching to the Python interface as the Scheme interface is no longer being maintained. The Conda packages are for PyMeep only. The following FAQ may be useful: https://meep.readthedocs.io/en/latest/FAQ/#are-there-precompiled-binary-packages-for-ubuntu.

**Comment by stevengj** [comment]
Is there something that needs to be updated in the docs or can this issue be closed?
