### ISSUE TITLE
GDSII import in scheme

### ISSUE THREAD

**Issue by jingham91** [NanoComp/meep#1172]
Hi all,
I am new to both MEEP and scheme. My question, Is it possible to import a GDSII file via scheme? I know that it is possible in python but the group I am entering tends to use the scheme interface, so I was wondering if it is possible in scheme for continuity reasons.
Thanks for any help
J

**Comment by oskooi** [comment]
The GDS import feature is currently only available for the Python interface. In principle, it should be possible to add it to the Scheme interface without too much work since Scheme already supports `prism` objects. We can add this feature to our list of ToDos.

**Comment by oskooi** [comment]
See #1175. Unfortunately, the Scheme interface is no longer being maintained.
