### ISSUE TITLE
mpi4py does not terminate Meep job when a single process is terminated

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#1180]
When running PyMeep parallel simulations on a cluster, if a given node is taken offline resulting in the termination of its MPI processes, the remaining MPI processes on the other nodes continue to run (even though they have effectively deadlocked). This seems to be a feature of mpi4py as described in https://groups.google.com/forum/#!topic/mpi4py/RovYzJ8qkbc.

Unfortunately, such an occurrence requires the user to manually intervene by having to kill the active MPI jobs in order to force the job to terminate. It would be useful if there were a built-in mechanism within Meep itself that would shut down the entire simulation in this event.

**Comment by stevengj** [comment]
There is a workaround posted in that thread:

> Unless your app really requires proper cleanup at finalization,
overriding `sys.excepthook` to call `MPI.COMM_WORLD.Abort()` is your best
change of get all processes die when a single one fails.

**Comment by oskooi** [comment]
Another solution which does not require any changes to Meep is to explicitly specify the `mpi4py` module at runtime as explained in https://mpi4py.readthedocs.io/en/stable/mpi4py.run.html:
```
mpirun -n 4 python -m mpi4py mysim.py
```
This method only works for `mpi4py` version 3.0+.

**Comment by smartalecH** [comment]
While using the nightly build on a red hat cluster I had to pass the `-m mpi4py` flag you describe just to get the simulation to start time-stepping. In other words, the simulation would initialize everything, and then stall just before timestepping was supposed to start.

Is this expected?

**Comment by oskooi** [comment]
Not sure why you need to invoke `-m mpi4py` just to enable time stepping. This command is only necessary for executing `mpi4py.run` which changes the case of unhandled exceptions to call `MPI_Abort()` (which is *not* the default).

Note that as soon as you load the Meep module in Python, the MPI version along with the number of MPI processes is [automatically displayed](https://github.com/NanoComp/meep/blob/master/python/meep.i#L1556-L1559). You can verify this in your output to confirm that `mpi4py` is loading properly.
