### ISSUE TITLE
Clean exit for "simulation fields are NaN or Inf"

### ISSUE THREAD

**Issue by smartalecH** [NanoComp/meep#1183]
#922 stops the simulation if a NaN or Inf is detected. Unfortunately, this also kills the process.

Is there a way to stop the simulation at this point without killing the process? This is problematic when optimizing over several simulations and a geometry is chosen that blows up the fields. Rather than kill everything (and lose progress) it would be better to stop the simulation early so the optimizer knows this is a poor route to pursue.

**Comment by stevengj** [comment]
Doesn't Python intercept this and turn it into an exception?

**Comment by smartalecH** [comment]
Yes you're right. Seems like a `try`, `except ` block should take care of this.

**Comment by hyounghankwon** [comment]
Hi, all.

I am Hyounghan Kwon who is doing reasearch about nanophotnoics.
Thank a lot for the development of the MEEP. It is really useful for my research.
I have a one question regarding the "simulation fields are NaN or Inf" issue.

I am using pmp (parallel meep) and try to solve eigenfrequency solver. (solve_eigfreq)
In that case, the try and except block seems not working.
I tested one processor without parallelization and multi-processors for this issue.
For one processor, it can nicely go to the exception block.
For many professors, "try and except" block doesn't work and the entire processes are killed when one of them encounters nan or inf field.
Is there anyway to circumvent the "simulation fields are NaN or Inf" issue when we are using the parallel meep and solve_eigfreq?

Thanks a lot and stay healthy!
Best
Han
