### ISSUE TITLE
coupler notbook example results not as expected

### ISSUE THREAD

**Issue by ValerioGiove** [NanoComp/meep#1195]
Hi,
I'm new on Meep.

Trying to run the coupler notebook example, without any change on code, and the results seem not consistent to what expected:

MPB solved for frequency_1(0.645161,0,0) = 0.645161 after 11 iters
Dominant planewave for band 1: (0.645161,-0.000000,0.000000)
MPB solved for frequency_1(0.645161,0,0) = 0.645161 after 11 iters
Dominant planewave for band 1: (0.645161,-0.000000,0.000000)MPB solved for frequency_1(0.645161,0,0) = 0.645161 after 11 iters
Dominant planewave for band 1: (0.645161,-0.000000,0.000000)
MPB solved for frequency_1(0.645161,0,0) = 0.645161 after 11 iters
Dominant planewave for band 1: (0.645161,-0.000000,0.000000)
MPB solved for frequency_1(0.645161,0,0) = 0.645161 after 11 iters
Dominant planewave for band 1: (0.645161,-0.000000,0.000000)
MPB solved for frequency_1(0.645161,0,0) = 0.645161 after 11 iters
Dominant planewave for band 1: (0.645161,-0.000000,0.000000)
trans:, 0.12, 0.000042, 0.079574, 0.069195
MPB solved for frequency_1(0.645161,0,0) = 0.645161 after 11 iters
Dominant planewave for band 1: (0.645161,-0.000000,0.000000)
MPB solved for frequency_1(0.645161,0,0) = 0.645161 after 11 iters
Dominant planewave for band 1: (0.645161,-0.000000,0.000000)
**trans:, 0.12, 0.000042, 0.079574, 0.069195**

The p3_trans,p4_trans should sum to 1, for energy conservation, instead are low as you can read here above. The Cell scale seem right to 34.4 x 8 um (with slight modification for d sweep accomodation) 

![image](https://user-images.githubusercontent.com/41860080/80311966-eb675d80-87e2-11ea-9f28-d59b3c58c417.png)

Furthermore the fields image seems to not take into account the coupler structure, even if the geometry seems right as attached below.

Thank you for your time
Regards
Valerio

-----------
Initializing structure...
time for choose_chunkdivision = 0.00104499 s
Working in 2D dimensions.
Computational cell is 34.4 x 7.82 x 0 with resolution 50
     prism, center = (-9.09425,1.32149,0)
          height 0, axis (0,0,1), sidewall angle: 0 radians, 174 vertices:
          (-4,0.06,0)
          (-4.108,0.061,0)
          (-4.215,0.062,0)
          (-4.322,0.065,0)
          (-4.429,0.07,0)
          (-4.535,0.075,0)
          (-4.641,0.081,0)
          (-4.747,0.089,0)
          (-4.852,0.097,0)
          (-5.062,0.117,0)
          (-5.167,0.129,0)
          (-5.271,0.141,0)
          (-5.479,0.169,0)
          (-5.582,0.184,0)
          (-5.685,0.2,0)
          (-5.788,0.217,0)
          (-5.891,0.235,0)
          (-5.993,0.253,0)
          (-6.095,0.272,0)
          (-6.197,0.292,0)
          (-6.299,0.313,0)
          (-6.4,0.334,0)
          (-6.501,0.356,0)
          (-6.703,0.402,0)
          (-6.803,0.425,0)
          (-6.904,0.45,0)
          (-7.204,0.525,0)
          (-7.303,0.552,0)
          (-7.403,0.578,0)
          (-7.502,0.605,0)
          (-7.601,0.633,0)
          (-7.7,0.66,0)
          (-7.799,0.688,0)
          (-7.898,0.717,0)
          (-7.996,0.745,0)
          (-8.095,0.774,0)
          (-8.193,0.803,0)
          (-8.291,0.833,0)
          (-8.389,0.862,0)
          (-8.487,0.892,0)
          (-8.585,0.921,0)
          (-8.781,0.981,0)
          (-8.878,1.011,0)
          (-9.074,1.071,0)
          (-9.268,1.131,0)
          (-9.366,1.161,0)
          (-9.463,1.191,0)
          (-9.56,1.22,0)
          (-9.658,1.25,0)
          (-9.949,1.337,0)
          (-10.047,1.366,0)
          (-10.144,1.395,0)
          (-10.338,1.451,0)
          (-10.436,1.478,0)
          (-10.533,1.506,0)
          (-10.63,1.533,0)
          (-10.728,1.559,0)
          (-10.922,1.611,0)
          (-11.02,1.636,0)
          (-11.117,1.66,0)
          (-11.215,1.685,0)
          (-11.313,1.708,0)
          (-11.41,1.731,0)
          (-11.508,1.754,0)
          (-11.606,1.776,0)
          (-11.704,1.797,0)
          (-11.802,1.817,0)
          (-11.901,1.837,0)
          (-11.999,1.856,0)
          (-12.098,1.875,0)
          (-12.196,1.893,0)
          (-12.295,1.91,0)
          (-12.394,1.926,0)
          (-12.592,1.956,0)
          (-12.691,1.97,0)
          (-12.791,1.982,0)
          (-12.89,1.994,0)
          (-12.99,2.005,0)
          (-13.19,2.025,0)
          (-13.291,2.033,0)
          (-13.392,2.04,0)
          (-13.492,2.046,0)
          (-13.593,2.051,0)
          (-13.695,2.055,0)
          (-13.796,2.058,0)
          (-14,2.06,0)
          (-17.2,2.06,0)
          (-17.2,2.56,0)
          (-14,2.56,0)
          (-13.892,2.559,0)
          (-13.785,2.558,0)
          (-13.678,2.555,0)
          (-13.571,2.55,0)
          (-13.465,2.545,0)
          (-13.359,2.539,0)
          (-13.253,2.531,0)
          (-13.148,2.523,0)
          (-12.938,2.503,0)
          (-12.833,2.491,0)
          (-12.729,2.479,0)
          (-12.521,2.451,0)
          (-12.418,2.436,0)
          (-12.315,2.42,0)
          (-12.212,2.403,0)
          (-12.109,2.385,0)
          (-12.007,2.367,0)
          (-11.905,2.348,0)
          (-11.803,2.328,0)
          (-11.701,2.307,0)
          (-11.6,2.286,0)
          (-11.499,2.264,0)
          (-11.297,2.218,0)
          (-11.197,2.195,0)
          (-11.096,2.17,0)
          (-10.796,2.095,0)
          (-10.697,2.068,0)
          (-10.597,2.042,0)
          (-10.498,2.015,0)
          (-10.399,1.987,0)
          (-10.3,1.96,0)
          (-10.201,1.932,0)
          (-10.102,1.903,0)
          (-10.004,1.875,0)
          (-9.905,1.846,0)
          (-9.807,1.817,0)
          (-9.709,1.787,0)
          (-9.611,1.758,0)
          (-9.513,1.728,0)
          (-9.415,1.699,0)
          (-9.219,1.639,0)
          (-9.122,1.609,0)
          (-8.926,1.549,0)
          (-8.732,1.489,0)
          (-8.634,1.459,0)
          (-8.537,1.429,0)
          (-8.44,1.4,0)
          (-8.342,1.37,0)
          (-8.051,1.283,0)
          (-7.953,1.254,0)
          (-7.856,1.225,0)
          (-7.662,1.169,0)
          (-7.564,1.142,0)
          (-7.467,1.114,0)
          (-7.37,1.087,0)
          (-7.272,1.061,0)
          (-7.078,1.009,0)
          (-6.98,0.984,0)
          (-6.883,0.96,0)
          (-6.785,0.935,0)
          (-6.687,0.912,0)
          (-6.59,0.889,0)
          (-6.492,0.866,0)
          (-6.394,0.844,0)
          (-6.296,0.823,0)
          (-6.198,0.803,0)
          (-6.099,0.783,0)
          (-6.001,0.764,0)
          (-5.902,0.745,0)
          (-5.804,0.727,0)
          (-5.705,0.71,0)
          (-5.606,0.694,0)
          (-5.408,0.664,0)
          (-5.309,0.65,0)
          (-5.209,0.638,0)
          (-5.11,0.626,0)
          (-5.01,0.615,0)
          (-4.81,0.595,0)
          (-4.709,0.587,0)
          (-4.608,0.58,0)
          (-4.508,0.574,0)
          (-4.407,0.569,0)
          (-4.305,0.565,0)
          (-4.204,0.562,0)
          (-4,0.56,0)
          dielectric constant epsilon diagonal = (12,12,12)
     prism, center = (9.09425,1.32149,0)
          height 0, axis (0,0,1), sidewall angle: 0 radians, 174 vertices:
          (4,0.06,0)
          (4,0.56,0)
          (4.204,0.562,0)
          (4.305,0.565,0)
          (4.407,0.569,0)
          (4.508,0.574,0)
          (4.608,0.58,0)
          (4.709,0.587,0)
          (4.81,0.595,0)
          (5.01,0.615,0)
          (5.11,0.626,0)
          (5.209,0.638,0)
          (5.309,0.65,0)
          (5.408,0.664,0)
          (5.606,0.694,0)
          (5.705,0.71,0)
          (5.804,0.727,0)
          (5.902,0.745,0)
          (6.001,0.764,0)
          (6.099,0.783,0)
          (6.198,0.803,0)
          (6.296,0.823,0)
          (6.394,0.844,0)
          (6.492,0.866,0)
          (6.59,0.889,0)
          (6.687,0.912,0)
          (6.785,0.935,0)
          (6.883,0.96,0)
          (6.98,0.984,0)
          (7.078,1.009,0)
          (7.272,1.061,0)
          (7.37,1.087,0)
          (7.467,1.114,0)
          (7.564,1.142,0)
          (7.662,1.169,0)
          (7.856,1.225,0)
          (7.953,1.254,0)
          (8.051,1.283,0)
          (8.342,1.37,0)
          (8.44,1.4,0)
          (8.537,1.429,0)
          (8.634,1.459,0)
          (8.732,1.489,0)
          (8.926,1.549,0)
          (9.122,1.609,0)
          (9.219,1.639,0)
          (9.415,1.699,0)
          (9.513,1.728,0)
          (9.611,1.758,0)
          (9.709,1.787,0)
          (9.807,1.817,0)
          (9.905,1.846,0)
          (10.004,1.875,0)
          (10.102,1.903,0)
          (10.201,1.932,0)
          (10.3,1.96,0)
          (10.399,1.987,0)
          (10.498,2.015,0)
          (10.597,2.042,0)
          (10.697,2.068,0)
          (10.796,2.095,0)
          (11.096,2.17,0)
          (11.197,2.195,0)
          (11.297,2.218,0)
          (11.499,2.264,0)
          (11.6,2.286,0)
          (11.701,2.307,0)
          (11.803,2.328,0)
          (11.905,2.348,0)
          (12.007,2.367,0)
          (12.109,2.385,0)
          (12.212,2.403,0)
          (12.315,2.42,0)
          (12.418,2.436,0)
          (12.521,2.451,0)
          (12.729,2.479,0)
          (12.833,2.491,0)
          (12.938,2.503,0)
          (13.148,2.523,0)
          (13.253,2.531,0)
          (13.359,2.539,0)
          (13.465,2.545,0)
          (13.571,2.55,0)
          (13.678,2.555,0)
          (13.785,2.558,0)
          (13.892,2.559,0)
          (14,2.56,0)
          (17.2,2.56,0)
          (17.2,2.06,0)
          (14,2.06,0)
          (13.796,2.058,0)
          (13.695,2.055,0)
          (13.593,2.051,0)
          (13.492,2.046,0)
          (13.392,2.04,0)
          (13.291,2.033,0)
          (13.19,2.025,0)
          (12.99,2.005,0)
          (12.89,1.994,0)
          (12.791,1.982,0)
          (12.691,1.97,0)
          (12.592,1.956,0)
          (12.394,1.926,0)
          (12.295,1.91,0)
          (12.196,1.893,0)
          (12.098,1.875,0)
          (11.999,1.856,0)
          (11.901,1.837,0)
          (11.802,1.817,0)
          (11.704,1.797,0)
          (11.606,1.776,0)
          (11.508,1.754,0)
          (11.41,1.731,0)
          (11.313,1.708,0)
          (11.215,1.685,0)
          (11.117,1.66,0)
          (11.02,1.636,0)

          (10.922,1.611,0)
          (10.728,1.559,0)
          (10.63,1.533,0)
          (10.533,1.506,0)
          (10.436,1.478,0)
          (10.338,1.451,0)
          (10.144,1.395,0)
          (10.047,1.366,0)
          (9.949,1.337,0)
          (9.658,1.25,0)
          (9.56,1.22,0)
          (9.463,1.191,0)
          (9.366,1.161,0)
          (9.268,1.131,0)
          (9.074,1.071,0)
          (8.878,1.011,0)
          (8.781,0.981,0)
          (8.585,0.921,0)
          (8.487,0.892,0)
          (8.389,0.862,0)
          (8.291,0.833,0)
          (8.193,0.803,0)
          (8.095,0.774,0)
          (7.996,0.745,0)
          (7.898,0.717,0)
          (7.799,0.688,0)
          (7.7,0.66,0)
          (7.601,0.633,0)
          (7.502,0.605,0)
          (7.403,0.578,0)
          (7.303,0.552,0)
          (7.204,0.525,0)
          (6.904,0.45,0)
          (6.803,0.425,0)
          (6.703,0.402,0)
          (6.501,0.356,0)
          (6.4,0.334,0)
          (6.299,0.313,0)
          (6.197,0.292,0)
          (6.095,0.272,0)
          (5.993,0.253,0)
          (5.891,0.235,0)
          (5.788,0.217,0)
          (5.685,0.2,0)
          (5.582,0.184,0)
          (5.479,0.169,0)
          (5.271,0.141,0)
          (5.167,0.129,0)
          (5.062,0.117,0)
          (4.852,0.097,0)
          (4.747,0.089,0)
          (4.641,0.081,0)
          (4.535,0.075,0)
          (4.429,0.07,0)
          (4.322,0.065,0)
          (4.215,0.062,0)
          (4.108,0.061,0)
          dielectric constant epsilon diagonal = (12,12,12)
     prism, center = (0,0.31,0)
          height 0, axis (0,0,1), sidewall angle: 0 radians, 4 vertices:
          (-4,0.06,0)
          (-4,0.56,0)
          (4,0.56,0)
          (4,0.06,0)
          dielectric constant epsilon diagonal = (12,12,12)
     prism, center = (-9.09425,-1.32149,0)
          height 0, axis (0,0,1), sidewall angle: 0 radians, 174 vertices:
          (-17.2,-2.56,0)
          (-17.2,-2.06,0)
          (-14,-2.06,0)
          (-13.796,-2.058,0)
          (-13.695,-2.055,0)
          (-13.593,-2.051,0)
          (-13.492,-2.046,0)
          (-13.392,-2.04,0)
          (-13.291,-2.033,0)
          (-13.19,-2.025,0)
          (-12.99,-2.005,0)
          (-12.89,-1.994,0)
          (-12.791,-1.982,0)
          (-12.691,-1.97,0)
          (-12.592,-1.956,0)
          (-12.394,-1.926,0)
          (-12.295,-1.91,0)
          (-12.196,-1.893,0)
          (-12.098,-1.875,0)
          (-11.999,-1.856,0)
          (-11.901,-1.837,0)
          (-11.802,-1.817,0)
          (-11.704,-1.797,0)
          (-11.606,-1.776,0)
          (-11.508,-1.754,0)
          (-11.41,-1.731,0)
          (-11.313,-1.708,0)
          (-11.215,-1.685,0)
          (-11.117,-1.66,0)
          (-11.02,-1.636,0)
          (-10.922,-1.611,0)
          (-10.728,-1.559,0)
          (-10.63,-1.533,0)
          (-10.533,-1.506,0)
          (-10.436,-1.478,0)
          (-10.338,-1.451,0)
          (-10.144,-1.395,0)
          (-10.047,-1.366,0)
          (-9.949,-1.337,0)
          (-9.658,-1.25,0)
          (-9.56,-1.22,0)
          (-9.463,-1.191,0)
          (-9.366,-1.161,0)
          (-9.268,-1.131,0)
          (-9.074,-1.071,0)
          (-8.878,-1.011,0)
          (-8.781,-0.981,0)
          (-8.585,-0.921,0)
          (-8.487,-0.892,0)
          (-8.389,-0.862,0)
          (-8.291,-0.833,0)
          (-8.193,-0.803,0)
          (-8.095,-0.774,0)
          (-7.996,-0.745,0)
          (-7.898,-0.717,0)
          (-7.799,-0.688,0)
          (-7.7,-0.66,0)
          (-7.601,-0.633,0)
          (-7.502,-0.605,0)
          (-7.403,-0.578,0)
          (-7.303,-0.552,0)
          (-7.204,-0.525,0)
          (-6.904,-0.45,0)
          (-6.803,-0.425,0)
          (-6.703,-0.402,0)
          (-6.501,-0.356,0)
          (-6.4,-0.334,0)
          (-6.299,-0.313,0)
          (-6.197,-0.292,0)
          (-6.095,-0.272,0)
          (-5.993,-0.253,0)
          (-5.891,-0.235,0)
          (-5.788,-0.217,0)
          (-5.685,-0.2,0)
          (-5.582,-0.184,0)
          (-5.479,-0.169,0)
          (-5.271,-0.141,0)
          (-5.167,-0.129,0)
          (-5.062,-0.117,0)
          (-4.852,-0.097,0)
          (-4.747,-0.089,0)
          (-4.641,-0.081,0)
          (-4.535,-0.075,0)
          (-4.429,-0.07,0)
          (-4.322,-0.065,0)
          (-4.215,-0.062,0)
          (-4.108,-0.061,0)
          (-4,-0.06,0)
          (-4,-0.56,0)
          (-4.204,-0.562,0)
          (-4.305,-0.565,0)
          (-4.407,-0.569,0)
          (-4.508,-0.574,0)
          (-4.608,-0.58,0)
          (-4.709,-0.587,0)
          (-4.81,-0.595,0)
          (-5.01,-0.615,0)
          (-5.11,-0.626,0)
          (-5.209,-0.638,0)
          (-5.309,-0.65,0)
          (-5.408,-0.664,0)
          (-5.606,-0.694,0)
          (-5.705,-0.71,0)
          (-5.804,-0.727,0)
          (-5.902,-0.745,0)
          (-6.001,-0.764,0)
          (-6.099,-0.783,0)
          (-6.198,-0.803,0)
          (-6.296,-0.823,0)
          (-6.394,-0.844,0)
          (-6.492,-0.866,0)
          (-6.59,-0.889,0)
          (-6.687,-0.912,0)
          (-6.785,-0.935,0)
          (-6.883,-0.96,0)
          (-6.98,-0.984,0)
          (-7.078,-1.009,0)
          (-7.272,-1.061,0)
          (-7.37,-1.087,0)
          (-7.467,-1.114,0)
          (-7.564,-1.142,0)
          (-7.662,-1.169,0)
          (-7.856,-1.225,0)
          (-7.953,-1.254,0)
          (-8.051,-1.283,0)
          (-8.342,-1.37,0)
          (-8.44,-1.4,0)
          (-8.537,-1.429,0)
          (-8.634,-1.459,0)
          (-8.732,-1.489,0)
          (-8.926,-1.549,0)
          (-9.122,-1.609,0)
          (-9.219,-1.639,0)
          (-9.415,-1.699,0)
          (-9.513,-1.728,0)
          (-9.611,-1.758,0)
          (-9.709,-1.787,0)
          (-9.807,-1.817,0)
          (-9.905,-1.846,0)
          (-10.004,-1.875,0)
          (-10.102,-1.903,0)
          (-10.201,-1.932,0)
          (-10.3,-1.96,0)
          (-10.399,-1.987,0)
          (-10.498,-2.015,0)
          (-10.597,-2.042,0)
          (-10.697,-2.068,0)
          (-10.796,-2.095,0)
          (-11.096,-2.17,0)
          (-11.197,-2.195,0)
          (-11.297,-2.218,0)
          (-11.499,-2.264,0)
          (-11.6,-2.286,0)
          (-11.701,-2.307,0)
          (-11.803,-2.328,0)
          (-11.905,-2.348,0)
          (-12.007,-2.367,0)
          (-12.109,-2.385,0)
          (-12.212,-2.403,0)
          (-12.315,-2.42,0)
          (-12.418,-2.436,0)
          (-12.521,-2.451,0)
          (-12.729,-2.479,0)
          (-12.833,-2.491,0)
          (-12.938,-2.503,0)
          (-13.148,-2.523,0)
          (-13.253,-2.531,0)
          (-13.359,-2.539,0)
          (-13.465,-2.545,0)
          (-13.571,-2.55,0)
          (-13.678,-2.555,0)
          (-13.785,-2.558,0)
          (-13.892,-2.559,0)
          (-14,-2.56,0)
          dielectric constant epsilon diagonal = (12,12,12)
     prism, center = (9.09425,-1.32149,0)
          height 0, axis (0,0,1), sidewall angle: 0 radians, 174 vertices:
          (14,-2.56,0)
          (13.892,-2.559,0)
          (13.785,-2.558,0)
          (13.678,-2.555,0)
          (13.571,-2.55,0)
          (13.465,-2.545,0)
          (13.359,-2.539,0)
          (13.253,-2.531,0)
          (13.148,-2.523,0)
          (12.938,-2.503,0)
          (12.833,-2.491,0)
          (12.729,-2.479,0)
          (12.521,-2.451,0)
          (12.418,-2.436,0)
          (12.315,-2.42,0)
          (12.212,-2.403,0)
          (12.109,-2.385,0)
          (12.007,-2.367,0)
          (11.905,-2.348,0)
          (11.803,-2.328,0)
          (11.701,-2.307,0)
          (11.6,-2.286,0)
          (11.499,-2.264,0)
          (11.297,-2.218,0)
          (11.197,-2.195,0)
          (11.096,-2.17,0)
          (10.796,-2.095,0)
          (10.697,-2.068,0)
          (10.597,-2.042,0)
          (10.498,-2.015,0)
          (10.399,-1.987,0)
          (10.3,-1.96,0)
          (10.201,-1.932,0)
          (10.102,-1.903,0)
          (10.004,-1.875,0)
          (9.905,-1.846,0)
          (9.807,-1.817,0)
          (9.709,-1.787,0)
          (9.611,-1.758,0)
          (9.513,-1.728,0)
          (9.415,-1.699,0)
          (9.219,-1.639,0)
          (9.122,-1.609,0)
          (8.926,-1.549,0)
          (8.732,-1.489,0)

          (8.634,-1.459,0)
          (8.537,-1.429,0)
          (8.44,-1.4,0)
          (8.342,-1.37,0)
          (8.051,-1.283,0)
          (7.953,-1.254,0)
          (7.856,-1.225,0)
          (7.662,-1.169,0)
          (7.564,-1.142,0)
          (7.467,-1.114,0)
          (7.37,-1.087,0)
          (7.272,-1.061,0)
          (7.078,-1.009,0)
          (6.98,-0.984,0)
          (6.883,-0.96,0)
          (6.785,-0.935,0)
          (6.687,-0.912,0)
          (6.59,-0.889,0)
          (6.492,-0.866,0)
          (6.394,-0.844,0)
          (6.296,-0.823,0)
          (6.198,-0.803,0)
          (6.099,-0.783,0)
          (6.001,-0.764,0)
          (5.902,-0.745,0)
          (5.804,-0.727,0)
          (5.705,-0.71,0)
          (5.606,-0.694,0)
          (5.408,-0.664,0)
          (5.309,-0.65,0)
          (5.209,-0.638,0)
          (5.11,-0.626,0)
          (5.01,-0.615,0)
          (4.81,-0.595,0)
          (4.709,-0.587,0)
          (4.608,-0.58,0)
          (4.508,-0.574,0)
          (4.407,-0.569,0)
          (4.305,-0.565,0)
          (4.204,-0.562,0)
          (4,-0.56,0)
          (4,-0.06,0)
          (4.108,-0.061,0)
          (4.215,-0.062,0)
          (4.322,-0.065,0)
          (4.429,-0.07,0)
          (4.535,-0.075,0)
          (4.641,-0.081,0)
          (4.747,-0.089,0)
          (4.852,-0.097,0)
          (5.062,-0.117,0)
          (5.167,-0.129,0)
          (5.271,-0.141,0)
          (5.479,-0.169,0)
          (5.582,-0.184,0)
          (5.685,-0.2,0)
          (5.788,-0.217,0)
          (5.891,-0.235,0)
          (5.993,-0.253,0)
          (6.095,-0.272,0)
          (6.197,-0.292,0)
          (6.299,-0.313,0)
          (6.4,-0.334,0)
          (6.501,-0.356,0)
          (6.703,-0.402,0)
          (6.803,-0.425,0)
          (6.904,-0.45,0)
          (7.204,-0.525,0)
          (7.303,-0.552,0)
          (7.403,-0.578,0)
          (7.502,-0.605,0)
          (7.601,-0.633,0)
          (7.7,-0.66,0)
          (7.799,-0.688,0)
          (7.898,-0.717,0)
          (7.996,-0.745,0)
          (8.095,-0.774,0)
          (8.193,-0.803,0)
          (8.291,-0.833,0)
          (8.389,-0.862,0)
          (8.487,-0.892,0)
          (8.585,-0.921,0)
          (8.781,-0.981,0)
          (8.878,-1.011,0)
          (9.074,-1.071,0)
          (9.268,-1.131,0)
          (9.366,-1.161,0)
          (9.463,-1.191,0)
          (9.56,-1.22,0)
          (9.658,-1.25,0)
          (9.949,-1.337,0)
          (10.047,-1.366,0)
          (10.144,-1.395,0)
          (10.338,-1.451,0)
          (10.436,-1.478,0)
          (10.533,-1.506,0)
          (10.63,-1.533,0)
          (10.728,-1.559,0)
          (10.922,-1.611,0)
          (11.02,-1.636,0)
          (11.117,-1.66,0)
          (11.215,-1.685,0)
          (11.313,-1.708,0)
          (11.41,-1.731,0)
          (11.508,-1.754,0)
          (11.606,-1.776,0)
          (11.704,-1.797,0)
          (11.802,-1.817,0)
          (11.901,-1.837,0)
          (11.999,-1.856,0)
          (12.098,-1.875,0)
          (12.196,-1.893,0)
          (12.295,-1.91,0)
          (12.394,-1.926,0)
          (12.592,-1.956,0)
          (12.691,-1.97,0)
          (12.791,-1.982,0)
          (12.89,-1.994,0)
          (12.99,-2.005,0)
          (13.19,-2.025,0)
          (13.291,-2.033,0)
          (13.392,-2.04,0)
          (13.492,-2.046,0)
          (13.593,-2.051,0)
          (13.695,-2.055,0)
          (13.796,-2.058,0)
          (14,-2.06,0)
          (17.2,-2.06,0)
          (17.2,-2.56,0)
          dielectric constant epsilon diagonal = (12,12,12)
     prism, center = (0,-0.31,0)
          height 0, axis (0,0,1), sidewall angle: 0 radians, 4 vertices:
          (-4,-0.56,0)
          (-4,-0.06,0)
          (4,-0.06,0)
          (4,-0.56,0)
          dielectric constant epsilon diagonal = (12,12,12)

**Comment by oskooi** [comment]
This is due to a bug in the script  where the `height` of the `Prism` object is `0` whereas it should be finite (or infinite via `meep.inf`) in a 2d cell.

You can fix it by changing one line:

```
si_zmax = t_Si if args.three_d else 0
```

to 

```
si_zmax = t_Si if args.three_d else 10
```

A `Prism` with a height of `0` in a 2d cell is effectively no object. 

The scripts will be updated shortly with this fix.

**Comment by ValerioGiove** [comment]
[SOLVED]

Thank you,
now the results are in line.
I have experience with 2.5D RF Simulators, and the 2D meep implementation, with indefinite Z values is still obscure to me. Need to read more docs.
