### ISSUE TITLE
material_grid API

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#1199]
Might be nice to have something like the `material_grid` feature in MPB where you can have a material function based on a numpy array of ε or u ∈ [0,1] values and it would linearly interpolate onto the Yee grid (implemented in C++ for performance) and then interpolate between two given materials as a function of u.

We might even implement the feature in MPB where you can have overlapping material grids, which is useful for projecting onto symmetry groups during optimization (http://arxiv.org/abs/arXiv:1405.4350) and potentially other applications (e.g. I initially implemented it to model overlapping lithography steps).

**Comment by stevengj** [comment]
We'll need to design this API so that it can be used by the adjoint solver.

**Comment by stevengj** [comment]
Given such a grid feature, we might want to implement a simpler subpixel averaging feature that just uses an MxMxM subgrid.

**Comment by smartalecH** [comment]
I'm trying to map out the API. 


It seems like we can adopt an approach that is very similar to the `material_file` material type. For example, we can create the grid using something like:

```C++
material_type make_material_grid(int Nx, int Ny, material_data *m1, material_data *m2);
```
which is similar to

https://github.com/NanoComp/meep/blob/65b69efa18e30a233896bb74c8f808e8f0a20b3a/src/meepgeom.cpp#L1580-L1584

The update call would also be similar, only with the proper interpolations:

https://github.com/NanoComp/meep/blob/65b69efa18e30a233896bb74c8f808e8f0a20b3a/src/meepgeom.cpp#L281-L299

Which will need a proper call in `get_material_pt`:
https://github.com/NanoComp/meep/blob/65b69efa18e30a233896bb74c8f808e8f0a20b3a/src/meepgeom.cpp#L516-L533

For the adjoint solver, we can do an implicit vector-jacobian-product (similar to the MPB routine). Obviously we would need proper SWIG hooks too, which shouldn't be too bad thanks to Chris.

Does this sound right? Also, can you explain each of the MPB `material_grid` enumerations:

https://github.com/NanoComp/mpb/blob/0935b95c362873c2dd871646c5f12899e48af1c6/mpb/mpb.h#L98

**Comment by stevengj** [comment]
Definitely it should be 3d (Nx x Ny x Nz).

**Comment by stevengj** [comment]
That enumeration is to support combining overlapping material grids from different objects. `U_PROD` (and `U_MIN`) are designed to represent overlapping lithography steps like in [this paper](http://math.mit.edu/~stevenj/papers/QiLi04.pdf).  `U_SUM` (which takes the mean of overlapping grids) is useful for imposing symmetries as in [this paper](http://doi.org/10.1364/OE.22.022632).  See [here](https://github.com/NanoComp/mpb/blob/c48ee748160b3989b8c3ddd68a290c84aab6d27c/mpb/epsilon.c#L161-L178) and [here](https://github.com/NanoComp/mpb/blob/master/mpb/material_grid.c#L97-L130) in the code.
