### ISSUE TITLE
interaction of discretization errors and non-robust designs

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#1210]
It would be useful to add a separate section to [Features/Subpixel Smoothing](https://meep.readthedocs.io/en/latest/Subpixel_Smoothing) to provide more details regarding the interaction of discretization errors with "non-robust" designs and in particular the effect of a structure's representation on the results. The key point is that users need to be aware of intrinsic accuracy limitations when trying to simulate certain structures which have subpixel dimensions in the case when subpixel smoothing is disabled and the structure is undersampled by the Yee grid (and whether the structure is linearly interpolated onto the Yee grid or not). Such kinds of structures are relevant for the [adjoint solver](https://meep.readthedocs.io/en/latest/Python_Tutorials/AdjointSolver/). Also useful would be a description of the differences between linearly interpolating a given structure onto the Yee grid versus subpixel smoothing (i.e., these two operations need *not* be mutually exclusive).

This effect can be demonstrated, for example, using a ring resonator in which the same ring geometry is represented using four different methods:

1. two overlapping `Cylinder` objects (subpixel smoothing)
2. two overlapping `Prism` objects, each with `40` vertices (subpixel smoothing; could also be imported as a [GDSII file](https://meep.readthedocs.io/en/latest/Python_Tutorials/GDSII_Import/))
3. `material_function` (no smoothing; since the adaptive quadrature routine is too slow)
4. `epsilon_input_file` (no smoothing; structure is linearly interpreted onto Yee grid).

(The HDF5 file used in (4) is generated via `output_epsilon` from (3) at resolution `80`.)

Of course, in the limit of infinite resolution, (2) and (4) are *not* the same structure as (1) and (3). Also, (3) is the same as (1) with *no* smoothing.

The 2d ring geometry and H<sub>z</sub>-polarized resonant mode are identical to the one in [Features/Subpixel Smoothing/Continuously-Varying Shapes and Results](https://meep.readthedocs.io/en/latest/Subpixel_Smoothing/#continuously-varying-shapes-and-results). The following three figures show as a function of resolution: (a) the mode frequency, (b) the error in the resonant frequency relative to the "exact" result of (1) at a resolution of `300`, (c) the error in the resonant frequency relative to the "exact" result for each method at a resolution of `300` (i.e., the exact result is different for each method).

![mode-freq-vs-res](https://user-images.githubusercontent.com/7152530/81241521-596c0b80-8fbf-11ea-919f-2eba63a0721c.png)

![relerror-vs-res-cylexact](https://user-images.githubusercontent.com/7152530/81241524-5c66fc00-8fbf-11ea-9b7c-9e6960149d2b.png)

![relerror-vs-res](https://user-images.githubusercontent.com/7152530/81241527-5ec95600-8fbf-11ea-9a18-0578755eb0fe.png)

These results are intended to demonstrate four points:
- in the first figure, (2) and (4) converge to a *different* resonant frequencies than (1) and (3). The error in the "exact" frequency of (4) and (2) relative to (1) or (3) (which are the same) are 0.3% and 0.2%.
- in the second figure, (1) converges with second-order accuracy and (3) with first-order accuracy but (2) and (4) converge to a constant. This demonstrates together with the first figure that (2) and (4) are in fact different structures than (1) and (3).
- in the second figure, even when the structures are the same in the continuum limit as in (1) and (3), given the slow (first-order) convergence rate when subpixel smoothing is disabled, it typically requires a *much* larger `resolution` to obtain the same relative error as when subpixel smoothing is used
- in the third figure, only (1) shows a smoothly varying convergence towards its "exact" result. The other methods show unpredictable changes with `resolution`

**Comment by stevengj** [comment]
To me, it's not surprising that (2) and (4) converge to different values — in the limit of infinite resolution, they are *different* structures than the cylinders.

Furthermore, since (4) is bilinearly interpolated, in the limit of infinite resolution it is converging to a *continuous* ε(x,y) function, so subpixel smoothing (even if we had it for `epsilon_input_file`) is not really needed once the Yee grid resolution exceeds the input image resolution.

**Comment by stevengj** [comment]
In general, if your input is a grid/image at a given resolution, I don't think it is meaningful to run Meep at a much higher resolution — you are just trying to resolve the individual pixels of your image, which is not physical.

**Comment by stevengj** [comment]
If you want the `epsilon_input_file` case without bilinear interpolation (in which case it will converge to a *different* value, and probably with more irregular convergence), just add `return D(x,y,z);` before [this line](https://github.com/NanoComp/meep/blob/c844fd80e86ea8fbcc161dfc87be7c5d8057dd28/src/fields.cpp#L705).

**Comment by stevengj** [comment]
Note that bilinear interpolation is mainly useful so that Meep responds continuously to changes in the parameters — otherwise, tiny changes in Meep's Yee grid could cause discontinous jumps in ε.

**Comment by oskooi** [comment]
Indeed, turning off the bilinear interpolation for `epsilon_input_file` introduces more noise into the mode-frequency results which also seems to converge to a different value than the case which does use interpolation.

![mode-freq-vs-res2](https://user-images.githubusercontent.com/7152530/81352944-a6fa7e00-907c-11ea-9015-5d9c485dac39.png)

Note what happens for resolutions below and above `80` (which is the resolution of the grid in the HDF5 file). For the interpolated structure, the mode frequency increases for resolutions below `80` and then flattens out for resolutions larger than `80`. The non-interpolated structure, however, shows no such qualitative change in the data. This reiterates the point made above that as long as ε(x,y) is continuous, subpixel smoothing is *not* necessary once the Yee grid resolution exceeds the input image resolution. 

It would still be useful to show results for two additional cases: subpixel smoothing and with/without bilinear interpolation. Unfortunately, this does not seem to be currently possible.

**Comment by stevengj** [comment]
Eventually the file-import no-interpolation case should converge once the Meep resolution is enough to resolve the individual pixels.

If this figure is included in the documentation, it should be emphasized that this is a conceptual experiment, but is not something anyone should normally do in practice, because it's not physically meaningful to try to get Meep to resolve the pixels of an imported image.
