### ISSUE TITLE
Eigenmode source - time index limited

### ISSUE THREAD

**Issue by rosanya** [NanoComp/meep#1213]
Hi, 

We are propagating light through a waveguide using an eigenmode source (with the intention of adding holes afterwards). We would like to plot the the mode overlap against radius of hole. 

A line of code from our simulation reads:
`sim.run(mp.at_beginning(mp.output_epsilon),
                mp.during_sources(mp.in_volume(v, mp.to_appended("hz-slice", mp.at_every(0.2, mp.output_hfield_z)))),
                until = 200)`
When using a non-eigenmode source, the hz-slice file contains 1000 as the time index, as we would expect as it is outputting 5 times a time step for 200 time steps. When we use an eigenmode source the hz-slice file no longer has 1000 as the time index, but has something much smaller. We found that with increased df (pulse width), the time index increases. 
We're just wondering if anyone knows why this is. 

The eigenmode source we're using is:
`src = [mp.EigenModeSource(src=mp.GaussianSource(fcen,width = df), 
                     eig_band=bnum,
                     eig_parity=mp.EVEN_Y+mp.EVEN_Z,         
                     center=mp.Vector3(-0.5*sx+dpml+1,0,0),
                     size=mp.Vector3(0,sy-2,sy-2))]`

We have a 3d cell, with a cylindrical waveguide aligned with the x-axis.

Any help will be appreciated. 

Thanks, 

Rosany

**Comment by stevengj** [comment]
You are using `mp.during_sources`, and you specified the time dependence of the source as a Gaussian pulse (`GaussianSource`), so it will only output for the duration of the pulse (which defaults to 5 standard deviations before and after the peak of the pulse, as specified by the [`cutoff` parameter](https://meep.readthedocs.io/en/latest/Python_User_Interface/#gaussiansource)).

If you want to output slices for the whole duration of the simulation (200), then remove the `during_sources` qualifier.
