### ISSUE TITLE
A bug in 3D similation of circular polarized  light

### ISSUE THREAD

**Issue by susappk** [NanoComp/meep#1215]
At first, i used Ex+iEy circular polarized light in z direction in 3D simulation,The calcualtin is no problem. However, when i was doing mode decompostion, there is no symmetry to choose in x direction(i.e. eig_parity=mp.ODD_X).

So i change the direction of light as Ey+iEz to use "eig_parity=mp.ODD_Z+mp.EVEN_Y". But at this time, the combination of two the source leads to the problem, that field at pt point is always at level e-34), here is the code
```python
import meep as mp

wvl_min = 0.45 #unit: um
wvl_max = 0.7
frq_min = 1/wvl_max #2pi=1
frq_max = 1/wvl_min
frq_cen = 0.5*(frq_min+frq_max)
dfrq = frq_max-frq_min
nfrq =100

resolution = 200#pixels/um
courant=0.55
rx=0.04
ry=0.08
#rz=0.04
dpml = 0.1
dair = 1/resolution
angle=0

sx = 2*(dpml+dair+rx)
sy = 0.3
sz = 0.3

cell_size = mp.Vector3(sx,sy,sz)
symmetries = []
pml_layers = [mp.PML(thickness=dpml,direction=mp.X)]


pt = mp.Vector3(rx,0,0)
L_R=1
field_to_check=mp.Ey+1j*mp.Ez

sources = [mp.Source(mp.GaussianSource(frq_cen,fwidth=dfrq,is_integrated=True,cutoff=5),center=mp.Vector3(x=-sx/2+dpml),
                     size=mp.Vector3(0,sy,sz),component=mp.Ey),
           mp.Source(mp.GaussianSource(frq_cen,fwidth=dfrq,is_integrated=True,cutoff=5),center=mp.Vector3(x=-sx/2+dpml),
                     size=mp.Vector3(0,sy,sz),component=mp.Ez,amplitude=L_R*1j)]
sim = mp.Simulation(resolution=resolution,Courant=courant,split_chunks_evenly=False,
                    cell_size=cell_size,
                    boundary_layers=pml_layers,
                    sources=sources,
                    k_point=mp.Vector3(),  #boundary condtion
                    symmetries=symmetries)
T0 = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(x=+rx),size=mp.Vector3(0,sy,sz)))
sim.run(until=([mp.stop_when_fields_decayed(3,field_to_check,pt,1e-9)]))
flux_inc = mp.get_fluxes(T0)
```

here is the result:
Using MPI version 3.1, 8 processes

Initializing structure...
Splitting into 8 chunks by cost
time for choose_chunkdivision = 0.000242949 s
Working in 3D dimensions.
Computational cell is 0.29 x 0.3 x 0.3 with resolution 200
time for set_epsilon = 0.042073 s

on time step 275 (time=0.75625), 0.0145858 s/step
on time step 573 (time=1.57575), 0.01347 s/step
on time step 864 (time=2.376), 0.0137523 s/step
field decay(t = 3.0002500000000003): 5.452501169245091e-34 / 5.452501169245091e-34 = 1.0
on time step 1171 (time=3.22025), 0.013048 s/step
on time step 1475 (time=4.05625), 0.0131853 s/step
on time step 1783 (time=4.90325), 0.0130279 s/step

-----------
If the source is Ex+iEy, there is no problem:
``` python

import meep as mp


################################### source 
wvl_min = 0.45 #unit: um
wvl_max = 0.7
frq_min = 1/wvl_max #2pi=1
frq_max = 1/wvl_min
frq_cen = 0.5*(frq_min+frq_max)
dfrq = frq_max-frq_min
nfrq =100
######################################### size 
## at least 8 pixels per smallest wavelength, i.e. np.floor(8/wvl_min)
resolution = 200#pixels/um
courant=0.55
rx=0.08
rz=0.04
dpml = 0.1
dair = 1/resolution
angle=0
sx = 0.3
sy = 0.3
sz = 2*(dpml+dair+rz)
cell_size = mp.Vector3(sx,sy,sz)
symmetries = []
pml_layers = [mp.PML(thickness=dpml,direction=mp.Z)]
################################################# monitor
pt = mp.Vector3(0,0,rz)
pt2 = mp.Vector3(rx,0,0).rotate(mp.Vector3(0,0,1),angle)
L_R=1
field_to_check=mp.Ey+1j*mp.Ez
####################################################################################
# is_integrated=True necessary for any planewave source extending into PML
sources = [mp.Source(mp.GaussianSource(frq_cen,fwidth=dfrq,is_integrated=True,cutoff=5),center=mp.Vector3(0,0,-sz/2+dpml),
                     size=mp.Vector3(sx,sy,0),component=mp.Ex),
           mp.Source(mp.GaussianSource(frq_cen,fwidth=dfrq,is_integrated=True,cutoff=5), center=mp.Vector3(0,0,-sz/2+dpml),
                     size=mp.Vector3(sx,sy,0),component=mp.Ey,amplitude=L_R*1j)]
sim = mp.Simulation(resolution=resolution,Courant=courant,split_chunks_evenly=False,
                    cell_size=cell_size,
                    boundary_layers=pml_layers,
                    sources=sources,
                    k_point=mp.Vector3(),  #boundary condtion
                    symmetries=symmetries)
T0 = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(z=+rz),size=mp.Vector3(sx,sy,0)))
#########################################################################################################################
sim.run(until=([mp.stop_when_fields_decayed(3,field_to_check,pt,1e-9),
               mp.stop_when_fields_decayed(3,field_to_check,pt2,1e-5)]))
flux_inc = mp.get_fluxes(T0)
```

And result:
Using MPI version 3.1, 8 processes
Initializing structure...
Splitting into 8 chunks by cost
time for choose_chunkdivision = 0.000237942 s
Working in 3D dimensions.
Computational cell is 0.3 x 0.3 x 0.29 with resolution 200
time for set_epsilon = 0.0416942 s
on time step 257 (time=0.70675), 0.0155653 s/step
on time step 540 (time=1.485), 0.0141549 s/step
on time step 828 (time=2.277), 0.0139226 s/step
field decay(t = 3.0002500000000003): 9.870476953831343e-05 / 9.870476953831343e-05 = 1.0
field decay(t = 3.0002500000000003): 9.921588869409332e-05 / 9.921588869409332e-05 = 1.0
on time step 1122 (time=3.0855), 0.0136126 s/step
on time step 1411 (time=3.88025), 0.0138661 s/step

**Comment by stevengj** [comment]
> So i change the direction of light as Ey+iEz to use "eig_parity=mp.ODD_Z+mp.EVEN_Y"

This polarization doesn't have that symmetry.  `mp.ODD_Z+mp.EVEN_Y` means that it has both of these mirror planes *individually*.  What you want is C₂ (180° rotation) symmetry, but MPB doesn't support this.

**Comment by susappk** [comment]
Thank you a lot for help, mp.ODD_Z+mp.EVEN_Y is used in the example: "Diffraction Spectrum of Liquid-Crystal Polarization Gratings"[https://meep.readthedocs.io/en/latest/Python_Tutorials/Mode_Decomposition/](url).
 I have a further quextion:
for linear incident light, source are used as :
```python 
 sources = [mp.Source(mp.GaussianSource(fcen,fwidth=0.05*fcen), component=mp.Ez, center=src_pt, size=mp.Vector3(0,sy,0)),
               mp.Source(mp.GaussianSource(fcen,fwidth=0.05*fcen), component=mp.Ey, center=src_pt, size=mp.Vector3(0,sy,0))]
```
and analysis monitor are used as:
```python
res1 = sim.get_eigenmode_coefficients(tran_flux, range(1,nmode+1), eig_parity=mp.ODD_Z+mp.EVEN_Y)
    res2 = sim.get_eigenmode_coefficients(tran_flux, range(1,nmode+1), eig_parity=mp.EVEN_Z+mp.ODD_Y)
```
and for circular polarized light:
```python
sources = [mp.Source(mp.GaussianSource(fcen,fwidth=0.05*fcen), component=mp.Ez, center=src_pt, size=mp.Vector3(0,sy,0)),
           mp.Source(mp.GaussianSource(fcen,fwidth=0.05*fcen), component=mp.Ey, center=src_pt, size=mp.Vector3(0,sy,0), amplitude=1j)]
```
at this time, what kinde of monitor eig_parity should be use to get all grating orders' transmittance.

**Comment by susappk** [comment]
> 
> 
> > So i change the direction of light as Ey+iEz to use "eig_parity=mp.ODD_Z+mp.EVEN_Y"
> 
> This polarization doesn't have that symmetry. `mp.ODD_Z+mp.EVEN_Y` means that it has both of these mirror planes _individually_. What you want is C₂ (180° rotation) symmetry, but MPB doesn't support this.

Thank you a lot for help, mp.ODD_Z+mp.EVEN_Y is used in the example: "Diffraction Spectrum of Liquid-Crystal Polarization Gratings"[https://meep.readthedocs.io/en/latest/Python_Tutorials/Mode_Decomposition/](url).
 I have a further quextion:
for linear incident light, source are used as :
```python 
 sources = [mp.Source(mp.GaussianSource(fcen,fwidth=0.05*fcen), component=mp.Ez, center=src_pt, size=mp.Vector3(0,sy,0)),
               mp.Source(mp.GaussianSource(fcen,fwidth=0.05*fcen), component=mp.Ey, center=src_pt, size=mp.Vector3(0,sy,0))]
```
and analysis monitor are used as:
```python
res1 = sim.get_eigenmode_coefficients(tran_flux, range(1,nmode+1), eig_parity=mp.ODD_Z+mp.EVEN_Y)
    res2 = sim.get_eigenmode_coefficients(tran_flux, range(1,nmode+1), eig_parity=mp.EVEN_Z+mp.ODD_Y)
```
and for circular polarized light:
```python
sources = [mp.Source(mp.GaussianSource(fcen,fwidth=0.05*fcen), component=mp.Ez, center=src_pt, size=mp.Vector3(0,sy,0)),
           mp.Source(mp.GaussianSource(fcen,fwidth=0.05*fcen), component=mp.Ey, center=src_pt, size=mp.Vector3(0,sy,0), amplitude=1j)]
```
at this time, what kinde of monitor eig_parity should be use to get all grating orders' transmittance.
