### ISSUE TITLE
smoothing kernel for material functions

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#1221]
As mentioned in the recently added section [Features/Subpixel Smoothing/Subpixel Smoothing vs. Bilinear Interpolation](https://meep.readthedocs.io/en/latest/Subpixel_Smoothing/#subpixel-smoothing-vs-bilinear-interpolation), currently there is no built-in interpolation provided for a [material function](https://meep.readthedocs.io/en/latest/Python_User_Interface/#material-function) (unlike the `epsilon_input_file`). Since continuous (or smoothed) structures are necessary for obtaining regular [convergence](https://meep.readthedocs.io/en/latest/FAQ/#checking-convergence), it would be useful for Meep (and consistent with its design philosophy of [pervasive interpolation](https://meep.readthedocs.io/en/latest/Introduction/#the-illusion-of-continuity)) to provide a built-in [gaussian smoothing kernel](https://en.wikipedia.org/wiki/Gaussian_blur) that could just be a wrapper around the material function when creating a geometry object or setting the default material. (The smoothing kernel itself could perhaps just be a simple wrapper around scipy's [gaussian_filter](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.ndimage.filters.gaussian_filter.html) or implemented directly in the low-level C with a few lines of code to skip the scipy module dependency.)

The interface could like something as follows:

```py
def ring_resonator(p):
    rr = (p.x**2+p.y**2)**0.5
    if (rr > rad) and (rr < rad+w):
        return mp.Medium(index=n)
    return mp.air

geometry = [mp.Block(center=mp.Vector3(),
                     size=mp.Vector3(sxy,sxy),
                     material=mp.smooth_matfunc(smoothing_radius, ring_resonator))]
```

In this example, a material function is defined to specify a ring resonator (not smooth). When the `Block` object containing `ring_resonator` is created, it is wrapped using a new function `smooth_matfunc` which has two arguments: a smoothing radius and the name of the material function. The smoothing radius could also be a keyword argument with a default value of the pixel width/length (i.e., 1/`resolution`).

**Comment by stevengj** [comment]
This has the same problem as enabling subpixel averaging for material functions — it would be crazy slow, because it requires an integral of a Python function for every pixel.

In fact, a Gaussian smoothing kernel would probably be slower than doing "correct" subpixel averaging, since it has unbounded support.    If we could make Gaussian smoothing fast enough, we might as well do the real anistropic averaging.

`gaussian_filter` and similar only apply if the input is an array, not an arbitrary function.

**Comment by oskooi** [comment]
To skip the call backs from C to Python (at every individual grid point in the material function region), would it be possible to generate a *pixel grid* of the material function in Python and then pass that entire array to C as just one data block in a single call? Perhaps this would require #1199 as a prerequisite.

**Comment by stevengj** [comment]
> would it be possible to generate a pixel grid of the material function in Python and then pass that entire array to C as just one data block in a single call?

Yes, but this seems equivalent to #1199

**Comment by oskooi** [comment]
As a practical demonstration of applying a smoothing kernel (scipy's `gaussian_filter`) to a material function (ring resonator), the figure below (from [Features/Subpixel Smoothing/Subpixel Smoothing vs. Bilinear Interpolation](https://meep.readthedocs.io/en/latest/Subpixel_Smoothing/#subpixel-smoothing-vs-bilinear-interpolation)) is updated to show the new result (black curve). The convergence is noticeably more regular compared with the material function with no smoothing (blue curve) but they both seem to be converging to nearly the *same* frequency which is unexpected because they are different structures. Nevertheless, setting up the smoothing kernel convolution in Python this way is slow and the time for `set_epsilon` is consistently more than 10% than the total wall clock time at all resolutions.

```py
def ring_resonator(p):
    rr = (p.x**2+p.y**2)**0.5
    if (rr > rad) and (rr < rad+w):
        return n
    return 1.0

import numpy as np
from scipy.ndimage import gaussian_filter

dxy = 1/resolution        # smoothing kernel radius                                                                                                              
Nxy = 5                   # smoothing grid pixel density                                                                                                         

def smooth_ring_resonator(p):
    cx = np.linspace(p.x-0.5*dxy,p.x+0.5*dxy,Nxy)
    cy = np.linspace(p.y-0.5*dxy,p.y+0.5*dxy,Nxy)
    n_local = np.zeros((Nxy,Nxy))
    for i in range(Nxy):
	for j in range(Nxy):
            n_local[i,j] = ring_resonator(mp.Vector3(cx[i],cy[j]))
    if np.sum(n_local) == Nxy**2:
	return mp.air
    elif np.sum(n_local) == n*Nxy**2:
	return mp.Medium(index=n)
    else:
        return mp.Medium(index=np.mean(gaussian_filter(n_local, sigma=1, mode='nearest')))
```

![mode-freq-vs-res4](https://user-images.githubusercontent.com/7152530/82105153-a8f0bc80-96ce-11ea-9ed6-810b754cb1b5.png)

**Comment by stevengj** [comment]
In this example, your smoothing radius is going to zero as the resolution goes to infinity, so it converges to the same discontinuous structure.

But if you are willing to do subpixel Gaussian smoothing on a 5x5 grid, you might as well do the correct anisotropic smoothing on the 5x5 grid.

An alternative is to do the smoothing analytically: just change your material function from a step function to a smoothed step function (e.g. a sigmoid).    This could be done any time you are defining the structure by a level set function. 

(Of course, if you have a level set function, you can get the normal vector analytically and you could do the correct anistropic smoothing analytically as well.)
