### ISSUE TITLE
Is it possible to use external refractive index information Data set without Lorentzian and drude?

### ISSUE THREAD

**Issue by emtiyl** [NanoComp/meep#1239]
Hello 
In our research we are using mixture of gold and a polymer for our material. And we generate the refractive index data.  I searched on documentation for using the refractive index data directly for simulation but I couldn't find anything other then modeling it with Drude an Lorentzian susceptibility. Is there any easy way for modeling susceptibilities with such refractive index data or is there a way for using that data directly?

**Comment by stevengj** [comment]
No, you have to fit it to the forms Meep supports.
