### ISSUE TITLE
Problem of transmittance spectrum example (shceme version)

### ISSUE THREAD

**Issue by chenyudong92** [NanoComp/meep#1247]
Hi,
I am the new user of meep. When I try to run the example to get transmittance by using scheme version meep, I faced a error:

on time step 48741 (time=1218.53), 0.000535037 s/step
field decay(t = 1250.625): 9.845036591680022e-8 / 6.062401894821005e-5 = 0.001623949840753786
field decay(t = 1300.65): 8.038713471792418e-8 / 6.062401894821005e-5 = 0.0013259948138145937
field decay(t = 1350.6750000000002): 6.621009853393293e-8 / 6.062401894821005e-5 = 0.0010921430100253658
on time step 55874 (time=1396.85), 0.000560813 s/step
field decay(t = 1400.7): 5.4085280444216835e-8 / 6.062401894821005e-5 = 8.92142774144038e-4
run 0 finished at t = 1400.7 (56028 timesteps)
Backtrace:
In ice-9/boot-9.scm:
 157: 11 [catch #t #<catch-closure c21ee0> ...]
In unknown file:
   ?: 10 [apply-smob/1 #<catch-closure c21ee0>]
In ice-9/eval.scm:
 432: 9 [eval # #]
 432: 8 [eval # #]
In unknown file:
   ?: 7 [primitive-load "./trans-try.clt"]
In ice-9/eval.scm:
 387: 6 [eval # #]
 387: 5 [eval # #]
 387: 4 [eval # #]
 387: 3 [eval # #]
 386: 2 [eval #<memoized (meep-dft-flux-freq-min-get <0>)> (# . #)]
 393: 1 [eval #<memoized meep-dft-flux-freq-min-get> (# . #)]
In unknown file:
   ?: 0 [memoize-variable-access! # #]

ERROR: In procedure memoize-variable-access!:
ERROR: Unbound variable: meep-dft-flux-freq-min-get

how do I fix it? Thanks a lot

**the script is:**
(define-param eps 13)         ; dielectric constant of waveguide
(define-param w 1.2)          ; width of waveguide
(define-param r 0.36)         ; radius of holes
(define-param d 1.4)          ; defect spacing (ordinary spacing = 1)
(define-param N 3)            ; number of holes on either side of defect

(define-param sy 6)           ; size of cell in y direction (perpendicular to wvg.)
(define-param pad 2)          ; padding between last hole and PML edge
(define-param dpml 1)         ; PML thickness

(define sx (+ (* 2 (+ pad dpml N)) d -1))    ; size of cell in x direction

(set! geometry-lattice (make lattice (size sx sy no-size)))

(set! geometry
      (append ; combine lists of objects:                                       
       (list (make block (center 0 0) (size infinity w infinity)
                   (material (make dielectric (epsilon eps)))))
       (geometric-object-duplicates (vector3 1 0) 0 (- N 1)
        (make cylinder (center (/ d 2) 0) (radius r) (height infinity)
              (material air)))
       (geometric-object-duplicates (vector3 -1 0) 0 (- N 1)
        (make cylinder (center (/ d -2) 0) (radius r) (height infinity)
              (material air)))))

(set! pml-layers (list (make pml (thickness dpml))))
(set-param! resolution 20)

(define-param fcen 0.25) ; pulse center frequency
(define-param df 0.2)    ; pulse frequency width
(define-param nfreq 500) ; number of frequencies at which to compute flux

(set! sources (list
               (make source
                 (src (make gaussian-src (frequency fcen) (fwidth df)))
                 (component Ey)
                 (center (+ dpml (* -0.5 sx)) 0)
                 (size 0 w))))
(set! symmetries (list (make mirror-sym (direction Y) (phase -1))))

(define trans ; transmitted flux                                          
        (add-flux fcen df nfreq
                  (make flux-region
                    (center (- (* 0.5 sx) dpml 0.5) 0) (size 0 (* w 2)))))

(run-sources+ (stop-when-fields-decayed
               50 Ey
               (vector3 (- (* 0.5 sx) dpml 0.5) 0)
               1e-3)
              (at-beginning output-epsilon)
              (during-sources
               (in-volume (volume (center 0 0) (size sx 0))
                (to-appended "hz-slice" (at-every 0.4 output-hfield-z)))))
(display-fluxes trans) ; print out the flux spectrum

**Comment by oskooi** [comment]
Your script works fine for me. Perhaps your `meep` Scheme binary is out of date? Try [building from source](https://meep.readthedocs.io/en/latest/Build_From_Source/) using the latest master.
