### ISSUE TITLE
Incorrect warning from add_dft_fields()?

### ISSUE THREAD

**Issue by Vinc0110** [NanoComp/meep#1249]
I'm adding a single-point DFT monitor for a list of fields with the following line:

`dft_monitor = self.sim.add_dft_fields([mp.Ex, mp.Ey, mp.Ez, mp.Hx, mp.Hy, mp.Hz],
                                              self.f_meep_center, self.f_meep_delta, self.n_freq_flux,
                                              center=pt_active_monitor, size=mp.Vector3())`

It throws the following warning:

`/home/vinc/meep_conda/envs/pmp_nightly/lib/python3.6/site-packages/meep/simulation.py:54: RuntimeWarning: add_dft_fields: df >= fcen (0.023349486663870645 >= 0.018346025235898365). input arguments are (fcen,df) rather than (freq_min,freq_max)
  warnings.warn("add_dft_fields: df >= fcen ({} >= {}). input arguments are (fcen,df) rather than (freq_min,freq_max)".format(df,fcen), RuntimeWarning)
`

As you see, my _df_ is indeed greater than _fcen_, but why should this be a problem? Maybe a warning should only be thrown if _df/2_ > _fcen_?

**Comment by oskooi** [comment]
This is a bug which is fixed by #1250.
