### ISSUE TITLE
Meep, python, macOS Catalina

### ISSUE THREAD

**Issue by anthmanni** [NanoComp/meep#1263]
Hello,
Is meep currently compatible with python 3.8.3 and macOS Catalina? I've installed meep and all its dependencies, and when I run 'make check' in the meep directory, all tests pass. However, when I try to run any of the python example files, I'm given "meep has no attribute: Vector3d" ... it appears meep has no attributes at all. I built everything from source and am using pyCharm as a virtual environment. I've tried installing and running in the terminal setting up a virtual environment and ran into the same issue.
Thanks for your time,
Anthony

**Comment by lighttn** [comment]
I installed meep. I have similar problem. I can run meep in terminal. But in python (spyder), import meep doesn't recognized. It says libctl is the one related that issue. I installed it. But it is not solving yet.

**Comment by RobinD42** [comment]
Are you sure that the same Python environment is being used in both cases? (The command-line and in the IDE.) You can check by looking at the value of `sys.prefix` in both cases. If they are the same then the next thing to do is to check the `sys.prefix` in both cases. One may be influenced by a `PYTHONPATH` setting that the other doesn't have.

**Comment by stevengj** [comment]
Yes, Meep works fine with MacOS 10.15 — I use it on my laptop with no problems.

Most likely, you have multiple Python distros installed and are either installing Meep for the wrong one (pass the correct `python` to `configure PYTHON=....` or are not setting your PYTHONPATH correctly after doing `make install`.

**Comment by lighttn** [comment]
Thank you, RobinD42 and stevengj, 

First, I check which python I have as following:
(base) MacBook-Pro-7:~ MyID$ which -a python
/Users/MyID/opt/anaconda3/bin/python
/usr/bin/python

I checked sys.prefix in python command: 
'/Users/MyID/opt/anaconda3'

In Spyder, PYTHONPATH manager add the following path. 
/Users/MyID/opt/anaconda3/pkgs/pymeep-1.15.0-nompi_py36h0cf7669_101

BUT It doesn't work. Which folder should I add?

**Comment by RobinD42** [comment]
If it was installed correctly then should have been installed into the `site-packages` for the Python environment. Based on your info above then it would be something like `/Users/MyID/opt/anaconda3/lib/python??/site-packages/meep`. If it was successfully installed then nothing extra should need to be done because `site-packages` is automatically on the Python path.

**Comment by RobinD42** [comment]
I just noticed that you mentioned Python 3.8, and I see that the conda packages are currently limited to Python 3.5 and 3.6. (See #1338 to track that issue.) Sorry for the confusion.

When following the build from source instructions the meep package will be installed at a location like `{prefix}/lib/python3.8/site-packages/meep`. For example, since I didn't specify a `--prefix` when I configure and build meep and it's dependencies then they end up in `/usr/local/lib/python3.8/site-packages` for me. That `site-packages` folder, under whatever {prefix} you specified for the builds is the one you should add to `PYTHONPATH`.

**Comment by stevengj** [comment]
Robin, we are talking about an Anaconda installation here, not building from source

**Comment by lighttn** [comment]
Hi Robin, 
I have a spyder (installed by anaconda) and the Python version is 3.7.6. 
I see the meep is installed under following path. "/Users/MyID/opt/anaconda3/envs/meep", (which includes folders like /bin, /conda-meta, /doc, /etc, /lib ...) I couldn't find a folder named site-package. Instead, I have "/Users/lighttn/opt/anaconda3/pkgs". which lncludes folder "pymeep-1.15.0-nompi_py36h0cf7669_101".

**Comment by lighttn** [comment]
Should I downgrade the python to 3.6 or 3.5?

**Comment by lighttn** [comment]
I just found the folder "/Users/lighttn/opt/anaconda3/lib/python3.7/site-packages", BUT I don't see "meep" folder under the folder above. 
Hm, the only way is to downgrade?

**Comment by stevengj** [comment]
Did you install Meep from the conda package, or from source, or both?

**Comment by lighttn** [comment]
I used conda and homebrew.

**Comment by stevengj** [comment]
> I used conda and homebrew.

Normally you would use one or the other.   When you have multiple versions of stuff (e.g. python) installed (it sounds like you have at least 3 python installations on your computer, since MacOS also comes with Python), you need to be pretty careful to be consistent about what you build with and use.

It's still not clear to me whether you installed Meep by downloading the source code and running the build script, or you used [the conda packages](https://meep.readthedocs.io/en/latest/Installation/#conda-packages).

But I have a suspicion that you've tried a sequence of increasingly desperate attempts to hack the installation using multiple methods and multiple software distributions (e.g. conda and homebrew, source and conda packages…), and i the process you've mucked up your system.   I would tend to recommend wiping your homebrew and anaconda installations, re-installing Conda, and then using the Meep conda package.

**Comment by RobinD42** [comment]
@lighttn, the recipes have been updated and new builds of pymeep-1.15.0 are now available on conda-forge for Linux and OSX, Python 3.6, 3.7 and 3.8. Please try again by creating a new conda environment and using `conda install pymeep` when that environment is activated, and let us know how it goes.

**Comment by lighttn** [comment]
@RobinD42 
I tried conda install pymeep. It tooks quite many hours. 
First I check my conda version: conda 4.8.4,
anaconda version: anaconda Command line client (version 1.7.2)
And I did 'conda install pymeep'. 
There are a huge amount of text lines in the ternimal

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for anaconda json5 jupyterlab jupyterlab_server: : 305it [59:Examining conflict for anaconda spyder qtawesome: : 305it [59:56,  3.06s/it] ......
....

There are many conflicts reported. 
I also check 'import meep' in my spyder. moduleNotfound.

**Comment by RobinD42** [comment]
Thanks, @lighttn. I'll take another look.

**Comment by RobinD42** [comment]
@lighttn, version 1.16.0 of Meep was released this week. Along with the release there were changes to how the conda packages are built and how the dependencies are defined. I tested with something that I hope comes close to your environment and I was able to install `pymeep` with no problems. Here are the steps I used:

* Create a new conda environment with `python=3.8` and activate the environment.
* Installed the `anaconda` set of packages. I used the `-c defaults` command-line option to ensure that the anaconda version of the packages would take precedence. I'm not sure if that matters. (Probably not.)
* I then installed `pymeep`. Conda added a few more dependencies and was finished relatively quickly.

```
conda create -y -n c-tmp38 python=3.8
conda activate c-tmp38
conda install -y -c defaults anaconda
conda install -y -c defaults pymeep
```

**Comment by lighttn** [comment]
@RobinD42 
I am following what you have done. Exactly same. 
In the last command, it is running for more than one day now. Should I continue? 

-- below
(c-tmp38) MacBook-Pro-26:~ lighttn$ conda install -y -c defaults pymeep
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for jupyterlab_server jupyterlab anaconda: : 299it [23:23:19,Examining conflict for jupyterlab_server jupyterlab anaconda: : 300it [23:23:19,Examining conflict for notebook anaconda nbconvert jupyterlab bokeh jinja2 sphinExamining conflict for notebook anaconda nbconvert jupyterlab bokeh jinja2 sphinExamining conflict for jupyterlab_server json5 jupyterlab anaconda: : 301it [23:Examining conflict for jupyterlab_server json5 jupyterlab anaconda: : 302it [23:Examining conflict for anaconda bokeh bkcharts dask distributed: : 302it [23:38:Examining conflict for anaconda bokeh bkcharts dask distributed: : 303it [23:38:Examining conflict for dask distributed: : 303it [23:43:07, 292.60s/it]         Examining conflict for msgpack-python dask anaconda distributed: : 304it [23:43:Examining conflict for msgpack-python dask anaconda distributed: : 305it [23:43:Examining conflict for dask anaconda distributed: : 305it [23:48:29, 212.88s/it]Examining conflict for locket partd anaconda dask distributed: : 306it [23:53:29Examining conflict for locket partd anaconda dask distributed: : 307it [23:53:29Examining conflict for dask anaconda tblib distributed: : 307it [23:58:28, 258.0Examining conflict for dask anaconda tblib distributed: : 308it [23:58:28, 270.3Examining conflict for anaconda path path.py: : 308it [24:03:33, 270.39s/it]    Examining conflict for anaconda flask itsdangerous: : 313it [24:29:17, 298.05s/iExamining conflict for anaconda flask itsdangerous: : 314it [24:29:17, 309.76s/iExamining conflict for sympy anaconda: : 314it [24:35:36, 309.76s/it]           Examining conflict for scikit-learn anaconda nltk: : 323it [25:22:38, 305.85s/itExamining conflict for scikit-learn anaconda nltk: : 324it [25:22:38, 310.52s/i|Examining conflict for get_terminal_size anaconda: : 324it [25:27:36, 310.52s/itExamining conflict for get_terminal_size anaconda: : 325it [25:27:36, 306.77s/i\Examining conflict for jupyterlab anaconda: : 325it [25:32:37, 306.77s/it]      Examining conflict for xlrd anaconda: : 327it [25:37:34, 302.72s/i-

**Comment by lighttn** [comment]
@RobinD42 The installation is finished. 
I can open the meep in the terminal. But "import meep" is not recognized in spyder.

**Comment by lighttn** [comment]
@RobinD42 Dear Robin, Many thanks for your supports. However, I did not solve the issue above yet. I really want to join the meep community to calculate the near-field of my gratings, etc. Could I ask you if you have some mins for the zoom meeting? So I can show you my problem. (my email: hyun-su dot kim at psi dot ch)

**Comment by anthmanni** [comment]
Hi All, 
Thank you so much for your help. Of course I was over complicating things. Conda installation of meep ended up working perfectly, and runs quite efficiently in PyCharm.
Best,
Anthony

**Comment by leo-usa** [comment]
I tried to re-install MEEP on my Mac. I am using MacOS Catalina 10.15.5. I use the following two commands from the MEEP installation document:

conda create -n mp -c chogan -c conda-forge pymeep
conda activate mp

Then I run the following command, I got error:

python -c 'import meep'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/leo/anaconda3/envs/mp/lib/python3.6/site-packages/meep/__init__.py", line 8, in <module>
    from . import _meep
ImportError: dlopen(/Users/leo/anaconda3/envs/mp/lib/python3.6/site-packages/meep/_meep.so, 2): Library not loaded: @rpath/libctlgeom.6.dylib
  Referenced from: /Users/leo/anaconda3/envs/mp/lib/python3.6/site-packages/meep/_meep.so
  Reason: image not found

Any idea?

Thanks!

Leo

**Comment by leo-usa** [comment]
After searching many pages on Internet, finally I found a GitHub installation guide, which is different from the MEEP Document. It replaced the command: conda create -n mp -c chogan -c conda-forge pymeep 
to
conda create -n mp -c conda-forge pymeep

Then it works. I don't know why, but it seem the MEEP Document is not updated.

Leo
