### ISSUE TITLE
absorbed power density tutorial

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#1276]
Someone recently asked about computing the absorbed power density in a dispersive material using the polarization fields.   I think actually there is an easy way to do it with our existing features.

The absorbed power density is `Re[E* dP/dt]` where P is the total polarization field, or in Fourier domain it is `Re[E* (-iωP)] = ωIm[E*P]` (where `E*P` denotes the dot product of `conj(E)` with `P`).    However, since `D = E + P`, this is equivalent to `ωIm[E*(D-E)]=ωΙm[E*D]` (since `E*E = |E|²` is purely real).

So, you just use the `dft_fields` feature to compute the Fourier-transformed `E` and `D` fields in a region (which is already supported), and then in post-processing compute `ωΙm[E*D]`.

A simple test case would be to have a cylinder of a Lorentzian absorbing material with an incident planewave, and then map out the absorbed power density.   Would be good to also compare to the net absorbed power (computed via `dft_flux`).

Note that `ωΙm[E*D]` will *not* include the absorption by a conductivity (if any), because of how conductivity is implemented in Meep.   However, you could include conductivity in post-processing by calculating ωΙm[(1+iσ/ω) E*D]`.

**Comment by oskooi** [comment]
Initial results for an E<sub>z</sub>-polarized planewave incident on a cylinder of SiO<sub>2</sub> from the [materials library](https://github.com/NanoComp/meep/blob/master/python/materials.py#L851-L863). A map of the absorbed photon density obtained using `ωΙm[E*D]` shows local absorption on the surface of the cylinder facing the incident source.

However, the total absorbed flux obtained by integrating the absorbed photon density using the interpolation weights from `get_array_metadata` does not match the same result computed using `dft_flux`, possibly due to a scaling issue? The result from `dft_flux` is larger by a factor of ~29.

![photon_density](https://user-images.githubusercontent.com/7152530/86544762-82851b80-bede-11ea-826d-8d13b46027d9.png)

```py
import numpy as np
import matplotlib
matplotlib.use('agg')
import matplotlib.pyplot as plt

import meep as mp
from meep.materials import SiO2

resolution = 50

r = 1.0  # radius of cylinder                                                                                                                                               

dpml = 1.0
pml_layers = [mp.PML(thickness=dpml)]

dair = 2.0

s = 2*(dpml+dair+r)
cell_size = mp.Vector3(s,s)

fcen = 1.0

# is_integrated=True necessary for any planewave source extending into PML                                                                                                  
sources = [mp.Source(mp.GaussianSource(fcen,fwidth=0.1*fcen,is_integrated=True),
                     center=mp.Vector3(-0.5*s+dpml),
                     size=mp.Vector3(0,s),
                     component=mp.Ez)]

symmetries = [mp.Mirror(mp.Y)]

geometry = [mp.Cylinder(material=SiO2,
                        center=mp.Vector3(),
                        radius=r,
                        height=mp.inf)]

sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size,
                    boundary_layers=pml_layers,
                    sources=sources,
	            k_point=mp.Vector3(),
	            symmetries=symmetries,
	            geometry=geometry,
	            force_complex_fields=True)

dft_fields = sim.add_dft_fields([mp.Dz,mp.Ez], fcen, 0, 1, center=mp.Vector3(), size=mp.Vector3(2*r,2*r))

flux_box = sim.add_flux(fcen, 0, 1,
                        mp.FluxRegion(center=mp.Vector3(x=-r),size=mp.Vector3(0,2*r),weight=+1),
                        mp.FluxRegion(center=mp.Vector3(x=+r),size=mp.Vector3(0,2*r),weight=-1),
                        mp.FluxRegion(center=mp.Vector3(y=+r),size=mp.Vector3(2*r,0),weight=+1),
                        mp.FluxRegion(center=mp.Vector3(y=-r),size=mp.Vector3(2*r,0),weight=-1))

sim.run(until_after_sources=100)

(x,y,z,w) = sim.get_array_metadata(dft_cell=dft_fields)
Dz = sim.get_dft_array(dft_fields, mp.Dz, 0)
Ez = sim.get_dft_array(dft_fields, mp.Ez, 0)

absorbed_photon_density = 2*np.pi*fcen * np.imag(np.conj(Ez)*Dz)
plt.pcolormesh(x,y,np.transpose(absorbed_photon_density),cmap='hot_r',shading='gouraud',vmin=0,vmax=np.max(absorbed_photon_density))
plt.xlabel("x")
plt.ylabel("y")
plt.gca().set_aspect('equal')
plt.title("absorbed photon density")
plt.colorbar()
plt.savefig('photon_density.png',dpi=150,bbox_inches='tight')

total_absorbed_photon_density = np.sum(w*absorbed_photon_density)
absorbed_flux = -1*mp.get_fluxes(flux_box)[0]

print("flux:, {}, {}".format(total_absorbed_photon_density,absorbed_flux))
```

```
Using MPI version 3.1, 1 processes
-----------
Initializing structure...
Halving computational cell along direction y
time for choose_chunkdivision = 0.00070434 s
Working in 2D dimensions.
Computational cell is 8 x 8 x 0 with resolution 50
     cylinder, center = (0,0,0)
          radius 1, height 1e+20, axis (0, 0, 1)
          dielectric constant epsilon diagonal = (1,1,1)
time for set_epsilon = 0.148661 s
lorentzian susceptibility: frequency=9.67865, gamma=0.0806554
-----------
Meep: using complex fields.
Meep progress: 31.740000000000002/200.0 = 15.9% done in 4.0s, 21.2s to go
on time step 3174 (time=31.74), 0.00126062 s/step
Meep progress: 63.79/200.0 = 31.9% done in 8.0s, 17.1s to go
on time step 6379 (time=63.79), 0.00124825 s/step
Meep progress: 95.84/200.0 = 47.9% done in 12.0s, 13.0s to go
on time step 9584 (time=95.84), 0.00124819 s/step
Meep progress: 127.8/200.0 = 63.9% done in 16.0s, 9.0s to go
on time step 12780 (time=127.8), 0.00125182 s/step
Meep progress: 159.45000000000002/200.0 = 79.7% done in 20.0s, 5.1s to go
on time step 15945 (time=159.45), 0.00126414 s/step
Meep progress: 191.18/200.0 = 95.6% done in 24.0s, 1.1s to go
on time step 19118 (time=191.18), 0.00126102 s/step
run 0 finished at t = 200.0 (20000 timesteps)
flux:, 0.5446501048672555, 15.893118065718301
```

**Comment by oskooi** [comment]
Whoops, there was a bug in the script in the way the absorbed power was being computed using `dft_flux` involving a closed, four-sided box surrounding the cylinder (two of the `weight` values needed to be flipped):
```
flux_box = sim.add_flux(fcen, 0, 1,
                        mp.FluxRegion(center=mp.Vector3(x=-r),size=mp.Vector3(0,2*r),weight=+1),
                        mp.FluxRegion(center=mp.Vector3(x=+r),size=mp.Vector3(0,2*r),weight=-1),
                        mp.FluxRegion(center=mp.Vector3(y=+r),size=mp.Vector3(2*r,0),weight=-1),
                        mp.FluxRegion(center=mp.Vector3(y=-r),size=mp.Vector3(2*r,0),weight=+1))
```
(Also, `force_complex_fields=True` can be removed from the `Simulation` constructor because it is not necessary.)

With this change, the values for the absorbed power computed using the two methods agree to within a relative error of ~0.015%:
```
flux:, 0.13616252647147556, 0.13618334277271416
```

**Comment by stevengj** [comment]
As discussed in #1281, to eliminate discretization artifacts the E⋅D dot product really needs to be done on the Yee grid and *then* interpolated to the centered grid.   It would be easiest to do this under the hood in the C++ code.
