### ISSUE TITLE
AttributeError: module 'meep' has no attribute 'MaterialGrid'

### ISSUE THREAD

**Issue by MalharJ** [NanoComp/meep#1280]
I installed meep with Conda and tried running this tutorial: https://nbviewer.jupyter.org/github/NanoComp/meep/blob/master/python/examples/adjoint_optimization/01-Introduction.ipynb, but got the bug

AttributeError: module 'meep' has no attribute 'MaterialGrid'.

How can I fix this?

**Comment by smartalecH** [comment]
You need to install the bleeding-edge version (i.e. build from source or install the conda nightly build) to run the adjoint tutorials.
