### ISSUE TITLE
Parallel version of HDF5 for MPI Meep

### ISSUE THREAD

**Issue by ilicog** [NanoComp/meep#1282]
When installing via the conda package route `conda create -n pmp -c conda-forge pymeep=*=mpi_mpich_*`, the HDF5 version is not parallelized (as reported by `h5cc -showconfig`).

Is there a workaround / way to force parallelized HDF5? (or perhaps compiling HDF5 against the mpicc/mpic++ in the conda environment?)

**Comment by oskooi** [comment]
The Conda packages are built using the parallel version of HDF5:

https://github.com/conda-forge/pymeep-feedstock/blob/5f6fe36238fd5d5bd8645e15e16454b3358e1e7c/recipe/meta.yaml#L54

Perhaps you have a conflicting serial HDF5 installed into your system directories?

**Comment by ilicog** [comment]
hm, it seems I'll have to debug on my end. On a vanilla CentOS install, it's parallel as you said.
Closing as solved. Thanks.
