### ISSUE TITLE
Nonlinear effects/Four wave mixing?

### ISSUE THREAD

**Issue by MalharJ** [NanoComp/meep#1288]
Is it possible to simulate nonlinear effects in meep, such as degenerate four wave mixing in silicon? A similar one in Lumerical would be along the lines of this: https://support.lumerical.com/hc/en-us/articles/360041718794-Four-wave-mixing-varFDTD-

**Comment by stevengj** [comment]
Yes. Meep supports chi3 nonlinearities, which are the source of four-wave mixing. 

(Though personally I find it more effective to use perturbation theory for this sort of thing.)
