### ISSUE TITLE
gray_indicator() returns incorrect type

### ISSUE THREAD

**Issue by Chuban** [NanoComp/meep#1299]
A typo in gray_indicator() ([python/adjoint/filters.py](https://github.com/NanoComp/meep/blob/7ff6c89de264408723891831a96ca67e53ae2115/python/adjoint/filters.py#L863)) is causing it to return an array. The doc string indicates that this was intended to return a float. I suspect that
`return np.mean(4 * x.flatten()) * (1-x.flatten()) * 100 `
should be
`return np.mean(4 * x.flatten() * (1-x.flatten())) * 100 `

**Comment by stevengj** [comment]
That sounds right.  Care to contribute a PR?
