### ISSUE TITLE
Tutorial and Jupyter notebook for absorbed power density; Yee_grid issue - from #1281

### ISSUE THREAD

**Issue by b10esun** [NanoComp/meep#1304]
I get the same results (i.e. artefacts) as those shown #1281 without the Yee_grid addition, so I know the code is working. However, as soon as I add in yee_grid=True line into the add_dft_fields section, I get the error below:

TypeError: add_dft_fields() got an unexpected keyword argument 'yee_grid'

Not sure why my meep jupyter notebook cannot read the yee_grid=True adaptation. 

Any thoughts/ideas?

Thanks

**Comment by oskooi** [comment]
Perhaps the version of Meep you are using is out of date and does not support that feature. The `yee_grid` argument to `add_dft_fields` was added in #1095. You need to be using [Meep v.1.13.0](https://github.com/NanoComp/meep/releases/tag/v1.13.0) or newer to access that feature. 

To determine the Meep version number:
```py
import meep as mp
print(mp.__version__)
```

**Comment by b10esun** [comment]
Thanks - that is the case. I am running Meep v.1.8.0-59-gd872b62
Old stuff.

Is there a straightforward way for me to install v1.13.0 via an Ubuntu terminal, which I am currently operating in? I have gotten the .zip file, but I think the location to put that is not so trivial. 

Many thanks

**Comment by oskooi** [comment]
To obtain the latest Meep binaries, the simplest method is to use the [Conda packages](https://meep.readthedocs.io/en/latest/Installation/#conda-packages). (Building from source can be tricky, especially if you are not familiar with building software on Unix-like/Linux systems.)

**Comment by b10esun** [comment]
Hi - Thanks.

I have a student who is working on this in a Mac (I am on Windows) and he sees that the most up-to-date version on the Mac is the v1.12.0. Is this the case?

I see on Linux it goes up to v1.15 at this point?

**Comment by b10esun** [comment]
Further to this, on my Windows/Ubuntu installation I seem to have (successfully?) installed the v1.15 via the Conda packages you have suggested. One tick mark check!

However, I am now getting the following error [ImportError: No module named materials] when I run this tutorial. It doesn't seem as though I can import anything from meep anymore. This is a bit odd, as I successfully ran it yesterday prior to the update.

Any thoughts?
Thanks!
Beth

**Comment by oskooi** [comment]
Currently, only the [Conda package for the nightly build](https://meep.readthedocs.io/en/latest/Installation/#nightly-build) contains the latest binaries for Linux and macOS. (The [Conda package for the tagged release](https://meep.readthedocs.io/en/latest/Installation/#official-releases) is only up to date for Linux, unfortunately.)

The correct way to import the materials library is:
```py
> import meep.materials
> meep.materials.Al
Medium()
```
or alternatively
```py
> from meep.materials import Al
> Al
Medium()
```
I suspect you tried doing:
```py
> import materials
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'materials'
```

**Comment by b10esun** [comment]
Thanks - about the macOS, do you have an anticipated release date for the new version? I appreciate if you don't, but just curious.


Regarding the code: I just was copying and pasting the text directly from the tutorial, so I was using:

```
> import meep as mp     # this works fine
> from meep.materials import SiO2 
```
The error I get, as mentioned is:  _ImportError:` No module named 'materials'_

I just tried your former code (using _import meep.materials_ and the error is the same ImportError)
 
My suspicion is that it has something to do with a kernelspec issue, and it isn't looking in the correct location for meep, but I am not sure...

**Comment by b10esun** [comment]
Quick update on my last comment:
As I suspected it was a kernelspec issue, my jupyter notebook was not running python 3, but rather python 2. I followed here: https://stackoverflow.com/questions/50914761/jupyter-notebook-cant-find-modules-for-python-3-6

And then made a new kernel in jupyter notebooks ensuring it was utilizing python 3 (upper right corner in jupyter notebook), and that worked.

Still curious about the macOS timeline, if possible to know it.

**Comment by b10esun** [comment]
Hi there,

The student I have using macOS has decided to try the Ubuntu desktop workaround to run Linux on his mac in order to get the most recent version of Meep. He is able to start up jupyter notebook fine, and he sees in his anaconda navigator that mp is an environment. However, when he runs the line
`import meep as mp`
into jupyter notebook, it gives the error 'No module named meep'. So somehow jupyter is not looking in the correct place

That said, he still can operate meep on his mac (outside of Linux/ubuntu desktop) but with an earlier version.

**Comment by stevengj** [comment]
Most likely you have multiple versions of Python installed on your machine and installed Meep for the wrong one.  You can configure Meep with `./configure PYTHON=/path/to/python` to specify a particular `python` installation.

**Comment by oskooi** [comment]
The macOS Conda package for the tagged release has been updated to the most version (`1.15.0`).
