### ISSUE TITLE
2d gaussian beams

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#1308]
As [commented in #1303](https://github.com/NanoComp/meep/pull/1303#issuecomment-668917384), our Gaussian beams (for #711) are really only correct in 3d.  In 2d, we need to apply the mathematical complex-point-source method to a *line* of dipoles, i.e. a "2d dipole" source.  There are two ways to do this:

1.  Just adapt the `green2d` function from `near2far.cpp`, extending it to allow a complex source point.   However, this would require Hankel functions supporting complex arguments, which we don't (yet) link to.  (GSL doesn't support this AFAIK.)  There are free-software Bessel functions by Amos (in Fortran) that implement this, which are wrapped by libraries like [openspecfun](https://github.com/JuliaMath/openspecfun), but it would add another dependency.

2. We could brute-force it — since we are only interested in localized Gaussian beams, we could just integrate the source in the z direction, either using a simple trapezoidal rule and truncating when the field decays enough or using a fancier scheme like Gauss–Hermite quadrature (since the beam is Gaussian with a known width).

Until we do this, our "2d Gaussian" isn't exactly a Maxwell solution and hence we'll have some backpropagating waves and other artifacts.

**Comment by smartalecH** [comment]
Closed by #2333.
