### ISSUE TITLE
Push some python timestepping to C

### ISSUE THREAD

**Issue by smartalecH** [NanoComp/meep#1309]
Currently, the python run functions loop every step and manually call `fields.step()` at each iteration:

https://github.com/NanoComp/meep/blob/d8bd779ba90731cb5e3439738322b74244424cbf/python/simulation.py#L2087-L2090

While this ensures maximum flexibility, I'm sure there's quite a bit of overhead looping in python and calling the swig function each iteration. There are quite a few python checks that are performed every timestep.

Would there be any performance gains if we had a dedicated `step_until(num_steps)` function in c, that was called through swig? This way, the python routine is only looping a few times (or only once in some cases) and there is minimal callback between the two?

Several of the current step-function modifiers only interrogate the fields after a certain number of steps anyway. It would be straightforward to adapt them to run this `step_until()` function between interrogation steps. Obviously this would only be worth it if we expect a decent speedup...

**Comment by stevengj** [comment]
> While this ensures maximum flexibility, I'm sure there's quite a bit of overhead looping in python and calling the swig function each iteration. There are quite a few python checks that are performed every timestep.

The cost of `fields.step` is surely vastly larger than the Python overhead?

**Comment by smartalecH** [comment]
> The cost of fields.step() is surely vastly larger than the Python overhead?

Absolutely, but that doesn't imply that the callbacks themselves are insignificant, especially for problems that have several 100,000 timesteps.

I can run a quick quantitive test to benchmark any gains.

**Comment by stevengj** [comment]
> Absolutely, but that doesn't imply that the callbacks themselves are insignificant, especially for problems that have several 100,000 timesteps.

I don't follow you.  If it spends 1% of the time in Python during one timestep, it also spends 1% of the time in Python during 10⁵ timestep.s

**Comment by smartalecH** [comment]
> All that should matter here is the fraction of the total runtime spent in Python overhead. Not the absolute amount of time spent in Python.

Yes, I see what you mean. I was hoping to save even a little bit for the really long simulations I run (on the order of several days) but you're probably right -- relatively speaking it's insignificant.
