### ISSUE TITLE
Stock material vs desginated n and k values

### ISSUE THREAD

**Issue by b10esun** [NanoComp/meep#1314]
We run the Meep Tutorial for absorbed power density, two times for c-Si material:

1. Using Si stock material in Meep Material Library (left of the attached slide)

2. Using manually input n and k values for c-Si from the literature (right side of slide)

In principle, the outputs should be exactly the same, however, it is clearly not the case. In run 2, the absorption is nearly zero throughout the entire region (max intensity is about e-11). The intensity scales are completely different.

Why are the outputs different? Does Meep analyse their Material Library different than just the standard n and k? Is there a unit issue?

Let me know if you need me to clarify anything further. Note: the excitation wavelength was the same for both runs, and the designated n and k values were designated appropriately for this.

[Absorption from Tutorial_Si_material.pptx](https://github.com/NanoComp/meep/files/5070615/Absorption.from.Tutorial_Si_material.pptx)

**Comment by stevengj** [comment]
How are you "manually inputting n and k values"?

**Comment by oskooi** [comment]
Note that the [`Medium`](https://meep.readthedocs.io/en/latest/Python_User_Interface/#medium) class has a member function `epsilon(freq)` which can be used to inspect its complex refractive index at a given frequency `freq`. As an example, crystalline silicon (`cSi`) from the materials library has an index of `13.64142192+0.04450991j` at a wavelength of 0.8 μm:

```py
>>> from meep.materials import cSi
>>> cSi.epsilon(1/0.8)
array([[13.64142192+0.04450991j,  0.        +0.j        ,
         0.        +0.j        ],
       [ 0.        +0.j        , 13.64142192+0.04450991j,
         0.        +0.j        ],
       [ 0.        +0.j        ,  0.        +0.j        ,
        13.64142192+0.04450991j]])
```
Probably the manually input values that you used do match those from the materials library.

**Comment by b10esun** [comment]
For Steven:
Most often the input of n and k would look something like (for wavelength = 0.785 um; note that I would change these parameters if I were to change the frequency and the values I am quoting here are from the literature):

`n_Si = 3.69 
k_Si = 0.00611
Sie1 = (n_Si**2)-(k_Si**2)  # dielectric constant of Si - 1
Sie2 = 2*n_Si*k_Si  # dielectric constant of Si - 2
D_cond_Si = 2*np.pi*mp_f*Sie2/Sie1`

then during the defintion of the material:

`def matf(r):
    x = r.x
    y = r.y
    else:
        return mp.Medium(epsilon=Sie1, D_conductivity=D_cond_Si)`

Following your note at the bottom Ardavan:
It does seem that the sqrt[13.641] is approximately the n_Si value I am inputting above, do I need to be squaring the n value for things to match? I wasn't aware that this was necessary.

**Comment by stevengj** [comment]
The absorbed power feature does not support conductivities yet if I recall correctly?

**Comment by b10esun** [comment]
Is that so? 
okay, then is this perhaps the problem?

**Comment by stevengj** [comment]
Yes, probably that’s what you’re seeing. We should document this limitation if we haven’t done so already.

**Comment by b10esun** [comment]
Thanks! Good to know.

Let me know if things change
