### ISSUE TITLE
Conda packages for newer Pythons

### ISSUE THREAD

**Issue by RobinD42** [NanoComp/meep#1338]
It seems that the conda packages for meep are limited to Python 2.7, 3.5 and 3.6. Is there a reason they shouldn't be updated to support 3.7, 3.8 and (soon) 3.9 as well?

**Comment by stevengj** [comment]
No reason that I can see.

**Comment by oskooi** [comment]
For reference, an overview of the Conda package is provided in [Developer Information/Conda Packages](https://meep.readthedocs.io/en/latest/Python_Developer_Information/#conda-packages).

**Comment by RobinD42** [comment]
And the conda-forge docs are at https://conda-forge.org/docs/

**Comment by RobinD42** [comment]
Do we have any metrics or estimates for how many Meep users are still using Python 2.7? I'm wondering how much effort I should put into keeping the conda recipe working for 2.7.  So far it looks like at least a few of the build and runtime dependencies may need to have py2-specific specs.

Conda-forge has said, "...Conda-forge is thus deprecating its Python 2.7 support. Conda-forge will provide no ongoing support for Python 2.7 builds and any existing builds are provided on an “as-is” basis."  which seems to be the general consensus for other Python runtime providers, except for ActiveState.

Status update:  I have local builds working for Linux and OSX for Python 3.6, 3.7 and 3.8, although I still need to do some more testing to verify that they are all working correctly.

**Comment by oskooi** [comment]
It seems that [`condastats`](https://condastats.readthedocs.io/en/latest/) can be used to obtain the download statistics of any package in the `conda-forge` channel. In fact, the subcommand `pkg_python` shows a breakdown by Python version. Unfortunately, when I tried running `condastats pkg_python pymeep`, it just stalls. 

(The page for the [tar.bz2](https://anaconda.org/conda-forge/pymeep/files) files containing the Conda package shows the download statistics but these files are only used for manual/offline installation.)

**Comment by stevengj** [comment]
I think it is fine to drop Python2.  Everyone else seems to be dropping it these days (finally).

**Comment by RobinD42** [comment]
Recipes have been updated and new builds of pymeep-1.15.0 are now available on conda-forge for Linux and OSX, Python 3.6, 3.7 and 3.8.
