### ISSUE TITLE
Choice of timescales in Multilevel Atomic Susceptibility

### ISSUE THREAD

**Issue by medbenz** [NanoComp/meep#1351]
Might be good to add a note in the documentation about the choice of timescales in Multilevel Atomic Susceptibility. 

In particular, I noticed that when some timescales are too short (e.g. large transition_rate), this can lead to divergences (nan values).

Thanks,

**Comment by stevengj** [comment]
@acerjan, Mohammed mentioned that you told him something about this.   Can you add more detail to the docs somewhere?

**Comment by acerjan** [comment]
yep, on it.
