### ISSUE TITLE
LED source tutorial clarification

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#1353]
Note that for smooth periodic functions, it is well known that a trapezoidal rule converges quite fast — generally even faster than the cosine-series expansion (comparable to a cosine+sine Fourier series) (see e.g. [these tutorial notes](http://math.mit.edu/~stevenj/trap-iap-2011.pdf), and Trefethen has written quite a bit about this as well).   So another competing approach would be to sample a set of dipole points and repeatedly double the sampling density until it converges — and in periodic cases, this could have similar or even better efficiency than the cosine-series approach if you use the right density of points.   You don't have to sample every grid point.

Two problems, however: (1) it probably won't converge as the cosine-series approach for non-periodic cases, and (2) repeatedly doubling the number of sampling points might overshoot the minimum number of points by more than if you increased the number of cosine-series terms one by one, especially if you have relatively coarse tolerances.

**Comment by oskooi** [comment]
The convergence rates of "Method 2" (point source) vs. "Method 3" (line source) are shown below. The error is defined as the L2 norm of the relative error in the averaged flux across all frequencies with the "exact" result being the flux at N=75 dipoles or M=15 cosine terms. Results for the point source are discontinuous as a function of the number of evenly spaced dipoles and the convergence rate is unclear but perhaps polynomial? The line source, however, shows results which are smooth and demonstrate exponential convergence with increasing number of cosine terms.

Are these results expected?

![method2_ndipoles_norm](https://user-images.githubusercontent.com/7152530/92836291-15d04680-f391-11ea-8cfc-629e2026c972.png)

![method3_costerms_norm](https://user-images.githubusercontent.com/7152530/92836304-1832a080-f391-11ea-8ac7-785dba9d1613.png)
