### ISSUE TITLE
Running the parallel version of Meep on a Cluster 

### ISSUE THREAD

**Issue by zebihcetin** [NanoComp/meep#1355]
I have installed parallel pymeep using the Conda package manager on a cluster, as explained here https://meep.readthedocs.io/en/latest/Installation/#conda-packages.

When i run parallel meep using
mpirun -np 12 python3 pythonCode.py
I get the following output: 

> Using MPI version 3.1, 1 processes
Using MPI version 3.1, 1 processes
Using MPI version 3.1, 1 processes
Using MPI version 3.1, 1 processes
Using MPI version 3.1, 1 processes
Using MPI version 3.1, 1 processes
Using MPI version 3.1, 1 processes
Using MPI version 3.1, 1 processes
Using MPI version 3.1, 1 processes
Using MPI version 3.1, 1 processes
Using MPI version 3.1, 1 processes
Using MPI version 3.1, 1 processes
Initializing structure...
time for choose_chunkdivision = 0.00165892 s
Working in 3D dimensions.
Computational cell is 6 x 6 x 12 with resolution 64
time for choose_chunkdivision = 0.00173116 s
Working in 3D dimensions.
time for choose_chunkdivision = 0.00163698 s>

But running the same command on my local computer, i get the following output :

>Using MPI version 3.1, 12 processes
Initializing structure...
Splitting into 6 chunks evenly
time for choose_chunkdivision = 0.00225592 s
Working in 3D dimensions.
Computational cell is 6 x 6 x 12 with resolution 64
time for set_epsilon = 0.0345771 s

Does that mean the parallel installation on the cluster is not running in parallel? any help would be greatly appreciated.

**Comment by oskooi** [comment]
Probably one of three things:
1. Rather than installing the parallel PyMeep Conda package on your cluster, you installed the serial version.
2. There are multiple conflicting versions (serial and parallel) of Meep installed (or you activated the wrong Conda environment)
3. Something is wrong with the MPI configuration (e.g., the hostname file).

**Comment by zebihcetin** [comment]
The problem appeared after i updated the conda package, i guess updating has interfered with my environment. Re-installation conda and then parallel PyMeep solved the problem. 
Thank you very much.
