### ISSUE TITLE
Version compatibility between Mac and Linux

### ISSUE THREAD

**Issue by momchilmm** [NanoComp/meep#1356]
I am using MEEP on both Mac and Linux machines. On linux, conda installs the latest version (1.15), but for some reason on Mac I can only get version 1.12. One consequence that took me some time to figure out is that DFT monitors work differently (specifying fmin and fmax vs f0 and fwidth), and the same script ran on Mac and Linux produces different results.

There may be a good reason why the current version is not supported on Mac, but it would be great if there's some way to at least show a warning about things like that, when the user is running an older version and calling something that has changed since.

**Comment by RobinD42** [comment]
Work on updating and fixing the conda recipes is in progress right now.

Just for curiosity's sake, which Python version are you trying to install `pymeep` into? Was it the `mpi` or `nompi` variant?

**Comment by stevengj** [comment]
See also #1263, #1338.

**Comment by stevengj** [comment]
According to [here](https://anaconda.org/conda-forge/pymeep), v1.15 is now available for MacOS?

**Comment by momchilmm** [comment]
I'm running python 3.7.9 and Mac OS 10.14.6 (haven't updated to Catalina). Just tried updating pymeep but it still stayed at 1.12.0.

**Comment by RobinD42** [comment]
Recipes have been updated and new builds of pymeep-1.15.0 are now available on conda-forge for Linux and OSX, Python 3.6, 3.7 and 3.8.
