### ISSUE TITLE
AttributeError: module 'meep' has no attribute 'GaussianBeamSource'

### ISSUE THREAD

**Issue by Mimifufu** [NanoComp/meep#1379]
Hello

I am trying to run this example: https://github.com/NanoComp/meep/blob/master/python/examples/gaussian-beam.py
and run into this problem. Meep version is 1.15.0.  Thank you!

**Comment by oskooi** [comment]
The `GaussianBeamSource` feature was added in #1310 which was *after* the 1.15 release and thus is *not* included in the tarball.

You will need to either build from source using the latest master branch or use the [Conda package for the nightly build](https://meep.readthedocs.io/en/latest/Installation/#nightly-builds) which was updated today for Linux and macOS.

**Comment by Mimifufu** [comment]
Hi, I updated to the nightly build version but showing error: No module named 'meep'
does `import meep as mp` correct in this version? Thank you.
