### ISSUE TITLE
h5topng and 1.16? 

### ISSUE THREAD

**Issue by Mimifufu** [NanoComp/meep#1385]
Hello

I am using 1.16.0-alpha.651486 since I need the Gaussian beam feature. I would like to verify the beam shape so I use ` mp.output_png`. However, looks like h5topng does not comes with 1.16? If try to use `conda install -c conda-forge h5utils` then it will downgrade the meep to 1.15. Is there any way to solve this problem, or can I use other available instruction instead? Thank you!

**Comment by RobinD42** [comment]
This issue should be solved by this change: https://github.com/Simpetus/pymeep-nightly-recipe/pull/18. When I do the following in a newly created environment, then it does pull in `h5utils` as expected.

```
conda install -c simpetus -c conda-forge pymeep
```

Please give it another try and let us know if there are still any problems.
