### ISSUE TITLE
Simulation using multiple cores consumes a multitude of RAM in v 1.15

### ISSUE THREAD

**Issue by kannesito** [NanoComp/meep#1394]
Hello,

I updated from v 1.12 to v1.15 and suddenly a simulation that used to work with mpirun and several cores crashed due to RAM overflow. For example, a simulation that I start with 1 core and takes 2GB RAM now needs n x 2GB RAM, n being the nr of cores. Also I get the console outputs n times (e.g. updates of time steps) in a time-delayed manner (order of several to tens of seconds).

Best,
Hannes

(P.S.: I just realized that there is a v1.16 out, didn't have the chance to test it yet!)

**Comment by kannesito** [comment]
Same issue in 1.16!

**Comment by oskooi** [comment]
> Also I get the console outputs n times (e.g. updates of time steps) in a time-delayed manner (order of several to tens of seconds).

One possibility could be that the parallel version of Meep was not installed correctly and that you are just launching multiple serial runs. See my [comment](https://github.com/NanoComp/meep/issues/1355#issuecomment-693105622) in #1355 for what might have caused this.

**Comment by kannesito** [comment]
Thank you for the hint! Reinstalling properly using pymeep=*=mpi_mpich_* solved the problem!

**Comment by oskooi** [comment]
We recently updated the recipes for the [Conda packages](https://meep.readthedocs.io/en/latest/Installation/#conda-packages) (official releases and nightly builds of the master branch) and they should now be more up to date and reliable than before.
