### ISSUE TITLE
Question of source setting

### ISSUE THREAD

**Issue by chenyudong92** [NanoComp/meep#1430]
Hi, 

I am the new user of the MEEP. For my simulation, I just want to set a Gaussian Source with rotation angle, waist width and divergence angle. And then, I want to let this source only propagate one direction. How do I define it？ Is there some examples could help me? Thanks a lot.

**Comment by stevengj** [comment]
See https://meep.readthedocs.io/en/latest/FAQ/#how-do-i-create-a-focused-beam-with-a-gaussian-envelope
