### ISSUE TITLE
Wrong geometry when using Prism

### ISSUE THREAD

**Issue by cparmenta** [NanoComp/meep#1439]
Hello, I’m using Meep (v.1.16.1 conda) to simulate tapered structures. I noticed that Prism object is not behaving properly. For example, here’s a simple script defining a linear 2D taper.
```python
import meep as mp
from matplotlib import pyplot as plt

w1 = 1.1
w2 = 0.7
sy = 4
Lin = 1.1
Lout = 1.1
Ltaper = 150
Ltotal = Lin + Lout + Ltaper

geometry = [
    mp.Block(
        center = mp.Vector3(-0.5*(Ltotal-Lin)),
        size = mp.Vector3(Lin, w1, mp.inf),
        material = mp.Medium(epsilon=12)
    ),
    mp.Block(
        center = mp.Vector3(0.5*(Ltotal-Lout)),
        size = mp.Vector3(Lout, w2, mp.inf),
        material = mp.Medium(epsilon=12)
    ),
    mp.Prism(
        center = mp.Vector3(),
        vertices = [
            mp.Vector3(-0.5*Ltaper, -0.5*w1),
            mp.Vector3(-0.5*Ltaper, 0.5*w1),
            mp.Vector3(0.5*Ltaper, 0.5*w2),
            mp.Vector3(0.5*Ltaper, -0.5*w2)
        ],
        height = 2,
        material = mp.Medium(epsilon=12)
    )
]

cell = mp.Vector3(Ltotal, sy)

sim = mp.Simulation(resolution=100,
                    cell_size=cell,
                    boundary_layers=[mp.PML(0.5)],
                    sources=[],
                    geometry=geometry,
                    eps_averaging=False,
)

sim.init_fields()
eps = sim.get_epsilon()

plt.figure()
plt.imshow(eps.T, cmap='binary', aspect='auto', interpolation='none', 
    origin='lower', extent=(-0.5*cell.x, 0.5*cell.x, -0.5*cell.y, 0.5*cell.y))
plt.xlabel('x'); plt.ylabel('y')
plt.title(f'$L_\mathrm{{taper}} = {Ltaper}$')
plt.show()
```
Launching this script for Ltaper = 50, 100 and 150 will give the following figures.
![L50](https://user-images.githubusercontent.com/27734762/100735772-0bdb4400-33d2-11eb-98f9-c64959c38eb6.png)
![L100](https://user-images.githubusercontent.com/27734762/100735787-1269bb80-33d2-11eb-938c-a4b6cfe7c432.png)
![L150](https://user-images.githubusercontent.com/27734762/100735795-14cc1580-33d2-11eb-9e6b-b43c91094f91.png)

As a workaround to this problem I had to add intermediate points to the taper prism modifying the script as follows.
```python
import meep as mp
from matplotlib import pyplot as plt

w1 = 1.1
w2 = 0.7
sy = 4
Lin = 1.1
Lout = 1.1
Ltaper = 150
N = 100

Ltotal = Lin + Lout + Ltaper
delta_L = Ltaper / (N + 1)
delta_w = 0.5 * (w2 - w1) / Ltaper * delta_L

geometry = [
    mp.Block(
        center = mp.Vector3(-0.5*(Ltotal-Lin)),
        size = mp.Vector3(Lin, w1, mp.inf),
        material = mp.Medium(epsilon=12)
    ),
    mp.Block(
        center = mp.Vector3(0.5*(Ltotal-Lout)),
        size = mp.Vector3(Lout, w2, mp.inf),
        material = mp.Medium(epsilon=12)
    ),
    mp.Prism(
        center = mp.Vector3(),
        # vertices = [
        #     mp.Vector3(-0.5*Ltaper, -0.5*w1),
        #     mp.Vector3(-0.5*Ltaper, 0.5*w1),
        #     mp.Vector3(0.5*Ltaper, 0.5*w2),
        #     mp.Vector3(0.5*Ltaper, -0.5*w2)
        # ],
        vertices = [mp.Vector3(-0.5*Ltaper + i*delta_L, 0.5*w1 + i*delta_w) 
                    for i in range(N + 2)] +
                   [mp.Vector3(-0.5*Ltaper + i*delta_L, -0.5*w1 - i*delta_w) 
                    for i in reversed(range(N + 2))],
        height = 2,
        material = mp.Medium(epsilon=12)
    )
]

cell = mp.Vector3(Ltotal, sy)

sim = mp.Simulation(resolution=100,
                    cell_size=cell,
                    boundary_layers=[mp.PML(0.5)],
                    sources=[],
                    geometry=geometry,
                    eps_averaging=False,
)

sim.init_fields()
eps = sim.get_epsilon()

plt.figure()
plt.imshow(eps.T, cmap='binary', aspect='auto', interpolation='none', 
    origin='lower', extent=(-0.5*cell.x, 0.5*cell.x, -0.5*cell.y, 0.5*cell.y))
plt.xlabel('x'); plt.ylabel('y')
plt.title(f'$L_\mathrm{{taper}} = {Ltaper}$ w/ {N} extra points')
plt.show()
```
Running this script with N = 5, 20 and 100 will return these figures:
![L150_N5](https://user-images.githubusercontent.com/27734762/100736076-87d58c00-33d2-11eb-9987-6bdde452e2fc.png)
![L150_N20](https://user-images.githubusercontent.com/27734762/100736085-8906b900-33d2-11eb-9224-c6d88c9d03e0.png)
![L150_N100](https://user-images.githubusercontent.com/27734762/100736087-899f4f80-33d2-11eb-88e9-2c151a1049fb.png)

Adding enough vertices will result in a really linear taper. However the subpixel averaging time will increase substantially. I have also tried enabling eps_averaging and 3D cells, but the behaviour is the same.

**Comment by stevengj** [comment]
As long as it converges to the correct geometry as you increase the resolution, I wouldn't consider it "wrong".

(However, if it is converging more slowly than it should, that would be a problem.   Does adding more points increase the accuracy, say of a transmission calculation, as computed relative to a higher resolution?)

**Comment by cparmenta** [comment]
Sorry, I forgot to include in my first message that increasing resolution won't solve my problem, but adding more vertices does. E.g. next figure uses the first script with `L = 100`, `resolution = 200` (twice the used in previous figures) and `eps_averaging=True`.
![Figure_1_](https://user-images.githubusercontent.com/27734762/100802861-6dc79800-342a-11eb-9298-f6bb653b1a5a.png)
I called it wrong because I would expect the taper to be linear with the 4 defined vertices, so the image should show "two staircases" (due to discretization) following the red lines.

I haven't done transmission calculations yet, since in what I'm really interested is in simulating structures like [Wang et al. (2015)](https://doi.org/10.1364/OL.40.001956) that use two coupled waveguides counter-tapered to separate modes. Not being able to define the taper correctly prevented me from simulating the device.

**Comment by oskooi** [comment]
Visualizing your taper structure comprised of a single `Prism` object using [`plot2D`](https://meep.readthedocs.io/en/latest/Python_User_Interface/#data-visualization) shows the expected geometry:

![taper_L3](https://user-images.githubusercontent.com/7152530/100805751-1b638880-33e4-11eb-9f2b-203a6dad2c6f.png)

![taper_L5](https://user-images.githubusercontent.com/7152530/100805558-b90a8800-33e3-11eb-8e3a-3d367b4803d5.png)

```py
import meep as mp
import matplotlib
matplotlib.use('agg')
from matplotlib import pyplot as plt

w1 = 2.0
w2 = 0.6
sy = 4
Lin = 1.1
Lout = 1.1
Ltaper = 12
Ltotal = Lin + Lout + Ltaper

geometry = [
    mp.Block(
        center = mp.Vector3(-0.5*(Ltotal-Lin)),
        size = mp.Vector3(Lin, w1, mp.inf),
        material = mp.Medium(epsilon=12)
    ),
    mp.Block(
        center = mp.Vector3(0.5*(Ltotal-Lout)),
        size = mp.Vector3(Lout, w2, mp.inf),
        material = mp.Medium(epsilon=12)
    ),
    mp.Prism(
        center = mp.Vector3(),
        vertices = [
            mp.Vector3(-0.5*Ltaper, -0.5*w1),
            mp.Vector3(-0.5*Ltaper, 0.5*w1),
            mp.Vector3(0.5*Ltaper, 0.5*w2),
            mp.Vector3(0.5*Ltaper, -0.5*w2)
        ],
        height = 2.0,
        material = mp.Medium(epsilon=12)
    )
]

cell = mp.Vector3(Ltotal, sy)

sim = mp.Simulation(resolution=100,
                    cell_size=cell,
                    boundary_layers=[mp.PML(0.5)],
                    sources=[],
                    geometry=geometry,
                    eps_averaging=False,
)

sim.plot2D()
plt.title("Ltaper = {}".format(Ltaper))
plt.savefig("taper_L{}.png".format(Ltaper),bbox_inches='tight',dpi=200)
```

**Comment by oskooi** [comment]
Note that you can create a taper geometry using a *single* `Prism` object as demonstrated in: [Tutorial/Mode Decomposition/Reflectance of a Waveguide Taper](https://meep.readthedocs.io/en/latest/Python_Tutorials/Mode_Decomposition/#reflectance-of-a-waveguide-taper).

**Comment by cparmenta** [comment]
It is only noticeable for long tapers.
![taper_L150](https://user-images.githubusercontent.com/27734762/100808491-8e94eb00-3434-11eb-9bdd-f341cbeea237.png)

(Added `plt.gca().set_aspect('auto')` before `savefig` to your code)

**Comment by oskooi** [comment]
You need to use `plt.gca().set_aspect('equal')`. It's obvious by the axes in your figure that the unequal axis dimensions are what is causing the distortion in the image.

**Comment by cparmenta** [comment]
Sorry, I expected the taper to remain linear after a linear scaling of the x axis.

Anyway, the original problem I wanted to simulate is the attached separator.gds file. I obtained the following fields with a continuous wave simulation. Zooming in it can be seen that the gap between the tapers is not constant as in the gds file. The lower taper reaches the final width too soon and the upper taper starts narrowing too late.
![separator](https://user-images.githubusercontent.com/27734762/102116858-e02e7400-3e3d-11eb-9d0b-1b6c42ddc227.png)

However, if I add extra vertices to the taper polygons the device shows the desired behaviour, i.e. the coupling occurs around the center of the device.
![separator_mod](https://user-images.githubusercontent.com/27734762/102116994-07854100-3e3e-11eb-9344-e6128eb8ba2a.png)
In this last case I couldn't use eps_averaging due to RAM limitations.

[gds_files.zip](https://github.com/NanoComp/meep/files/5690671/gds_files.zip)
