### ISSUE TITLE
Regeneralize adjoint simulation for multiple objective functions

### ISSUE THREAD

**Issue by smartalecH** [NanoComp/meep#1449]
We recently removed the ability to run the adjoint simulation for multiple *different* objective functions. See #1417.

Currently, it assumes each objective function is linearly combined into a "master" objective function, correspondingly adding all the individual adjoint sources. This obviously isn't what we want. Each independent objective function requires it's own adjoint run.

(Note that it's okay for each objective to be a function of multiple quantities (i.e. to have multiple adjoint sources). This is different from the behavior described above.)

**Comment by smartalecH** [comment]
Actually, it might be fine as is -- I'm just wondering if this is the best way to accomplish this...

**Comment by stevengj** [comment]
I'm not sure what you mean by multiple objectives.  Do you mean a single objective and multiple constraints?

**Comment by stevengj** [comment]
Probably @mochen4 wasn't thinking about this case…

**Comment by mochen4** [comment]
I think the current code is still able to run adjoint simulations for multiple objective functions. In fact, I have two objective functions (i.e. two adjoint runs at each step) for the focal sensitivity optimization problem that I am working on right now. #1417 was simply adding the functionality that, if you have several (scalar) objective functions, and each of them is about different frequencies, we can combine them into a single vector "master" objective function, so only one adjoint run is necessary. It is still able to run multiple objective functions as before.

Please let me if I understand the issue correctly, or if there are any other questions.

**Comment by smartalecH** [comment]
Yes, I think you're right Mo -- it should work for multiple objective functions.

The only downside from this implementation is that it's a little more work to debug adjoint simulations (i.e. it requires some more boilerplate code than before). That being said, I don't think there's any way to get around this. It's important to calculate the Jacobian and adjoint sources *before* we reset meep each time (as you do now). That means we have to loop through the adjoint simulations as you specified.

Thanks for the help!
