### ISSUE TITLE
MEEP for microwave waveguides

### ISSUE THREAD

**Issue by khazaddim** [NanoComp/meep#1450]
Hi, I was just wondering if meep can be used to model microwave waveguides with conductive walls.  I do not see an example on how to do this.  

Thanks, I am very much an amature at this.  Never done this kind of modeling before.

**Comment by stevengj** [comment]
Yes.

**Comment by khazaddim** [comment]
Thanks, I will look into that.  And sorry for asking here instead of the mailing list.  I just saw the FAQ.
