### ISSUE TITLE
A simple question about gaussian source in meep

### ISSUE THREAD

**Issue by zebihcetin** [NanoComp/meep#1451]
I am trying to use this `g(x)=a*exp(-0.5*((f-mu)/sigma)**2)` gaussian profile in meep. I am having a hard time relating parameters of this function, `a`, `mu` and `sigma` with `GaussianSource()` parameters, `amplitude`, `frequency` and `fwidth`. I did the following attempt but the resulting source profile width is too narrow and when i try to increase `fwidth` without changing `frequency` then the peak starts to move around. 
`sources = [mp.Source(src=mp.GaussianSource(frequency=mu, fwidth=sigma, is_integrated=True), 
						component=mp.Ex, 
						center=mp.Vector3(0, 0, -0.5 * sz + dpml), 
						size=mp.Vector3(sy,sx,0), 
						amplitude=a)]`
 
I have looked at documents on the web about sources and I also checked issues on github but so far i couldn't find any helpful information. It would be nice if someone could clarify this. 
Thank you very much.

**Comment by oskooi** [comment]
The formula for the Gaussian pulse and a description of the parameters are provided in: https://meep.readthedocs.io/en/latest/Python_User_Interface/#gaussiansource.
