### ISSUE TITLE
How to import mpb from meep

### ISSUE THREAD

**Issue by parimalsah04** [NanoComp/meep#1452]
Dear Sir

I have installed meep and mpb on ubuntu. I am running mpb_tri_rods.py file.  Here I am getting following error:
ImportError: cannot import name 'mpb' from 'meep
Please help me out to solve the error.

The code is as follows:

`import math
import meep as mp
from meep import mpb

num_bands = 8
resolution = 32
geometry_lattice = mp.Lattice(size=mp.Vector3(1, 1),
                              basis1=mp.Vector3(math.sqrt(3)/2, 0.5),
                              basis2=mp.Vector3(math.sqrt(3)/2, -0.5))
geometry = [mp.Cylinder(0.2, material=mp.Medium(epsilon=12))]
k_points = [
    mp.Vector3(),               # Gamma
    mp.Vector3(y=0.5),          # M
    mp.Vector3(-1./3, 1./3),    # K
    mp.Vector3(),               # Gamma
]
k_points = mp.interpolate(4, k_points)

ms = mpb.ModeSolver(
    geometry=geometry,
    geometry_lattice=geometry_lattice,
    k_points=k_points,
    resolution=resolution,
    num_bands=num_bands
)
ms.run_tm(mpb.output_at_kpoint(mp.Vector3(-1./3, 1./3), mpb.fix_efield_phase,
          mpb.output_efield_z))
tm_freqs = ms.all_freqs
tm_gaps = ms.gap_list
ms.run_te()
te_freqs = ms.all_freqs
te_gaps = ms.gap_list`

I am running the code by:
python mpb_tri_rods.py >& tri-rods.out

**Comment by Vinc0110** [comment]
The import of MPB works on my system with
`from meep import mpb`

If that does not work on your system, it probably means your Python environment is not configured correctly, so Python cannot find MPB. You can check your Python path like this:
`import sys`
`print(sys.path)`

**Comment by parimalsah04** [comment]
Dear Sir

Thank you very much for your quick and quality really.

When I installed miniconda, after running conda it shows no conda found. Is
there right path of installing miniconda on Ubuntu?

Please help me.

**Comment by Vinc0110** [comment]
After miniconda, anaconda or any other type of Conda is installed, you should be able to run `conda` in the terminal. This and all further steps are also explained in the documentation:
[https://meep.readthedocs.io/en/latest/Installation/#conda-packages](https://meep.readthedocs.io/en/latest/Installation/#conda-packages)

Installation of Meep:
`conda create -n mp -c conda-forge pymeep`

Every time you open a new terminal, you first need to activate the Conda environment you want to work with. In this example, it's called _mp_:
`conda activate mp`

Then, you can run Python and the import of Meep and MPB will work.

**Comment by stevengj** [comment]
Closing as this is more of a question (how to install MPB) than an issue.

**Comment by stevengj** [comment]
Thanks, @Vinc0110, for helping with a detailed answer here!
