### ISSUE TITLE
AttributeError: 'Simulation' object has no attribute 'get_array_slice_dimensions'

### ISSUE THREAD

**Issue by mawc2019** [NanoComp/meep#1457]
The example code for adjoint optimization throws errors when using Version 1.17. The error message is
**AttributeError: 'Simulation' object has no attribute 'get_array_slice_dimensions'**
This happens when opt.plot2D(True) or solver.optimize(x) is invoked. This error does not occur when using a previous version. The file simulation.py in the new version seems to lack the segment where get_array_slice_dimensions is defined.

**Comment by smartalecH** [comment]
See #1464.

You need to be running 1.17.1.

**Comment by mawc2019** [comment]
Thank you!
