### ISSUE TITLE
Finite grating scattered field example in MEEP Document: Python code result is different from the document 

### ISSUE THREAD

**Issue by leo-usa** [NanoComp/meep#1485]
I run the finite grating example in the tutorial, but the result is different from the document. I just need someone to run it and confirm that the result in the document is correct. It's the code on this page:

https://meep.readthedocs.io/en/latest/Python_Tutorials/Near_to_Far_Field_Spectra/

My result is in the attachment, you can see it's different from the one shown on this page. I have run quite a few MEEP examples including those related to this one: binary grating and metasurface lens, the results are all consistent with the document, so I suspect this one is not right.

Leo
<img width="941" alt="Screen Shot 2021-01-26 at 8 01 55 PM" src="https://user-images.githubusercontent.com/56208994/106063308-d048b780-60ac-11eb-8746-b5494739ffc6.png">

**Comment by oskooi** [comment]
I ran [python/examples/finite_grating.py](https://github.com/NanoComp/meep/blob/master/python/examples/finite_grating.py) *as-is* from [Tutorial/Near to Far Field Spectra/Diffraction Spectrum of a Finite Binary Grating
](https://meep.readthedocs.io/en/latest/Python_Tutorials/Near_to_Far_Field_Spectra/#diffraction-spectrum-of-a-finite-binary-grating) using the latest master and the field profile matches exactly what is shown in that tutorial (shown below).

![finite_grating_field_profile](https://user-images.githubusercontent.com/7152530/106100151-b7fa8c00-60f0-11eb-9b4f-02c2be511f36.png)

Note that the colorbar in your figure has a scale of `1e-16` which is an obvious sign that something is wrong. Perhaps you used a saturated color scale in the plot or changed some of the default parameters (e.g., the source amplitude)?

**Comment by leo-usa** [comment]
Ardavan,

I just ran the Python file from the link, but I still got the same result
as before. Here is the log file. I will try to re-install MEEP, see if it
will fix the problem.

-----------

Initializing structure...

Halving computational cell along direction y

time for choose_chunkdivision = 0.000468016 s

Working in 2D dimensions.

Computational cell is 14.5 x 9 x 0 with resolution 50

     block, center = (-5.75,0,0)

          size (3,1e+20,1e+20)

          axes (1,0,0), (0,1,0), (0,0,1)

          dielectric constant epsilon diagonal = (2.25,2.25,2.25)

time for set_epsilon = 0.389007 s

-----------

Meep progress: 12.200000000000001/125.0 = 9.8% done in 4.0s, 37.0s to go

on time step 1220 (time=12.2), 0.00328006 s/step

Meep progress: 24.990000000000002/125.0 = 20.0% done in 8.0s, 32.0s to go

on time step 2499 (time=24.99), 0.00312822 s/step

Meep progress: 37.72/125.0 = 30.2% done in 12.0s, 27.8s to go

on time step 3772 (time=37.72), 0.00314339 s/step

Meep progress: 50.410000000000004/125.0 = 40.3% done in 16.0s, 23.7s to go

on time step 5041 (time=50.41), 0.00315415 s/step

Meep progress: 63.07/125.0 = 50.5% done in 20.0s, 19.6s to go

on time step 6307 (time=63.07), 0.00316198 s/step

Meep progress: 75.56/125.0 = 60.4% done in 24.0s, 15.7s to go

on time step 7556 (time=75.56), 0.00320399 s/step

Meep progress: 87.66/125.0 = 70.1% done in 28.0s, 11.9s to go

on time step 8766 (time=87.66), 0.00330711 s/step

Meep progress: 100.35000000000001/125.0 = 80.3% done in 32.0s, 7.9s to go

on time step 10035 (time=100.35), 0.0031529 s/step

Meep progress: 112.72/125.0 = 90.2% done in 36.0s, 3.9s to go

on time step 11272 (time=112.72), 0.0032352 s/step

Meep progress: 124.82000000000001/125.0 = 99.9% done in 40.0s, 0.1s to go

on time step 12482 (time=124.82), 0.00330612 s/step

run 0 finished at t = 125.0 (12500 timesteps)

-----------

Initializing structure...

Halving computational cell along direction y

time for choose_chunkdivision = 0.000353813 s

Working in 2D dimensions.

Computational cell is 14.5 x 9 x 0 with resolution 50

     block, center = (-5.75,0,0)

          size (3,1e+20,1e+20)

          axes (1,0,0), (0,1,0), (0,0,1)

          dielectric constant epsilon diagonal = (2.25,2.25,2.25)

     block, center = (-4,-2,0)

          size (0.5,0.5,1e+20)

          axes (1,0,0), (0,1,0), (0,0,1)

          dielectric constant epsilon diagonal = (2.25,2.25,2.25)

     block, center = (-4,-1,0)

          size (0.5,0.5,1e+20)

          axes (1,0,0), (0,1,0), (0,0,1)

          dielectric constant epsilon diagonal = (2.25,2.25,2.25)

     block, center = (-4,0,0)

          size (0.5,0.5,1e+20)

          axes (1,0,0), (0,1,0), (0,0,1)

          dielectric constant epsilon diagonal = (2.25,2.25,2.25)

     block, center = (-4,1,0)

          size (0.5,0.5,1e+20)

          axes (1,0,0), (0,1,0), (0,0,1)

          dielectric constant epsilon diagonal = (2.25,2.25,2.25)

     block, center = (-4,2,0)

          size (0.5,0.5,1e+20)

          axes (1,0,0), (0,1,0), (0,0,1)

          dielectric constant epsilon diagonal = (2.25,2.25,2.25)

time for set_epsilon = 0.438338 s

-----------

Meep progress: 12.08/125.0 = 9.7% done in 4.0s, 37.4s to go

on time step 1208 (time=12.08), 0.00331635 s/step

Meep progress: 21.11/125.0 = 16.9% done in 8.0s, 39.4s to go

on time step 2111 (time=21.11), 0.00443288 s/step

Meep progress: 25.8/125.0 = 20.6% done in 12.0s, 46.2s to go

on time step 2580 (time=25.8), 0.00854998 s/step

Meep progress: 31.560000000000002/125.0 = 25.2% done in 16.2s, 47.9s to go

on time step 3156 (time=31.56), 0.00722111 s/step

Meep progress: 36.35/125.0 = 29.1% done in 20.2s, 49.2s to go

on time step 3635 (time=36.35), 0.00835759 s/step

Meep progress: 43.37/125.0 = 34.7% done in 24.2s, 45.5s to go

on time step 4337 (time=43.37), 0.0057083 s/step

Meep progress: 49.58/125.0 = 39.7% done in 28.2s, 42.9s to go

on time step 4958 (time=49.58), 0.00644152 s/step

Meep progress: 55.120000000000005/125.0 = 44.1% done in 32.2s, 40.8s to go

on time step 5512 (time=55.12), 0.00722371 s/step

Meep progress: 60.95/125.0 = 48.8% done in 36.2s, 38.1s to go

on time step 6095 (time=60.95), 0.00695764 s/step

Meep progress: 66.69/125.0 = 53.4% done in 40.2s, 35.2s to go

on time step 6669 (time=66.69), 0.00696983 s/step

Meep progress: 72.38/125.0 = 57.9% done in 44.2s, 32.2s to go

on time step 7238 (time=72.38), 0.00703092 s/step

Meep progress: 77.83/125.0 = 62.3% done in 48.3s, 29.2s to go

on time step 7783 (time=77.83), 0.0073451 s/step

Meep progress: 84.94/125.0 = 68.0% done in 52.3s, 24.6s to go

on time step 8494 (time=84.94), 0.00562759 s/step

Meep progress: 92.33/125.0 = 73.9% done in 56.3s, 19.9s to go

on time step 9233 (time=92.33), 0.00541472 s/step

Meep progress: 98.63/125.0 = 78.9% done in 60.3s, 16.1s to go

on time step 9863 (time=98.63), 0.00635656 s/step

Meep progress: 105.08/125.0 = 84.1% done in 64.3s, 12.2s to go

on time step 10508 (time=105.08), 0.00620398 s/step

Meep progress: 112.46000000000001/125.0 = 90.0% done in 68.3s, 7.6s to go

on time step 11246 (time=112.46), 0.00542328 s/step

Meep progress: 121.63/125.0 = 97.3% done in 72.3s, 2.0s to go

on time step 12163 (time=121.63), 0.00436536 s/step

run 0 finished at t = 125.0 (12500 timesteps)

Thanks!

Leo

**Comment by leo-usa** [comment]
I tried to re-install MEEP on my Mac. I am using MacOS Catalina 10.15.5. I
use the following two commands from the MEEP installation document:

conda create -n mp -c chogan -c conda-forge pymeep
conda activate mp

Then I run the following command, I got error:

python -c 'import meep'

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File
"/Users/leo/anaconda3/envs/mp/lib/python3.6/site-packages/meep/__init__.py",
line 8, in <module>

    from . import _meep

ImportError:
dlopen(/Users/leo/anaconda3/envs/mp/lib/python3.6/site-packages/meep/_meep.so,
2): Library not loaded: @rpath/libctlgeom.6.dylib

  Referenced from:
/Users/leo/anaconda3/envs/mp/lib/python3.6/site-packages/meep/_meep.so

  Reason: image not found


Any idea?


Thanks!


Leo

**Comment by leo-usa** [comment]
After searching many pages on Internet, finally I found a GitHub installation guide, which is different from the MEEP Document. It replaced the command: conda create -n mp -c chogan -c conda-forge pymeep
to
conda create -n mp -c conda-forge pymeep

Then it works. I don't know why, but it seem the MEEP Document is not updated.

I re-ran the finite-grating example, now I got the correct result. It looks like the MEEP version I downloaded before has a bug.

<img width="944" alt="Screen Shot 2021-01-29 at 8 37 49 PM" src="https://user-images.githubusercontent.com/56208994/106347274-1c912480-6272-11eb-981c-48a9f601dbfc.png">

Leo

**Comment by oskooi** [comment]
As described in [Installation/Conda Packages](https://meep.readthedocs.io/en/latest/Installation/#conda-packages), the Conda package for the latest release is available from the `conda-forge` channel. The `chogan` channel that you seem to have been using is discontinued and out of date.
