### ISSUE TITLE
Metal material problem

### ISSUE THREAD

**Issue by chenyudong92** [NanoComp/meep#1493]
Hi, All

When I want to introduce the Au as one of my structure layer, I can't get a convergence results. But, when I run my structure and Au layer separately with same source and boundary setting, I can get convergence results separately. I am not sure why?

For Au material, I introduce the material library, while I use frequency independent permittivity to build my other structure.

Could you somebody know what wrong? Thanks a lot

**Comment by oskooi** [comment]
Obtaining converged and accurate results can be challenging when lossy materials such as Au are present in the simulation. For reference, see the discussion in #1530 ([comment](https://github.com/NanoComp/meep/issues/1530#issuecomment-1002192047)).
