### ISSUE TITLE
Excitation with radially polarized field

### ISSUE THREAD

**Issue by yu-ting-py** [NanoComp/meep#1494]
The radially polarized light field is described as the longitudinal electric field _Ez_ and the transverse _Etr_ components. The formula of field can be found in OPTICS LETTERS / Vol. 34, No. 12 / June 15, 2009.

Is it possible to implement this kind of field for source in meep for field enhancement calculation?

![radial](https://user-images.githubusercontent.com/42253517/107028409-d0803b80-67ad-11eb-8995-5ff39ffb7b99.jpg)

J0, J1 are bessel function, P(theta) is pupil function of a bessel-gaussian beam.

**Comment by stevengj** [comment]
You can implement any field pattern you want just by putting in a current source with the desired field pattern function.      And of course, there are many different field patterns with radially polarized light, from Bessel beams to TEM modes in coaxial cables.

(In a 3d Meep simulation, you specify current sources in Cartesian coordinates, but of course it is a simple transformation from any desired radial polarization to the corresponding xyz components.)
