### ISSUE TITLE
GDS datatype import

### ISSUE THREAD

**Issue by flaport** [NanoComp/meep#1501]
Hi,

I'm getting started with importing gds files into meep and found this tutorial really helpful: https://meep.readthedocs.io/en/latest/Python_Tutorials/GDSII_Import.

However, I was wondering if there is a way to specify the datatype as well during import. Right now it seems that specifying a layer number imports all polygons irrespective of their datatype. It would be useful if I could specify a (layer, datatype) tuple instead of just the layer index.

Or maybe there's a different way to distinguish the datatypes of the imported volumes after importing? If so, I can't seem to find it.

**Comment by oskooi** [comment]
To import a layer as a tuple from a GDS file rather than as just a single number, you will need to use [`gdspy`](https://gdspy.readthedocs.io/en/stable/) because this feature is not supported by `libGDSII`.

Here is a demonstration of how to set this up:
```py
## load the GDS file                
gds = gdspy.GdsLibrary(infile=gds_file)

## define cell size and center                  
box = gds.top_level()[0].get_bounding_box()
cell_center = 0.5*mp.Vector3(box[1][0] + box[0][0],box[1][1] + box[0][1])

## define the geometry using all the polygons from layer (37,4)                    
polygons = gds.top_level()[0].get_polygons(True)[37,4]

design_geometry = []
for pg in polygons:
  vertices = []
  for vt in pg:
    # define vertices relative to center of cell                                           
    vertices.append(mp.Vector3(vt[0],vt[1])-cell_center)
    design_geometry.append(mp.Prism(vertices=vertices,
                                    height=0.5,
                                    axis=mp.Vector3(0,0,+1),
                                    material=mp.Medium(index=3.5)))
    design_geometry.append(mp.Prism(vertices=vertices,
                                    height=0.5,
                                    axis=mp.Vector3(0,0,-1),
                                    material=mp.Medium(index=3.5)))
```
Note that there are *two* `Prism` objects: one extending in the +z direction and the other in -z with a combined height of `1.0`.

It would probably be useful to add this example to https://meep.readthedocs.io/en/latest/Python_Tutorials/GDSII_Import.

**Comment by flaport** [comment]
Thanks a lot @oskooi, this method works good enough for me. 

It might still be useful to add native support for this into libGDSII as well. [I have opened an issue there](https://github.com/HomerReid/libGDSII/issues/13).
