### ISSUE TITLE
Failure of gdsII import from meep 1.12 to meep 1.15

### ISSUE THREAD

**Issue by simbilod** [NanoComp/meep#1511]
Last year I was using MEEP (v1.12) to perform 2D FDTD on a GDSII geometry generated by another software. It worked well, with the 2D epsilon distribution as expected from the mask.

When I use a conda environment with a newer version of MEEP (1.15), the exact same GDSII mask imported using the exact same code now only returns a constant epsilon array. The prisms still seem to be loaded as evidenced from the text output of `init_sim` being the same for both releases. 

This behaviour happens regardless of whether `eps_averaging` is set to False or True, and for various settings of `maxeval` and `tol` if True. The code we use is identical to the one from the [GDSII import tutorial](https://meep.readthedocs.io/en/latest/Python_Tutorials/GDSII_Import/), except with our own geometries and port locations.

The GDSII import example, still works fine for both versions, so this may be due to something in the geometry interacting with something that was introduced between these two releases. Any thoughts?

This is a visualization of the geometry as loaded in v1.12 :
![image](https://user-images.githubusercontent.com/46427609/109095282-69d5aa00-76e9-11eb-8cba-6b07a9ea2f1f.png)
In 1.15 this is just a constant array.

And here is the initialization output with default `eps_averaging` in v1.12 : 

> Initializing structure...
time for choose_chunkdivision = 0.000294209 s
Working in 2D dimensions.
Computational cell is 14.7656 x 14.7656 x 0 with resolution 64
     prism, center = (-0.476562,0,0)
          height 0, axis (0,0,1), 4 vertices:
          (-0.953125,-0.25,0)
          (-0.953125,0.25,0)
          (0,0.25,0)
          (0,-0.25,0)
          dielectric constant epsilon diagonal = (12,12,12)
     prism, center = (10,-10.4766,0)
          height 0, axis (0,0,1), 4 vertices:
          (9.75,-10.9531,0)
          (9.75,-10,0)
          (10.25,-10,0)
          (10.25,-10.9531,0)
          dielectric constant epsilon diagonal = (12,12,12)
     prism, center = (7.56641,-2.43359,0)
          height 0, axis (0,0,1), 4 vertices:
          (18.375,-13.5938,0)
          (-3.59375,8.375,0)
          (-3.23438,8.71875,0)
          (18.7188,-13.2344,0)
          dielectric constant epsilon diagonal = (12,12,12)
time for set_epsilon = 4.46206 s
MPB solved for omega_1(1,-2,0) = 0.454667 after 22 iters
MPB solved for omega_1(1.48447,-2.96894,0) = 0.645606 after 8 iters
MPB solved for omega_1(1.48335,-2.96669,0) = 0.645161 after 5 iters
MPB solved for omega_1(1.48335,-2.96669,0) = 0.645161 after 1 iters`

and 1.15 :

> Initializing structure...
time for choose_chunkdivision = 0.000291824 s
Working in 2D dimensions.
Computational cell is 14.7656 x 14.7656 x 0 with resolution 64
     prism, center = (-0.476562,0,0)
          height 0, axis (0,0,1), sidewall angle: 0 radians, 4 vertices:
          (-0.953125,-0.25,0)
          (-0.953125,0.25,0)
          (0,0.25,0)
          (0,-0.25,0)
          dielectric constant epsilon diagonal = (12,12,12)
     prism, center = (10,-10.4766,0)
          height 0, axis (0,0,1), sidewall angle: 0 radians, 4 vertices:
          (9.75,-10.9531,0)
          (9.75,-10,0)
          (10.25,-10,0)
          (10.25,-10.9531,0)
          dielectric constant epsilon diagonal = (12,12,12)
     prism, center = (7.56641,-2.43359,0)
          height 0, axis (0,0,1), sidewall angle: 0 radians, 4 vertices:
          (18.375,-13.5938,0)
          (-3.59375,8.375,0)
          (-3.23438,8.71875,0)
          (18.7188,-13.2344,0)
          dielectric constant epsilon diagonal = (12,12,12)
time for set_epsilon = 11.8167 s
MPB solved for frequency_1(1,-2,0) = 0.942809 after 15 iters
MPB solved for frequency_1(0.684297,-1.36859,0) = 0.645161 after 1 iters`

The geometries are the same (although all of the modes cannot be solved for the second time around?)

**Comment by oskooi** [comment]
Have you tried the latest release which is [1.17.1](https://github.com/NanoComp/meep/releases/tag/v1.17.1)? The currently available Conda package for the [official release](https://meep.readthedocs.io/en/latest/Installation/#official-releases) is also 1.17.1 (Linux only). Unfortunately, the macOS version of the Conda package has yet to be updated and is 1.16.1.

(We are currently in the process of updating the Conda packages; see conda-forge/pymeep-feedstock#56.)

**Comment by simbilod** [comment]
Thank you for the suggestion. I created a fresh conda environment on Linux which runs 1.17.1, and unfortunately get the same result as for v1.15.

I also note that while the epsilon distribution plot seems constant for MEEP 1.15 and 1.17, the array does contain a few different values for both `eps_averaging = True` and `False` (in MEEP v.1.12 where it worked properly, these range all the way to silicon at 12 as expected). 

`np.unique(eps_array)
array([2.25      , 2.45454545, 3.        , 3.375     , 5.4       ])`

So something is changing between 1.12 (at least) and newer versions when setting epsilon from loaded geometry.

**Comment by simbilod** [comment]
I think we found a suitable solution : if the zmax of the loaded geometry is not 0, the geometry loads fine. The cell zmax can be left to 0 for 2D simulations.
