### ISSUE TITLE
Query, is it possible to add optics model?

### ISSUE THREAD

**Issue by AravindChandradoss** [NanoComp/meep#1514]
On high level, say, we have source optics (laser, focus lens....), die layout, collection optics, sensor (camera)... All I'm interested is to generate the camera image (theoretical optical image) for various die layout/structure.

I want to know is there any option in MEEP, to include such optics model?

If so, can I get some pointers? or workaround? (btw, I did went through the doc, but didn't get much info on optics). 

Thanks!

**Comment by stevengj** [comment]
Meep models the full Maxwell equations of electromagnetism, which covers all of optics.  If you don't understand the low-level description of optics in terms of electromagnetic fields, however, you won't be able to use it.

(Sometimes by "optics model" what people really mean is an *approximate* optics solver, such as ray optics or scalar diffraction theory, which are useful for macroscopic phenomena.  This isn't covered by Meep — Meep only solves the exact Maxwell equations.)

**Comment by AravindChandradoss** [comment]
Thanks for the response, @stevengj! 
I am not from optics background, but, I am interested to know whether I can use MEEP for my analysis (coz, learning curve is bit steep). 
Basically, the notion is to render the optical image at sensor plane (camera) for a given die layout (with nano-scale particles/patterns on it) and for a given tool model (laser source, collection optics, sensors...). 

My understanding about MEEP is that, (plz, do correct me if I am wrong), we can model the entire tool (like laser sources, filters, polarizers, focus lens, collection optics...) and import die layout (GDSII), and run the simulation to get the optical image (intensity) at the camera plane. Or am I missing anything? 

Again, I'm not from optics background, but, I expect that the generate image should include the effects of near/far-field scattering, mie-scattering...  

Thanks!

**Comment by stevengj** [comment]
> generate image should include the effects of near/far-field scattering, mie-scattering

Meep includes all effects, because it includes all of electromagnetism.

> we can model the entire tool (like laser sources, filters, polarizers, focus lens, collection optics...)

In practice, this would probably be too large a simulation to do in a single model — typically you would model some of the components separately (possibly using different techniques) and then feed the output into a model for the next component.

But ultimately you'll have to figure this out on your own; electromagnetism is a large subject.

**Comment by AravindChandradoss** [comment]
> typically you would model some of the components separately (possibly using different techniques) 

different techniques means? 

> In practice, this would probably be too large a simulation to do in a single model 

The tool 'source model' is going to be constant (same for all runs)... in such case, we only need to simulate after the die layout (collection optics -> camera plane) coz, the only variable is die layout. Do you think, it would be still a large model to simulate? 

On a separate note, is it possible to combine all the optical model to a single block? more like single source and sink block... and use variable die layout in the middle to run the simulation? (single_source_block -> die_layout -> single_sink_block -> final_image)

> But ultimately you'll have to figure this out on your own; electromagnetism is a large subject.

yes, I can understand, the learning curve for using this simulator is also steep. That's the reason, I want to check whether my needs can be reach or not. -- in the first place. Thanks for you inputs @stevengj !
