### ISSUE TITLE
computing the normal vector to an interface for a MaterialGrid

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#1537]
The following schematic shows the analytic expressions necessary to compute the gradient of the `weights` array `u` for a `MaterialGrid` in 2d from which the normal vector to an interface can be obtained at any Yee grid point using bilinear interpolation. In the figure, the `MaterialGrid` are the green points and the Yee grid points for E<sub>x</sub> and E<sub>y</sub> are the blue and red points, respectively.

![Meep_Adjoint_Meeting_Notes](https://user-images.githubusercontent.com/7152530/112772182-4b164c00-8fe4-11eb-9266-254651d898fe.png)

To set this up, we will need to modify the existing `material_function::normal_vector` routine which uses spherical quadrature such that for the case of a `MaterialGrid` it uses the analytic formulas shown above:

https://github.com/NanoComp/meep/blob/272bd0caa1cd88665389c7edfb14f3194db7bcbb/src/anisotropic_averaging.cpp#L40-L64

We can then verify that the new approach to computing the normal vector is working correctly by comparing with the results obtained using spherical quadrature for e.g. a test case involving a cylinder (similar to [#1522 (comment)](https://github.com/NanoComp/meep/pull/1522#issue-586470739)).

**Comment by stevengj** [comment]
The first thing is to implement a function `matgrid_grad` that computes the gradient, similar to `matgrid_val`.   Then you can call this when computing the normal vector if you detect that that pixel is completely within a material-grid object.
