### ISSUE TITLE
Source setting problem

### ISSUE THREAD

**Issue by chenyudong92** [NanoComp/meep#1543]
Hi, all

I want to set a continue plane wave source at center of my structure. But, I found generated field is symmetric about original filed position. (as shown below). Is there any way to control the phase of two output direction to make it like a normal plane wave?

![field_profile](https://user-images.githubusercontent.com/57641431/113228911-8c646100-925b-11eb-84f1-bb3349d36788.PNG)

![symetry](https://user-images.githubusercontent.com/57641431/113228993-b027a700-925b-11eb-80a1-d6614d7f32f8.PNG)

**Comment by stevengj** [comment]
If you want to create a unidirectional planewave, you need to use both electric and magnetic currents as described here: https://arxiv.org/abs/1301.5366

The eigenmode-source feature will do that for you.

**Comment by Superwbb1999** [comment]
I added two sources with component components Ez and Hx, which can achieve unidirectional plane wave transmission in the normal direction, and the other half is well offset. But during oblique incidence, the other half being cancelled out is not in a good state. May I ask what is going on? Thank you.
sources = [
    mp.Source(
        mp.GaussianSource(fcen, fwidth=0.2228427 * fcen, is_integrated=False),
        center=mp.Vector3(0, 0, 0),       #源中心的位置
        size=mp.Vector3(s, 0, 0),        #线源的宽度（大小）
        component=mp.Ez,
        amp_func=pw_amp1(k1, mp.Vector3(x=0)),      #
    ),
    mp.Source(
        mp.GaussianSource(fcen, fwidth=0.2228427 * fcen, is_integrated=False),
        center=mp.Vector3(0, 0, 0),  # 源中心的位置
        size=mp.Vector3(s, 0, 0),  # 线源的宽度（大小）
        component=mp.Hx,
        amp_func=pw_amp2(k1, mp.Vector3(x=0)),
    ),
]

**Comment by Superwbb1999** [comment]
> If you want to create a unidirectional planewave, you need to use both electric and magnetic currents as described here: https://arxiv.org/abs/1301.5366
> 
> The eigenmode-source feature will do that for you.

I added two sources with component components Ez and Hx, which can achieve unidirectional plane wave transmission in the normal direction, and the other half is well offset. But during oblique incidence, the other half being cancelled out is not in a good state. May I ask what is going on? Thank you.
sources = [
    mp.Source(
        mp.GaussianSource(fcen, fwidth=0.2228427 * fcen, is_integrated=False),
        center=mp.Vector3(0, 0, 0),       #源中心的位置
        size=mp.Vector3(s, 0, 0),        #线源的宽度（大小）
        component=mp.Ez,
        amp_func=pw_amp1(k1, mp.Vector3(x=0)),      #
    ),
    mp.Source(
        mp.GaussianSource(fcen, fwidth=0.2228427 * fcen, is_integrated=False),
        center=mp.Vector3(0, 0, 0),  # 源中心的位置
        size=mp.Vector3(s, 0, 0),  # 线源的宽度（大小）
        component=mp.Hx,
        amp_func=pw_amp2(k1, mp.Vector3(x=0)),
    ),
]
