### ISSUE TITLE
Gaussian beam source in cylindrical coordinates

### ISSUE THREAD

**Issue by gpl-chs** [NanoComp/meep#1558]
Hello,
I try to use a gaussian beam in cylindrical coordinates.
I used this code to do so.
https://github.com/NanoComp/meep/blob/master/python/examples/gaussian-beam.py
Unfortunately, I'm getting the following error:
RuntimeError: meep: wrong dimensionality in gaussianbeam
I thought setting dimensions = mp.CYLINDRICAL meant that all the vectors are now in cylindrical coordinates.
If that were the case, why am I getting this error.
Please help.
Thank in advance

**Comment by oskooi** [comment]
The [`GaussianBeamSource`](https://meep.readthedocs.io/en/latest/Python_User_Interface/#gaussianbeamsource) feature is only supported in 2d and 3d Cartesian coordinates. It is not supported in cylindrical coordinates.
