### ISSUE TITLE
population density

### ISSUE THREAD

**Issue by ryouta1120** [NanoComp/meep#1561]
Hello

In multilevel atomic class(python), I want to access to local population density.
Then, measure volume averange it.
Is it possible?

Thank you

**Comment by oskooi** [comment]
Meep only allows you to specify the *initial* population levels through the Python API. Unfortunately, it is not currently possible to access the instantaneous population density `N` which is defined internally as a member of a [`C struct object`](https://github.com/NanoComp/meep/blob/master/src/multilevel-atom.cpp#L119-L128).

**Comment by ryouta1120** [comment]
Thank you very much, Ardavan.

If you don'm mind, I want to ask another question.

I'm trying to make multilevel-laser system in meep.
However I've struggled choose proper constant in meep units.

Off cource,I've already check meep website(also examples and materials), your papers and books. 
Furthermore, I know how to use other dispersion materials.
But I couldn't undarstand the units of population density and coupling tensor between the electric field and nonlinear polarization.

 Is it available to set up actual values for any application?

I'm sorry for disturbing you.

**Comment by acerjan** [comment]
First, if it's really necessary, you can likely find the population density from the polarization of the field in steady state given knowledge of the E field.

If I understand your question correctly, you're having difficulty finding values for sigma, and the various decay rates? In physical systems, choices of these values are highly dependent upon the actual gain materials used, so you'll have to dig through the experimental literature to find reasonable values for your system.

You may also wish to look at https://arxiv.org/abs/2007.09329.

If you can be a bit more specific about what you want to do, I might be able to help more.

**Comment by ryouta1120** [comment]
Thank you all.

I'll try again.
