### ISSUE TITLE
Segfault depending on import order and source type

### ISSUE THREAD

**Issue by mrbaozi** [NanoComp/meep#1564]
Hi, I came across a weird bug: The plotting routines in Meep cause a segfault if matplotlib is imported _before_ Meep and one uses eigenmode sources. See the following minimal snippet to reproduce (geometry is irrelevant, hence not included):

```python
import matplotlib.pyplot as plt
import meep as mp

fcen = 1 / 1.55
df = 0.2 * fcen
dpml = 1.0
res = 20
cell = mp.Vector3(10, 5)

sources = [
    mp.EigenModeSource(
        mp.GaussianSource(frequency=fcen, fwidth=df),
        size=mp.Vector3(0, cell.y),
        center=mp.Vector3(-cell.x / 2 + dpml),
        eig_band=1,
    )
]

sim = mp.Simulation(
    cell_size=cell, boundary_layers=[mp.PML(dpml)], sources=sources, resolution=res,
)

sim.plot2D()
plt.show()
```
This snippet gives a `SIGSEGV` in a fresh conda environment, latest pymeep. Changing the import order from
```python
import matplotlib.pyplot as plt
import meep as mp
```
to
```python
import meep as mp
import matplotlib.pyplot as plt
```
fixes the issue, as does changing the source from
```python
sources = [
    mp.EigenModeSource(
        mp.GaussianSource(frequency=fcen, fwidth=df),
        size=mp.Vector3(0, cell.y),
        center=mp.Vector3(-cell.x / 2 + dpml),
        eig_band=1,
    )
]
```
to
```python
sources = [
    mp.Source(
        mp.GaussianSource(frequency=fcen, fwidth=df),
        size=mp.Vector3(0, cell.y),
        center=mp.Vector3(-cell.x / 2 + dpml),
        component=mp.Ez,
    )
]
```
I can see how the import order might lead to conflicts, but the fact that the source type changes things baffles me a bit :sweat_smile:

**Comment by mrbaozi** [comment]
Small followup - I just noticed that the same thing happens if you're importing h5py, i.e. importing h5py before meep causes the same crash. Importing after meep is fine.

**Comment by oskooi** [comment]
I tried running the first example as-is (i.e., the `meep` module is imported *after* `matplotlib`) and it ran without any problems.

You mentioned that you were running in a "fresh conda environment" which could mean there is a module conflict because there exists another version of `matplotlib` or `meep` in e.g. a system directory somewhere? Can you try running in a different environment?

**Comment by mrbaozi** [comment]
Oh man :man_facepalming:... So it turns out that I had numpy pinned as a default package in my `.condarc` - it was installing the MKL version. Anyways, thank you for taking the time to look into it.
