### ISSUE TITLE
Import meep error with spyder

### ISSUE THREAD

**Issue by Rub-Ric** [NanoComp/meep#1565]
Hello,

I am a new user of Meep and I am facing issues when importing meep.

I am using Spyder (with Python 3.8) in meep environment, but when I import the package (```import meep as mp ```) the following error occurs:
```python
Traceback (most recent call last):

  File "<ipython-input-1-08e93272f3df>", line 1, in <module>
    runfile('/home/ruben/.config/spyder-py3/temp.py', wdir='/home/ruben/.config/spyder-py3')

  File "/usr/lib/python3/dist-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python3/dist-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/ruben/.config/spyder-py3/temp.py", line 10, in <module>
    import meep as mp

  File "/usr/lib/python3/dist-packages/meep/__init__.py", line 2600, in <module>
    class dft_ldos(object):

  File "/usr/lib/python3/dist-packages/meep/__init__.py", line 2639, in dft_ldos
    __swig_getmethods__["freq_min"] = get_omega_min

NameError: name '__swig_getmethods__' is not defined
```

From #965 it seems that the issue is solved, but it is not the case for me. I tried modifying the relevant file (__init__.py) but it is read-only. I am on Ubuntu 20.04.2 LTS, if that matters.

Thanks in advance!

**Comment by oskooi** [comment]
You may be using an older version of Meep which does not support SWIG 4.0 (added in #1159 and version [1.14.0](https://github.com/NanoComp/meep/releases/tag/v1.14.0)). Assuming you haven't tried to build from source and installed things into your system directory (which could create conflicts with the dependencies when trying to install elsewhere), can you try installing Meep version 1.18 using the [Conda package](https://meep.readthedocs.io/en/latest/Installation/#official-releases)?

**Comment by Rub-Ric** [comment]
Thanks for the answer!

I re-installed Meep with Conda (and SWIG as well, just to be sure) and it is now working with Jupyter Notebook, but still not with Spyder. This is fine for me as far as I am concerned, as I don't mind either of them.
