### ISSUE TITLE
How to create a truncated elliptical cone?

### ISSUE THREAD

**Issue by lpyzz** [NanoComp/meep#1567]
A hole shaped as a truncated elliptical cone may happen when an elliptical cylinder is to be fabracated, while imperfectness happens during the etching process. It seems that this can be harmful to the quality factor of a designed photonic crystal cavity; numerical simulation is required for assessment. 

A material function may be used, but the subpixel averaging tend to be slow. Is it possible to provide a concise guideline (for a work seems to be not so easy) to define a new type of geometric object? Some sourcecodes may have to be revised. I remember, for example that mentioned in #606, libctl need to be added. But there are probably more procedures need to be listed concisely. I want to try first on my own computer.  

Thanks a lot!

lpyzz

**Comment by stevengj** [comment]
The simplest way is to take a cone and use another object (e.g. a block) to "chop off" the tip.

Alternatively you could define a prism with a sidewall angle.
