### ISSUE TITLE
Issues for mpb calculating the photonic crystal with gyrotropic materials

### ISSUE THREAD

**Issue by zhiyut** [NanoComp/meep#1581]
I'm trying to calculate the photonic crystal band diagram with gyrotropic medium, as:
```
susc = [mp.GyrotropicLorentzianSusceptibility(frequency=f0, gamma=gamma, sigma=sn,
                                              bias=mp.Vector3(0, 0, b0))]
mat = mp.Medium(epsilon=epsn, mu=1, E_susceptibilities=susc)
geometry_lattice = mp.Lattice(size=mp.Vector3(1, 1, 0),
                              basis1=mp.Vector3(1, 0, 0),
                              basis2=mp.Vector3(0, 1, 0))
geometry = [mp.Sphere(0.15, material=mp.Medium(epsilon=5))]
```
the results is:
![image](https://user-images.githubusercontent.com/43514047/120097420-f10c4100-c162-11eb-9cfd-cd8381091b55.png)
**However, it is seems the same with the normal material:**
`geometry = [mp.Sphere(0.15, material=mat)]
`
![image](https://user-images.githubusercontent.com/43514047/120097841-3cbfea00-c165-11eb-9190-692126e62956.png)
 
If the mpb cannot support the gyrotropic medium for band calculation?

**Comment by stevengj** [comment]
MPB doesn't support dispersive materials.  You just specify the off-diagonal complex elements of the ε or µ tensors directly: https://mpb.readthedocs.io/en/latest/Python_User_Interface/#medium
