### ISSUE TITLE
mpb.py check test fail in meep-1.18.0

### ISSUE THREAD

**Issue by mmcilrath** [NanoComp/meep#1595]
I got the following errors in python/tests/mpb.py when running 
make check after building meep-1.18.0.
Does the first one indicate an actual problem?

mpb is 1.11.1 but I saw similar with 1.8.  
python is 3.6.8, with numpy 1.19.5.  

All other tests appear to have succeeded (meep and mpb).
RHEL7 with stock compilers, nothing special.

======================================================================
FAIL: test_diamond (__main__.TestModeSolver)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/mpb.py", line 726, in test_diamond
    self.compare_h5_files(ref_path, res_path)
  File "./tests/mpb.py", line 241, in compare_h5_files
    compare_arrays(self, ref[k][()], res[k][()], tol=tol)
  File "/u/mit/dist/meep-1.18.0/python/tests/utils.py", line 15, in compare_arrays
    test_instance.assertLess(diff, tol)
AssertionError: 0.6768965571384077 not less than 0.001

======================================================================
FAIL: test_epsilon_input_file (__main__.TestModeSolver)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/mpb.py", line 1244, in test_epsilon_input_file
    self.check_gap_list(expected_gap_list, ms.gap_list)
  File "./tests/mpb.py", line 217, in check_gap_list
    self.check_freqs(expected_gap_list, result)
  File "./tests/mpb.py", line 214, in check_freqs
    self.assertAlmostEqual(r, e, places=3)
AssertionError: 1.4651880980148877 != 1.469257717113039 within 3 places

======================================================================
FAIL: test_hole_slab (__main__.TestModeSolver)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/mpb.py", line 754, in test_hole_slab
    self.compare_h5_files(ref_path, res_path)
  File "./tests/mpb.py", line 239, in compare_h5_files
    self.assertEqual(ref[k][()], res[k][()])
AssertionError: b'h field, kpoint 1, band 9, freq=0.592619' != b'h field, kpoint 1, band 9, freq=0.59253'

======================================================================
FAIL: test_output_efield_z (__main__.TestModeSolver)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/mpb.py", line 485, in test_output_efield_z
    self.compare_h5_files(ref_path, res_path)
  File "./tests/mpb.py", line 241, in compare_h5_files
    compare_arrays(self, ref[k][()], res[k][()], tol=tol)
  File "/u/mit/dist/meep-1.18.0/python/tests/utils.py", line 15, in compare_arrays
    test_instance.assertLess(diff, tol)
AssertionError: 0.0013161313531953377 not less than 0.001

======================================================================
FAIL: test_strip (__main__.TestModeSolver)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/mpb.py", line 891, in test_strip
    self.assertAlmostEqual(e, r, places=3)
AssertionError: -0.9945407488966614 != -0.9950905164299376 within 3 places

----------------------------------------------------------------------
Ran 46 tests in 239.631s

FAILED (failures=5)

**Comment by ahoenselaar** [comment]
I observed the same while setting up a GitHub workflow to automatically run the unit test suites.

**Comment by stevengj** [comment]
Seems like this is now fixed?  CI is passing.
