### ISSUE TITLE
master build fails on macos

### ISSUE THREAD

**Issue by smartalecH** [NanoComp/meep#1617]
I'm trying to build off of master on macos 11.4 (intel hardware). I get several errors like the following (all relating to abort):

```
array_slice.cpp:727:20: error: no matching function for call to 'abort'
  if (!data.slice) abort("%s:%i: out of memory (%zu)", __FILE__, __LINE__, slice_size);
                   ^~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdlib.h:131:7: note: candidate function not viable: requires 0 arguments, but 4 were provided
void     abort(void) __cold __dead2;
```

I'm using the default build instructions in the manual (with mpi). I'm using openmpi 4.1.1 installed via homebrew. This method has been rather robust in the past. I'm wondering if the recent CI updates broke something?

**Comment by stevengj** [comment]
Maybe we should change `abort(...)` to `meep::abort(...)` everywhere to fix these ambiguities...

**Comment by stevengj** [comment]
I can't reproduce your problem, however — I'm building Meep `master` on macos 11.4 as well.

**Comment by stevengj** [comment]
Oh, with MPI I'm having the same problem.
