### ISSUE TITLE
Non-linear interpolation in phase_in_material(self, structure, time)

### ISSUE THREAD

**Issue by Nikolaos-MAtthaiakakis** [NanoComp/meep#1638]
Dear all,

I am interested in working on simulations involving dynamic control over the permittivity of the materials.

I see that phase_in_material(self, structure, time) is a great way to do so but seems to only linearly scale from one state to the other. I guess this could be overcome by including several geometry objects to try and achieve something that looks like a non-linear interpolation by having "goals" in between.

I was wondering if an alternative method can be included in the function itself.

I suppose is another option as suggested here https://meep.readthedocs.io/en/latest/FAQ/#can-meep-simulate-time-varying-structures is to " re-initialize the material at every timestep by calling field::set_materials or set_materials_from_geometry in C++, or simulation.set_materials in Python" but that would indeed take much longer to run.

It would be nice to have a more flexible version of  phase_in_material(self, structure, time)  if possible (I don't have a deep knowledge regarding how this is implemented). It would be useful for simulation real time responses obtained from carrier thermalization,  application of a voltage with delays due to capacitance, etc.

Is there any possibility for this to be included in the future?

Thank you very much

**Comment by stevengj** [comment]
Yes, we’ve definitely talked about this as nice to have.

 (I feel like there may already be an open issue for this?)

**Comment by Nikolaos-MAtthaiakakis** [comment]
I did find this one looking again https://github.com/NanoComp/meep/issues/207 sorry if it is overlapping with what I mentioned.

**Comment by stevengj** [comment]
No problem. Closing as a duplicate.
