### ISSUE TITLE
 error: ‘H5T_NATIVE_FLOAT’ was not declared in this scope  

### ISSUE THREAD

**Issue by MKAbdElrahman** [NanoComp/meep#1658]
I got the follwing error after running `make`

h5file.cpp: In member function ‘void meep::h5file::write_chunk(int, const size_t*, const size_t*, float*)’:
h5file.cpp:688:16: error: ‘H5T_NATIVE_FLOAT’ was not declared in this scope
  688 |                H5T_NATIVE_FLOAT, data);
      |                ^~~~~~~~~~~~~~~~
h5file.cpp: In member function ‘void meep::h5file::write_chunk(int, const size_t*, const size_t*, double*)’:
h5file.cpp:694:16: error: ‘H5T_NATIVE_DOUBLE’ was not declared in this scope
  694 |                H5T_NATIVE_DOUBLE, data);
      |                ^~~~~~~~~~~~~~~~~
h5file.cpp: In member function ‘void meep::h5file::read_chunk(int, const size_t*, const size_t*, float*)’:
h5file.cpp:829:15: error: ‘H5T_NATIVE_FLOAT’ was not declared in this scope
  829 |               H5T_NATIVE_FLOAT, data);
      |               ^~~~~~~~~~~~~~~~
h5file.cpp: In member function ‘void meep::h5file::read_chunk(int, const size_t*, const size_t*, double*)’:
h5file.cpp:835:15: error: ‘H5T_NATIVE_DOUBLE’ was not declared in this scope
  835 |               H5T_NATIVE_DOUBLE, data);
      |               ^~~~~~~~~~~~~~~~~
make[4]: *** [Makefile:660: h5file.lo] Error 1
make[4]: Leaving directory '/home/mk/Downloads/meep-1.19.0/src'
make[3]: *** [Makefile:721: all-recursive] Error 1
make[3]: Leaving directory '/home/mk/Downloads/meep-1.19.0/src'
make[2]: *** [Makefile:506: all] Error 2
make[2]: Leaving directory '/home/mk/Downloads/meep-1.19.0/src'
make[1]: *** [Makefile:515: all-recursive] Error 1
make[1]: Leaving directory '/home/mk/Downloads/meep-1.19.0'
make: *** [Makefile:422: all] Error 2
`
`

**Comment by stevengj** [comment]
What version of HDF5 do you have?  Those types should be defined by `hdf5.h`.

**Comment by oskooi** [comment]
I think the problem here is that you installed the *parallel* version of HDF5 and are trying to build *serial* Meep (the default in the configure script) without specifying `CC=mpicc CXX=mpic++` when configuring. This is why your compiler is unable to find `hdf5.h`. This procedure is actually explained in the [HDF5 build instructions of the user manual](https://meep.readthedocs.io/en/latest/Build_From_Source/#hdf5):

```
Note: If you have a version of HDF5 compiled with MPI parallel I/O support, 
then you need to use the MPI compilers to link to it, even when you are compiling 
the serial version of Meep. Just use ./configure CC=mpicc CXX=mpic++ or whatever 
your MPI compilers are when configuring.
```

**Comment by shamefulCake1** [comment]
No, this essense of this bug is that this error appears even if meep is built with `--without-hdf5`, so those functions should not even be compiled.

**Comment by shamefulCake1** [comment]
These lines are at the very bottom of this file, and there are no `#ifdef HAVE_HDF5`  guards in them, which is a bug really.

**Comment by stevengj** [comment]
See #2742
