### ISSUE TITLE
C++ to python 

### ISSUE THREAD

**Issue by ReDoDx09** [NanoComp/meep#1663]
Hello All,
i would be so grateful if someone help me to translate this part of code from C++ to python
Thank you 

#include <meep.hpp>
using namespace meep;
int main(int argc, char **argv) {
  initialize mpi(argc, argv); // do this even for non-MPI Meep
  double resolution = 20;     // pixels per distance
  grid_volume v = vol2d(5, 10, resolution); // 5x10 2d cell
  structure s(v, eps, pml(1.0));
  fields f(&s);

  f.output_hdf5(Dielectric, v.surroundings());

  double freq = 0.3, fwidth = 0.1;
  gaussian_src_time src(freq, fwidth);
  f.add_point_source(Ey, src, vec(1.1, 2.3));
  while (f.time() < f.last_source_time()) {
     f.step();
  }

  f.output_hdf5(Hz, v.surroundings());

  return 0;
}
double eps(const vec &p) {
  if (p.x() < 2 && p.y() < 3)
    return 12.0;
  return 1.0;
}

**Comment by ahoenselaar** [comment]
I would recommend to take a look at the [examples](https://github.com/NanoComp/meep/tree/master/python/examples) folder to get started.

**Comment by stevengj** [comment]
Closing this as it is not a specific issue or even a specific question.
