### ISSUE TITLE
setting the number of processes/threads for MPI/OpenMP tests

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#1671]
Currently, the number of MPI processes for tests is hard-coded to 2, and if OpenMP is enabled then it uses 2 threads.   See: https://github.com/NanoComp/meep/blob/89c93498ead04290b42acbb35b2c09c9813e04eb/configure.ac#L255-L265

This can be overridden by passing `RUNCODE` to `make`, e.g.
```sh
make RUNCODE="env OMP_NUM_THREADS=4 mpirun -np 3" check
```

Might be worth documenting this?

On a related note, whenever Coverage is found, it *doesn't* use MPI for the Python tests, because of this line: https://github.com/NanoComp/meep/blob/89c93498ead04290b42acbb35b2c09c9813e04eb/python/Makefile.am#L90-L94  .  Probably we should require the user to explicitly do `./configure --with-coverage` instead of [enabling it automatically](https://github.com/NanoComp/meep/blob/89c93498ead04290b42acbb35b2c09c9813e04eb/configure.ac#L575-L583) whenever the `coverage` module is found.

**Comment by oskooi** [comment]
Closed by #1672 and #1713.
