### ISSUE TITLE
error :Exited with exit code 7

### ISSUE THREAD

**Issue by RadouaneBjm** [NanoComp/meep#1679]
Hello everyone,
so i'm trying to do FDTD simulations using parallel meep but  after several steps I get this error : 

BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
 PID 40153 RUNNING AT hpc5-0103
EXIT CODE: 9
CLEANING UP REMAINING PROCESSES
YOU CAN IGNORE THE BELOW CLEANUP MESSAGES

[proxy:0:5@hpc5-0104] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:887): assert (!closed) failed
[proxy:0:5@hpc5-0104] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:5@hpc5-0104] main (pm/pmiserv/pmip.c:202): demux engine error waiting for event
[proxy:0:3@hpc5-0102] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:887): assert (!closed) failed
[proxy:0:3@hpc5-0102] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:3@hpc5-0102] main (pm/pmiserv/pmip.c:202): demux engine error waiting for event
[proxy:0:7@hpc5-0202] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:887): assert (!closed) failed
[proxy:0:7@hpc5-0202] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:7@hpc5-0202] main (pm/pmiserv/pmip.c:202): demux engine error waiting for event
[proxy:0:2@hpc5-0101] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:887): assert (!closed) failed
[proxy:0:2@hpc5-0101] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:2@hpc5-0101] main (pm/pmiserv/pmip.c:202): demux engine error waiting for event
[proxy:0:0@hpc4-0103] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:887): assert (!closed) failed
[proxy:0:0@hpc4-0103] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:0@hpc4-0103] main (pm/pmiserv/pmip.c:202): demux engine error waiting for event
[proxy:0:6@hpc5-0201] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:887): assert (!closed) failed
[proxy:0:6@hpc5-0201] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:6@hpc5-0201] main (pm/pmiserv/pmip.c:202): demux engine error waiting for event
[proxy:0:1@hpc4-0104] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:887): assert (!closed) failed
[proxy:0:1@hpc4-0104] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:1@hpc4-0104] main (pm/pmiserv/pmip.c:202): demux engine error waiting for event
srun: error: hpc5-0104: task 5: Exited with exit code 7
srun: error: hpc5-0101: task 2: Exited with exit code 7
srun: error: hpc5-0201: task 6: Exited with exit code 7
srun: error: hpc4-0103: task 0: Exited with exit code 7
srun: error: hpc4-0104: task 1: Exited with exit code 7
I'm using cluster for my simulation, before every simulation i allocate resources like this salloc --x11 --nodes=8 --cpus-per-task=8 --mem-per-cpu=16G --time=5:00:00
than i activate my virtuel env using conda and finally i run my code mpirun -np 64 python projs0Cpx.py
Here is my script :

import meep as mp
import math
import cmath
from matplotlib import pyplot as plt
from meep.materials import Al
from meep.materials import W

complex_f = True
eps_av = True
force_all_components=True
simulation_size = 21

dpml =3
sxx = simulation_size + dpml
sxy = simulation_size + dpml#simulation_size + dpml

def pw_amp(k, x0):
    def _pw_amp(x):
        return cmath.exp(1j * k.dot(x + x0))
    return _pw_amp

resolution = 50
t=50
cell_radius = 3
cell = mp.Vector3(sxx, sxy, 0)
pml_layers = [mp.PML(dpml)]
wavelength=0.002
f=1/wavelength
base_directory = "/home/red/meep_sim"
ri_cytoplasm = 1.4
#ri_media = 1.33
ri_thylakoid = 1.5
thylakoid_material = mp.Medium(index=ri_thylakoid)
cytoplasm_material = mp.Medium(index=ri_cytoplasm)
thylakoid_thickness = cell_radius / 3

kdir = mp.Vector3(1, 0, 0)  # direction of k (length is irrelevant)
n = 1 
k = kdir.unit().scale(2 * math.pi *f * n)  

thylakoid_region = mp.Sphere(radius=cell_radius,
                                     center=mp.Vector3(0, 0),
                                     material=thylakoid_material)
cytoplasm_region = mp.Sphere(radius=cell_radius-thylakoid_thickness,
                                     center=mp.Vector3(0, 0),
                                     material=cytoplasm_material)
geometry = [thylakoid_region, cytoplasm_region]

source = [
            mp.Source(
                mp.ContinuousSource(frequency=f),  # along x axis
                component=mp.Ez,
                center=mp.Vector3(-0.5 * simulation_size, 0),  # x, ,y ,z
                size=mp.Vector3(0, sxy, 0),
                amp_func=pw_amp(k, mp.Vector3(x=-0.5 * simulation_size))
            )
            ]

sim = mp.Simulation(
            cell_size=cell,
            sources=source,
            boundary_layers=pml_layers,
            resolution=resolution,
            geometry=geometry,force_complex_fields=complex_f,eps_averaging=eps_av)
        
base_directory = base_directory + str('projsRe')
sim.use_output_directory(base_directory)
nonpml_vol = mp.Volume(mp.Vector3(), size=mp.Vector3(sxx-2*dpml,sxy-2*dpml))       
near_fields = sim.add_dft_fields([mp.Ex,mp.Ey,mp.Ez],250,750,1000, where=nonpml_vol)
sim.run(mp.at_every(0.6,mp.output_efield,mp.output_bfield), until=t)

sim.output_dft(near_fields, "projsRe_dft")

**Comment by stevengj** [comment]
Exit code 9 is sigkill, which means something killed your job.   Maybe you were using too much memory, or ran too long, and the OS killed it.  See e.g. https://stackoverflow.com/questions/40888164/c-program-crashes-with-exit-code-9-sigkill

You are asking Meep to compute the Fourier-transformed (Ex,Ey,Ez) fields at 1000 frequencies over the entire 21x21 non-PML volume, at a resolution of 50.   This corresponds to 3×1000×21²×50² complex numbers (16 bytes each), or about 50GB for the DFT fields alone.   This is also quite expensive to simulate.

I would recommend starting with a much smaller simulation and ramping up to figure out how much compute power you need.  You might also want to re-think how you are approaching the problem in order to find a more efficient approach.

PS. You have a 2d simulation with an Ez source, so the Ex and Ey fields will be zero.
