### ISSUE TITLE
Calculation does not converge

### ISSUE THREAD

**Issue by RadouaneBjm** [NanoComp/meep#1686]
Good morning All,

i can't guess how much the simulation time should be, so after visiting meep readocs i found that **stop_when_fields_decayed(dt, c, pt, decay_by)** can do this. I found an example that shows how to use this function and the only thing I changed is “**pt**”. I supposed that this **point(pt)** should be at the end of cell (right side as shown in the picture) .
![Image](https://user-images.githubusercontent.com/87535204/126195093-8fcece9b-a1cb-4325-ab13-2aa4e64d8bad.jpeg)

after several iterations (field decay(t = 3350.62): 9.281924539535954e-23 / 5.6078298130578845e-22 = 0.16551722946232972
) calculation does not converge … i’m missing something ?

below my code 

`import meep as mp
import math
import cmath
from matplotlib import pyplot as plt
from meep.materials import Al
from meep.materials import W

complex_f = True
eps_av = True
force_all_components=True
simulation_size = 11

dpml =1
sxx = simulation_size + 2 * dpml
sxy = sxx#simulation_size + dpml

def pw_amp(k, x0):
    def _pw_amp(x):
        return cmath.exp(1j * k.dot(x + x0))
    return _pw_amp

resolution = 50
t=50
cell_radius = 2
cell = mp.Vector3(sxx, sxy, 0)
pml_layers = [mp.PML(dpml)]
wavelength=0.002
f=1/wavelength
base_directory = "/home/meep_sim"
ri_cytoplasm = 1.4
ri_thylakoid = 1.5
thylakoid_material = mp.Medium(index=ri_thylakoid)
cytoplasm_material = mp.Medium(index=ri_cytoplasm)
thylakoid_thickness = cell_radius / 2

kdir = mp.Vector3(1, 0, 0)  # direction of k (length is irrelevant)
n = 1  # refractive index of material containing the source
k = kdir.unit().scale(2 * math.pi *f * n)  # k with correct length

thylakoid_region = mp.Sphere(radius=cell_radius,
                                     center=mp.Vector3(0, 0),
                                     material=thylakoid_material)
cytoplasm_region = mp.Sphere(radius=cell_radius-thylakoid_thickness,
                                     center=mp.Vector3(0, 0),
                                     material=cytoplasm_material)
geometry = [thylakoid_region, cytoplasm_region]

source = [
            mp.Source(
                mp.ContinuousSource(frequency=f),  # along x axis
                component=mp.Ez,
                center=mp.Vector3(-0.5 * simulation_size, 0),  # x, ,y ,z
                size=mp.Vector3(0, sxy-2*dpml, 0),
                amp_func=pw_amp(k, mp.Vector3(x=-0.5 * simulation_size))
            )
            ]

sim = mp.Simulation(
            cell_size=cell,
            sources=source,
            boundary_layers=pml_layers,
            resolution=resolution,
            geometry=geometry,force_complex_fields=complex_f, eps_averaging=eps_av)
        
base_directory = base_directory + str('projsRe')
sim.use_output_directory(base_directory)
nonpml_vol = mp.Volume(mp.Vector3(), size=mp.Vector3(sxx-2*dpml,sxy-2*dpml))       
near_fields = sim.add_dft_fields([mp.Ez],250,750,500, where=nonpml_vol)
pt=mp.Vector3(+0.5*simulation_size,0)
sim.run(mp.at_end(mp.output_efield,mp.output_bfield), until=mp.stop_when_fields_decayed(50,mp.Ez,pt,1e-3))

sim.output_dft(near_fields, "projsRe_dft")`

**Comment by stevengj** [comment]
A `ContinuousSource` goes on forever — the fields will never decay.

`stop_when_fields_decayed` is only useful for sources that turn on, typically gaussian pulses.

**Comment by RadouaneBjm** [comment]
@stevengj  Thank you for your answer.

what should i do in order to know that the continuous source (in my case plane wave ) went through the whole cell ? 
also I tried with materials available in meep (aluminum and  tungsten) and it worked for (field decays after 1000 sec )
field decay(t = 1000.1): 4.0285364810481384e-11 / 5.132040109352269e-08 = 0.0007849775908233485) 
Elapsed run time = 1244.9162 s

Field time usage:
        connecting chunks: 0.540769 s
            time stepping: 565.177 s
            communicating: 381.813 s
        outputting fields: 189.977 s
     Fourier transforming: 0.0852089 s
          everything else: 101.601 s

**Comment by stevengj** [comment]
> what should i do in order to know that the continuous source (in my case plane wave ) went through the whole cell ?

It depends on your structure, since you need to run long enough for any transient modes to decay away.    The simplest approach is to keep doubling the runtime until whatever you are trying to compute stops changing to within your tolerance.

What are you trying to compute?

**Comment by RadouaneBjm** [comment]
for the moment I'm trying to propagate an electromagnetic wave from left to right (from -x to x as shown in the picture)  through an object with different refractive index and collect the Electric & magnetic field's, compute the Fourier transform for all the cell (except PML layers) 
but I don't know when i should stop the simulation or how to find the correct run time.
![Image](https://user-images.githubusercontent.com/87535204/126231373-d8309e73-4750-4cfd-b864-7c26562b59bc.jpeg)

**Comment by stevengj** [comment]
Use a Gaussian pulse. The DFT feature in Meep lets you extract the Fourier components you want.
