### ISSUE TITLE
complex refractive index

### ISSUE THREAD

**Issue by ReDoDx09** [NanoComp/meep#1689]
Hello All,
I want to create my own material object (medium) with a complex refractive index (n=1-delta-j*beta) where alpha is related to the phase shift and beta incorporates the absorption (attenuation). 
can i specify beta and delta for my customized material using meep? if yes, how to do that?

Thank you .

**Comment by stevengj** [comment]
Meep supports absorption and complex refractive indices (complex ε and/or μ), but these *must* have dispersion (frequency dependence) in the time-domain Maxwell equations.

If you only care about a narrow bandwidth, an easy way to do this is by specifying a conductivity:
https://meep.readthedocs.io/en/latest/Materials/#conductivity-and-complex

More generally, see: https://meep.readthedocs.io/en/latest/FAQ/#how-do-i-import-n-and-k-values-into-meep

**Comment by ReDoDx09** [comment]
Thank you very much ! 
in my case it's a narrow bandwidth, so if I understand correctly the complex refractive equals epsilon where epsilon=Reel+j*imginary (Reel=1-delta) and imaginary=beta ?  my syntax should be like :
meep.Medium(epsilon=1-alpha, D_conductivity=2*math.pi*f*beta/(1-delta)) ?

**Comment by stevengj** [comment]
ε is the dielectric constant.

**Comment by oradwastaken** [comment]
I would like to solve for modes in a cylindrical waveguide that might have some loss-ey materials.

To do so, I would like to specify a conductivity for a "narrow bandwidth" for a medium in my MPB ModeSolver. Does MPB not support this work-around? I am getting the following warning:
`ComplexWarning: Casting complex values to real discards the imaginary part`
