### ISSUE TITLE
Question about implementation of subpixel smoothing 

### ISSUE THREAD

**Issue by chendw98-1664366** [NanoComp/meep#1697]
Dear all, 

I'm self-learning FDTD and find the book referenced this project for subpixel smoothing. I have some question about this method's implementation, so sorry for bothering!
<img width="245" alt="Screen Shot 2021-07-21 at 3 29 41 PM" src="https://user-images.githubusercontent.com/59671868/126548378-7904434d-183a-47cb-b5b8-d73459d3a2f6.png">
I see this being used in the book where the average of inverse of permittivity is used for normal direction of isotropic material interface and the other one for the parallel directions. If considering 2D case, because of the projection matrix, the generated permittivity matrix should be a 2x2 matrix that contains off-diagonal terms which are epsilon_xy and epsilon_yx right?
And this operation is performed at each questioning point which means ,for 2D, the location of Dx, Dy and the node for interpolation. However, wouldn't this make there exist a 2x2 matrix at each location of Dx and Dy and since they are at different locations so the effective permittivity generated should be different? So, I want to understand that is it true for location Dx, just epsilon_xx is selected from the generated 2x2 permittivity matrix at that location and the similar operation is done for the matrix at location Dy? 
If so, how about the value of epsilon_xy and epsilon_yx? And why doing this will preserve the property that the epsilon^-1 tensor is a PSD operator? (I think if not doing this selecting process, it is a PSD operator but I don't know why this will still be the case). 
If not, is it possible for me to check how it is implemented?

Thank you so much for your time reading this and sorry if this actually has an obvious answer :( 

Best,
Justin

**Comment by stevengj** [comment]
Yes, it gives an ε matrix.   The implementation of the off-diagonal elements on the Yee grid is a bit tricky, and is described e.g. in http://math.mit.edu/~stevenj/papers/OskooiKo09.pdf based on https://www.sciencedirect.com/science/article/pii/S0021999107002227?via%3Dihub

**Comment by chendw98-1664366** [comment]
Hi professor,

I've read that paper and interpolation method it referenced. That's where I'm confusing about.
1. In the paper you wrote, it seems that the smoothing is taken at [i, j] and [i , j +- 0.5], [i +-0.5, j] for 2D. And just the corresponding epsilon_xy or epsilon_xx or epsilon_yy is choosen from the resulting matrix. I want to make sure this understanding is correct~
2. With this choosing behavior, why it preserves that epsilon^-1 is still a PSD operator as the interpolation paper requires? I understand average with uniform epsilon will give me a PSD epsilon^-1 operator if the component are all from the same location. But if they are constructed from values from different location, why this will still be the case?

Really thank you for your response! 

Best,
Justin
