### ISSUE TITLE
X-ray simulations ?

### ISSUE THREAD

**Issue by RadouaneBjm** [NanoComp/meep#1699]
Dear Meep users and developers,

I would like to know if it is possible to do FDTD simulations using meep because after looking at the meep documentation I think I have two problems
the first one is related to the **resolution**, meep has a rule of thumb for the grid resolution; at least 8/wavelength but most X-rays have a wavelength ranging from 1e-5 to 0.01 micrometers which means that the resolution will be between 800 and 8e+5 so it will be very complicated to do calculations even with Cluster
the second problem is related to the **parameter S (Courant)**, the refractive index of X-rays is always less than one, so I have to reduce S for numerical stability, which means that the calculation time will also increase.
Given these two problems, is it practical to run FDTD simulations? For example, if the condition for resolution is not satisfied, will the result have a big fault?

Best Regards,

**Comment by stevengj** [comment]
The computational cost really depends on the diameter of your computational cell divided by the wavelength.   If you want to model a system that is 100λ in diameter (or periodic), that is do-able, for any λ. 

*Directly* modeling systems that are 10000λ in diameter or more are not really practical, regardless of the λ.

(You can still model systems of such size, but you need to be more clever — break it up into small components that can be modeled individually, and then put them together in some other way.  A classic example of this is ray optics — the Fresnel reflection coefficients at interfaces are determined from the full Maxwell equations, but once you know these you can just do ray tracing as long as your radius of curvature is much larger than the wavelength.)

(Of course, at X-ray wavelengths you also have to worry about whether continuum models of materials are accurate … at some point you start to see individual atoms.)
