### ISSUE TITLE
What is the default_worker-eps-000000.00.h5 file?

### ISSUE THREAD

**Issue by ThyrixYang** [NanoComp/meep#1706]
Can we avoid creating this file?

---

I noticed that this file will be created in the workdir. Is this file shared among the different processes of meep? Will this file be modified by different processes?

---

I want to run multiple meep instances in parallel, will this file affect the output of each instance?

**Comment by stevengj** [comment]
If you are running the Scheme-based `meep` program, then the `run-kpoints` function calls `output-epsilon` by default, which uses the filename that you are running it from.    If you are running Meep in parallel with MPI, then only a single `.h5` file is outputted, so no worries.  (You could suppress it by `(set! output-epsilon (lambda () 0))`, I guess.)

In the Python Meep interface, I don't think it ever outputs an HDF5 file by default?
