### ISSUE TITLE
flush zero subnormals

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#1708]
During the beginning of a simulation, when the sources are exponentially small, depending on the cutoff parameters we might be seeing [subnormal values](https://en.wikipedia.org/wiki/Denormal_number) — these are values with magnitudes `< 2.2e-308` in double precision and `< 1.2e-38` in single precision.     Unfortunately, on many CPUs the floating-point computations are much slower for subnormal values.

Since we don't actually care about representing such small values accurately, you can change the floating-point mode to simply "flush" subnormal values to `0.0`.    It might be good to just do this unconditionally when Meep is initialized.

How to do this is CPU-specific, but on x86 processors you can call the `_mm_set_csr` intrinsic.  Here is an example of how it is done in the Julia standard library: https://github.com/JuliaLang/julia/blob/bb5b98e72a151c41471d8cc14cacb495d647fb7f/src/processor_x86.cpp#L1087-L1104
(This code is [MIT-licensed](https://github.com/JuliaLang/julia/blob/master/LICENSE.md), which is GPL-compatible, so we can simply copy it into Meep if we want.)

(This needs to be done per-thread, so for OpenMP-enabled runs we will need to call this on each thread.)

**Comment by stevengj** [comment]
In addition, it would be good to check the default cutoff for Gaussian and CW sources to make sure that the cutoff is not so far in the tail that the values are subnormal.

**Comment by stevengj** [comment]
Note that on Apple M4 processors, we will need different code, e.g. here it is for Julia: https://github.com/JuliaLang/julia/blob/bb5b98e72a151c41471d8cc14cacb495d647fb7f/src/processor_arm.cpp#L1835-L1842

**Comment by thchr** [comment]
One downside to this is that loading meep in e.g., Python or Julia will also `set_zero_subnormals` in their context.
This e.g., lead to https://github.com/MakieOrg/Makie.jl/issues/5122 for me when loading meep.

Would it be possible to `set_zero_subnormals` "locally" rather than globally: i.e., enable before time-stepping and disable again after?

**Comment by stevengj** [comment]
Yes, that should be possible: we can just set it at the beginning of `fields::step` and unset it at the end of that function.
