### ISSUE TITLE
Effective index in Phc is negative, cannot observe in transmission 

### ISSUE THREAD

**Issue by yilmazutku** [NanoComp/meep#1716]
Hello,

I am trying to obtain the output of an MZI which has photonic crystal with different radii on its two arms. Normally, at the targeted frequency (assume arbitrary) crystals are at different bands, one of which has negative effective refractive index. I should be able to observe modulation even with short phase shifter lengths, yet I can't make use of this effect in MEEP simulations. 

Does meep handle my simulation as I want, or do I have to modify some parts in its source codes?

I'd appreciate it much if anyone can spare time for my issue.

Best regards,

Utku.

**Comment by stevengj** [comment]
If you are trying to implement a negative "effective index" as an ε<0 and μ<0 material (as opposed to directly modeling the microstructure that produces this effect), see the FAQ: https://meep.readthedocs.io/en/latest/FAQ/#why-does-my-simulation-diverge-if-the-permittivity-is-less-than-0

**Comment by stevengj** [comment]
I'm I guess you mean β/ω as the "effective index", which is negative for a positive group velocity for a downward curving band (though beware β itself, and hence the concept of a "negative phase velocity" or "negative effective index" is ambiguous if you are talking about periodic waveguides; see e.g. https://journals.aps.org/pra/abstract/10.1103/PhysRevA.76.063810). 

In any case, Meep simulates the full Maxwell's equations, so if you aren't seeing the behavior that you want then you are either using the wrong simulation parameters (e.g. not simulating the structure you think you are simulating) or are misunderstanding the physics.
