### ISSUE TITLE
near-to-far field transformation used by adjoint solver always uses Yee grid for near fields

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#1725]
The `Near2FarFields` class of the adjoint solver is currently set up to compute the near fields on the Yee grid rather than the centered grid:

https://github.com/NanoComp/meep/blob/74c97520ccf68403cf5ef64824ed70cf78902985/python/adjoint/objective.py#L312-L316

The weird thing is unlike [`fields::add_dft_fields`](https://github.com/NanoComp/meep/blob/master/src/meep.hpp#L2011-L2025) (used by the `FourierFields` class) and [`fields::add_mode_monitor`](https://github.com/NanoComp/meep/blob/74c97520ccf68403cf5ef64824ed70cf78902985/src/meep.hpp#L1997-L2009) (used by the `EigenmodeCoefficient` class), `fields::add_dft_near2far` does *not* have a `use_centered_grid`/`centered_grid` argument or equivalent:

https://github.com/NanoComp/meep/blob/74c97520ccf68403cf5ef64824ed70cf78902985/src/meep.hpp#L2093-L2105

However, this is actually not a problem here because `fields::add_dft_near2far` calls `fields::add_dft` with a hard-coded `use_centered_grid = false` (third to last argument):

https://github.com/NanoComp/meep/blob/74c97520ccf68403cf5ef64824ed70cf78902985/src/near2far.cpp#L635 

For reference, all objective-function classes of the adjoint solver use the Yee grid rather than the centered grid when computing the DFT fields. In order to avoid this one ambiguity, we can either (1) modify `add_dft_near2far` to have an additional argument `use_centered_grid` which seems unnecessary or (2) we can just remove `yee_grid=True` from the call to `add_dft_near2far` inside `register_monitors` of `Near2FarFields` since it is not doing anything.

cc @mochen4

**Comment by mochen4** [comment]
You are right, thanks Ardavan!
