### ISSUE TITLE
Build PDF documentation.

### ISSUE THREAD

**Issue by lockywolf** [NanoComp/meep#1734]
Would it be possible to add an option to build a PDF version of the documentation? My e-book reader is not good at showing webpages, and generating pdf files indirectly from html is also no lossless.

**Comment by stevengj** [comment]
Hmm, I added [PDF output](https://docs.readthedocs.io/en/stable/downloadable-documentation.html) 
 to the readthedocs config (https://github.com/NanoComp/meep/commit/cd2a18b000e84cbb4e32422abcca7d8e4450aac0), but I'm not seeing a PDF link in the documentation and none of the suggestions in the stackoverflow discussion work (https://stackoverflow.com/questions/50425740/how-to-find-the-pdf-version-of-a-read-the-docs-project).   Any ideas?

**Comment by oskooi** [comment]
@stevengj perhaps you also need to update the "Repository" setting in https://readthedocs.org/projects/meep/?

Note that if you navigate to https://meep.readthedocs.io/en/latest/, at the bottom right corner of this page you will see a button next to a book icon labeled "v: latest" which expands to reveal several options (none of which are PDF output). When the PDF output feature is finally working, this is where it will be found.

**Comment by lockywolf** [comment]
FWIW, I have managed to create an improvised version of the documentation by using this plugin to mkdocs: [[https://github.com/orzih/mkdocs-with-pdf]] and tweaking `requirements.txt`

I am feeling that the font generated is too small, but at least I do have a pdf file now.

**Comment by oskooi** [comment]
Unfortunately, `mkdocs` (which we are using to create the documentation for readthedocs) does not support building additional formats such as `pdf` or `epub` as described in https://docs.readthedocs.io/en/stable/config-file/v2.html#formats. (These formats are only supported by `sphinx`.)
