### ISSUE TITLE
Coordinates from `get_array_metadata()` are incorrect when monitor `yee_grid=True`

### ISSUE THREAD

**Issue by ianwilliamson** [NanoComp/meep#1736]
When setting up a DFT monitor like so,

```python
monitor = simulation.add_dft_fields(
  [mp.Ex, mp.Ey, mp.Ez],
  some_frequencies,
  where=some_volume,
  yee_grid=True,
)
```
the coordinates that are later obtained by calling:
```python
(x, y, z, _) = simulation.get_array_metadata(dft_cell=monitor)
```
are not correct. They appear to be the center coordinates of the Yee cells inside `some_volume` instead of the locations of the Ex, Ey, and Ez components on the Yee grid.

**Comment by smartalecH** [comment]
Did you pass the component you are interested in?

**Comment by smartalecH** [comment]
Ah I remember now. Typically we use `get_array_slice_dimensions ` (and pass the component we care about). It will return the edges of the grid and you can manually fill in the grid yourself. 

It's not ideal, but it works. We could easily generalize `get_array_metadata()` to do this too with the automated mesh generation.

**Comment by ianwilliamson** [comment]
> Ah I remember now. Typically we use `get_array_slice_dimensions ` (and pass the component we care about). It will return the edges of the grid and you can manually fill in the grid yourself.

Ah, I was unaware of this function! Thanks for pointing that out.

> It's not ideal, but it works. We could easily generalize get_array_metadata() to do this too with the automated mesh generation.

Definitely would be nice to have this one day!

**Comment by ianwilliamson** [comment]
For the suggested workaround, it seems that this:

```
tuple(s for s, _, _ in zip(*simulation.get_array_slice_dimensions(component, vol=monitor.where)))
```

doesn't always match the shape of the array that gets returned by `get_array_metadata()`.

**Comment by smartalecH** [comment]
Yes that's expected, because `get_array_metadata` doesn't work on the yee grid -- it always assumes you are interpolating to the center. 

But `get_array_slice_dimensions` should give you the expected array size and the boundaries that you care about. 

It might be helpful to draw an extended yee grid to see how the actual field component points occasionally extend 1 "point" beyond the total number of enclosed centers within a particular volume (I had to draw many different variations when debugging the function). The above dimensions should always align with the dimensions of the dft field array (as a sanity check)

**Comment by ianwilliamson** [comment]
> It might be helpful to draw an extended yee grid to see how the actual field component points occasionally extend 1 "point" beyond the total number of enclosed centers within a particular volume (I had to draw many different variations when debugging the function). The above dimensions should always align with the dimensions of the dft field array (as a sanity check)

Sorry I transposed the function names in my head when writing my previous reply. I edited my reply above to say that it's actually `get_dft_array()` that returns an incorrectly sized array when evaluated on the Yee grid (at least relative to what `get_array_slice_dimensions()` returns).

**Comment by ianwilliamson** [comment]
Here is an example:
```
source = mp.EigenModeSource(
    mp.GaussianSource(frequency=1 / 1550, fwidth=1 / 1550 * 0.2),
    eig_band=1,
    direction=mp.NO_DIRECTION,
    eig_kpoint=mp.Vector3(1, 0, 0),
    size=mp.Vector3(0, 1, 0),
    center=[-1, 0, 0],
)

simulation = mp.Simulation(
    cell_size=mp.Vector3(5.0, 6.5, 0.0),
    resolution=20,
    sources=[source],
)

monitor = simulation.add_dft_fields(
    [mp.Ex, mp.Ey, mp.Ez],
    [1 / 1500],
    where=mp.Volume(center=mp.Vector3(), size=mp.Vector3(1.0, 0.5, 0.0)),
    yee_grid=False,
)

simulation.init_sim()
simulation.run(until=1)

fields = simulation.get_dft_array(monitor, mp.Ex, 0)
print(fields.shape)

shape, _, _ = simulation.get_array_slice_dimensions(mp.Ex, vol=monitor.where)
print(shape)
```

which prints
```
(22, 12)
[22 11  1]
```
