### ISSUE TITLE
calculate capacitance

### ISSUE THREAD

**Issue by anadb** [NanoComp/meep#1757]
Hello!

I used sonnet lite to calculate capacitance of a simple capacitor, but then I moved to complex geometry and lite version wasn't enough for such structure.

I read meep documentation and didn't find easy way to simulate capacitors. Could anyone give an example how to do it? Maybe some finger type capacitor.

**Comment by stevengj** [comment]
Meep is for electrodynamics (wave simulations) — capacitance is an electrostatic property and isn't well suited to Meep.

Solving for capacitance is simply a matter of solving Laplace's equation.  Maybe try one of the many free/open-source finite-element method (FEM) packages, e.g. FEniCS.

**Comment by anadb** [comment]
thank you for the answer, I will check fenics
