### ISSUE TITLE
meep: simulation fields are NaN or Inf

### ISSUE THREAD

**Issue by zhongluu** [NanoComp/meep#1761]
The material of ring waveguide was changed to Si in [example.](https://github.com/NanoComp/meep/blob/f5b60e5b8e9decfd65166dc1f3f82947aecb259a/python/examples/ring.py) Meanwhile, the default material was changed to SiO2. But the simulation encouter not a  number error. And I try use mp.Absorber to replace PML. The result diverges again. However, the straight waveguide simulation success when these material applied in.
Whether this operation is not supported in meep?
`from __future__ import division

import meep as mp
import matplotlib.pyplot as plt
from meep.materials import Si
from meep.materials import SiO2

def main():
    n = 3.4                 # index of waveguide
    w = 1                   # width of waveguide
    r = 1                   # inner radius of ring
    pad = 4                 # padding between waveguide and edge of PML
    dpml = 2                # thickness of PML
    sxy = 2*(r+w+pad+dpml)  # cell size

    # Create a ring waveguide by two overlapping cylinders - later objects
    # take precedence over earlier objects, so we put the outer cylinder first.
    # and the inner (air) cylinder second.

    c1 = mp.Cylinder(radius=r+w, material=Si)
    c2 = mp.Cylinder(radius=r)

    # If we don't want to excite a specific mode symmetry, we can just
    # put a single point source at some arbitrary place, pointing in some
    # arbitrary direction.  We will only look for Ez-polarized modes.

    fcen = 1/1.55             # pulse center frequency
    df = 0.1                # pulse width (in frequency)

    src = mp.Source(mp.GaussianSource(fcen, fwidth=df), mp.Ez, mp.Vector3(r+0.1))

    sim = mp.Simulation(cell_size=mp.Vector3(sxy, sxy),
                        geometry=[c1, c2],
                        sources=[src],
                        resolution=10,
                        symmetries=[mp.Mirror(mp.Y)],
						force_complex_fields=True,
                        default_material=SiO2,
                        boundary_layers=[mp.Absorber(dpml)])

    plt.figure(dpi=150)
    sim.plot2D(fields=mp.Ez)
    plt.show()

    sim.run(mp.at_beginning(mp.output_epsilon),
            mp.after_sources(mp.Harminv(mp.Ez, mp.Vector3(r+0.1), fcen, df)),
            until_after_sources=300)

    # Output fields for one period at the end.  (If we output
    # at a single time, we might accidentally catch the Ez field when it is
    # almost zero and get a distorted view.)
    sim.run(mp.at_every(1/fcen/20, mp.output_efield_z), until=1/fcen)

if __name__ == '__main__':
    main()`

The terminal output as follow:

`Working in 2D dimensions.
Computational cell is 16 x 16 x 0 with resolution 10
     cylinder, center = (0,0,0)
          radius 2, height 1e+20, axis (0, 0, 1)
          dielectric constant epsilon diagonal = (1,1,1)
     cylinder, center = (0,0,0)
          radius 1, height 1e+20, axis (0, 0, 1)
          dielectric constant epsilon diagonal = (1,1,1)
time for set_epsilon = 0.0283693 s
time for set_conductivity = 0.0004739 s
time for set_conductivity = 0.0005832 s
time for set_conductivity = 0.000629999 s
time for set_conductivity = 0.0005767 s
time for set_conductivity = 0.0005952 s
time for set_conductivity = 0.000631 s
lorentzian susceptibility: frequency=0.000905797, gamma=0
lorentzian susceptibility: frequency=0.88125, gamma=0
lorentzian susceptibility: frequency=3.31657, gamma=0
-----------
Meep: using complex fields.
creating output file "./ring-eps-000000.00.h5"...
Traceback (most recent call last):
  File "/home/mine/Documents/examples/ring.py", line 55, in <module>
    main()
  File "/home/mine/Documents/examples/ring.py", line 47, in main
    until_after_sources=300)
  File "/usr/local/lib/python3.6/site-packages/meep/simulation.py", line 3759, in run
    self._run_sources_until(until_after_sources, step_funcs)
  File "/usr/local/lib/python3.6/site-packages/meep/simulation.py", line 2285, in _run_sources_until
    self._run_until(new_conds, step_funcs)
  File "/usr/local/lib/python3.6/site-packages/meep/simulation.py", line 2249, in _run_until
    self.fields.step()
  File "/usr/local/lib/python3.6/site-packages/meep/__init__.py", line 3757, in step
    return _meep.fields_step(self)
RuntimeError: meep: simulation fields are NaN or Inf`

**Comment by oskooi** [comment]
The fields are blowing up because the `resolution` of 10 is too low for the dispersive materials (Si and SiO2) you are using. This is described in https://meep.readthedocs.io/en/latest/FAQ/#why-are-the-fields-blowing-up-in-my-simulation.

Increase the resolution to 50 and it runs fine.
