### ISSUE TITLE
[Question] Is it possible to get epsilon tensor after subpixel smoothing?

### ISSUE THREAD

**Issue by dc3505** [NanoComp/meep#1764]
Dear all,

Since in the paper that subpixel smoothing's implementation is referring, at different grid point, different diagonal terms or off-diagonal terms of the smoothed epsilon tensor is taken and off-diagonal terms are used for interpolation. Is it possible to get values for those terms? Or is there a way to get the full 2*2 smoothed epsilon matrix in 2d (3 * 3 in 3d)?

Thanks in advance!

**Comment by stevengj** [comment]
You have to call a low-level C++ function for this, [`get_inveps`](https://github.com/NanoComp/meep/blob/f5b60e5b8e9decfd65166dc1f3f82947aecb259a/src/meep.hpp#L2139-L2142).  It is possible to do this from Python, even though it is not documented.

For example, this returns ε⁻¹_{xy} tensor component the at (x,y)=(0.2,0.3):
```py
v3 = mp.py_v3_to_vec(sim.dimensions, mp.Vector3(0.2,0.3), sim.is_cylindrical)
sim.fields.get_inveps(mp.Ex, mp.Y, v3)
```
(Given the components of ε⁻¹, you can invert the matrix to get the components of ε.)

**Comment by dc3505** [comment]
Dear all,

I'm wondering since for isotropic material, I thought the smoothed epsilon matrix will be symmetric. In other words, the epsilon_xy and epsilon_yx component will be the same. However, when I run the following code:
```
e2 = np.zeros([101, 101], dtype=np.complex128)
e1 = np.zeros([101, 101], dtype=np.complex128)
x = np.linspace(-1, 1, 101)
y = np.linspace(-1, 1, 101)
for i in range(len(x)):
    for j in range(len(y)):
        v3 = mp.py_v3_to_vec(sim.dimensions, mp.Vector3(x[i], y[j], 0), sim.is_cylindrical)
        e2[i, j] = sim.fields.get_inveps(mp.Ex, mp.Y, v3)
        e1[i, j] = sim.fields.get_inveps(mp.Ey, mp.X, v3)
```
`e1 - e2` will not be 0. May I check why this is the case? Or is my understanding of the paper incorrect?

Thanks!
