### ISSUE TITLE
Segmentation fault when solving for eigenmodes

### ISSUE THREAD

**Issue by scottkenning** [NanoComp/meep#1765]
MEEP has been segfaulting from the Python interface when higher band numbers are specified on wave-guides that do not support those bands. I would expect an exception in this case, rather than a segfault. 

To reproduce, create a conda environment:
`conda create -n meep_nomkl nomkl`
`conda activate meep_nomkl`
`conda install --override-channels -c conda-forge pymeep=*=mpi_mpich_*`
`conda install --override-channels -c conda-forge matplotlib`

Then, the reproducible example is a modification of the first example in [MEEP's eigenmode source tutorial](https://meep.readthedocs.io/en/latest/Python_Tutorials/Eigenmode_Source/) where I set
`bnum = 2`.

By running, I quickly receive a segfault.

**Comment by oskooi** [comment]
Thanks. Should be fixed by #1770.
