### ISSUE TITLE
Bug with vector-valued objectives and `get_objective_arguments()`

### ISSUE THREAD

**Issue by smartalecH** [NanoComp/meep#1778]
We have a naive check to make sure a forward run has been executed before the user can query the evaluated objective arguments:

https://github.com/NanoComp/meep/blob/fa23466a6112b9abe98f25b488fa972fa4095761/python/adjoint/objective.py#L46

This works for scalar-valued functions, but not vector-valued functions (where `self._eval` contains arrays).

The minimax tutorials should actually *fail* on master because of this issue -- we just haven't updated them in a while.

It'd be trivial to fix this and add a check to the adjoint test.

(Note that in earlier versions of the code, the check was actually `if self._eval is not None:` which isn't as "clean" but always works.)

**Comment by ianwilliamson** [comment]
Perhaps a vector-valued loss function test should be added?

**Comment by ianwilliamson** [comment]
This actually may be my fault. Can you clarify what the purpose of `get_evaluation()` is? I see that this is only called by the `OptimizationProblem`'s `get_objective_arguments()` method, but is it used for some other purpose? It seems duplicative of what you get when you call the `OptimizationProblem`, which returns the objective function value(s).

**Comment by smartalecH** [comment]
No worries. There's actually a big (and useful) difference between `get_objective_arguments()` and the output of `OptimizationProblem`.

Of course, your objective function is a *function* of your objective arguments. As you know, the arguments could be eigenmode overlaps, far-field profiles, etc. One simple example is a function that maximizes the power of the S21 coefficient (which requires two eigenmode overlaps as arguments). The output of this function, however, is most likely an error quantity, not the actual overlaps themselves. If we want to access the actual overlap quantities (e.g. for some postprocessing, storing, visualization, manipulation, etc.), we can use `get_objective_arguments()`.

Essentially, this function returns the raw differentiable quantities themselves, regardless of what the objective function actually does with them.

Furthermore, we can place other "monitors" or differentiable quantities as objective arguments, but not require that the objective function depends on them! This is really useful for simultaneously monitoring the S11 coefficient, for example, without explicitly optimizing it. If the Jacobian for a particular coefficient is just a zeros matrix (i.e. the objective function doesn't depend on it) then the adjoint source routine just bypasses that coefficient. But its forward calculation is still performed!
