### ISSUE TITLE
absorption penalty for intermediate material-grid pixels

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#1788]
To help encourage the topology-optimized structure to binarize, a common trick is to penalize intermediate pixel values by adding an artificial dissipation loss — as suggested by @raelch, this works well in any problem where we are optimizing transmission or similar functions that want to avoid loss.

In Meep, the most efficient way to add dissipation is via an artificial conductivity term, i.e. for a density ρ we would add an artificial conductivity σ = ρ(1–ρ)σ₀ for some amplitude σ₀.   (σ₀ should be proportional 2π times a typical frequency in the problem, e.g. the center frequency of the DFT bandwidth.)

It would be good to add a σ₀ parameter to the material grid object (defaulting to σ₀=0), to make it easy to specify such a term if desired.

(Note that @smartalecH already implemented something like this for dispersive materials, I thought, but maybe it isn't turned on by default at the moment?)

cc @mochen4

**Comment by stevengj** [comment]
> Obviously, we want it off by the time our structure is fully binarized...

Not necessarily.  If we set β = ∞, and it is fully binarized (before subpixel smoothing), the artificial dissipation term will vanish anyway.

>  Does this preclude us from using subpixel smoothing in the design region (and consequently, prevents us from using our "hybrid" levelset)?

No, I don't think so.   If we define the artificial dissipation as applying to the projected DOF before smoothing, then in the level-set limit (β = ∞) it won't even show up.

Because of that it might be fine to not apply any subpixel smoothing when calculating the artificial dissipation term (i.e. we just handle it with the old code using `matgrid_val` at the Yee grid points).

**Comment by smartalecH** [comment]
It looks like the gradient calculation is incorrect when damping is applied.

When I run [this gist](https://gist.github.com/smartalecH/e2e84d5f5b806a52582ba9dabc841c4f), I get a rather large difference between finite differences and the adjoint:

```
Directional derivative -- adjoint solver: [4.41477249e-05], FD: [-2.4637409e-05]|| rel_error = [2.79189804]
```

Conversely, if I turn the damping off, I get agreement:

```
Directional derivative -- adjoint solver: [-0.00048496], FD: [-0.00048496]|| rel_error = [2.37482024e-08]
```

**Comment by mochen4** [comment]
Thanks for testing it, Alec. I thought the original finite difference part would automatically take care of the damping term, so I didn't check the adjoint gradient against the FD gradient. I will re-examine the code.

**Comment by smartalecH** [comment]
No problem. Now that I think about it, I think that's why the other conductivity terms are commented out in the code -- I'm not sure I was ever able to get conductivities to work! 

The lorentzians worked just fine, even without the compensating synthetic conductivity, so long as the interpolated material was stable (no zero crossings). The point of those conductivity terms, however, was to stabilize those corner cases. 

Either there is a simple bug with how I'm calculating epsilon from the conductivity, or the conductivity requires some extra care.
