### ISSUE TITLE
error regarding "Module Not Found Error: No module named 'meep'"

### ISSUE THREAD

**Issue by dhiraj177** [NanoComp/meep#1800]
**I run this simple code but i found error.**
import meep as mp
cell = mp.Vector3(16,8,0)

geometry = [mp.Block(mp.Vector3(mp.inf,1,mp.inf),
                     center=mp.Vector3(),
                     material=mp.Medium(epsilon=12))]

sources = [mp.Source(mp.ContinuousSource(frequency=0.15),
                     component=mp.Ez,
                     center=mp.Vector3(-7,0))]

pml_layers = [mp.PML(1.0)]

resolution = 10

sim = mp.Simulation(cell_size=cell,
                    boundary_layers=pml_layers,
                    geometry=geometry,
                    sources=sources,
                    resolution=resolution)

sim.run(until=200)

**when i run this code i get this error message.
ModuleNotFoundError: No module named 'meep'
Kindly please help me regarding this.**

**Comment by stevengj** [comment]
If Python is not finding the `meep` module, then you didn't install it in a place that Python can find it.   For example, maybe you have multiple versions of Python installed on your machine and you installed Meep in the wrong one.
