### ISSUE TITLE
no configure script in release

### ISSUE THREAD

**Issue by VictorEijkhout** [NanoComp/meep#1813]
The documentation [https://meep.readthedocs.io/en/latest/Build_From_Source/#unix-installation-basics](https://meep.readthedocs.io/en/latest/Build_From_Source/#unix-installation-basics) speaks of a `./configure` which I am not finding in the v1.21.0.tar.gz file.

**Comment by ahoenselaar** [comment]
Please run `autogen.sh` before `configure`, as illustrated in this section: https://meep.readthedocs.io/en/latest/Build_From_Source/#ubuntu-1604-and-1804

**Comment by VictorEijkhout** [comment]
1. I don't have ubuntu.

2. could you document the flags to that script?

I've set the `CC` flag and that compiler gets picked up, but I set `FC` and that does not get picked up.

How do I specify the location of hdf5?

How do I specify blas/lapack?  With MKL that is done through a compiler option `-mkl`.

**Comment by VictorEijkhout** [comment]
Also, those instructions say:
```
git clone https://github.com/NanoComp/meep.git
cd meep/
sh autogen.sh --enable-shared --with-mpi --with-openmp PYTHON=python3 LDFLAGS="${MY_LDFLAGS}" CPPFLAGS="${MY_CPPFLAGS}"
make && sudo make install
```
so there is no `./configure` involved. I'm confused. Can I skip configure completely if I do `autogen`?

**Comment by smartalecH** [comment]
> Can I skip configure completely if I do autogen?

Yes. 

`autogen.sh` calls `configure`. If you look inside the `autogen.sh` script:

https://github.com/NanoComp/meep/blob/fc5ea4a9665106323b1a9bffb22a7af17ced584f/autogen.sh#L1-L8

Pass all the flags you would normally pass to `configure` to `autogen` (that's what `"$@"` is doing).

**Comment by stevengj** [comment]
You are downloading the wrong file.   The official release tarball is https://github.com/NanoComp/meep/releases/download/v1.21.0/meep-1.21.0.tar.gz linked to under "Assets" from https://github.com/NanoComp/meep/releases/tag/v1.21.0, which *does* include the `configure` script and all other generated files — you *don't* need to run `autogen.sh` with this or have the autoconf/automake tools on your system.

**Comment by stevengj** [comment]
I added a note on this to the instructions: https://github.com/NanoComp/meep/commit/ee3101007850b9b530261981d55922907ab45f1f

**Comment by VictorEijkhout** [comment]
Got it. Now that you mention it, some people put a warning on the download page not to download the `v123456.tar.gz` file.

How do I specify hdf5? `configure --help` only says how to configure without, not with.

**Comment by stevengj** [comment]
`configure` tries to link HDF5 by default.   If you installed it in a nonstandard location, you will need to tell `configure` where to find it by passing `CPPFLAGS="-I..."` and `LDFLAGS="-L..."` flags as explained in the manual under "Unix Installation Paths".
