### ISSUE TITLE
plot geometry directly (without discretization)

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#1824]
Would be nice to be able to plot the geometry directly, without creating the `structure` object and the discretization first (which can be slow for large simulations).

It's pretty tricky to implement in its full generality for all possible objects, but would be easy to support a subset of objects (e.g. prisms and other objects aligned with the grid).

The `get_epsilon_grid` function actually implements one possible version of this functionality, and we could simply plot it.

cc @joamatab

**Comment by smartalecH** [comment]
The main geometric plotting function is found here:

https://github.com/NanoComp/meep/blob/d4b1e1a519037f4a63c8e81caf4711de50f5378b/python/visualization.py#L307

You can add all the new code there.

All the boundaries, monitors, sources, etc. are already implemented generically.

**Comment by stevengj** [comment]
For example, we could just add a `resolution` argument to `sim.plot2d` — if that is passed, then instead of initializing the structure it calls `get_epsilon_grid` instead .

**Comment by smartalecH** [comment]
And the key is that `get_epsilon_grid` only pulls the *2D slice* at the specified resolution (where normally you have to initialize *everything* at the *full* resolution).
