### ISSUE TITLE
Correct GaussianBeamSource in 2D

### ISSUE THREAD

**Issue by smartalecH** [NanoComp/meep#1838]
As discussed in [this comment](https://github.com/NanoComp/meep/pull/1303#issuecomment-668917384), the current `GaussianBeamSource` object simply pulls a 2D slice of the full 3D solution when trying to simulate a 2D Gaussian beam (which is incorrect).

This has some important ramifications when trying to design grating couplers and verifying the results with other software (see [here](https://github.com/simbilod/grating_coupler_meep/pull/2#issuecomment-967713536)).

It would be nice to eventually implement the correct source profile.

(cc @joamatab @simbilod @oskooi)

**Comment by stevengj** [comment]
Duplicate of #1308
