### ISSUE TITLE
homebrew/science was deprecated.

### ISSUE THREAD

**Issue by tomsturges** [NanoComp/meep#1850]
On [this](https://meep.readthedocs.io/en/latest/Installation/#installation-from-source-on-macos) page, that details how to install on Mac OS from source. It instructs to do the following

`brew install homebrew/science/hdf5 homebrew/science/openblas guile fftw h5utils`

This results in the error warning

`Error: homebrew/science was deprecated. This tap is now empty and all its contents were either deleted or migrated.`

I am using a Macbook Air with M1 chip

**Comment by smartalecH** [comment]
Maybe just try `brew install openblas hdf5` ([see here](https://formulae.brew.sh/formula/openblas)). You can always build openblas from source, too (it's pretty straightforward, luckily).

For the record, I don't know if anyone has successfully built on M1 yet. Can you continue to post your updates here (especially if successful)?

**Comment by stevengj** [comment]
I've updated the build instructions.

I've built all of the dependencies on Apple M4, but I'm running into a compiler error due to a C++ incompatibility with clang:
```
dft.cpp:1448:31: error: non-constant-expression cannot be narrowed from type 'ptrdiff_t' (aka 'long') to 'size_t' (aka 'unsigned long') in initializer list [-Wc++11-narrowing]
        size_t site_ind[4] = {idx,idx + f->avg1,idx + f->avg2,idx + f->avg1 + f->avg2};
```
I'll try to fix it later today.

**Comment by stevengj** [comment]
See #1853.

**Comment by tomsturges** [comment]
@smartalecH I have never built anything from source before, so I doubt I'll be successful. But sure, I'll let you know if there are any updates.
