### ISSUE TITLE
decay_fields no longer in OptimizationProblem

### ISSUE THREAD

**Issue by DurhamSmith** [NanoComp/meep#1862]
I am currently trying to run some of the adjoint method examples. These however fail when trying to initialize an optimization problem with they keyword argument `decay_fields` which I see is no longer present in the `OptimizationProblem` class.

Commenting out this keyword argument the a\so gives the following result when trying to run the 02-Waveguide_Bend notebook

```
algorithm = nlopt.LD_MMA
n = Nx * Ny
maxeval = 10

solver = nlopt.opt(algorithm, n)
solver.set_lower_bounds(0)
solver.set_upper_bounds(1)
solver.set_max_objective(f)
solver.set_maxeval(maxeval)
x = solver.optimize(x0);


algorithm = nlopt.LD_MMA

n = Nx * Ny

maxeval = 10

​

solver = nlopt.opt(algorithm, n)

solver.set_lower_bounds(0)

solver.set_upper_bounds(1)

solver.set_max_objective(f)

solver.set_maxeval(maxeval)

x = solver.optimize(x0);

​

Starting forward run...
Starting adjoint run...
Calculating gradient...

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_13372/2809643958.py in <module>
      8 solver.set_max_objective(f)
      9 solver.set_maxeval(maxeval)
---> 10 x = solver.optimize(x0);

~/anaconda3/envs/mp/lib/python3.9/site-packages/nlopt.py in optimize(self, *args)
    333 
    334     def optimize(self, *args):
--> 335         return _nlopt.opt_optimize(self, *args)
    336 
    337     def last_optimize_result(self):

ValueError: nlopt invalid argument

```

Is the adjoint solver still supported/under development? Is it working enough for use to do topology optimization of devices?

**Comment by DurhamSmith** [comment]
Additionally it seems in all most of the adjoint method notebooks, when `decay_fields` is commented out there is a `cannot reshape array of size 5625 into shape (76,76)` error which I suspect comes from rounding errors or math errors happening somewhere (75^2 =5625). I can dig into this a little deeper in the morning.

**Comment by smartalecH** [comment]
All of the notebooks are out of date

**Comment by DurhamSmith** [comment]
Thanks!
