### ISSUE TITLE
Mailing list issues

### ISSUE THREAD

**Issue by DurhamSmith** [NanoComp/meep#1875]
Just a comment/question.

I tried to post a question to the mailing list last night. I did this via mailing the mailing list by emailing a query to meep-discuss@ab-initio.mit.edu . I see that my question has not been posted there yet. I could understand if it needs manual review to stop spambots and I don't expect review to happen immediately.  Additionally, when I tired to click [the link to the mailing list found in the FAQ](https://meep.readthedocs.io/en/latest/FAQ/#where-can-i-ask-questions-regarding-meep) I got the following error:
```
Mailman CGI error!!!
The Mailman CGI wrapper encountered a fatal error. This entry is being stored in your syslog:

No such file or directory
```

These two things lead me to wonder if there may not perhaps be issues with the mailing list currently. 

Regards,
Durham

**Comment by DurhamSmith** [comment]
Thanks! I will open an issue in the meantime. 

Regards,
D

**Comment by stevengj** [comment]
https://github.com/NanoComp/meep/discussions now exists.
