### ISSUE TITLE
h5topng keeps throwing different errors, any other way to get images/gif out of h5 files?

### ISSUE THREAD

**Issue by Utsav-Matukumalli** [NanoComp/meep#1876]
`(h5topng) utsav@UtsavMatukumalli-T480:~/meep_projects/90degree_bent_waveguide$ h5ls ez-slice.h5`
`ez                       Dataset {160, 4001/Inf}`
`(h5topng) utsav@UtsavMatukumalli-T480:~/meep_projects/90degree_bent_waveguide$ h5topng -t 0:332 -R -Zc dkbluered -a yarg -A eps-000000.00.h5 ez-slice.h5`
`HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140404925413184:`
  `#000: H5F.c line 509 in H5Fopen(): unable to open file`
    `major: File accessibilty`
    `minor: Unable to open file`
  `#001: H5Fint.c line 1400 in H5F__open(): unable to open file
    major: File accessibilty
    minor: Unable to open file`
  `#002: H5Fint.c line 1548 in H5F_open(): unable to open file: name = 'eps-000000.00.h5', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file`
 `#003: H5FD.c line 734 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object`
  `#004: H5FDsec2.c line 346 in H5FD_sec2_open(): unable to open file: name = 'eps-000000.00.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file`
`h5topng error: error opening HD5 file`

I am using h5topng as another environment as suggested in #1066 , and it was working till now. But somehow, it is now giving me the "unable to open file" error. 
It throws the exact same error when I use 'h5topng' in the default directory as well. 

How can I fix this? Is there any other way to interact with these h5 files to get image/gif outputs instead of using the `h5topng` command? 

UPDATE: I changed the package from chogan to conda-forge and it is throwing me a different error now:
h5topng error: invalid colormap file

**Comment by stevengj** [comment]
Maybe the file permissions are wrong?  What does:
```
ls -l ez-slice.h5
```
give?

**Comment by Utsav-Matukumalli** [comment]
In meep environment, it gives 
'
-rw-r--r-- 1 utsav utsav 68221752 Jan  2 20:58 ez-slice.h5

'

**Comment by Utsav-Matukumalli** [comment]
Update: 

I removed h5utils from meep environment using 
```
conda remove h5utils

```
Now, there is only one `h5utils` in ubuntu 20.04 LTS and it is in its own conda environment. Now it works without issues.
