### ISSUE TITLE
Error while installing meep 'Libctl'

### ISSUE THREAD

**Issue by Anirudh-K16** [NanoComp/meep#1887]
checking whether libctl version is at least 4.2.0... configure: error: libctl version 4.2.0 or later is required
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
![Screenshot 2022-01-07 at 20 27 00](https://user-images.githubusercontent.com/79514859/148602975-9da8adb7-a696-47a7-b6cb-07a24a888749.png)

**Comment by stevengj** [comment]
The error means exactly what it says — you need to install a newer version of libctl.

**Comment by Anirudh-K16** [comment]
I understand, Im having trouble finding and downloading the newest version for libctl, maybe a link would help? Thank you so much!

**Comment by oskooi** [comment]
See: https://meep.readthedocs.io/en/latest/Build_From_Source/#libctl.
