### ISSUE TITLE
Unable to subscribe to Simpetus on AWS

### ISSUE THREAD

**Issue by Anirudh-K16** [NanoComp/meep#1891]
![Screenshot 2022-01-09 at 20 39 03](https://user-images.githubusercontent.com/79514859/148699950-072d6440-c622-48e0-a623-4d5de78a9578.png)
![Screenshot 2022-01-09 at 20 39 15](https://user-images.githubusercontent.com/79514859/148699960-86c296ef-dbf1-4ac0-918e-fe8c9660286a.png)

**Comment by oskooi** [comment]
As you can see from the notice in that screenshot: "This version has been removed and is no longer available to new customers."

Please note that GitHub issues are for filing bug reports and feature requests. This is not a general help desk. If you are having trouble installing Meep, you can try contacting a system administrator at your institution, for example.
