### ISSUE TITLE
fix incorrect claim that near-to-far transform only works in the far field

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#1909]
This line seems wrong: https://github.com/NanoComp/meep/blob/1f5833454b2e0954f91658a5e86a60ef2ae4ac85/doc/docs/Python_User_Interface.md.in#L305

The name "near-to-far field transform" is something of a misnomer — since we use the full Green's function, this is just an application of the Equivalence Principle, and we should be able to compute fields *anywhere* outside the near2far surface.   The only limiting factor should be discretization errors, but for any given distance it should converge with resolution (once the distance >> resolution).

**Comment by oskooi** [comment]
I verified that the near-to-far field transformation can indeed be used to compute the fields anywhere outside the near2far surface. The validation test is based on [Tutorial/Far-field Profile of a Cavity](https://meep.readthedocs.io/en/latest/Python_Tutorials/Near_to_Far_Field_Spectra/#far-field-profile-of-a-cavity) and involved comparing the far fields with the actual DFT fields at the same location while varying the distance between the near2far surface and the far fields ([script](https://gist.github.com/oskooi/504f3271fc677b136c38f912723aa3fa)). 

Here is a side-by-side comparison of the real and imaginary parts of the H<sub>z</sub> far field for two different "far"-field monitors and a pulsed source with center vacuum wavelength of 4 μm: (1) 0.1 μm (2 pixels) and (2) 1.0 μm (20 pixels). Both cases show fairly good agreement between the computed "far" fields and the actual DFT fields.

![farfields_Hz_dft_vs_n2f_0 1](https://user-images.githubusercontent.com/7152530/151271800-887313e6-7e8f-4d80-9f68-5b4112c8dd26.png)

![farfields_Hz_dft_vs_n2f_1 0](https://user-images.githubusercontent.com/7152530/151271817-c0fc2b5d-cb63-44e0-a72b-996b6029ab07.png)

**Comment by stevengj** [comment]
> the discrepancy in the two results actually becomes larger with increasing distance of the far fields from the near-field monitor.

Isn't that just numerical dispersion?  The farther you propagate, the bigger the differences between the exact Green's function and the discrete grid become.

If it's numerical dispersion, you should see agreement improve (at any given distance) if you double the resolution.

**Comment by oskooi** [comment]
> If it's numerical dispersion, you should see agreement improve (at any given distance) if you double the resolution.

The results do not change even if you increase the resolution by a factor of 5 as shown here for two runs at resolutions 20 and 100. 

![farfields_Hz_dft_vs_n2f_res20 0_0 2_2 0](https://user-images.githubusercontent.com/7152530/152467606-6480b568-21a5-4f0d-ac1e-7d45432f4e6c.png)

![farfields_Hz_dft_vs_n2f_res100 0_0 2_2 0](https://user-images.githubusercontent.com/7152530/152467587-9fd876e5-e4aa-4740-848c-772ab0a514f4.png)

**Comment by stevengj** [comment]
There is also a systematic error introduced by your truncation of the cell in the x direction, because your near2far surface is not closed. 

You could try increasing the cell size in the x direction.

**Comment by oskooi** [comment]
> You could try increasing the cell size in the x direction.

Increasing the cell size in the x direction does indeed produce better agreement between the near2far and actual DFT fields as shown below. The only weird thing is how large the cell size needs to be to show such reasonably good agreement. In this example, the "padding" region on either side of the holey waveguide cavity needs to be more than *ten times* the length of the actual holey waveguide. 

Another thing to note is that when there is agreement, the near2far and DFT fields match *exactly* in both the real and imaginary part. There is *no* phase offset. This is different from what is written in [Tutorial/Far-field profile of a cavity](https://meep.readthedocs.io/en/latest/Python_Tutorials/Near_to_Far_Field_Spectra/#far-field-profile-of-a-cavity):
```
Finally, given that the far-field spectra is derived from the Fourier-transformed
fields which includes an arbitrary constant factor, we should expect an overall 
scale and phase difference in the results obtained using the near-to-far-field 
feature with those from a corresponding simulation involving the full computational 
volume. The key point is that the results will be qualitatively but not quantitatively 
identical.
```

**Case 1: sx=21.05**

![cavity_farfield_plot2D_dpad4_0 2_2 0](https://user-images.githubusercontent.com/7152530/152910814-71c8ba34-cc27-40f3-b743-e0307a30d95d.png)

![test_Hz_dft_vs_n2f_res20_dpad4_d10 2_d22 0](https://user-images.githubusercontent.com/7152530/152910599-f486c005-e261-4f65-ab07-39e07d12a838.png)

**Case 2: sx=77.05**

![cavity_farfield_plot2D_dpad32_0 2_2 0](https://user-images.githubusercontent.com/7152530/152911109-5293f29f-21cb-4c9d-85e8-d0537be1634a.png)

![test_Hz_dft_vs_n2f_res20_dpad32_d10 2_d22 0](https://user-images.githubusercontent.com/7152530/152910612-b6b9cb89-c290-4e76-8a4e-d7234eacf3dd.png)
