### ISSUE TITLE
Custom path to libctl

### ISSUE THREAD

**Issue by Yaraslaut** [NanoComp/meep#1915]
If libctl was installed at some custom path and this path was used to configure  `--with-libctl=LIBCTL_PATH`, configure fail.

When configure script is trying to find library [here](https://github.com/NanoComp/meep/blob/master/configure.ac#L408)
```
if test x != x"$LIBCTL_DIR" -a -r "$LIBCTL_DIR/share/libctl/base/ctl.scm"; then
￼	LIBCTL_DIR="$LIBCTL_DIR/share/libctl"
fi
```
in LIBCTL_DIR it saves some path, but no infromation about library path saves in `LIBS`.
And when we are trying to link to the library -lctl [here](https://github.com/NanoComp/meep/blob/master/configure.ac#L435), we get an error, that libctl can not be found

```
# check for -lctl:
AC_CHECK_LIB(ctl, ctl_get_vector3, [], [AC_MSG_ERROR([Couldn't find the required libctl library.])])
```

Then, when script is trying to find ctl.h there is no custom path in the list of possible paths
```
CTL_H_CPPFLAG=""
AC_CHECK_HEADER(ctl.h, [CTL_H_CPPFLAG=" "], [
  save_CPPFLAGS=$CPPFLAGS
  AC_MSG_CHECKING([for alternate ctl.h location])
  for ctl_h_path in /usr/include/ctl /usr/local/include/ctl; do  <-------------------- HERE
     CPPFLAGS="$save_CPPFLAGS -I$ctl_h_path"
     AC_COMPILE_IFELSE([AC_LANG_PROGRAM([[#include <ctl.h>]],[])], [CTL_H_CPPFLAG=-I$ctl_h_path; break])
  done
  AC_MSG_RESULT([$CTL_H_CPPFLAG])
  CPPFLAGS=$save_CPPFLAGS])
```
and if the correct path is found, it is not saved in `CPPFLAGS`

**Comment by stevengj** [comment]
You need to set `LDFLAGS` (to find `-lctl`), `CPPFLAGS` (to find `ctl.h`) *and* `--with-libctl-dir` (which is basically the location of the scheme files used in the scheme interface).   The latter does not set the former.

**Comment by stevengj** [comment]
See also https://meep.readthedocs.io/en/latest/Build_From_Source/#paths-for-configuring
