### ISSUE TITLE
ax_cxx_maxopt.m4 breaks any CXXFLAGS

### ISSUE THREAD

**Issue by StefanBruens** [NanoComp/meep#1934]
The following line should skip the whole block when CXXFLAGS has been set:

https://github.com/NanoComp/meep/blob/61fae689eb7d891223bbc9d4f24827d196938d51/m4/ax_cxx_maxopt.m4#L36-L37

Unfortunately, `ac_test_CXXFLAGS` is only ever set to `y` (not `set`), so the block is always executed and any specified CXXFLAGS are replaced, e.g. for GCC `CXXFLAGS="-O3"`.

The `configure` shipped in the tarball (generated with autoconf 2.71) has the following lines:
```
4801:ac_test_CFLAGS=${CFLAGS+y}
4870:if test $ac_test_CFLAGS; then
5476:ac_test_CXXFLAGS=${CXXFLAGS+y}
5545:if test $ac_test_CXXFLAGS; then
7204:if test "$ac_test_CXXFLAGS" != "set"; then
```
apparently, autoconf > 2.69 no longer assigns `set`. Processing the same configure.ac with autoconf 2.69 yields:
```
4674:ac_test_CXXFLAGS=${CXXFLAGS+set}
```

Checking for `"$ac_test_CXXFLAGS" != "set"` is bad, as it (ab)uses an autoconf implementation detail.

**Comment by stevengj** [comment]
Yikes, looks like this was [change in autoconf in 2015](https://git.savannah.gnu.org/cgit/autoconf.git/commit/?id=76754e04fce5f6a7701bec57b057020585df2ae3).
