### ISSUE TITLE
mode decomposition for 2d cell with out-of-plane wavevector

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#1957]
All the examples in [Tutorial/Mode Decomposition](https://meep.readthedocs.io/en/latest/Python_Tutorials/Mode_Decomposition) involve a 2d cell with *in-plane* wavevector. Since Meep supports the special case of a [2d cell with *out-of-plane* wavevector](https://meep.readthedocs.io/en/latest/2d_Cell_Special_kz/), it would be useful to demonstrate this feature using mode decomposition. Currently, there is only one example for the `kz_2d` feature involving a flux calculation which is not that interesting.  As a practical example, we could demonstrate how to compute the diffraction orders via `get_eigenmode_coefficients` of a 2d binary-phase grating for an incident planewave with out-of-plane wavevector.

**Comment by stevengj** [comment]
Should be straightforward change to `mpb.cpp`.  After we call `get_eigenmode` in both the mode-coefficient and eigenmode-source code, if we are doing "special_kz" then you need to call a `special_kz_phasefix` function, which looks something like:
```cxx
function special_kz_phasefix(eigenmode_data *edata) {
  size_t n = edata->n[0] * edata->n[1] * edata->n[2];
  complex<mpb_real> *E = (complex<mpb_real> *)edata->fft_data_E;
  complex<mpb_real> *H = (complex<mpb_real> *)edata->fft_data_H;
  complex<mpb_real> im(0,1);
  for (size_t i = 0; i < n; ++i) {
    E[3*i + 2] *= im; // Ez
    H[3*i + 0] *= im; // Hx
    H[3*i + 1] *= im; // Hy
  }
}
```

**Comment by stevengj** [comment]
Or it might be `-im`?   Maybe for the eigenmode source, since there is no complex-conjugation there.
