### ISSUE TITLE
Cylindrical Adjoint Documentation Suggestion for Monitors

### ISSUE THREAD

**Issue by ianmatthewhammond** [NanoComp/meep#1974]
I've been running optimizations of a Microdisk in cylindrical coordinates using a near2far objective argument. With the setup below I was facing NaN's in my adjoint run (which I further debugged and found the source NaN's in objective.py during the call to self._monitor.swigobj.near_sourcedata. 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/51729722/156390551-5c219bcd-0528-444b-90f5-4665cdb16a44.png)

After a series of trial and error, I realized the problem was having my monitor at r=0. Moving it away from the origin fixed the issue. It could be useful to note this somewhere so future users don't encounter the same issue. Thanks!

**Comment by smartalecH** [comment]
(cc @mochen4)
