### ISSUE TITLE
Incorrect fit parameters Gold (Grosges and Barchiesi)

### ISSUE THREAD

**Issue by andrewsalij** [NanoComp/meep#1987]
https://github.com/NanoComp/meep/blob/master/python/materials.py 
has flipped parameters for the damping of drude and lorentz oscillators from the citation (lorentz should have the lower energy).
That noted, their parameters don't seem to reproduce Johnson and Christy

**Comment by oskooi** [comment]
Whoops, this is a bug. Nice catch. Feel free to file a pull request with the fix.

Separately, Fig. 1a of the Grosges and Barchiesi reference does show reasonably good agreement for the complex refractive index of Au comparing their fitted model and the results from Johnson and Christy. If the corrected data for Au from the materials library is showing some discrepancies, perhaps there is another bug in the materials library data?
