### ISSUE TITLE
New adjoint filtering scheme

### ISSUE THREAD

**Issue by smartalecH** [NanoComp/meep#2012]
The current filtering scheme often induces a spatial delay in each dimension. This implies the filter kernel is not a ["zero-phase" filter](https://ccrma.stanford.edu/~jos/fp/Zero_Phase_Filters_Even_Impulse.html). In theory, all of the example impulse responses currently in the codebase (top-hat, conic, and Gaussian) *should* be zero-phase, indicating our setup is wrong.

One way to get around this is to implement a "filt-filt" (essentially filter in both directions, and remove the phase delay). This is what is implemented in #1625. This, of course, is *not* what we want, as this changes the underlying kernel of the final filter operation, rendering all of our minimum length-scale constraint math invalid. It should be possible to properly implement a single-pass filter with the above kernels.

Since all of our kernels are *separable*, we can actually do a batched convolution (natively supported by `autograd`) so long as we construct our filter kernels properly and apply the right padding (to preserve the correct shape).

Right now we do an fft-based filter. We may not need to with a batched convolution (depending on the size of the kernel, an fft convolution [may be *slower*](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.fftconvolve.html)).

(cc @hammy4815)

**Comment by stevengj** [comment]
[This coordinate system](https://github.com/NanoComp/meep/blob/master/python/adjoint/filters.py#L236-L239) looks wrong to me.  For FFT-based filtering one has periodic boundary conditions, so ±L/2 are equivalent points and should not be included twice.

It's pretty easy to get the boundary conditions / origin slightly wrong for this sort of thing, especially in conjunction with padding and `fftshift`.

**Comment by stevengj** [comment]
One option would be to use `np.fftfreq` instead of `linspace` to get the coordinates, then zero-pad in the *center* and omit the `fftshift`.  This might be less error-prone.

**Comment by smartalecH** [comment]
> For FFT-based filtering one has periodic boundary conditions, so ±L/2 are equivalent points and should not be included twice.

The kernel is symmetric though. So `f(-L/2) = f(L/2)`.

> (Then you subsequently zero-pad, but you do so by equal amounts on both sides, so you have the same problem.)

But if the padding is identical on both sides, it's still "periodic" right?

**Comment by stevengj** [comment]
In particular, for a filter length `n` (even or odd), I think you want the filter to be centered at `n/2` *rounded down* before the `ifftshift`.  In particular:

1. Create the filter kernel array of length `n` centered at `n/2` (rounded down).
2. Zero-pad it as needed by adding `k` zeros to both ends.  (Now the center is at `n/2 + k == (n+2k)/2` rounded down, which is correct for the new length `n+2k`.)
3. `ifftshift` the filter array.
4. Do the convolution: `ifft(fft(ρ) * fft(paddedkernel))`

**Comment by smartalecH** [comment]
> Zero-pad it as needed by adding k zeros to both ends. (Now the center is at n/2 + k == (n+2k)/2 rounded down, which is correct for the new length n+2k.)

By zero-padding, doesn't that mean the new array is no longer symmetric (if the number of taps is even)? 

For example, suppose `x = [1,2,3,2]`. `x` is indeed symmetric (it's DFT is purely real):

```
> fft(ifftshift([1,2,3,2]))
[8.+0.j 2.+0.j 0.+0.j 2.+0.j]
```

However, as soon as I pad it (`y=[0,0,0,0,1,2,3,2,0,0,0,0]`) It's no longer symmetric (with or without the `ifftshift`):
```
> fft.fft(fft.ifftshift([0,0,0,0,1, 3, 2, 3,0,0,0,0]))
[ 9.        +0.00000000e+00j  7.69615242+8.66025404e-01j
  4.5       +8.66025404e-01j  1.        +0.00000000e+00j
 -1.5       -8.66025404e-01j -2.69615242-8.66025404e-01j
 -3.        -2.22044605e-16j -2.69615242+8.66025404e-01j
 -1.5       +8.66025404e-01j  1.        +0.00000000e+00j
  4.5       -8.66025404e-01j  7.69615242-8.66025404e-01j]
```

Or am I missing something?

**Comment by stevengj** [comment]
Yes, right, sorry.  You need to split the Nyquist (middle) element 50–50 between the positive and negative components when zero-padding an even-length array.

i.e. zero-pad with something like:
```py
# zero pad by k (before ifftshift)
def symmetric_zeropad(x, k):
    y = np.pad(x, (k, k))
    if len(x) % 2 == 0: # even
        middle = x[0]
        y[k] = middle/2
        y[-k] = middle/2
    return y
```

**Comment by stevengj** [comment]
e.g.
```py
>>> x = [1,2,3.0,2]
>>> y = symmetric_zeropad(x, 3)
array([0. , 0. , 0. , 0.5, 2. , 3. , 2. , 0.5, 0. , 0. ])
>>> np.fft.ifftshift(y)
array([3. , 2. , 0.5, 0. , 0. , 0. , 0. , 0. , 0.5, 2. ])
>>> np.fft.fft(np.fft.ifftshift(y))
array([8.00000000e+00+0.j, 6.54508497e+00+0.j, 3.42705098e+00+0.j,
       9.54915028e-01+0.j, 7.29490169e-02+0.j, 3.33066907e-16+0.j,
       7.29490169e-02+0.j, 9.54915028e-01+0.j, 3.42705098e+00+0.j,
       6.54508497e+00+0.j])
```

**Comment by stevengj** [comment]
Alternatively, it might be clearer to enforce that the convolution kernel is symmetric by only specifying half of it (from [0,L/2]), and then constructing the other half by mirror flipping (and padding as needed).
