### ISSUE TITLE
rotate_reciprocal function error

### ISSUE THREAD

**Issue by zebihcetin** [NanoComp/meep#2038]
Hi,
Is this a bug or am i doing something wrong, the version of meep is 1.23.0

`import math`
`import meep as mp`
`axis = mp.Vector3(0, 0.5, 0.5)`
`theta = np.radians(90)`
`lat = mp.Vector3(0.25, 0.75, 0.5)`

`mp.Vector3.rotate_reciprocal(axis,theta,lat)`

`TypeError Traceback (most recent call last)
mp.Vector3.rotate_reciprocal(axis,theta,lat)

TypeError: rotate_reciprocal() missing 1 required positional argument: 'lat'`

**Comment by stevengj** [comment]
The `lat` argument should be a `mp.Lattice`, as in the example here: https://github.com/NanoComp/meep/blob/74cb6dd9b0c1d92ffa270fe759d5f1afe69763d7/python/tests/test_geom.py#L444-L449
