### ISSUE TITLE
"Planewave Sources Extending into PML" not possible with meep version 1.23.0

### ISSUE THREAD

**Issue by linaku94** [NanoComp/meep#2043]
I want to create a plane-wave source extending into a PML-Layer. Therefore, I tried to reproduce this [tutorial/example](https://meep.readthedocs.io/en/latest/Perfectly_Matched_Layer/#planewave-sources-extending-into-pml)

I used the exact same code:

```
import meep as mp
import matplotlib.pyplot as plt

pml_layers = [mp.PML(thickness=1)]
cell_size = mp.Vector3(10,10)

sources = [mp.Source(mp.ContinuousSource(1,is_integrated=True),
                     center=mp.Vector3(-4),
                     size=mp.Vector3(y=10),
                     component=mp.Ez)]

sim = mp.Simulation(resolution=20,
                    cell_size=cell_size,
                    boundary_layers=pml_layers,
                    sources=sources,
                    k_point=mp.Vector3())

sim.run(until=30)

sim.plot2D(fields=mp.Ez)
plt.show()
```

However, the `is_integrated` option doesn't change anything, I never get an actual plane-wave source. My meep version is 1.23.0, but the same issue appears with 1.22. With version 1.21 it works.

resulting figure, `is_integrated = True` with meep 1.23.0
![Figure_1](https://user-images.githubusercontent.com/66686961/163358986-1ee54d5e-da04-4e7e-a9e9-57e3eb3d6867.png)

**Comment by stevengj** [comment]
Thanks for the bug report!  `git bisect` says that the problem is due to ce4d151a06e74077ccfd8e71bd62f44aa2442f2e (#1829) by @oskooi
