### ISSUE TITLE
scaling factor for eigenmode adjoint source

### ISSUE THREAD

**Issue by MarkMa1990** [NanoComp/meep#2074]
Hi,

I just tested the code "https://nbviewer.org/github/NanoComp/meep/blob/master/python/examples/adjoint_optimization/01-Introduction.ipynb", and for version 1.18.0, the gradients from adjoin method and finite difference match, for version 1.22.0, it requires 4 times extra scale to make the gradient match. 

![image](https://user-images.githubusercontent.com/10673026/168597465-7a570bcc-2ee2-4fae-9bc0-9a857e21ecb0.png)

at meep/python/objective.py, line 99, the scale should be "scale *= 8" instead of "scale *= 2". 

Can I ask where are these scale factor coming from? because of field FFT?

left figure, version 1.18.0, right, 1.22.0.

**Comment by smartalecH** [comment]
See #1984.
