### ISSUE TITLE
Mirror with phase=1 results in wrong behavior

### ISSUE THREAD

**Issue by AhmedOthman7** [NanoComp/meep#2075]
I am testing a Gaussian beam source for a beam propagating in -y and polarized in z direction.
Both the structure and the fields should be symmetric around x and z axes.
However, when I use `mp.Mirror(mp.Z, phase=1)`, I get the mirrored field with flipped phase around z. 
 `mp.Mirror(mp.Z, phase=-1)` on the other hand, results in the required behavior (actual symmetry around z).

Maybe you consider this as an odd symmetry as you see the field direction change if you "look" at it from z=0, but it is somewhat counter-intuitive as the field is still in the +z-direction. At least this needs some clarification to avoid confusion.

I am using the latest release from conda-forge.
The code I use is as below.
Thank you so much in advance.

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr 19 02:02:09 2022

@author: ahmed
"""


import meep as mp
import matplotlib.pyplot as plt

sim_until_time = 25
s = 12
source_lambda = 0.8
resolution = 10
dpml = 0.5


cell_size = mp.Vector3(s, s, s)
boundary_layers = [mp.PML(thickness=dpml)]
source_center = mp.Vector3(0,s/2-2*dpml,0)


beam_x0 = mp.Vector3(0,0,0)    # beam focus (relative to source center)
beam_kdir = mp.Vector3(0,-1,0)
beam_w0 = 1
beam_E0 = mp.Vector3(0,0,1)

fsim_fcen = 1/source_lambda
fsim_df = 0.5
structure_symmetry = [mp.Mirror(mp.X, phase=1), mp.Mirror(mp.Z, phase=-1)]
# structure_symmetry = [mp.Mirror(mp.X, phase=1), mp.Mirror(mp.Z, phase=1)]

sources = [mp.GaussianBeamSource(src=mp.GaussianSource(fsim_fcen,fsim_df),
                                 center=source_center,
                                 size=mp.Vector3(s-2*dpml,0,s-2*dpml),
                                 beam_x0=beam_x0,
                                 beam_kdir=beam_kdir,
                                 beam_w0=beam_w0,
                                 beam_E0=beam_E0)]

geometry = []


sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size,
                    boundary_layers=boundary_layers,
                    sources=sources,
                    geometry=geometry,
                    symmetries=structure_symmetry)

dft_obj = sim.add_dft_fields([mp.Ex,mp.Ez,mp.Hx,mp.Hz], fsim_fcen, 0, 1, center=mp.Vector3(), size=cell_size)
            
sim.run(until=sim_until_time)

#%%
plt.figure()
sim.plot2D(fields=mp.Ez,
           output_plane=mp.Volume(center=mp.Vector3(),
size=mp.Vector3(s,s,0)))

plt.figure()
sim.plot2D(fields=mp.Ez,
           output_plane=mp.Volume(center=mp.Vector3(),
size=mp.Vector3(s,0,s)))

plt.figure()
sim.plot2D(fields=mp.Ez,
           output_plane=mp.Volume(center=mp.Vector3(),
size=mp.Vector3(0,s,s)))
```

**Comment by stevengj** [comment]
Your beam is polarized in the z direction (`beam_E0 = (0,0,1)`).   If you mirror flip this `z -> -z` then it flips the sign.  Therefore, `phase = -1` is correct, and `phase = +1` is wrong.

**Comment by stevengj** [comment]
See also this diagram of even (phase = +1) and odd (phase= -1) electric fields:
<img width="581" alt="image" src="https://user-images.githubusercontent.com/2913679/169528584-af5183e9-00d2-4a9c-bac3-894238be6286.png">
from chapter 7 of [our book](http://ab-initio.mit.edu/book/)

**Comment by AhmedOthman7** [comment]
Ok.
Sorry for my misunderstanding.
Thank you so much.
