### ISSUE TITLE
Mie Scattering result difference

### ISSUE THREAD

**Issue by chenyudong92** [NanoComp/meep#2084]
Hi,

I run the example of Mie Scattering. But the result shown like:
![output](https://user-images.githubusercontent.com/57641431/170534706-785e6844-619b-49f2-b737-3feb328e2c82.png)

It is different with the tutorial shown result:
![1](https://user-images.githubusercontent.com/57641431/170534966-5f3caa64-83c9-4747-9034-5a8a9aaa66c0.PNG)

What is the problem?

**Comment by oskooi** [comment]
This is probably because the results are not yet [converged](https://meep.readthedocs.io/en/latest/FAQ/#checking-convergence). Since the mismatch in your data appears for the small wavelengths, try doubling the resolution.
