### ISSUE TITLE
Incorrect FourierFields gradients for D components

### ISSUE THREAD

**Issue by mochen4** [NanoComp/meep#2090]
The FourierFields gradients for D fields is incorrect by a factor of the permittivity ε (at the location of interest).

Here is an example
```
Si = mp.Medium(index=3.4)
resolution = 20
Sx = 5
Sy = 3
cell_size = mp.Vector3(Sx,Sy)
pml_layers = [mp.PML(1.0)]
fcen = 1/1.55
width = 0.3
fwidth = width * fcen
frequencies = [fcen]
source_center  = [-1,0,0]
source_size    = mp.Vector3(0,0.5,0)
src = mp.GaussianSource(frequency=fcen,fwidth=fwidth)
source = [mp.Source(src, component=mp.Ez, size = source_size,center=source_center)]
design_region_resolution = 20
Nx = design_region_resolution//2
Ny = design_region_resolution//2

design_variables = mp.MaterialGrid(mp.Vector3(Nx,Ny),mp.air,Si)
design_region = mpa.DesignRegion(design_variables,volume=mp.Volume(center=mp.Vector3(), size=mp.Vector3(0.5, 0.5, 0)))
geometry = [
    mp.Block(center=mp.Vector3(1,0), size = mp.Vector3(0.5, 0.5), material=Si),                 
    mp.Block(center=design_region.center, size=design_region.size, material=design_variables), # design region                          
]
sim = mp.Simulation(cell_size=cell_size,
                    boundary_layers=pml_layers,
                    geometry=geometry,
                    sources=source,
                    resolution=resolution)

Dz = mpa.FourierFields(sim,mp.Volume(center=mp.Vector3(1,0),size=mp.Vector3(0, 0.1)),mp.Dz,yee_grid=True)

ob_list = [Dz]                                                                                          
def J(dz):
    return npa.abs(dz[0,0])**2
opt = mpa.OptimizationProblem(
    simulation=sim,
    objective_functions=J,
    objective_arguments=ob_list,
    design_regions=[design_region],
    frequencies=frequencies)
```
which has the layout:
![image](https://user-images.githubusercontent.com/25192039/171524691-b8fe8d74-a786-4946-953a-792d506ee7a9.png)

I found the fd_gradients was approximately ε(=12 in the code above) * adjoint_gradients. If the monitor is placed inside the design region, then the factor is the permittivity corresponding to the design parameter weight at that point.

**Comment by stevengj** [comment]
Possibly the adjoint current for a `D` Fourier-field output should be a `D` current rather than an `E` current, and similarly for `B`?

There is an [undocumented feature](https://github.com/NanoComp/meep/blob/master/src/sources.cpp#L275-L281) in which you can specify a current source as `D` rather than `E` and it gets multiplied by ε (at least for isotropic media), and similarly a `B` current is multiplied by µ.

**Comment by stevengj** [comment]
Oh, I think I may see the problem — [this line](https://github.com/NanoComp/meep/blob/master/src/sources.cpp#L275-L281) to multiply the current by ε for a `D` source is only executed when you add the source term with the usual high-level interface.  It's not done by the low-level `add_srcdata` function that we switched to with @mawc2019's work.

**Comment by mawc2019** [comment]
PR #2095 is a tentative fix for this issue. I tweaked `fourier_sourcedata` in dft.cpp instead of `add_srcdata` in sources.cpp to avoid adding extra loops.

**Comment by mawc2019** [comment]
> If the monitor is placed inside the design region, then the factor is the permittivity corresponding to the design parameter weight at that point.

In this example, the monitor is not placed inside the design region. If the monitor is placed inside the design region, PR #2095 does not work even if the design region is uniform. The variation of permittivity with respect to the design parameters needs to be taken into account.
