### ISSUE TITLE
adjoint optimization with multiple objective functions

### ISSUE THREAD

**Issue by mochen4** [NanoComp/meep#2097]
Adjoint optimization fails if there are more than one objective functions. https://github.com/NanoComp/meep/blob/91d36ba73d1ae0eb135d18c783840cff9fcd71ef/python/adjoint/utils.py#L54-L58 Somewhere in ``mp._get_gradient`` frees the memory of the fields, causing problems when we reuse the forward fields again for the another objective function.

The issue actually exists before #1855 , where we could make copies of forward fields before passing in ``mp._get_gradient``. Right now, the naive fix could be installing one forward design region monitor for each objective function, so that we have a fresh copy each time we call ``mp._get_gradient``.

**Comment by smartalecH** [comment]
> Somewhere in mp._get_gradient frees the memory of the fields

I'm guessing this is the culprit, in `meepgeom.cpp`:

https://github.com/NanoComp/meep/blob/91d36ba73d1ae0eb135d18c783840cff9fcd71ef/src/meepgeom.cpp#L3023-L3029

**Comment by stevengj** [comment]
@smartalecH, it seems odd that those chunks are being deleted in this routine, since they aren't allocated by this routine.  Shouldn't they be deleted by the code that "owns" them?

**Comment by smartalecH** [comment]
Basically, we need a new routine that separately deletes DFT chunks when we want to. The tricky part is we need to remember *when* to delete them.

For example, we want to delete each adjoint chunk after we "recombine" it with the forward runs. So modifying the earlier block of code should suffice:
```c++
 // clear all the dft data structures 
 for (int i=0;i<3;i++){ 
   for (int ii=0;ii<adjoint_dft_chunks[i].size();ii++){ 
     delete adjoint_dft_chunks[i][ii]; 
   } 
 } 
```

However, we need to hang on to the *forward* chunks until we are all done looping through objective functions (and performing their recombination steps), which is done here:

https://github.com/NanoComp/meep/blob/405b7e607f87d7dd4a81baf3d5473aa4c28e7a4a/python/adjoint/optimization_problem.py#L264-L272

So after this point, we can *now* delete the forward chunks.
