### ISSUE TITLE
Use Blender as a Frontend?

### ISSUE THREAD

**Issue by KJ7LNW** [NanoComp/meep#2113]
Does Meep already have a 3D graphical frontend?

If not, what about Blender?

Meep is written in python, so is [Blender](https://www.blender.org/).  Sounds like a match made in heaven:

 - Blender provides a 3D editing environment
 - Meep supports 3D EM FDFD and blender could provide the 3D representation
 - Blender already has a rich plugin framework
 - Objects could be shaded by current or field density in the 3D modeler

I'm not a Python dev (too many years of Perl) but was thinking this could be a good fit.

What do you think?

Just a suggestion if it is helpful. 

-Eric

**Comment by stevengj** [comment]
For scientific visualization, Paraview and Mayavi are probably better fits.   Blender.

Blender also isn't really designed as a CAD tool, so I'm not sure how well it would work as an input control.   (It outputs a standard mesh format called FBX, but it isn't so easy to support arbitrary polyhedral meshes in Meep.  Anyway, supporting FBX would probably be a different issue.)
