### ISSUE TITLE
Allow disabling of sub-pixel smoothing for mpb.ModeSolver

### ISSUE THREAD

**Issue by flaport** [NanoComp/meep#2167]
currently it's not possible to disable sub-pixel smoothing for the mpb `ModeSolver`. However, the meep `Simulation` object *has* a `eps_averaging` flag. It would be great if we could add the same flag to the mpb `ModeSolver`. Disabling sub-pixel smoothing is important to be able to compare to other simulation tools (which might not implement it, or who might implement it differently.)

**Comment by stevengj** [comment]
Definitely this is possible in the Scheme interface.

**Comment by stevengj** [comment]
I think if you set `mesh_size=1` it will disable subpixel smoothing.

**Comment by stevengj** [comment]
One possibility would be to (re-)disable averaging when `mesh_size=1`.  This way you won't need to change the API.

Before this line, https://github.com/NanoComp/mpb/blob/84de012de21b34884ce174ebe0168d59b8a19671/src/maxwell/maxwell_eps.c#L588

you could add something like:
```c
if (mesh_prod == 1) {
  epsilon(&eps_mean, &eps_inv_mean, r, epsilon_data);
  md->eps_inv[xyz_index] = eps_inv_mean;
  goto got_eps_inv;
}
```
in a PR for the MPB repo.

To test it out, I would do something like the convergence plot of figure 4 of [this paper](https://math.mit.edu/~stevenj/papers/KottkeFa08.pdf), though you can just use isotropic ε and a cylinder.   That is, plot the convergence value of a single eigenvalue ω(k) for a square lattice of cylinders (for the TE/in-plane polarization) vs resolution.  By default it should be second-order convergence, and should switch to first-order convergence with `mesh_size=1`.
