### ISSUE TITLE
Fields diverge at some values of resolution in inclined plane wave simulation

### ISSUE THREAD

**Issue by AhmedOthman7** [NanoComp/meep#2187]
I am simulating a structure with an inclined plane wave input (Block boundary conditions).
The fields diverge and the power goes to very large values in some cases.
I made a minimalistic example to illustrate the issue (only a plane wave propagating).

In this example, the flux goes to very large values (starting from t~160). Changing the resolution to 45 instead of 50 however doesn't cause this problem. 

```
import meep as mp
import numpy as np
import matplotlib.pyplot as plt




sim_window_lateral = 1.25
source_lambda = 5
df = 1/(4*source_lambda)
theta = 45 # CCW rotation angle (degrees) about Y-axis of PW current source; 0 degrees along -z axis
resolution = 50
dpml = 1
sim_window_height = 13.5
sub_n_real = 3.5

cell_size = mp.Vector3(sim_window_lateral, sim_window_lateral, sim_window_height)
boundary_layers = [mp.PML(thickness=dpml,direction=mp.Z,side=mp.High),
                  mp.PML(thickness=dpml,direction=mp.Z,side=mp.Low)]
source_center = mp.Vector3(0,0, -sim_window_height/2+2*dpml)

sub_medium = mp.Medium(epsilon=sub_n_real**2)




structure_symmetry = [mp.Mirror(mp.Y, phase=1)]



fcen = 1/source_lambda
theta_rad = np.radians(theta) 
# k with correct length (plane of incidence: XZ) 
k = mp.Vector3(np.sin(theta_rad),0,np.cos(theta_rad)).scale(fcen*sub_n_real)

def pw_amp(k, x0):
    def _pw_amp(x):
        return np.exp(1j * 2 * np.pi * k.dot(x - x0))
    return _pw_amp

# p-polarizeed
sources = [ mp.Source(mp.GaussianSource(fcen, fwidth=df), component=mp.Ex, center=source_center,
                      size=mp.Vector3(sim_window_lateral,sim_window_lateral,0), amplitude=np.cos(theta_rad),
                      amp_func=pw_amp(k, source_center)),
           mp.Source(mp.GaussianSource(fcen, fwidth=df), component=mp.Ez, center=source_center,
                                 size=mp.Vector3(sim_window_lateral,sim_window_lateral,0),amplitude=-np.sin(theta_rad),
                                 amp_func=pw_amp(k, source_center))]

    
sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size,
                    boundary_layers=boundary_layers,
                    sources=sources,
                    k_point = k,
                    symmetries=structure_symmetry,
                    default_material=sub_medium
                    )


refl_pt = source_center + mp.Vector3(0,0,1)
refl_flux = sim.add_flux(fcen, df, 100, mp.FluxRegion(center=refl_pt, size=mp.Vector3(sim_window_lateral,sim_window_lateral,0)))


sim.use_output_directory('Fields_Time')

sim.run(until=500)



input_flux = np.array(mp.get_fluxes(refl_flux))
input_flux_data = sim.get_flux_data(refl_flux)

freq = mp.get_flux_freqs(refl_flux)
plt.figure()
plt.plot(freq, input_flux)
```

![image](https://user-images.githubusercontent.com/92053102/182962489-5ac1cc5b-764e-45a3-a1ac-705c5a00cba4.png)

**Comment by AhmedOthman7** [comment]
It seems to be related to the fact that the simulation window is not an integer number of the simulation cell side (1/resolution) in the lateral direction. Choosing an integer number worked for all the trials I did.
The resolution 45 does not make an integer either but it works.

So probably: 
Integer number of cells ==> works
Non-integer number of cells ==> may or may not work

Should we make the resolution be automatically chosen to be the closest number to the number entered by the user that makes an integer number of cells in all directions?

**Comment by MarkMa1990** [comment]
> I am simulating a structure with an inclined plane wave input (Block boundary conditions). The fields diverge and the power goes to very large values in some cases. I made a minimalistic example to illustrate the issue (only a plane wave propagating).
> 
> In this example, the flux goes to very large values (starting from t~160). Changing the resolution to 45 instead of 50 however doesn't cause this problem.
> 
> ```
> import meep as mp
> import numpy as np
> import matplotlib.pyplot as plt
> 
> 
> 
> 
> sim_window_lateral = 1.25
> source_lambda = 5
> df = 1/(4*source_lambda)
> theta = 45 # CCW rotation angle (degrees) about Y-axis of PW current source; 0 degrees along -z axis
> resolution = 50
> dpml = 1
> sim_window_height = 13.5
> sub_n_real = 3.5
> 
> cell_size = mp.Vector3(sim_window_lateral, sim_window_lateral, sim_window_height)
> boundary_layers = [mp.PML(thickness=dpml,direction=mp.Z,side=mp.High),
>                   mp.PML(thickness=dpml,direction=mp.Z,side=mp.Low)]
> source_center = mp.Vector3(0,0, -sim_window_height/2+2*dpml)
> 
> sub_medium = mp.Medium(epsilon=sub_n_real**2)
> 
> 
> 
> 
> structure_symmetry = [mp.Mirror(mp.Y, phase=1)]
> 
> 
> 
> fcen = 1/source_lambda
> theta_rad = np.radians(theta) 
> # k with correct length (plane of incidence: XZ) 
> k = mp.Vector3(np.sin(theta_rad),0,np.cos(theta_rad)).scale(fcen*sub_n_real)
> 
> def pw_amp(k, x0):
>     def _pw_amp(x):
>         return np.exp(1j * 2 * np.pi * k.dot(x - x0))
>     return _pw_amp
> 
> # p-polarizeed
> sources = [ mp.Source(mp.GaussianSource(fcen, fwidth=df), component=mp.Ex, center=source_center,
>                       size=mp.Vector3(sim_window_lateral,sim_window_lateral,0), amplitude=np.cos(theta_rad),
>                       amp_func=pw_amp(k, source_center)),
>            mp.Source(mp.GaussianSource(fcen, fwidth=df), component=mp.Ez, center=source_center,
>                                  size=mp.Vector3(sim_window_lateral,sim_window_lateral,0),amplitude=-np.sin(theta_rad),
>                                  amp_func=pw_amp(k, source_center))]
> 
>     
> sim = mp.Simulation(resolution=resolution,
>                     cell_size=cell_size,
>                     boundary_layers=boundary_layers,
>                     sources=sources,
>                     k_point = k,
>                     symmetries=structure_symmetry,
>                     default_material=sub_medium
>                     )
> 
> 
> refl_pt = source_center + mp.Vector3(0,0,1)
> refl_flux = sim.add_flux(fcen, df, 100, mp.FluxRegion(center=refl_pt, size=mp.Vector3(sim_window_lateral,sim_window_lateral,0)))
> 
> 
> sim.use_output_directory('Fields_Time')
> 
> sim.run(until=500)
> 
> 
> 
> input_flux = np.array(mp.get_fluxes(refl_flux))
> input_flux_data = sim.get_flux_data(refl_flux)
> 
> freq = mp.get_flux_freqs(refl_flux)
> plt.figure()
> plt.plot(freq, input_flux)
> ```
> 
> ![image](https://user-images.githubusercontent.com/92053102/182962489-5ac1cc5b-764e-45a3-a1ac-705c5a00cba4.png)

I just tested your code for meep version 1.,24.0, the issue can not be reproduced, which version were you using?

**Comment by AhmedOthman7** [comment]
I am using:
pymeep                    1.23.0          mpi_mpich_py39h1234567_1    conda-forge
on ubuntu 21.04

I will try to upgrade to 1.24 and try again

**Comment by AhmedOthman7** [comment]
I updated my meep to V1.24 and the problem is fixed in this version.
Sorry for the interruption.
