### ISSUE TITLE
Python tests fail with latest MPB

### ISSUE THREAD

**Issue by thomasdorch** [NanoComp/meep#2189]
It looks like the latest [MPB commit](https://github.com/NanoComp/mpb/commit/f44d025b32d1679f2126c3ab06a010b581d2edc5) is causing the Python tests to fail with segmentation faults. The Python tests pass when using the [previous commit](https://github.com/NanoComp/mpb/commit/84de012de21b34884ce174ebe0168d59b8a19671), but some fail with the most recent.

Related to #2186 #2188

**Comment by stevengj** [comment]
See also https://github.com/NanoComp/mpb/issues/151
