### ISSUE TITLE
Computing the gradient of a level-set function

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#2235]
Related to #2011.

This is an initial attempt to use the new subpixel smoothing feature of the adjoint solver to compute the gradient of a structure parameterized by its geometry (a level set) as an alternative to the conventional density-based (`MaterialGrid`) representation. The example involves computing the gradient of the diffraction efficiency of the m=+1 transmitted order of a 1D binary grating with respect to its height and fill factor. The results are to be validated by the usual method of the brute-force gradient computed using a finite difference. Once everything is working correctly, this demonstration will be converted into a tutorial for the user manual and a unit test.

The main feature of this calculation is a *differentiable* wrapper function  (`grating_matgrid` in the script below) that takes the grating height and fill factor as arguments and returns the weights of a `MaterialGrid` for the binary grating. These weights are then passed to the adjoint solver via a `DesignRegion` object in the usual way and the gradient which is computed is then backpropagated through the wrapper function. 

An image of the geometry created using this approach confirms that the structure is set up correctly. However, it seems there is a bug in the current setup because the final gradient is *zero*. Also, there is an important warning from autograd:
```
/.local/lib/python3/site-packages/autograd/tracer.py:14: UserWarning: Output seems independent of input.
  warnings.warn("Output seems independent of input.")
```

This message suggests there is a likely bug in the backpropagation step.

![binary_grating_matgrid](https://user-images.githubusercontent.com/7152530/190065757-a0317b65-70e3-403d-b9ff-3adccda20d04.png)

**output of running the script below**
```
-----------
Initializing structure...
Halving computational cell along direction y
Splitting into 2 chunks by voxels
time for choose_chunkdivision = 0.000121082 s
Working in 2D dimensions.
Computational cell is 8.5 x 0.78 x 0 with resolution 100
time for set_epsilon = 0.024535 s
-----------
field decay(t = 50.005): 0.04304565716016541 / 0.04304565716016541 = 1.0
field decay(t = 100.01): 0.11354452052348654 / 0.11354452052348654 = 1.0
on time step 29645 (time=148.225), 0.000134933 s/step
field decay(t = 150.01500000000001): 1.3975259335832059e-08 / 0.11354452052348654 = 1.2308175922008755e-07
field decay(t = 200.02): 5.861816753051918e-16 / 0.11354452052348654 = 5.162571232875486e-15
run 0 finished at t = 200.02 (40004 timesteps)
Starting forward run...
-----------
Initializing structure...
Warning: grid volume is not an integer number of pixels; cell size will be rounded to nearest pixel.
Halving computational cell along direction y
Splitting into 2 chunks by voxels
time for choose_chunkdivision = 0.000153305 s
Working in 2D dimensions.
Computational cell is 8.5 x 0.78 x 0 with resolution 100
     block, center = (-2.25,0,0)
          size (4,1e+20,1e+20)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (2.25,2.25,2.25)
     block, center = (1.5,0,0)
          size (3.5,0.777862,0)
          axes (1,0,0), (0,1,0), (0,0,1)
time for set_epsilon = 0.10944 s
-----------
run 0 finished at t = 160.28 (32056 timesteps)
Warning: grid volume is not an integer number of pixels; cell size will be rounded to nearest pixel.
MPB solved for frequency_1(1.53209,0,0) = 1.53209 after 11 iters
MPB solved for frequency_1(2,0,0) = 2 after 1 iters
Dominant planewave for band 1: (2.000000,-0.000000,0.000000)
Starting adjoint run...
Warning: grid volume is not an integer number of pixels; cell size will be rounded to nearest pixel.
MPB solved for frequency_1(-1.53209,0,0) = 1.53209 after 11 iters
MPB solved for frequency_1(-2,0,0) = 2 after 1 iters
run 1 finished at t = 106.055 (21211 timesteps)
Calculating gradient...
objective:, [0.1019033]
Warning: grid volume is not an integer number of pixels; cell size will be rounded to nearest pixel.
     block, center = (-2.25,0,0)
          size (4,1e+20,1e+20)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (2.25,2.25,2.25)
     block, center = (1.5,0,0)
          size (3.5,0.777862,0)
          axes (1,0,0), (0,1,0), (0,0,1)
/.local/lib/python3/site-packages/autograd/tracer.py:14: UserWarning: Output seems independent of input.
  warnings.warn("Output seems independent of input.")
gradient:, 0.0

Elapsed run time = 15.9436 s
```

```py
import math
import cmath
from enum import Enum

import numpy as np
import matplotlib
matplotlib.use('agg')
import matplotlib.pyplot as plt
from autograd import numpy as npa
from autograd import tensor_jacobian_product

import meep as mp
import meep.adjoint as mpa


dpml = 1.0 # PML thickness                                                                                         
dsub = 3.0 # substrate thickness                                                                                   
dpad = 3.0 # padding between PML and grating                                                                       

ng = 1.5
glass = mp.Medium(index=ng)

# angle of transmtted order                                                                                        
# 0 is +x with CCW rotation around z axis                                                                          
theta_tran = math.radians(40.0)

boundary_layers = [mp.PML(thickness=dpml,direction=mp.X)]

Polarization = Enum('Polarization','S P')


def tran_order(res: float, wvl: float, theta_pw: float, pol: Polarization,
               m: int, gp: float, gh: float, gff: float):
  """Computes the gradient of the diffraction efficiency of the m'th                                               
     transmitted order of a 1D binary grating with respect to the grating                                          
     height and fill factor using the adjoint solver.                                                              
                                                                                                                   
     Args:                                                                                                         
        res: resolution (pixels/μm)                                                                                
        wvl: wavelength of the diffraction order.                                                                  
        theta_pw: angle (degrees) of incident planewave.                                                           
                  0° is +x with CCW rotation around z axis.                                                        
                  plane of incidence is xy.                                                                        
        pol: polarization of the incident planewave.                                                               
        m: diffraction order in y direction.                                                                       
        gp: grating period.                                                                                        
        gh: grating height.                                                                                        
        gff: grating fill factor.                                                                                  
  """
  sx = dpml+dsub+gh+dpad+dpml
  sy = gp
  cell_size = mp.Vector3(sx,sy,0)

  design_region_size = mp.Vector3(gh+dpad,sy,0)
  design_region_resolution = int(2*res)
  Nx = int(design_region_size.x*design_region_resolution)
  Ny = int(design_region_size.y*design_region_resolution)

  matgrid = mp.MaterialGrid(mp.Vector3(Nx,Ny),
                            mp.air,
                            glass,
                            weights=np.ones((Nx,Ny)))

  matgrid_region = mpa.DesignRegion(
      matgrid,
      volume=mp.Volume(
          center=mp.Vector3(0.5*sx-dpml-0.5*(gh+dpad),0),
          size=mp.Vector3(design_region_size.x,
                          design_region_size.y)
      )
  )

  matgrid_geometry = [mp.Block(center=matgrid_region.center,
                               size=matgrid_region.size,
                               material=matgrid)]

  if pol.name == 'S':
    src_cmpt = mp.Ez
    mode_parity = mp.ODD_Z
  elif pol.name == 'P':
    src_cmpt = mp.Hz
    mode_parity = mp.EVEN_Z
  else:
    raise ValueError("pol must be S or P, only.")

  fcen = 1/wvl

  # wavevector of transmitted order in air                                                                         
  kdiff = mp.Vector3((fcen**2-(m/sy)**2)**0.5,m/sy,0)

  if theta_pw == 0:
    k = mp.Vector3()
    symmetries = [mp.Mirror(direction=mp.Y,
                            phase=1. if pol.name == 'S' else -1.)]
  else:
    k = mp.Vector3(ng*fcen,0,0).rotate(mp.Vector3(0,0,1),math.radians(theta_pw))
    symmetries = []

  def pw_amp(k,x0):
    def _pw_amp(x):
      return cmath.exp(1j*2*math.pi*k.dot(x+x0))
    return _pw_amp

  src_pt = mp.Vector3(-0.5*sx+dpml,0,0)
  sources = [mp.Source(mp.GaussianSource(fcen,fwidth=0.05*fcen),
                       component=src_cmpt,
                       center=src_pt,
                       size=mp.Vector3(0,sy,0),
                       amp_func=pw_amp(k,src_pt))]

  sim = mp.Simulation(resolution=res,
                      cell_size=cell_size,
                      default_material=glass,
                      symmetries=symmetries,
                      boundary_layers=boundary_layers,
                      k_point=k,
                      sources=sources)

  tran_pt = mp.Vector3(0.5*sx-dpml,0)
  tran_mon = sim.add_flux(fcen,
                          0,
                          1,
                          mp.FluxRegion(center=tran_pt,
                                        size=mp.Vector3(0,sy,0)))

  sim.run(
      until_after_sources=mp.stop_when_fields_decayed(
          50,
          src_cmpt,
          tran_pt,
          1e-9
      )
  )

  input_flux = mp.get_fluxes(tran_mon)[0]

  sim.reset_meep()

  substrate = [mp.Block(material=glass,
                        size=mp.Vector3(dpml+dsub,mp.inf,mp.inf),
                        center=mp.Vector3(-0.5*sx+0.5*(dpml+dsub),0,0))]

  geometry = substrate + matgrid_geometry

  sim = mp.Simulation(resolution=res,
                      cell_size=cell_size,
                      symmetries=symmetries,
                      boundary_layers=boundary_layers,
                      k_point=k,
                      sources=sources,
                      geometry=geometry)

  obj_list = [mpa.EigenmodeCoefficient(
      sim,
      mp.Volume(center=tran_pt,
                size=mp.Vector3(0,sy,0)),
      1,
      eig_parity=mode_parity,
      kpoint_func=lambda *not_used: kdiff
  )]

  def J(mode_mon):
    return npa.power(npa.abs(mode_mon),2) / input_flux

  opt = mpa.OptimizationProblem(simulation=sim,
                                objective_functions=J,
                                objective_arguments=obj_list,
                                design_regions=[matgrid_region],
                                frequencies=[fcen])

  def grating_matgrid(h, ff):
    """Generates the weights for a `MaterialGrid`                                                                  
       based on the grating height and fill factor.                                                                
    """
    xcoord = npa.linspace(-0.5*design_region_size.x,
                          +0.5*design_region_size.x,
                          Nx)
    ycoord = npa.linspace(-0.5*design_region_size.y,
                          +0.5*design_region_size.y,
                          Ny)
    xv, yv = npa.meshgrid(xcoord,ycoord)
    p = npa.where(npa.abs(yv) <= 0.5*ff*gp,
                  npa.where(xv <= xcoord[0] + h,
                            1.,
                            0.),
                  0.)
    p = p.flatten(order='F')
    return p

  design_params = grating_matgrid(gh, gff)
  f, dJ_du = opt([design_params])
  print(f"objective:, {f}")

  opt.plot2D()
  if mp.am_master():
    plt.savefig('binary_grating_matgrid.png',dpi=150,bbox_inches='tight')

  backprop_dJ_du = tensor_jacobian_product(grating_matgrid, 0)(gh, gff, dJ_du)
  sim.reset_meep()

  return backprop_dJ_du


if __name__ == '__main__':
  res = 100

  wvl = 0.5  # wavelength                                                                                          
  inc_ang = 0.
  m = +1

  pol = Polarization.S

  gp = wvl/math.sin(theta_tran) # grating period                                                                   
  gh = 0.5  # grating height                                                                                       
  gff = 0.5 # grating fill factor                                                                                  

  diff_eff_grad = tran_order(res, wvl, inc_ang, pol, m, gp, gh, gff)
  print(f"gradient:, {diff_eff_grad}")
```

**Comment by smartalecH** [comment]
Recall that our level set requires a filter step (or that you transform your grid into a signed distance function) in order to work properly. Then you must internally set $/beta=/infty$.

I may have missed it, but it looks like you are simply populating the grid with a binary array.

**Comment by oskooi** [comment]
Unfortunately, work on this issue is blocked by the bug in #2226 involving an incorrect mode (an oblique planewave) as computed by the Newton-method solver via MPB in `fields::get_eigenmode`. It seems that while #2114 fixed a different bug in `fields::get_eigenmode`related to oblique modes, it uncovered a new and separate bug  which had somehow gone unnoticed.

**Comment by smartalecH** [comment]
@oskooi check out [this comment](https://github.com/NanoComp/meep/discussions/2002#discussioncomment-2361602) too when you are back to looking at this. It describes essentially what you want to do.

**Comment by smartalecH** [comment]
> We are also using subpixel smoothing of the MaterialGrid via do_averaging=True and beta=np.inf.

Frankly, I would use the smoothed projection feature we recently implemented in python (rather than what we tried to implement in c++). We know there are bugs in 3D, I imagine there are bugs in 2D too. 

> should we just perturb one of the geometric parameters of the grating such as the height or duty cycle? 

Yes that should work fine. You may have to play with how big the step needs to be.

**Comment by oskooi** [comment]
> Frankly, I would use the smoothed projection feature we recently implemented in python

Why is it necessary to apply a smoothing projection to the design weights when they are already smoothed using the signed-distance function?

Separately, I have updated the script in my previous comment to compute the adjoint gradient of the diffraction efficiency with respect to the **height of the grating**. However, the adjoint gradient back propagated through the signed-distance function using Autograd's `tensor_jacobian_product` is zero which is incorrect:

 ```
directional-deriv:, [-0.01232668] (finite difference), 0.0 (adjoint)
```

I suspect this is because the signed-distance function implemented in the function `map_to_signed_distance_function` uses SciPy's `skfmm.distance` function which is not differentiable using Autograd. Do we therefore need to implement our own signed-distance function using Autograd to make this work?

**Comment by smartalecH** [comment]
> Why is it necessary to apply a smoothing projection to the design weights when they are already smoothed using the signed-distance function?

So keep in mind that the underlying framework using the material grid assumes a density based approach to TO. In order to turn it into a level set, you need to do subpixel smoothing, and our modified projection function lets us do that easily without leaving the realm of density-based TO. 

If you already have a level-set function that does smoothing for you, and you can backprop through it, then you don't need any extra smoothing (and you should turn off both the smoothing and set beta=0 in the material grid). 

The challenge is that we don't always have level set functions available to us. For trivial geometries, like squares or circles it's easy. But if you are trying to evolve something more difficult, (like starting with a simple waveguide crossing and doing shape optimization) then using the smoothed projection function makes this easy. 

> which is not differentiable using Autograd.

I would just write a custom level set for this. Rectangles are easy and you can do it in native autograd. Lots of resources online.

**Comment by oskooi** [comment]
> If you already have a level-set function that does smoothing for you, and you can backprop through it, then you don't need any extra smoothing (and you should turn off both the smoothing and set beta=0 in the material grid).

I have modified the script to disable the internal subpixel smoothing in `MaterialGrid` and instead apply a filter and projection via `conic_filter` and the new `smoothing_projection` functions to the level set *directly*:

**1. unperturbed grating**
```py
   # Obtain the grating as a level set.
    unperturbed_design_weights = grating_weights(
        grating_height_um,
        grating_duty_cycle,
        design_region_size,
        nx,
        ny,
    )
   # Apply a filter and projection to the level set.
    mapped_unperturbed_design_weights = mapping(
        unperturbed_design_weights,
        eta_intrinsic,
        npa.inf,
        filter_radius_um,
        design_region_size,
        design_region_resolution_um,
    )

    obj_value_unperturbed, grad_unperturbed = opt(
        [mapped_unperturbed_design_weights],
        need_gradient=True,
    )
```

**2. grating with perturbed height**
```py
   # Obtain the grating as a level set.
    height_perturbation_um = 1e-2
    perturbed_design_weights = grating_weights(
        grating_height_um + height_perturbation_um,
        grating_duty_cycle,
        design_region_size,
        nx,
        ny,
    )
   # Apply a filter and projection to the level set.
    mapped_perturbed_design_weights = mapping(
        perturbed_design_weights,
        eta_intrinsic,
        npa.inf,
        filter_radius_um,
        design_region_size,
        design_region_resolution_um,
    )

    obj_value_perturbed, _ = opt(
        [mapped_perturbed_design_weights],
        need_gradient=False
    )
```

Now it seems we just need to backpropagate *twice*: the first time through the `mapping` function *and* then through the `grating_weights` function:

```py
def mapping(
        weights: npa.ndarray,
        eta: float,
        beta: float,
        filter_radius_um: float,
        design_region_size: mp.Vector3,
        design_region_resolution: float
) -> np.ndarray:
    """A differentiable mapping function for the design weights."""

    filtered_field = mpa.conic_filter(
        weights,
        filter_radius_um,
	design_region_size.x,
        design_region_size.y,
        design_region_resolution,
    )

    if beta == 0:
        return filtered_field.flatten()

    else:
        projected_field = mpa.smoothed_projection(
            filtered_field,
            beta,
            eta,
            design_region_resolution,
        )

        return projected_field.flatten()
```

Is this the correct approach?

**Comment by stevengj** [comment]
You want to skip the conic filter, which moves your level set.

**Comment by oskooi** [comment]
> You want to skip the conic filter, which moves your level set.

There is a comment in the docstrings of the `smoothed_projection` function which states that the input to this function must have been already filtered:

https://github.com/NanoComp/meep/blob/87bc763dc2d0100d717fcf62b5f4daa0ee98080f/python/adjoint/filters.py#L717-L718

@smartalecH: what will happen if we remove the `conic_filter` step in the `mapping` function and thus only apply `smoothed_projection` to the level set?

**Comment by smartalecH** [comment]
@oskooi the only assumption for this new projection function is that you have a level set and that it's smoothly varying.

You don't appear to have that. You just have binary shapes derived from fundamental parameters. 

So in your case, you do need to filter. But you would also need to map this ad hoc levelset to your new shape using eg a marching squares algorithm. 

It would be much easier to simply use a signed distance function of a rectangle. Lots of resources online like this [one](https://www.ronja-tutorials.com/post/034-2d-sdf-basics/). Offset the zero levelset to be 0.5 (our standard eta value) and use the new smoothed projection function to do the proper smoothing. You should be able to code it up in autograd.

**Comment by stevengj** [comment]
(To be clear, the main application of this smoothed projection is for topology optimization, i.e. when the density/level-set function *itself* comprises the degrees of freedom.)

**Comment by oskooi** [comment]
As a test to verify that the gradient calculation has been set up correctly, I would like to demonstrate that we can compute a non-zero gradient of the diffraction efficiency with respect to the grating height. (The gradient is incorrect until we have implemented the signed-distance function using Autograd and used it to replace the `conic_filter` in the `mapping` function.)

For now, applying a `mapping` consisting of a `conic_filter` followed by a `smoothed_projection` to a levelset (full script is [above](https://github.com/NanoComp/meep/issues/2235#issuecomment-1918118883)) and then trying to back propagate the gradient through the functions `mapping` and then `grating_levelset`  always produces a **zero** gradient along with this warning from autograd:

```
/python3.10/site-packages/autograd/tracer.py:14: UserWarning: Output seems independent of input.
  warnings.warn("Output seems independent of input.")
```

```
grad_backprop (grating_levelset):, 0.0, ()
directional-deriv:, [-0.00056425] (finite difference), 0.0 (adjoint)
```

It is unclear why the gradient of the levelset function is always zero. @smartalecH, any thoughts?

**Comment by oskooi** [comment]
Looks like the problem is that Autograd does not support gradients of `numpy.meshgrid` (HIPS/autograd#457) which is currently used by the levelset construction function:

```py
def grating_levelset(
        grating_height_um: float,
        grating_duty_cycle: float,
        design_region_size: mp.Vector3,
        nx: int,
        ny: int
) -> npa.ndarray:
    """Returns the weights for the grating as a 1D array."""

    xcoord = npa.linspace(
        -0.5*design_region_size.x,
        +0.5*design_region_size.x,
        nx
    )
    ycoord = npa.linspace(
        -0.5*design_region_size.y,
        +0.5*design_region_size.y,
        ny
    )
    xv, yv = npa.meshgrid(xcoord, ycoord, indexing='ij')
    weights = npa.where(
        npa.abs(yv) <= 0.5 * grating_duty_cycle * GRATING_PERIOD_UM,
        npa.where(
            xv <= xcoord[0] + grating_height_um,
            1,
            0
        ),
        0
    )

    return weights.flatten()
```

Also, it does not seem to be an issue but Autograd *does* support gradients of [`np.abs`](https://github.com/HIPS/autograd/blob/9a90bd6172d1882235c326c56c17a9540357d86b/autograd/numpy/numpy_vjps.py#L70-L71) which is not normally differentiable.

The fix is that we therefore just need to rewrite `grating_levelset` and replace `np.meshgrid`.

**Comment by stevengj** [comment]
Here is an easier approach:

1. write a function f(p) that generates the binary image from your geometric parameters p
2. call fast-marching or similar to generate a "smooth/signed-distance" level set from f(p), call this F(f(p))
3. write a custom vJp routine for F(f(p)) that just uses finite differences to obtain the Jacobian matrix.

This is feasible because your number of parameters p is very small, and F(f(p)) is very fast (no PDE solve), so finite differences are cheap.  Just make sure that the image is high enough resolution that finite differences are sufficiently accurate.

**Comment by stevengj** [comment]
(Your f(p) function above, i.e. `grating_levelset`, has a derivative zero almost everywhere, because an infinitesimal perturbation doesn't change the image.   To fix that you would need to do subpixel smoothing *within* that function.  However, with my suggested finite-difference approach, you can just use finite differences that change the image by at least one pixel, and the problem goes away.)

**Comment by oskooi** [comment]
> write a custom vJp routine for F(f(p)) that just uses finite differences to obtain the Jacobian matrix.

This seems to be working now after I added a custom VJP function for my levelset construction function (shown below). We can now demonstrate good agreement in the directional derivative computed using the adjoint gradient and finite differences:

```
directional-deriv:, [0.00161151] (finite difference), 0.0019102441087774935 (adjoint)
```

These results were obtained using a resolution of 200 pixels/μm and a runtime of nearly 1.5 hours using a single Xeon 4.2 GHz. Unfortunately, using finite differences to approximate the Jacobian necessarily requires large resolutions to obtain accurate results. This feature has already been noted in the [comments above](https://github.com/NanoComp/meep/issues/2235#issuecomment-1949268433):

```
Just make sure that the image is high enough resolution that finite differences are sufficiently accurate.
```

Details of the calculation involving composition of the objective function and computing the Jacobian matrix using finite differences are summarized in the slide below. The current calculation does *not* use subpixel smoothing (which will be added next by extending this approach to the signed-distance function in order to replace the conic filter in the `mapping` function).

![backpropagation_levelset](https://github.com/NanoComp/meep/assets/7152530/1aefc0ba-59ec-4e03-8a10-9563b7c9ddf3)

```py
def grating_levelset_vjp(
        ans,
        grating_height_um: float,
        grating_duty_cycle: float,
        design_region_size: mp.Vector3,
        nx: int,
        ny: int
) -> np.ndarray:
    """Returns the vector-Jacobian product."""

    xv, yv = design_region_to_meshgrid(design_region_size, nx, ny)

    # pixel dimensions
    delta_x = design_region_size.x / (nx - 1)
    delta_y = design_region_size.x / (ny - 1)

    # Gradient of the level set with respect to the grating height.
    # The gradient is obtained using a finite difference. The gradient is
    # therefore a zero matrix with non-zero entries only at the locations
    # of the height boundary. Since the height boundary is normal to the
    # x axis, these non-zero matrix elements have a value of 1 / Δx.
    weights = np.where(
        np.abs(yv) <= 0.5 * grating_duty_cycle * GRATING_PERIOD_UM,
        np.where(
            xv <= xv[0][0] + grating_height_um + 0.5 * delta_x,
            np.where(
                xv >= xv[0][0] + grating_height_um - 0.5 * delta_x,
                1 / delta_x,
                0
            ),
            0
        ),
        0
    )

    jacobian = weights.flatten()

    return lambda g: np.tensordot(g, jacobian, axes=1)
```

**Comment by oskooi** [comment]
Using the same approach involving a custom VJP described in my [previous comment](https://github.com/NanoComp/meep/issues/2235#issuecomment-1952888267) applied to the signed-distance function via the module [`scikit-fmm`](https://github.com/scikit-fmm/scikit-fmm) and computing the adjoint gradient of a level-set representation of the 1D grating using the *internal* subpixel smoothing feature of the `MaterialGrid` class (rather than the alternative approach proposed by @smartalecH of replacing the conic filter of the `mapping` function with the `smoothed_projection` filter) seems to produce the expected agreement with the brute-force result obtained using finite differences. 

Here are the results comparing the directional derivatives obtained using the two methods (finite difference vs. adjoint gradient) for the $\mathcal{S}$ and $\mathcal{P}$ polarization at a resolution of **200** pixels/μm.

**S polarization**
```
directional-deriv:, -0.00146690 (finite difference), -0.00128812 (adjoint), 0.121877 (error)
```

**P polarization**
```
directional-deriv:, 0.00021602 (finite difference), 0.00136521 (adjoint), 5.319892 (error)
```

There is good agreement for the $S$ polarization but that is the "easy" case for a 2D simulation because the electric field is always perpendicular to the material interfaces. The relative error for the $\mathcal{P}$-polarization case is more than an order of magnitude larger than the $\mathcal{S}$-polarization case. The accuracy of the $P$ polarization result can probably be improved by increasing the grid resolution at the expense of a significantly longer runtime. This is what I am currently investigating.

The script used to generate the results is available in this [gist](https://gist.github.com/oskooi/f9396e26e766b2fcf9fdc280b81bfdda). There are two key parts:
1. Use of subpixel smoothing via the `MaterialGrid` object and $\beta = \infty$.
2.  The level-set construction function which uses the signed-distance function via `scikit-fmm` for smoothing the grating boundaries and its custom VJP.

```py
    matgrid = mp.MaterialGrid(
        mp.Vector3(nx, ny),
        mp.air,
        glass,
        weights=anp.ones((nx, ny)),
        do_averaging=True,
        beta=anp.inf
    )
```

```py
def signed_distance(weights: anp.ndarray) -> anp.ndarray:
    """Maps the 2D weights using a signed-distance function."""

    # Create signed distance function.
    sd = skfmm.distance(weights - 0.5)

    # Linear interpolation of zero-levelset onto 0.5-levelset.
    xp = [anp.min(sd.flatten()), 0, anp.max(sd.flatten())]
    yp = [0, 0.5001, 1]

    return anp.interp(sd.flatten(), xp, yp)
  
  
@primitive
def levelset_and_smoothing(
        grating_height_um: float,
        grating_duty_cycle: float,
        design_region_size: mp.Vector3,
        nx: int,
        ny: int
) -> anp.ndarray:
    """Generates the grating as a levelset with signed-distance smoothing."""

    xv, yv = design_region_to_meshgrid(design_region_size, nx, ny)

    weights = anp.where(
        anp.abs(yv) <= 0.5 * grating_duty_cycle * GRATING_PERIOD_UM,
        anp.where(
            xv <= xv[0][0] + grating_height_um,
            1,
            0
        ),
        0
    )

    return signed_distance(weights)


def levelset_and_smoothing_vjp(
        ans: anp.ndarray,
        grating_height_um: float,
        grating_duty_cycle: float,
        design_region_size: mp.Vector3,
        nx: int,
        ny: int
) -> anp.ndarray:
    """Computes the vector-Jacobian product."""

    xv, yv = design_region_to_meshgrid(design_region_size, nx, ny)

    # pixel dimensions 
    delta_x = design_region_size.x / (nx - 1)

    weights = anp.where(
        anp.abs(yv) <= 0.5 * grating_duty_cycle * GRATING_PERIOD_UM,
        anp.where(
            xv <= xv[0][0] + grating_height_um + delta_x,
            1,
            0
        ),
        0
    )

    jacobian = (signed_distance(weights) - ans) / delta_x

    return lambda g: anp.tensordot(g, jacobian, axes=1)
```

This figure shows the smoothed grating obtained by applying the signed-distance function to its level-set representation.

![grating_weights](https://github.com/NanoComp/meep/assets/7152530/0b2f05a0-4a37-430b-a5bb-864844257bde)

Pending the results for the $\mathcal{P}$-polarization case at a resolution of **400** pixels/μm, we may be ready to use these results as part of a new unit test and tutorial.
