### ISSUE TITLE
How to set up two sources with phase difference e^ikx?

### ISSUE THREAD

**Issue by nolanloo** [NanoComp/meep#2255]
I am using meep to simulate a 2d band diagram(triangle lattice). Here is my result.
<img width="849" alt="Screen Shot 2022-10-03 at 19 26 40" src="https://user-images.githubusercontent.com/65316936/193971043-c32780a2-52ba-4bf9-8d3f-a73fcdfbef85.png">
These two red lines show the first two bands(Gamma-K-M-Gamma), and it seems the rest dots are from the folded bands.
According to  Chapter 4 ("Electromagnetic Wave Source Conditions") of [Advances in FDTD Computational Electrodynamics: Photonics and Nanotechnology], I could remove these folded bands by setting two point sources which are separated by unit vector and differing by an e^ikx phase.
I wonder how I can set up two sources with phase difference e^ikx.
Here is part of my code for these two sources(it seems wrong because I still have folded bands as above) 
```

fcen = 0.4  
df = 1.0  
sim = mp.Simulation(
                       cell_size=cell,
                       geometry=geometry,
                       resolution=20,
                       ensure_periodicity=True,
                       force_complex_fields=True,
                       )
k_interp = 9  
k_points = mp.interpolate(k_interp, [ 
                                                            mp.Vector3(0, 0, 0),##Γ                
                                                            mp.Vector3(1/3, math.sqrt(3)/3, 0), ##K                                        
                                                            mp.Vector3(1/2, 0.5/math.sqrt(3), 0), ##M
                                                            mp.Vector3(0, 0, 0),##Γ
                                                            ])
all_freqs = []
for pt in k_points:
               s1 = mp.Source(
                    src=mp.GaussianSource(fcen, fwidth=df, cutoff=10.0,),
                    component=mp.Hz,
                    center=mp.Vector3(-1/4,-math.sqrt(3)/4, 0),
                    amplitude=cmath.exp(2 * math.pi*1j * pt.dot(mp.Vector3(-1/4,-math.sqrt(3)/4, 0))),
                )
                
                s2 = mp.Source(
                    src=mp.GaussianSource(fcen, fwidth=df, cutoff=10.0,),
                    component=mp.Hz,
                    center=mp.Vector3(1/4,math.sqrt(3)/4, 0),
                    amplitude=cmath.exp(2 * math.pi*1j * pt.dot(mp.Vector3(1/4,math.sqrt(3)/4, 0))),
                );

                sim.restart_fields()
                sim.change_sources([s1,s2])
                hinv = sim.run_k_point(300,pt)
                all_freqs.append(hinv.modes)


```

**Comment by Dj1312** [comment]
If you want to add a phase difference between `s1` and `s2`, you can simply add a term $e^{i \phi}$ (where $\phi$ is you phase difference) on the `amplitude` parameter of one of your sources

**Comment by stevengj** [comment]
Right, you just set a complex `amplitude`.
