### ISSUE TITLE
adding support for `load_minus_flux` to `EigenmodeCoefficient` objective function of adjoint solver

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#2266]
In calculations involving the $S_{11}$ scattering parameter (i.e., the reflectance into a given port from a source located in the same port), it is often useful prior to the start of the run to first subtract out the incident fields using the [`load_minus_flux`](https://meep.readthedocs.io/en/latest/Python_User_Interface/#flux-spectra) feature, particularly if the reflectance is smaller than e.g. 1e-6. While the computation of $S_{11}$ does [not typically require require a normalization run](https://meep.readthedocs.io/en/latest/Python_Tutorials/GDSII_Import/#when-computing-the-reflection-coefficient-s112-is-it-necessary-to-perform-a-separate-normalization-run-to-obtain-the-incident-fields) because in most telecom applications reflectance values less than 40 dB are considered negligible, adding support for  `load_minus_flux` to the adjoint solver's objective function `EigenmodeCoefficient` (and also `FourierFields` and Poynting flux in #2191)  would be useful as e.g. a means to validate the adjoint gradient against the brute-force finite-difference result for arbitrary values and problems.

**Comment by smartalecH** [comment]
Are you seeing a discrepancy in gradients with the typical approach?

**Comment by oskooi** [comment]
I am trying to set up a test problem involving a 2d waveguide mode converter based on [Schubert et al., (2022)](https://pubs.acs.org/doi/10.1021/acsphotonics.2c00313) (in particular, Figures 6a and 7a). The objective function involves minimizing the reflectance $|S_{11}|^2$ across several frequencies (and also maximizing $|S_{21}|^2$ but the transmittance is not relevant here). The problem, though, is that at a (typically coarse) resolution suitable for fast throughput, there is no guarantee whether small values of the $S_{11}$ computed by the adjoint solver are accurate and not dominated by discretization error. The only way to ensure the accuracy of the $S_{11}$ values at *any* resolution is to subtract away the incident fields first in the mode monitor.

**Comment by smartalecH** [comment]
But if you're running at a coarse resolution, does it really matter if you are truly 60 dB down?

**Comment by oskooi** [comment]
The issue here is that at a given resolution, we do not know apriori what the discretization error of the $S_{11}$ calculation is unless we do a convergence analysis similar to the one in the [tutorial](https://meep.readthedocs.io/en/latest/Python_Tutorials/GDSII_Import/#when-computing-the-reflection-coefficient-s112-is-it-necessary-to-perform-a-separate-normalization-run-to-obtain-the-incident-fields). If the discretization error is 60 dB or smaller then it will likely not affect the optimization results. However, it can be larger, e.g., the discretization error is 50 dB at a resolution of 50 pixels/μm in the convergence analysis of the directional coupler. A large discretization error could also make the optimization fail to converge.
