### ISSUE TITLE
solve-cw example fails: error in the fields is NOT decreasing with increasing resolution

### ISSUE THREAD

**Issue by corecode** [NanoComp/meep#2359]
When running the solve-cw.py example, I get

`FAILED solve_cw test: error in the fields is NOT decreasing with increasing resolution`

and produces this chart:

![image](https://user-images.githubusercontent.com/177979/210005870-e29b4e0f-33c3-41be-93b9-6af3c6e32b1c.png)

**Comment by oskooi** [comment]
Thanks for pointing this out. Should be fixed by #2360.

**Comment by corecode** [comment]
Thanks!  the notebook has the same issues - sorry for not mentioning this before.
