### ISSUE TITLE
issue with simulation domain visualization after v1.21.0

### ISSUE THREAD

**Issue by Nikolaos-Matthaiakakis** [NanoComp/meep#2377]
I have been facing an issue with the simulation domain for all versions including 1.21 and newer. The following images both correspond to the same code, running on different meep versions.

v1.20
![simulation](https://user-images.githubusercontent.com/58590846/213746514-5e39ac45-d1fd-4f70-9fea-16e0e7536b19.png)

v1.25
![simulation](https://user-images.githubusercontent.com/58590846/213746436-1450e6d6-f127-4217-9fb8-cea7e4a877b7.png)

There are also some differences that appear in the logs file of the simulation. There are some extra listings of blocks in v1.25 (are the blocks information printed again when I use plot2d in the new versions of meep?). The following is for Using MPI version 4.0, 6 processes, and for split_chunks_evenly=True. The code is quite large and I cannot currently include it here. What could be the reason behind these differences between versions?

The problem also seems to sometimes affect the results of the simulations, although I need to further test this. Either way I am curious as to why the simulation domain is not properly plotted in newer versions for the same code. 

```
V1.20
-----------
Initializing structure...
Splitting into 6 chunks by voxels
time for choose_chunkdivision = 0.000154018 s
Working in 3D dimensions.
Computational cell is 0.07 x 0.07 x 0.4 with resolution 500
     block, center = (0,0,0.051)
          size (0.07,0.07,0.1)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (2.89,2.89,2.89)
     block, center = (0,0,0)
          size (0.044,0.04,0.002)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (5.5,5.5,5.5)
time for set_epsilon = 0.180225 s
drude susceptibility: frequency=1, gamma=0.00736304
-----------
FreqRange(min=0.022727272727272728, max=0.3333333333333333)
Epsilon = Vector3<5.5, 5.5, 5.5>
on time step 459 (time=0.459), 0.00871666 s/step
on time step 967 (time=0.967), 0.00788063 s/step
on time step 1473 (time=1.473), 0.00791198 s/step
on time step 1981 (time=1.981), 0.00787857 s/step
field decay(t = 2.001): 3.3344328726522684e-12 / 3.3344328726522684e-12 = 1.0

V1.25
-----------
Initializing structure...
Splitting into 6 chunks by voxels
time for choose_chunkdivision = 0.000149965 s
Working in 3D dimensions.
Computational cell is 0.07 x 0.07 x 0.4 with resolution 500
     block, center = (0,0,0.051)
          size (0.07,0.07,0.1)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (2.89,2.89,2.89)
     block, center = (0,0,0)
          size (0.044,0.04,0.002)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (5.5,5.5,5.5)
time for set_epsilon = 0.17914 s
drude susceptibility: frequency=1, gamma=0.00736304
-----------
FreqRange(min=0.022727272727272728, max=0.3333333333333333)
Epsilon = Vector3<5.5, 5.5, 5.5>
     block, center = (0,0,0.051)
          size (0.07,0.07,0.1)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (2.89,2.89,2.89)
     block, center = (0,0,0)
          size (0.044,0.04,0.002)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (5.5,5.5,5.5)
     block, center = (0,0,0.051)
          size (0.07,0.07,0.1)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (2.89,2.89,2.89)
     block, center = (0,0,0)
          size (0.044,0.04,0.002)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (5.5,5.5,5.5)
     block, center = (0,0,0.051)
          size (0.07,0.07,0.1)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (2.89,2.89,2.89)
     block, center = (0,0,0)
          size (0.044,0.04,0.002)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (5.5,5.5,5.5)
     block, center = (0,0,0.051)
          size (0.07,0.07,0.1)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (2.89,2.89,2.89)
     block, center = (0,0,0)
          size (0.044,0.04,0.002)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (5.5,5.5,5.5)
     block, center = (0,0,0.051)
          size (0.07,0.07,0.1)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (2.89,2.89,2.89)
     block, center = (0,0,0)
          size (0.044,0.04,0.002)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (5.5,5.5,5.5)
on time step 1430 (time=1.43), 0.00279722 s/step
field decay(t = 2.001): 3.3344328726522235e-12 / 3.3344328726522235e-12 = 1.0
on time step 3002 (time=3.002), 0.00254507 s/step
field decay(t = 4.002): 1.0166490499007866e-10 / 1.0166490499007866e-10 = 1.0
```

**Comment by smartalecH** [comment]
Well a lot has changed between those two versions...

The difference in contrast makes me wonder if you have metals? Earlier versions of plot2D didn't properly account for metals. 

We also changed how plot2D pulls the permittivity. Now you no longer initialize the full simulation. You just pull the 2D slices you request. You can specify a higher resolution too (as described in the docs). 

Can you describe what's "wrong" with the current version? What are you expecting to see?

**Comment by Nikolaos-Matthaiakakis** [comment]
The simulation region includes a dielectric substrate and patterned graphene (which is conductive) and they are both visible in the old version. So this could be a due to a change of contrast between the two versions? How could I get both structures to be visible in the new version?

Another issue is that while for linear simulations the old and new versions provide the same results

v1.20
![PyPxPhase_re](https://user-images.githubusercontent.com/58590846/213865076-ce2449d2-69bb-43f1-8217-65b1b1b87449.png)
v1.25
![PyPxPhase_re](https://user-images.githubusercontent.com/58590846/213865086-b1abcaec-63c7-4dda-a994-a30b8fd91b68.png)

for nonlinear simulations (Kerr - third harmonic generation) the results are different, again without changing anything in the code. Have there been any changes that could possibly affect this?

v1.20
![PyPxPhase_tr](https://user-images.githubusercontent.com/58590846/213865115-02e15ab1-8f6a-4dca-9b1e-ca0a9216b0b7.png)

v1.25
![PyPxPhase_re](https://user-images.githubusercontent.com/58590846/213865124-e23730cf-3778-4aad-8f5a-0bcbcf23fb09.png)

**Comment by stevengj** [comment]
Is there any chance you could do a `git bisect` to find out exactly which commit caused the nonlinear results to change?  This would require you to build Meep from source.

**Comment by Nikolaos-Matthaiakakis** [comment]
I could try although I am busy with other projects right now. What is certain is that the code works up to v1.20 and the changes appear at v1.21. I will let you know if I get the chance to check for specific commits.

**Comment by smartalecH** [comment]
Is this also fixed with #2413?

**Comment by Nikolaos-Matthaiakakis** [comment]
I will try to verify as soon as possible, but it might be within the next few weeks.

**Comment by Nikolaos-Matthaiakakis** [comment]
setting decimation=1 in the monitor resolves the issue.
