### ISSUE TITLE
Missing ifftshift in filter code?

### ISSUE THREAD

**Issue by smartalecH** [NanoComp/meep#2399]
I think we are missing an `ifftshift` in the adjoint filter code:

https://github.com/NanoComp/meep/blob/6abb8b3c6692fb17d08a6a5b36b320e1c54f9c55/python/adjoint/filters.py#L99-L106

per the [discussion](https://github.com/NanoComp/meep/issues/2012#issuecomment-1076978807) we had awhile back.

While writing a 1D variant of this, I noticed that the `_centered` function ends up grabbing the _ends_ of the filtered array (i.e. all the padding) because we never shifted the origin... but maybe numpy's 2D fft has a different convention?

(cc @mawc2019, @mochen4)

**Comment by mawc2019** [comment]
> I think we are missing an ifftshift in the adjoint filter code

I do not think fftshift or ifftshift is missing. Here the kernel is padded with zeros at the center, in contrast to the previous case (before PR #2016) where the kernel is padded with zeros at ends.

> While writing a 1D variant of this, I noticed that the _centered function ends up grabbing the ends of the filtered array (i.e. all the padding) because we never shifted the origin... but maybe numpy's 2D fft has a different convention?

Are you referring to the case before or after PR #2016? After PR #2016, the 1d variant was used, but fftshift or ifftshift was not used. Before PR #2016, the 1d variant was not used, but fftshift was used.

**Comment by smartalecH** [comment]
Ah yes you're right. I forgot we padded the center, not the edges. Thanks!
