### ISSUE TITLE
Add EVEN_X, ODD_X to eigenmode constraints for sources not along X direction

### ISSUE THREAD

**Issue by Andeloth** [NanoComp/meep#2403]
Tags: Enhancement

Currently meep only has the EVEN_Y, ODD_Y, EVEN_Z, ODD_Z symmetry parameters for eigenmode sources, but for sources that aren't along the X direction this leaves out half of the possible parity options. The EVEN_X, ODD_X should be added to the possible parities to be able to enforce symmetries along the X direction when applicable.

Alternatively, if the EVEN_Y, ODD_Y, EVEN_Z, ODD_Z parameters instead denote symmetries along the k_point direction of the source, the documentation should be updated to indicate that the Y/Z parameters don't correspond to the cartesian axis directions but to the orthogonal directions of the source k_point. Aka. indicate that the Y/Z parameters behave as if the source was rotated to face the X direction, then the symmetries were applied.

It was not clear upon reading the documentation which case is true. I'd appreciate a comment from one of the meep devs that know what exactly the Y/Z stand for in this case.

**Comment by smartalecH** [comment]
See #1107 and #1139. Feel free to resurrect that PR. Closing as duplicate.
