### ISSUE TITLE
Third Harmonic Generation Tutorial gives different results in current release?

### ISSUE THREAD

**Issue by yungcm** [NanoComp/meep#2408]
Can somebody please shed some light on this?

[This example](https://github.com/NanoComp/meep/blob/master/python/examples/3rd-harm-1d.ipynb) should produce this spectrum:
![3hg_meep1 20](https://user-images.githubusercontent.com/74578413/220820522-0e6c43eb-dc29-407f-bd99-09b7ecc5ab4a.png)

Recent releases of Meep available via Conda produces this instead:
![3hg_meep1 24](https://user-images.githubusercontent.com/74578413/220820539-dce15980-8398-450c-b32d-ae10f806355e.png)
with a spurious peak around 0.74.

I have gone back to earlier releases and version 1.20 is the newest which gives the intended result.

**Comment by smartalecH** [comment]
Hmm seems related to #2377. Could you `git bisect` (as described there) until you find the commit that breaks the feature?

**Comment by smartalecH** [comment]
(@oskooi seems like this feature needs a unit test)

**Comment by yungcm** [comment]
Thank you. I will give it a go.

**Comment by yungcm** [comment]
OK. Here is the result of git bisect:

74cb6dd9b0c1d92ffa270fe759d5f1afe69763d7 is the first bad commit
commit 74cb6dd9b0c1d92ffa270fe759d5f1afe69763d7
Author: Ardavan Oskooi <ardavano@google.com>
Date:   Thu Aug 26 07:55:43 2021 -0700

     enable automatic DFT decimation by default (#1732)
    
    * automatic DFT decimation
    
    * disable automatic decimation for certain tests
    
    * fixes
    
    * disable decimation for more tests
    
    * compute the maximum frequency of the DFT monitor rather than use the last array element
    
    * replace get_width with get_fwidth and use analytic formula for gaussian_src_time
    
    * add missing 2pi factor to gaussian_src_time::get_fwidth
    
    * add factor of 2 to gaussian_src_time::get_fwidth(double tol)
    
    * various fixes
    
    * disable automatic decimation for test_n2f_periodic.py
    
    * switch ceil to floor when setting decimation_factor

 doc/docs/Python_User_Interface.md         | 83 +++++++++++++++-------------
 python/adjoint/objective.py               |  6 +-
 python/adjoint/optimization_problem.py    |  2 +-
 python/adjoint/utils.py                   |  1 +
 python/geom.py                            |  2 +-
 python/simulation.py                      | 91 +++++++++++++++++--------------
 python/tests/test_3rd_harm_1d.py          |  6 +-
 python/tests/test_adjoint_jax.py          |  3 +-
 python/tests/test_bend_flux.py            |  5 +-
 python/tests/test_cavity_farfield.py      |  3 +-
 python/tests/test_chunks.py               |  4 +-
 python/tests/test_dft_energy.py           |  6 +-
 python/tests/test_dft_fields.py           |  3 +-
 python/tests/test_divide_mpi_processes.py |  5 +-
 python/tests/test_force.py                |  2 +-
 python/tests/test_geom.py                 |  4 +-
 python/tests/test_holey_wvg_cavity.py     |  3 +-
 python/tests/test_mode_decomposition.py   |  3 +-
 python/tests/test_refl_angular.py         |  4 +-
 python/tests/test_visualization.py        |  8 +--
 src/dft.cpp                               | 19 +++++++
 src/meep.hpp                              | 52 ++++++++++--------
 src/sources.cpp                           |  7 +++
 tests/harmonics.cpp                       |  9 ++-
 24 files changed, 193 insertions(+), 138 deletions(-)

**Comment by oskooi** [comment]
Thanks for looking into this. The fix is straightforward: turn off [DFT decimation](https://meep.readthedocs.io/en/latest/Python_User_Interface/#flux-spectra) by passing `decimation_factor=1` as an additional argument to `sim.add_flux(...)`. This change was already made to the unit test based on this example:

https://github.com/NanoComp/meep/blob/ccb3c372dc34ca75ce01f99c2b50e0e89ad0a203/python/tests/test_3rd_harm_1d.py#L48-L49

We just forgot to update the tutorials. I will update those as well shortly.

**Comment by yungcm** [comment]
Excellent. I can confirm it.

**Comment by stevengj** [comment]
Re-opening until this is fixed in the source/docs.
