### ISSUE TITLE
Radiation pattern of a dipole emitter does not converge with resolution in cylindrical coordinates

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#2489]
As part of a convergence analysis of the radiation pattern of a dipole emitter in cylindrical coordinates (based on the calculation procedure described in #2472), it seems the results do not converge with resolution. Not sure whether this is an indication of a bug somewhere or the way the calculation has been set up.

The test structure involves a point source at $r = 0$ in a finite-size "disc" (a modification of the structure in the [LED tutorial](https://meep.readthedocs.io/en/latest/Python_Tutorials/Local_Density_of_States/#extraction-efficiency-of-a-light-emitting-diode-led) which is infinitely extended). There are two different configurations of the closed box of near-field monitors (see schematics below). By Poynting's theorem, the two monitor configurations should produce *identical* results in the limit of infinite resolution. 

While the extraction efficiency over *all* angles computed using the Poynting flux is in fact identical (= 1.0), there are small but noticeable differences in the radiation pattern computed using a near-to-far field transformation. These discrepancies do not go away with increasing resolution.  The script used to generate the results is [here](https://gist.github.com/oskooi/07bf0800ef2c8146c7602c10b710f476).

Here is a side-by-side comparison of the extraction efficiency (really the fractional flux $P_\theta$ in the far field) within four angular cones at a resolution of 200. The final column is the absolute difference in the results (i.e., a measure of the error).

| **half angle of collection cone** | **Config. 1** ext. eff. | **Config. 2** ext. eff. | \|ee<sub>1</sub>-ee<sub>2</sub>\| |
|:---------------------------------:|:-----------------------:|:-----------------------:|:---------------------------------:|
|                10°                |          0.4539         |          0.4421         |               0.0118              |
|                20°                |          0.7451         |          0.7480         |               0.0029              |
|                30°                |          0.8683         |          0.8642         |               0.0041              |
|                40°                |          0.9143         |          0.9154         |               0.0011              |

Same results at a resolution of 400. The difference in the results (final column) is not decreasing as would be expected.

| **half angle of collection cone** | **Config. 1** ext. eff. | **Config. 2** ext. eff. | \|ee<sub>1</sub>-ee<sub>2</sub>\| |
|:---------------------------------:|:-----------------------:|:-----------------------:|:---------------------------------:|
|                10°                |          0.4524         |          0.4399         |               0.0125              |
|                20°                |          0.7420         |          0.7446         |               0.0026              |
|                30°                |          0.8644         |          0.8601         |               0.0043              |
|                40°                |          0.9110         |          0.9118         |               0.0008              |

**Configuration 1**

![led_disc_cyl_plot2D_res200_1](https://user-images.githubusercontent.com/7152530/234470458-f46a31d1-436f-4c1e-9182-452a69f2ba2d.png)

*resolution = 200*

![led_disc_cyl_radpattern_h0 5_res200_polar_1](https://user-images.githubusercontent.com/7152530/234470483-b3888066-abc2-4cd3-992e-a84d192b2a0e.png)

*resolution = 400*

![led_disc_cyl_radpattern_h0 5_res400_polar_1](https://user-images.githubusercontent.com/7152530/234473713-dbf771f8-6730-4e20-aa95-6116df94ca78.png)

**Configuration 2**

![led_disc_cyl_plot2D_res200_3](https://user-images.githubusercontent.com/7152530/234470574-93c28d98-879e-4d71-9e94-f651b3347411.png)

*resolution = 200*

![led_disc_cyl_radpattern_h0 5_res200_polar_3](https://user-images.githubusercontent.com/7152530/234470591-f23c50d5-bbc4-4ca3-98ce-e43ea8a566f2.png)

*resolution = 400*

![led_disc_cyl_radpattern_h0 5_res400_polar_3](https://user-images.githubusercontent.com/7152530/234474862-be533fae-f1c3-4f4e-8853-c7f9506897d6.png)

**Comment by oskooi** [comment]
There is an even larger disparity in the radiation pattern for Configurations 1 and 2 for a dipole source at $r = 0.5$ μm. These results are for a resolution of 200 pixels/μm. For λ = 1 μm and a disc radius of 0.625 μm, this is equivalent to 200 pixels and 125 pixels, respectively, which should be sufficient for convergence.

These results seem to indicate that there is likely a bug somewhere, possibly in the near-to-far field transformation in cylindrical coordinates?

**Configuration 1**

![led_disc_cyl_plot2D_rpos0 5_1a](https://user-images.githubusercontent.com/7152530/234762227-b05a39b0-f0a8-49fc-9415-879a9d489118.png)

![image](https://user-images.githubusercontent.com/7152530/234762313-30647365-e609-4961-9cb0-ab5007199991.png)

**Configuration 2**

![led_disc_cyl_plot2D_rpos0 5_3](https://user-images.githubusercontent.com/7152530/234762368-07dd83d1-e472-4bf0-86c5-f3ea1beada38.png)

![image](https://user-images.githubusercontent.com/7152530/234762404-4aec6fad-7d72-4649-be2b-38c22a9f57b1.png)

**Comment by smartalecH** [comment]
Does the total LEE itself converge?

If so, then you can narrow the bug down to the near2far.

**Comment by oskooi** [comment]
> Does the total LEE itself converge?

The total EE is converged as I mentioned in my first comment. 

The bug is likely in the near to far transformation function [`greencyl`](https://github.com/NanoComp/meep/blob/master/src/near2far.cpp#L279).

**Comment by smartalecH** [comment]
From your gist:

```python3

for i in range(npts):
        ff = sim.get_farfield(n2f_mon,
                              mp.Vector3(r*math.cos(angles[i]),
                                         0,
                                         r*math.sin(angles[i])))
        E[i,:] = [np.conj(ff[j]) for j in range(3)]
        H[i,:] = [ff[j+3] for j in range(3)]
        
    Pr = np.real(E[:,1]*H[:,2]-E[:,2]*H[:,1])
    Pz = np.real(E[:,0]*H[:,1]-E[:,1]*H[:,0])
    Prz = np.sqrt(np.square(Pr)+np.square(Pz))

```

Note that in the far field, the solutions are plane waves, and you should simply be able to calculate the Poynting flux using $|E|^2$.

Is 1000 wavelengths far enough away (should be... but still)?

Also, where is the integral that computes the fractional LEE in a cone? I didn't see that in the gist.

**Comment by smartalecH** [comment]
So I would expect a difference between configuration 1 and configuration 2 because of that vertical line monitor that changes in $r$. Recall that the integration weights have a first order error with $r$. That error increases the closer you get to $r=0$. 

But that error should go away with resolution.

**Comment by oskooi** [comment]
It looks like the radiation pattern obtained using two different configurations of the near-field monitors converges to the same result only when the length $L$ of the cell in the $r$ direction approaches $\infty$. This means that the **DFT monitor in the $r$ direction becomes further and further away from $r = 0$.** 

As a demonstration, here are the radiation patterns generated from a dipole at $r = 0.2$ ($M + 1 = 7$ simulations) inside a "disc" for $L$ of 5, 10, 20, and 40. Also shown are the schematic of the cell for each configuration and two rows of data, one per DFT monitor configuration, listing the total flux and four numbers (in parentheses) for the fractional flux in the far field within an angular cone of 10°, 20°, 30°, and 40° half angles. 

*Note 1:* The size of the disc is $0.2L$ and thus increases with $L$. This is why the radiation pattern changes for each $L$. The position of the dipole source, however, is fixed at $r = 0.2$ for all cases.)

*Note 2:* I verified that the results are converged with the PML thickness in $r$ and $z$.

**1. $L = 5$**

```
exteff-1:, 0.999059, (0.05, 0.22, 0.41, 0.58)
exteff-2:, 0.998968, (0.04, 0.22, 0.41, 0.59)
```

![led_disc_cyl_L5 0_dpmlr3 0_dpmlz1 0_plot2D](https://github.com/NanoComp/meep/assets/7152530/e55a99b3-4d20-4b76-9a61-0dd988aa9684)

![led_disc_cyl_radpattern_res100 0_L5 0_dpmlr3 0_dpmlz1 0](https://github.com/NanoComp/meep/assets/7152530/8f3aa977-754e-4138-beb4-feac27e9e389)

**2. $L = 10$**

```
exteff-1:, 0.2, 0.999256, (0.21, 0.46, 0.67, 0.75)
exteff-2:, 0.2, 0.999203, (0.21, 0.46, 0.68, 0.75)
```

![led_disc_cyl_L10 0_dpmlr3 0_dpmlz1 0_plot2D](https://github.com/NanoComp/meep/assets/7152530/a98086b1-aae1-48b7-bbbf-ed9ae53e72b2)

![led_disc_cyl_radpattern_res100 0_L10 0_dpmlr3 0_dpmlz1 0](https://github.com/NanoComp/meep/assets/7152530/21bc3243-cc6b-4bb2-8300-850b6eaeefe8)

**3. $L = 20$**

```
exteff-1:, 0.2, 0.999384, (0.31, 0.56, 0.70, 0.79)
exteff-2:, 0.2, 0.999346, (0.31, 0.56, 0.70, 0.79)
```

![led_disc_cyl_L20 0_dpmlr3 0_dpmlz1 0_plot2D](https://github.com/NanoComp/meep/assets/7152530/589ee5f0-b84e-4ab4-acda-d758cc79a8c5)

![led_disc_cyl_radpattern_res100 0_L20 0_dpmlr3 0_dpmlz1 0](https://github.com/NanoComp/meep/assets/7152530/6ee584e9-dc58-4ea5-8f33-9bd218faef17)

**4. $L = 40$**

```
exteff-1:, 0.2, 0.999691, (0.39, 0.59, 0.71, 0.80)
exteff-2:, 0.2, 0.999606, (0.39, 0.59, 0.71, 0.80)
```

![led_disc_cyl_L40 0_dpmlr3 0_dpmlz1 0_plot2D](https://github.com/NanoComp/meep/assets/7152530/cc51e216-00d6-4f93-b2fa-48117fc5f0d9)

![led_disc_cyl_radpattern_res100 0_L40 0_dpmlr3 0_dpmlz1 0](https://github.com/NanoComp/meep/assets/7152530/d9c52cd1-53e8-468b-bcd8-09d54ce9be2a)

**Comment by smartalecH** [comment]
> This means that the DFT monitor in the $r$ direction becomes further and further away from $r=0$

Hmm. I'm wondering if this is because the monitors are further away, or if it's because the fields are converging better with the larger cells?

This test is turning too many knobs... it's changing the cell size, the size of the disc, *and* the locations of the monitors. Can we simplify the test matrix here to *exactly* narrow down what's going on here?

For example, keep the geometry and inner monitor position at the same position, but increase the cell size (and obviously the outer monitor should move with it). Then, you can *safely* test two things: (1) Does the inner-monitor response change as the cell size increase? (2)  does the difference between inner and outer monitor response decrease with cell size?

**Comment by stevengj** [comment]
There could be a bug in the near2far calculation for the radial-direction interface?

In particular, the cylindrical near2far is implemented by integrating the Cartesian Green's function over φ.  For the ±z surfaces, only the *position* of the near-field source point changes during this integral.  However, for the radial surface, the normal vector `r̂` changes direction with φ as well, and maybe we aren't taking this into account.

**Comment by oskooi** [comment]
> Maybe there is a bug in [these lines](https://github.com/NanoComp/meep/blob/28ee9f6bb35ad58c46ff4286339a5116356f085d/src/near2far.cpp#L320-L326)? But that would affect the ±z surface as well? It would be good to check that these lines are actually being executed — i.e. that we are passing `c0` as cylindrical components and not cartesian?

Checked. These lines are being executed as expected.

> It could also be as simple as the +r surface missing the r factor? i.e. the weight `f0` in `greencyl` (which comes from the DFT weight) should be multiplied by r.

Tried scaling the weight `f0` by $r$ as suggested but it does not fix the problem.

**Comment by stevengj** [comment]
Might be worth doing a simple test of cylindrical near2far, just like we did for Cartesian: put a source somewhere (at the center?), compute the field at some point by explicit FDTD, and then compute the field at the same point using near2far.  They should match (in the limit of infinite resolution).   This can be a relatively small calculation, for a single m.

**Comment by oskooi** [comment]
> Might be worth doing a simple test of cylindrical near2far, just like we did for Cartesian: put a source somewhere (at the center?), compute the field at some point by explicit FDTD, and then compute the field at the same point using near2far. They should match (in the limit of infinite resolution). This can be a relatively small calculation, for a single m.

Setting up such a test involving a point source within a "disc" at a single `m` demonstrates that there indeed is a discrepancy in the radiated fields in air above the disc computed using the two different methods of: (1) a DFT monitor and (2) a near-to-far field transformation. The discrepancy does *not* go away with increasing resolution which would be expected if numerical dispersion was the primary cause. I tested this with different values of `m` and monitor configurations and the results are similar.

The script used to generate to these results is [here](https://gist.github.com/oskooi/8946d61da945f5ab68ce26cf028c6cb0).

![disc_n2f_m2_dair1 0_plot2D](https://github.com/NanoComp/meep/assets/7152530/d9907cec-5e93-4617-bb77-25853704cc9a)

![er_dft_vs_n2f_m2_dair1 0_res100](https://github.com/NanoComp/meep/assets/7152530/2a66f167-0bc7-48ca-856b-c3ac4a81bf46)

**Comment by oskooi** [comment]
After further investigation, it looks like the discrepancy between the DFT fields and the near-to-far field transformation only occurs for `m = 0`. For `m ≠ 0`, there is excellent agreement. This can be demonstrated for a point source in **vacuum** (i.e., no disc) above the perfect-metallic reflector ground plane. The previous setup placed the point source within a dielectric disc which was in fact a weak cavity (the radiated flux in air was nearly 100% of the input power of the dipole). We demonstrated in a [separate tutorial](https://meep.readthedocs.io/en/latest/Python_Tutorials/Near_to_Far_Field_Spectra/#truncation-errors-from-a-non-closed-near-field-surface) that when computing the radiated fields of a cavity using the near-to-far field transformation, the enclosing box must be *as close to the cavity as possible* in order to fully capture its fields. This is why two different near-field monitor configurations were producing different far-field radiation patterns. The monitor configuration furthest from the disc cavity was less accurate.

With the modified setup, here are the results for the radiated fields for `m` of `0`, `1` and `2`. The `m = 1, 2` case show nearly exact agreement between the DFT fields and near-to-far field transformation. For `m = 0`, there is a large discrepancy near `r = 0`. These results were generated using this [script](https://gist.github.com/oskooi/971f2bac2538dac19342b7e3d3e26a97).

![cyl_n2f_dair1 0_plot2D](https://github.com/NanoComp/meep/assets/7152530/7111ff1c-8dc2-474d-80b4-887d9eded825)

![er_dft_vs_n2f_m0_dair1 0_res100](https://github.com/NanoComp/meep/assets/7152530/32b05eba-c356-4d48-b873-6b77aa85de3b)

![er_dft_vs_n2f_m1_dair1 0_res100](https://github.com/NanoComp/meep/assets/7152530/8d749486-92b3-47ad-ac75-953621857e11)

![er_dft_vs_n2f_m2_dair1 0_res100](https://github.com/NanoComp/meep/assets/7152530/0cff256b-6248-4017-894b-e8bbf27ef966)

**Comment by stevengj** [comment]
The Er fields for m=0 don't make sense.  (They should look similar to the m=2 case.)   Can you plot the raw time-domain Er field (e.g. in a movie) for the m=0 case to see what they look like, and whether they are going to zero as r goes to zero?

**Comment by oskooi** [comment]
> Can you plot the raw time-domain Er field (e.g. in a movie) for the m=0 case to see what they look like, and whether they are going to zero as r goes to zero?

If we take a snapshot of $|E_r|$ on a logscale over the entire cell at some time $t > 0$ and from this data plot a cross section along $r$ at a $z$ corresponding to the point source, we find that the $E_r$ fields do *not* go to zero at $r = 0$ as would be expected for this field component. This is a clear indication of a bug. 

The presence of a bug is perhaps not surprising since currently there is no unit test for the $m = 0$ case.

(Note: the time-domain results are consistent with the DFT fields above which also show a non-zero $E_r$ at $r = 0$.) 

![er_t87 36](https://github.com/NanoComp/meep/assets/7152530/3347accf-40a0-429f-bd87-73d0f892a917)

![er_t87 36_z0 85](https://github.com/NanoComp/meep/assets/7152530/3745c13b-7f59-4b4b-8c9c-3bdfd5188997)

The peak in the second plot is the position of the point source. Note that the fields are decaying to zero in the PML region.

Script used to generate these results is [here](https://gist.github.com/oskooi/1c1ececada771f9103dc422d50a918ca).

**Comment by stevengj** [comment]
Can you try a really old version of Meep and see if it ever worked?

**Comment by oskooi** [comment]
Looks like the bug is due to the change to `update_eh.cpp` in #2383 which affects $E_z$ at $r = 0$. Reverting this change produces the expected result.

![src_er_mon_er_dft_vs_n2f_m0_dair1 0_res100_PR2383](https://github.com/NanoComp/meep/assets/7152530/3d59fe2c-4b34-4d1b-8b39-85d429667a5a)


![er_t87 36](https://github.com/NanoComp/meep/assets/7152530/3d18d8ba-e22f-4e08-9d33-c058a56eea0f)

![er_t87 36_z0 85](https://github.com/NanoComp/meep/assets/7152530/5e84b3d3-0c01-4926-9cbf-72cf17b0cf87)

**Comment by stevengj** [comment]
It seems like we really want an `r=0` version of `step_EDHB`, which is specialized to assume that there are no off-diagonal terms (since that would break axisymmetry at r=0, regardless of `m`).  Something like this that you call *after* `step_update_EDHB`, where you pass in `little_corner` and `big_corner for `is` and `ie`, and not `little_corner0`:
```cxx
void step_update_EDHB0(RPR f, component fc, const grid_volume &gv, const ivec is, const ivec ie,
                      const RPR g, const RPR u,  ptrdiff_t s, const RPR chi2,
                      const RPR chi3, RPR fw, direction dsigw, const RPR sigw, const RPR kapw) {
  (void)fc; // currently unused
  if (!f) return;

  // 1.  check that is is cylindrical and starts at r=0, otherwise exit
  // 2. change ie.set_direction(R) = is.set_direction(R)   ... this way it will only loop over r=0

  if (dsigw != NO_DIRECTION) { //////// PML case (with fw) /////////////
    KSTRIDE_DEF(dsigw, kw, is, gv);
    { // diagonal u
      if (chi3) {
        {
          PLOOP_OVER_IVECS(gv, is, ie, i) {
            realnum gs = g[i];
            realnum us = u[i];
            DEF_kw;
            realnum fwprev = fw[i], kapwkw = kapw[kw], sigwkw = sigw[kw];
            fw[i] = (gs * us) * calc_nonlinear_u(gs * gs, gs, us, chi2[i], chi3[i]);
            f[i] += (kapwkw + sigwkw) * fw[i] - (kapwkw - sigwkw) * fwprev;
          }
        }
      }
      else if (u) {
        PLOOP_OVER_IVECS(gv, is, ie, i) {
          realnum gs = g[i];
          realnum us = u[i];
          DEF_kw;
          realnum fwprev = fw[i], kapwkw = kapw[kw], sigwkw = sigw[kw];
          fw[i] = (gs * us);
          f[i] += (kapwkw + sigwkw) * fw[i] - (kapwkw - sigwkw) * fwprev;
        }
      }
      else {
        PLOOP_OVER_IVECS(gv, is, ie, i) {
          DEF_kw;
          realnum fwprev = fw[i], kapwkw = kapw[kw], sigwkw = sigw[kw];
          fw[i] = g[i];
          f[i] += (kapwkw + sigwkw) * fw[i] - (kapwkw - sigwkw) * fwprev;
        }
      }
    }
  }
  else {            /////////////// no PML (no fw) ///////////////////
    { // diagonal u
      if (chi3) {
        {
          PLOOP_OVER_IVECS(gv, is, ie, i) {
            realnum gs = g[i];
            realnum us = u[i];
            f[i] = (gs * us) * calc_nonlinear_u(gs * gs, gs, us, chi2[i], chi3[i]);
          }
        }
      }
      else if (u) {
        PLOOP_OVER_IVECS(gv, is, ie, i) {
          realnum gs = g[i];
          realnum us = u[i];
          f[i] = (gs * us);
        }
      }
      else
        PLOOP_OVER_IVECS(gv, is, ie, i) { f[i] = g[i]; }
    }
  }
}
```
