### ISSUE TITLE
hdf5 version compatability with meep 1.26

### ISSUE THREAD

**Issue by ctison-zz** [NanoComp/meep#2491]
Hello,
I am on Arch Linux and recently tried to update meep to v1.26 but was getting a python 3.10.10 import error for libhdf5 files. I'm not sure the best way to report this so below are a couple instances of errors I've found between meep v1.26/v1.25 and some recent versions of hdf5.

# Works:
 meep-1.25.0-1
 hdf5-1.12.2-1

# Doesn't work:
## meep-1.26.0-1 and hdf5-1.12.2-1
The error:
```
>>> import meep
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/meep/__init__.py", line 10, in <module>
    from . import _meep
ImportError: libhdf5.so.310: cannot open shared object file: No such file or directory
```
## meep-1.26.0-1 and hdf5-1.14.0-2
```
>>> import meep
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/meep/__init__.py", line 10, in <module>
    from . import _meep
ImportError: libhdf5.so.200: cannot open shared object file: No such file or directory
```
## meep-1.25.0-1 and hdf5-1.14.0-2
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/meep/__init__.py", line 13, in <module>
    from . import _meep
ImportError: libhdf5.so.200: cannot open shared object file: No such file or directory
```

If there is anything else I can add please let me know. I noticed there are some compiler flags that can be throw in to get backwards compatibility but it is honestly outside my scope of knowledge
https://portal.hdfgroup.org/display/support/HDF5+1.14.0

**Comment by stevengj** [comment]
Did you build Meep from source?

`libhdf5.so.200: cannot open shared object file: No such file or directory` looks like you didn't set up your [shared library paths correctly](https://meep.readthedocs.io/en/latest/Build_From_Source/#paths-for-running-shared-libraries).

**Comment by ctison-zz** [comment]
You're correct, it is compiled from source as guided by a PKGBUILD file. 

When I use meep V1.26.0 compiled this way, the installed binary for meep expects there to be 2 libraries from libhdf5.so. One that is `libhdf5.so.200` and another that is `libhdf5.so.310`

I have no idea how computer specific this is but for me, hdf5-openmpi V1.14 installs `libhdf5.so.310` while V1.12 installs `libhdf5.so.200` so I guess I would need both libraries installed?

Example with meep 1.26
```
[usr]$ meep
meep: error while loading shared libraries: libhdf5.so.200: cannot open shared object file: No such file or directory
[usr]$ ldd $(which meep)
	libhdf5.so.310 => /usr/lib/libhdf5.so.310 (0x00007f325a600000)
	libhdf5.so.200 => not found
```
With many other libraries that I am leaving out for brevity.

Meanwhile, if I install meep V1.25, it still expects 2 libraries from libhdf5.so but luckily they are both `libhdf5.so.200` so I can satisfy the requirement. 
```
[usr]$ ldd $(which meep)
	libhdf5.so.200 => not found
	libhdf5.so.200 => not found
```

It is bizarre to me that there are two instances of libhdf5 needed but trust your judgement because I cannot seem to figure out what changes the expected libraries by the meep binary. Since I can't figure out what flag I am or am-not setting, I'll just stick to the combination of libraries that does work. Thanks for looking at this
