### ISSUE TITLE
test_ldos.py/test_ldos_ext_eff Wrong result?

### ISSUE THREAD

**Issue by NiKeYiGuN** [NanoComp/meep#2525]
Initializing structure...
Warning: grid volume is not an integer number of pixels; cell size will be rounded to nearest pixel.
N
time for choose_chunkdivision = 0.000148058 s
Working in Cylindrical dimensions.
Computational cell is 6.52 x 0 x 1.72 with resolution 25
     block, center = (0,0,-0.75)
          size (1e+20,1e+20,0.208333)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (5.76,5.76,5.76)
time for set_epsilon = 0.011044 s

Meep: using complex fields.
field decay(t = 20.02): 1.7830353438847258e-05 / 1.7830353438847258e-05 = 1.0
field decay(t = 40.04): 0.04577904613919186 / 0.04577904613919186 = 1.0
field decay(t = 60.06): 0.11478411196199398 / 0.11478411196199398 = 1.0
field decay(t = 80.08): 0.03846241083526685 / 0.11478411196199398 = 0.33508479682277015
on time step 4651 (time=93.02), 0.00086006 s/step
field decay(t = 100.10000000000001): 1.06906485284892e-05 / 0.11478411196199398 = 9.313700603467635e-05
field decay(t = 120.12): 3.3756330671288554e-08 / 0.11478411196199398 = 2.940853929546066e-07
field decay(t = 140.14000000000001): 1.9632471176738175e-10 / 0.11478411196199398 = 1.7103822855935548e-09
ldos0:, 1.0, 0.3975263868240353
run 0 finished at t = 140.14000000000001 (7007 timesteps)
extraction efficiency (cyl):, 0.2083, 0.5000, 0.330209

Initializing structure...
Warning: grid volume is not an integer number of pixels; cell size will be rounded to nearest pixel.
Padding x to even number of grid points.
Padding y to even number of grid points.
Halving computational cell along direction x
Halving computational cell along direction y
time for choose_chunkdivision = 0.000220776 s
Working in 3D dimensions.
Computational cell is 7 x 7 x 1.72 with resolution 25
     block, center = (0,0,-0.75)
          size (1e+20,1e+20,0.208333)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (5.76,5.76,5.76)
time for set_epsilon = 0.96771 s

on time step 163 (time=3.26), 0.0245934 s/step
on time step 458 (time=9.16), 0.0135734 s/step
on time step 753 (time=15.06), 0.0135629 s/step
field decay(t = 20.02): 0.03681737437488015 / 0.03681737437488015 = 1.0
on time step 1050 (time=21), 0.0135128 s/step
on time step 1342 (time=26.84), 0.0137081 s/step
on time step 1636 (time=32.72), 0.0136077 s/step
on time step 1932 (time=38.64), 0.0135437 s/step
field decay(t = 40.04): 114.36734321611935 / 114.36734321611935 = 1.0
on time step 2228 (time=44.56), 0.013539 s/step
on time step 2515 (time=50.3), 0.0139691 s/step
on time step 2796 (time=55.92), 0.0142845 s/step
field decay(t = 60.06): 317.3820663526947 / 317.3820663526947 = 1.0
on time step 3077 (time=61.54), 0.0142386 s/step
on time step 3370 (time=67.4), 0.0136578 s/step
on time step 3654 (time=73.08), 0.0141005 s/step
on time step 3940 (time=78.8), 0.0140249 s/step
field decay(t = 80.08): 107.70977826532278 / 317.3820663526947 = 0.33936945304788885
on time step 4224 (time=84.48), 0.0141081 s/step
on time step 4515 (time=90.3), 0.0137632 s/step
on time step 4804 (time=96.08), 0.0138477 s/step
field decay(t = 100.10000000000001): 0.03084315201553605 / 317.3820663526947 = 9.71798828143655e-05
on time step 5093 (time=101.86), 0.0138754 s/step
on time step 5380 (time=107.6), 0.0139511 s/step
on time step 5668 (time=113.36), 0.0138935 s/step
on time step 5950 (time=119), 0.014228 s/step
Warning: grid volume is not an integer number of pixels; cell size will be rounded to nearest pixel.
field decay(t = 120.12): 3.7060394015848805e-09 / 317.3820663526947 = 1.1676902366205212e-11
ldos0:, 1.0, 3.0341729410263265
run 0 finished at t = 120.12 (6006 timesteps)
extraction efficiency (3D):, 0.2083, 0.5000, 0.327121

Initializing structure...
time for choose_chunkdivision = 7.89165e-05 s
Working in Cylindrical dimensions.
Computational cell is 6.52 x 0 x 1.72 with resolution 25
     block, center = (0,0,-0.75)
          size (1e+20,1e+20,0.208333)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (5.76,5.76,5.76)
time for set_epsilon = 0.0120192 s

Meep: using complex fields.
field decay(t = 20.02): 1.7830353438847258e-05 / 1.7830353438847258e-05 = 1.0
field decay(t = 40.04): 0.04577904613919186 / 0.04577904613919186 = 1.0
field decay(t = 60.06): 0.11478411196199398 / 0.11478411196199398 = 1.0
field decay(t = 80.08): 0.03846241083526685 / 0.11478411196199398 = 0.33508479682277015
on time step 4696 (time=93.92), 0.00085179 s/step
field decay(t = 100.10000000000001): 1.06906485284892e-05 / 0.11478411196199398 = 9.313700603467635e-05
field decay(t = 120.12): 3.3756330671288554e-08 / 0.11478411196199398 = 2.940853929546066e-07
field decay(t = 140.14000000000001): 1.9632471176738175e-10 / 0.11478411196199398 = 1.7103822855935548e-09
ldos0:, 1.0, 0.3975263868240353
run 0 finished at t = 140.14000000000001 (7007 timesteps)
extraction efficiency (cyl):, 0.2083, 0.5000, 0.336305

0.33630477536814285 != 0.3302091863327887

Expected :0.3302091863327887
Actual   :0.33630477536814285

**Comment by NiKeYiGuN** [comment]
I am confused about this results.Please provide some clues. thanks!

**Comment by smartalecH** [comment]
We can't help without more information... the above isn't helpful. What system are you on? How did you install meep? What are you trying to do? What do you expect to happen?

**Comment by NiKeYiGuN** [comment]
ubuntu18.04,build from source,l want to learn meep. expect the test pass.
