### ISSUE TITLE
Reduce size of data files used in gold master tests for `unfilter_design`

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#2542]
The gold master test for the function `unfilter_design` of the adjoint-solver module added as part of #2462 involved adding two data files ([`mpa_unfilter_design.npy`](https://github.com/NanoComp/meep/blob/master/python/tests/data/mpa_unfilter_design.npy) and [`mpa_unfilter_design_target.npy`](https://github.com/NanoComp/meep/blob/master/python/tests/data/mpa_unfilter_design_target.npy)) to the repository which are *each* 1.3MB in size. The size of these files can likely be reduced considerably  without affecting the tests. (Unfortunately, I did not realize how large these files were during the review.)

cc @mochen4

**Comment by mochen4** [comment]
Thanks! I reduced the size of those files in PR #2543
