### ISSUE TITLE
Plot labels for geometric objects

### ISSUE THREAD

**Issue by Yaraslaut** [NanoComp/meep#2614]
At the moment plot can add additional labels to the figure, it will point out to sources and monitors
It would be great if user can provide label for geometry entity so plot will shows this labels of the objects as well.

**Comment by stevengj** [comment]
I guess an interface for this would involve:

1. add an optional string `label` field to `GeometricObject`
2. add a `labelgeometry=True` flag to `sim.plot2D`, which would simply plot the given object labels (if any) at the (2d-projected) centers of the corresponding objects.  (Or in 3d, maybe only plot them if they intersect the 2d slice.)

**Comment by Yaraslaut** [comment]
> 

I can try to make a PR for this

**Comment by oskooi** [comment]
> 2. add a labelgeometry=True flag to sim.plot2D, which would simply plot the given object labels (if any) at the (2d-projected) centers of the corresponding objects. (Or in 3d, maybe only plot them if they intersect the 2d slice.)

Following the [naming conventions](https://google.github.io/styleguide/pyguide.html#3162-naming-conventions) for method parameters, it would be good to use `label_geometry` rather than `labelgeometry` as the new parameter to `sim.plot2D`.
