### ISSUE TITLE
Using swap partition in simulations

### ISSUE THREAD

**Issue by leSemaleon** [NanoComp/meep#2697]
In my simulations, sometimes the RAM becomes full and the swap partition becomes involved. However, the time per step becomes unstable. at some point it may be 0.2 s/step but at others 20 s/step. at moments of small s/step the processor is loaded at 100%, but not for long; at other times the load is around 10%. Is this behavior normal, or does something need to be fixed?

**Comment by stevengj** [comment]
That’s normal if you are thrashing swap. 

If your problem is that big you should consider paralleling your simulation on a cluster.
