### ISSUE TITLE
Dependence of calculation speed on the selected length unit

### ISSUE THREAD

**Issue by leSemaleon** [NanoComp/meep#2714]
There is a simulation where the unit of length is 1 micron. Computation time is about 10 minutes. If I change the unit of length to 100 microns, the time increases to several hours. Of course, I proportionally reduce all lengths. I don't think this is working correctly

**Comment by stevengj** [comment]
You probably forgot to scale something dimensionful, e.g. you didn't scale the resolution correctly.

**Comment by leSemaleon** [comment]
I use until_after_source=mp.stop_when_fields_decayed(50/unit, mp.Ey, pt, accuracityOfDecay), where unit is meep unit. I think this equation takes into account the change in time when the measurement of length changes

**Comment by leSemaleon** [comment]
I actually didn't change the stop_when_fields_decayed field at first. That is, with a different unit of length, the field was checked too rarely, which is why the simulation was delayed. Now the simulation time does not depend on the unit of length
