### ISSUE TITLE
This discussion is intended for people who is trying to simulate transmission lines in RF World (mainly focused on microstrip lines)

### ISSUE THREAD

**Issue by manujmg** [NanoComp/meep#2744]
This discussion is intended for people who is trying to simulate transmission lines in RF World (mainly focused on microstrip lines) (Started in #2493) 

_Originally posted by @manujmg in https://github.com/NanoComp/meep/discussions/2743_

**Comment by stevengj** [comment]
Closing as a duplicate thread
