### ISSUE TITLE
Using your own functions to permittivity

### ISSUE THREAD

**Issue by leSemaleon** [NanoComp/meep#2748]
Why can you specify your materials only through the Lorentz Drude model? Is this something important?
Can I make an artificial material with fixed real and imaginary parts of the permittivity over the entire frequency range?

**Comment by stevengj** [comment]
No.  This is a [FAQ](https://meep.readthedocs.io/en/latest/FAQ/#how-do-i-set-the-imaginary-part-of).

The problem is that an arbitrary ε(ω) function, e.g. a constant imaginary part, does not correspond in the time domain to a causal, passive material.
