### ISSUE TITLE
Dielectric for Au using JC values

### ISSUE THREAD

**Issue by kombatEldridge** [NanoComp/meep#2750]
Thank you for all the work you have put into meep!

Do the JC values for Au in materials.py need to have a range of wavelength values for where it is valid? Right now, it does not have a range but the two other Au fitting values have a wavelength range.

**Comment by oskooi** [comment]
The wavelength range for `Au_JC_visible` in `materials.py` is [400, 800] nm as the fitting data is from [D. Barchiesi and T. Grosges, J. Nanophotonics, Vol. 8, 08996 (2015)](https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=e93db899c22bbb6e7495435d88b2955cdfdf065c) as well this [errata](https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=dcca866b075aa385caf72cf63c6f713045647bd3).

However, the definition of the `Au_JC_visible` object is missing assignment of its `valid_freq_range` property:

https://github.com/NanoComp/meep/blob/7c9d2083d391b7b79310755bf9c92445c74d5d95/python/materials.py#L720

Thanks for catching this bug. The fix would require adding `valid_freq_range=metal_visible_range`. Feel free to submit a PR with this change.

**Comment by oskooi** [comment]
Fixed by #2751.
