### ISSUE TITLE
Strange plot2D image

### ISSUE THREAD

**Issue by zcshinee** [NanoComp/meep#2784]
I got strange structure from plot2D when running  [python/examples/zone_plate.py](https://github.com/NanoComp/meep/blob/master/python/examples/zone_plate.py) of [Tutorial/Focusing Properties of a Binary-Phase Zone Plate](https://meep.readthedocs.io/en/latest/Python_Tutorials/Cylindrical_Coordinates/#focusing-properties-of-a-binary-phase-zone-plate):

![image](https://github.com/NanoComp/meep/assets/34888732/9d86ba81-b2fc-4aaf-945d-87ad332c8046)

According to https://github.com/NanoComp/meep/pull/2136, the correct plot should be:
![image](https://github.com/NanoComp/meep/assets/34888732/e16a7baf-736c-42eb-b5c5-fe93320ab11a)

Is this a bug in the plot2D function?

**Comment by oskooi** [comment]
The first image that you posted shows coordinate axes "X" and "Z" which is clearly not the cylindrical coordinates of the tutorial. Perhaps you mixed something up?

If I run `python/examples/zone_plate.py` as-is using Meep built using the master branch (9d93e2b), the output image from `Simulation.plot2D` of `zone_plate_layout.py` is as expected:

![zone_plate_layout](https://github.com/NanoComp/meep/assets/7152530/4e092d9b-e9fe-4c0b-ba32-710e2449c7cd)

**Comment by oskooi** [comment]
The notebook you are using is likely out of date. I have updated this notebook in #2785. This should hopefully fix it.

**Comment by oskooi** [comment]
Closing as completed.
