### ISSUE TITLE
mini coda website gives 404 error

### ISSUE THREAD

**Issue by b4wen** [NanoComp/meep#2834]
### Discussed in https://github.com/NanoComp/meep/discussions/2833

<div type='discussions-op-text'>

<sup>Originally posted by **b4wen** May 12, 2024</sup>
Hi, 
I have been struggling installing MEEP for a few days. If anyone can help me with this it would be very appreciated! 
My first question:
Did mini coda website moved? When I run it, it gives me 404 error. 
![image](https://github.com/NanoComp/meep/assets/48703883/d491b00b-9f57-426b-9d1c-3f1ae9f3ee57)
My second question:
Then I tried to use Ubuntu to install meep, it didn't give any error until I try to call any attribute from Meep:
![image](https://github.com/NanoComp/meep/assets/48703883/56aeeec5-73ba-4f09-b707-5e8e19652298)
I'm very confused now. What should I do to install Meep? 
Thanks to any response in advance. </div>

**Comment by stevengj** [comment]
close as duplicate
