### ISSUE TITLE
meep built against mpb-mpi does not work

### ISSUE THREAD

**Issue by zerothi** [NanoComp/meep#2900]
This problem is very similar to #2485

- I compile mpb with mpi support.
- I then try to compile meep with mpb support + python support

It then fails with the same problems mentioned in #2485.

1. It can't find `mpb.h` hence configure step says mpb support is not enabled
2. This occurs because mpb installed with mpi support only installs the `mpb_mpi.h` header files.
3. Does this mean that meep can only be compiled against the serial version of mpb? Perhaps I have completely missed this ;)?

**Comment by stevengj** [comment]
Yes, Meep requires the serial MPB.

**Comment by efferre79** [comment]
@stevengj can meep be compiled with mpi/openmp support when using serial MPB?
