### ISSUE TITLE
Meep on Mac OS Sierra

### ISSUE THREAD

**Issue by ebuckley002** [NanoComp/meep#35]
Meep 1.3 seems to be incompatible with Guile 2.0.12. Any plans to update Meep to work with this version?

For example, the straight waveguide example gives

creating output file "./eps-000000.00.h5"...
ERROR: In procedure %run-finalizers:
ERROR: In procedure delete-meep-volume: Wrong type argument in position 1: #<finalized smob 10aa7dc80>

**Comment by Daniel-M** [comment]
I have the same problem with Meep 1.3, using libctl 3.2.2 and Guile 2.0.13. in Debian Testing (Buster). Installed from sources.

**Comment by om-mani-padme-hum** [comment]
Example not working for me either on fresh install on Mac OS X Sierra.

**Comment by Daniel-M** [comment]
@om-mani-padme-hum Hey, can you provide the versions of guile, libctl and meep? It would help to diagnose the problem

**Comment by stevengj** [comment]
(With Guile 2.2 and the latest Meep master, I get an error message about `procedure delete-meep-volume`, but the simulation actually still runs correctly.  For the time being, you can just ignore the error message, I hope.  Hopefully soon I'll get a chance to track it down.

**Comment by om-mani-padme-hum** [comment]
Looks like I'm using Guile 2.2.2, latest Meep master cloned direct from GitHub, libctl 3.2.2.

Result when I try to run demo in file waveguide.ctl:

-----------
Initializing structure...
Working in 2D dimensions.
Computational cell is 16 x 8 x 0 with resolution 10
     block, center = (0,0,0)
          size (1e+20,1,1e+20)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (12,12,12)
time for set_epsilon = 0.0222449 s
-----------
creating output file "./waveguide-eps-000000.00.h5"...
Backtrace:
           0 (apply-smob/1 #<catch-closure 11097fa60>)

ERROR: In procedure apply-smob/1:
ERROR: In procedure delete-meep-volume: Wrong type argument in position 1: #<finalized smob 110649d80>
creating output file "./waveguide-ez-000200.00.h5"...
run 0 finished at t = 200.0 (4000 timesteps)

Elapsed run time = 0.647028 s

**Comment by om-mani-padme-hum** [comment]
And while it does create 104KB H5 output files, h5topng errors out when trying to convert them to PNG with seemingly random seg faults or out of memory-like errors.

**Comment by Daniel-M** [comment]
I'm not a meep developer, but in your case I would try to track the source of the segfault. I wonder if you have some debugger installed, I use `gdb` the GNU debugger, and it's useful to trace back the issue. I guess you compiled Meep without  the `--enable-debug` flag, doing it so would include debugging symbols useful to diagnose the problem better, but still, If you have `gdb` execute (where you have the ctl file),
```
$ gdb meep waveguide.ctl
```

And in the console of `gdb` type and execute `run`. It should raise some messages about the reason for the segfault.

**Comment by ChristopherHogan** [comment]
As of version `1.6.0` Meep is compatible with guile >= `2.0.12`.
