### ISSUE TITLE
Enhancement: Medium Evaluation

### ISSUE THREAD

**Issue by smartalecH** [NanoComp/meep#415]
Along with #398, it would be nice to simply evaluate a Medium at a given frequency point and return the complex permittivity. This would be useful for verifying that a given dispersion profile really is what you intend. It's all too easy to incorrectly convert one dispersion format to Meep's...

This would also enable the same dispersion material definitions within MPB and the frequency domain solver.

**Comment by stevengj** [comment]
Yes, that would be nice.  We've also discussed adding a `frequency` argument to `output-epsilon` or similar in order to output the dielectric profile evaluated at a given frequency.

**Comment by smartalecH** [comment]
I agree that would also be useful.

Do the eigenmode source and eigenmode expansion features currently support material dispersion? If not, would this be a viable way to enable that feature?

**Comment by smartalecH** [comment]
If this hasn't been assigned to anyone, I'm willing to work on this feature (I need it for my research).

**Comment by stevengj** [comment]
Since all the susceptibilities are of the form `χ = σ f(ω)` (where `f` is a scalar and `σ` can be a tensor), we basically just need to give `f(ω)`.   Probably should start with a virtual method `double susceptibility::chi1(double freq, double sigma=1)` in C++ with a corresponding method in `lorentzian_susceptibility` that returns `σ f(ω)` for a scalar `σ` that defaults to `1`.

**Comment by smartalecH** [comment]
Sorry this is taking so long. I'm still learning to balance my various research projects with a newborn...

I have a few questions regarding your preferred implementation:

Would it be practical to create a member function within `medium_struct` that loops through each susceptibility within its corresponding `E_susceptibilities` list, summing up each call to `susceptibility::chi1`? i.e. `double medium_struct::get_chi1(double freq)` could cleanly and natively account for multiple susceptibilities and for predefined `sigmas`. This function could even return a tensor for anisotropic materials (i.e `σ` is a tensor).

This approach seems to encourage a more object-oriented description of the `Medium` class in both python and C++. It could also (temporarily) enable dispersion within the eigenmode source/ deomposition features by adding it to the `meep_mpb_eps()` function (I'm looking at a possible alternative to the `get_chi1inv ()` function).

Or would you prefer to leave everythin to the user and stick strictly with the `susceptibility::chi1` member function? This approach seems easier to implement with the swig interface since the susceptibilities are explicately defined, while the python `Medium` class doesn't appear to have an explicit mapping to the C++ backend.

I may be misinterpreting several of these C++ functions so please set me straight! It's a lot of code to parse through...

**Comment by stevengj** [comment]
To start with, I think we should have just a `susceptibility::chi1(double freq)` function.

Once that is built, additional functionality can be built on top of that, e.g. to interpolate `σ(x)` for a given point x, evaluate ε for a medium, etcetera.
