### ISSUE TITLE
normalize eigenmode source to unit power

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#470]
It would be possible to change the normalization of the eigenmode source so that the eigenmodes are launched with unit power (optionally multiplied by a user specified complex amplitude).  This way you wouldn't have to do a separate normalization run.

(Note that this could also be used for planewave sources, just via an eigenmode source in a uniform region.)

One drawback of this would be that it would only be unit power up to discretization error, i.e. it would converge to unit power, but I'm not sure that would be a big deal.  (For the specific case of a planewave source, in principle you could solve for the exact discrete-space unit-power planewave, as reviewed in section 4.2.2 of https://arxiv.org/abs/1301.5366).

(Suggested by Colton Bukowsky on meep-discuss.)

**Comment by oskooi** [comment]
Note that this enhancement would facilitate calculations where the structure/sources are imported via a GDSII file such as the [tutorial example](https://meep.readthedocs.io/en/latest/Python_Tutorials/BidirectionalCoupler/) involving a directional coupler. An eigenmode source with unit power by default would obviate a separate normalization run to obtain the incident flux which is a little cumbersome to set up when only the entire device geometry made up of several subunits is known/provided.

**Comment by oskooi** [comment]
Closed by #728.
