### ISSUE TITLE
zero current amplitudes in solve_cw

### ISSUE THREAD

**Issue by smartalecH** [NanoComp/meep#501]
When using the CW solver, I occasionally get the following error:

`zero current amplitudes in solve_cw`

For a given geometry, the solver works for some resolutions and fails with others. I can't seem to understand why. The codebase itself is a little vague:
https://github.com/stevengj/meep/blob/05b9778823beed36672f3054eea6b264c51f6973/src/cw_fields.cpp#L151-L171

Any thoughts as to why the solver fails with only some resolutions?

**Comment by stevengj** [comment]
For the CW solver, it really shouldn't be using the smoothing at all (it should really turn it off automatically), because you want the eventual steady-state fields of the time-harmonic source, not the transient turn-on amplitudes.

**Comment by stevengj** [comment]
(The default smoothing width is zero, which is probably why we haven't noticed this before.)

**Comment by stevengj** [comment]
In the short term, we should add a note to the documentation.
