### ISSUE TITLE
get_array clarification

### ISSUE THREAD

**Issue by smartalecH** [NanoComp/meep#502]
While I use the `get_array` function in the Python API quite frequently, I can't seem to predict its behavior 100% of the time.

For example, if I pass a (1D) volume that is 4 units long with a predefined simulation resolution of 10, I would expect `get_array` to return an array of length 40. Instead, it returns an array of length 42.

Now, If I pass that same volume on a simulation domain with a resolution of 15, it returns an array of length 63.

I'm assuming this has something to do with Meep's averaging (grid interpolation), but I feel like the results should be much more predictable. The documentation is a little vague in this regard.

Am I missing something obvious here?

**Comment by stevengj** [comment]
This depends sensitively on whether the volume lies exactly on a pixel boundary or somewhere in between, which depends on the resolution etc.

**Comment by stevengj** [comment]
It might be useful to include some metadata about the array axes in the return value.

**Comment by ChristopherHogan** [comment]
`xarray` has a 2 dependencies that require hdf5, which means I would have to build and maintain those conda packages with parallel hdf5 support.  I would prefer to avoid that if possible until conda-forge can support a parallel hdf5 package. I'm not 100 percent clear on what is needed. Is it something that can be done with a subclass of `numpy.ndarray`?

**Comment by stevengj** [comment]
An alternative would be to add a `xaxis, yaxis, zaxis = simulation.volume_axes(volume)` function that returned 3 1d arrays (or 3 ranges) corresponding to the coordinates along each axis for a given volume (for `get_array` etcetera).

**Comment by ChristopherHogan** [comment]
This should be fixed by #655.
