### ISSUE TITLE
Add MPB info to runtime statistics

### ISSUE THREAD

**Issue by ChristopherHogan** [NanoComp/meep#541]
From @oskooi :

```
The test involving the binary grating (attached) spends the large majority of its total wall-clock time
 calling MPB via get_eigenmode_coefficients. However, the final simulation statistics which are
displayed at the end of the computation do not indicate this (see below). It seems that the time
spent doing MPB calculations does not appear at all in the output (it's even missing from the
"everything else" field).

Would it be possible to add the MPB-related calculations as an extra field?
----------------------------------------------------------------------
Ran 1 test in 16.345s

OK

Elapsed run time = 16.3472 s

Field time usage:
     connecting chunks: 0.00123 s
         time stepping: 1.3625 s
         communicating: 0.0728698 s
    Fourier transforming: 0.0847478 s
       everything else: 0.0303917 s

Field time usage:
     connecting chunks: 0.000766993 s
         time stepping: 0.385167 s
         communicating: 0.036778 s
    Fourier transforming: 0.0410931 s
       everything else: 0.0280201 s
```

It seems to me that since we go back and forth between Meep and MPB we'd have to time every MPB call and add them all up at the end. Is this feasible? And does `get_eigenmode_coefficients` count as "MPB time," or just actual calls to MPB?

**Comment by nengyi2019** [comment]
I have run a simulation about 1d photonic crystal with defect and calculate its flux:
(define (display-flux-in-box dir box)
(print "flux:, " (meep-time) ", " (flux-in-box dir box) "\n"))
and at the last
(run-sources+ 2000
(at-beginning output-epsilon)
(at-end output-efield-z)
(at-every 20 (display-flux-in-box Y (volume (center 0 (+ (* -0.5 sy) dpml 0.5) 0) (size (* 2 d3) 0 0))))

when I run this ,there is a error
"core dumped"

I don't know why this error comes up?
Thank you very much!

**Comment by stevengj** [comment]
@nengyi2019, I deleted your comment because it has nothing to do with this issue.  Please do not post help requests on random issues.  File a new issue if you think there is a problem with Meep.

**Comment by stevengj** [comment]
@ChristopherHogan, I would just time calls to `fields::get_eigenmode`
