### ISSUE TITLE
GDSII tutorial fails to complete

### ISSUE THREAD

**Issue by ahgibbons** [NanoComp/meep#553]
I have been running into several issues trying to run the GDSII tutorial, "coupler.py".
I am using pymeep-parallel, installed using conda-forge a couple days ago. The meep version is 1.5.0-96-gb20895b

The first issue I am having is that the tutorial contains a function `GDSII_vol` and my version does not contain this function, only `get_GDSII_volume`. I wasn't sure what to do so I just renamed all the `GDSII_vol` functions to `get_GDSII_volume`. 

The current error is 
```
Traceback (most recent call last):
  File "coupler.py", line 115, in <module>
    main(args)
  File "coupler.py", line 58, in main
    p1.center += delta
TypeError: unsupported operand type(s) for +=: 'method' and 'Vector3'
```
Is there any advice on what to do?

**Comment by ChristopherHogan** [comment]
Since the `coupler.py` example relies on recently added features, you'll have to use the latest conda package from the `dev` label of the `chogan` channel. Installation instructions can be found [here](https://meep.readthedocs.io/en/latest/Installation/#nightly-builds). Here's the gist:
```bash
conda create -n pmp_dev -c chogan/label/dev -c chogan -c conda-forge pymeep-parallel
```

**Comment by ahgibbons** [comment]
Thank you. I can confirm that downloading the `dev` version of Meep works. In general, do you recommend sticking with the `dev` version? I'm not very familiar with `conda-forge`. In the future, how can I keep my Meep package up to date?

**Comment by ChristopherHogan** [comment]
The `dev` version always aligns with the latest tutorials, and is generally as stable as master. It's required for features that aren't available in an official release yet (e.g., for `coupler.py` ), but keep in mind that the API may change. To update an existing environment with the latest dev package:
```bash
# With current meep environment activated
$ conda update -c chogan/label/dev -c chogan -c conda-forge pymeep-parallel
```
