### ISSUE TITLE
I'm new and feel lost. I need directions

### ISSUE THREAD

**Issue by DiegoGuisasola** [NanoComp/meep#556]
Greetings fellas.
I'm new to Ubuntu and Meep and I'm having a hard time trying to follow alone the tutorials using python.
I've installed Meep, Python 3 and Pycharm in order to write the scripts shown in [this link](https://meep.readthedocs.io/en/latest/Python_Tutorials/Basics/).
I don't know if i run the commands on the terminal or to create a script using pycharm and run it, either way, none of these work for me and i'm sure is simple but not for me.
For example, when I want to follow alone those examples in the site I listed above, I get and error on pycharm.
My script for the first example is:

`import meep as mp
cell = mp.Vector3(16, 8, 0)
geometry = [mp.Block(mp.Vector3(1e20, 1, 1e20),
                     center=mp.Vector3(0, 0),
                     material=mp.Medium(epsilon=12))]`

I get this error:

`/home/diego/PycharmProjects/Meep/venv/bin/python /home/diego/PycharmProjects/Meep/Example1.py
Traceback (most recent call last):
  File "/home/diego/PycharmProjects/Meep/Example1.py", line 1, in <module>
    import meep as mp
ModuleNotFoundError: No module named 'meep'

Process finished with exit code 1`

What am I doing wrong?

Thanks in advance!

Edit:

What I've done so far:
1. Install ubuntu 18.04.
2. Install Meep using [this link](https://meep.readthedocs.io/en/latest/Download/). The one that says: Precompiled Packages for Ubuntu because it states that Meep can be installed with just one command.
`sudo apt-get install meep h5utils`
4. Under the [installation tab ](https://meep.readthedocs.io/en/latest/Installation/) it states that if I want to use PyMeep (because I want to learn Meep by using Python scripts instead of MIT's Scheme) I have to install Conda Packages. So, I did. I installed miniconda and followed alone all the steps. (See picture 1 where the miniconda3 folder is shown).
![1](https://user-images.githubusercontent.com/44145128/46923326-cb46c380-cfdb-11e8-8ce2-391f635846ea.png)
5. Below the previous section there is another one named: "Installation on Linux" where its stated that I only need to use one command, the one shown in my list (number 2).
6. But then again, there is [this link](https://meep.readthedocs.io/en/latest/Build_From_Source/) and Idk if I have to carry out those steps. Is it necessary to build from source? As I stated, I'm new to both, Ubuntu and Meep.
7. Then there is `libctl`, [HDF5](https://support.hdfgroup.org/HDF5/release/obtain518.html) and there is too much to do and I feel overwhelmed.

Should I uninstall Meep, Conda and Python and start all over again?
Please, be patient, I'm trying to learn.

Thanks in advance!

------------------------------------------------------
Edit 2:

I've installed meep again (without uninstalling the first one because idk how to do it) using [this script](https://www.mail-archive.com/meep-discuss@ab-initio.mit.edu/msg05819.html#) with a few changes:

> 	If libpng16-dev error
		fix: change it for libpng-dev and delete ~/install folder
	If configure: error: cannot compile a simple Fortran program
		fix: sudo apt-get install f2c gfortran libblas-dev liblapack-dev			(reference: https://ubuntuforums.org/showthread.php?t=1560828)

In the script's link it's said that the installation takes about 1 hour to complete but in my computer it took around 25 minutes and idk if something went wrong or my laptop is just faster. The screenshots I show belowed are from the terminal after completing the installation. I also show a few lines in which there are warnings:
![screenshot from 2018-10-14 23-34-28](https://user-images.githubusercontent.com/44145128/46930386-f8f73100-d00a-11e8-822c-e65e74bf81be.png)
![screenshot from 2018-10-14 23-34-22](https://user-images.githubusercontent.com/44145128/46930387-f98fc780-d00a-11e8-876b-3c843a96410c.png)
![screenshot from 2018-10-14 23-34-17](https://user-images.githubusercontent.com/44145128/46930388-f98fc780-d00a-11e8-9bdb-8e7b7113bf58.png)
![screenshot from 2018-10-14 23-34-06](https://user-images.githubusercontent.com/44145128/46930389-f98fc780-d00a-11e8-9fda-829f07317f1b.png)
![screenshot from 2018-10-14 23-33-51](https://user-images.githubusercontent.com/44145128/46930390-f98fc780-d00a-11e8-96cd-f428b891ade5.png)

Any comments would be very much appreciated.

**Comment by mrbaozi** [comment]
**Disclaimer:** I'm not a Meep author/contributor, but I have installed Meep on many machines before so I thought I might be able to help. But please, do not take this as official advice.

It seems like you have mixed up a few different ways of installing Meep and have ended up with a bit of a mess. A better place to ask for this kind of help is probably the [meep-discuss](http://ab-initio.mit.edu/cgi-bin/mailman/listinfo/meep-discuss) mailing list.

The Meep version on the official Ubuntu repositories is outdated and doesn't include full Python support (it's Meep 1.3, the Python API was introduced in 1.4). I think you should ignore the [precompiled packages section](https://meep.readthedocs.io/en/latest/Download/#precompiled-packages-for-ubuntu) in the documentation.

Generally, you can install Meep by [building it from source](https://meep.readthedocs.io/en/latest/Installation/#building-from-source), or you install the [conda packages](https://meep.readthedocs.io/en/latest/Installation/#conda-packages). If you install from source, you need to build/manage all the dependencies yourself, which can be problematic especially if you're new to Linux. I would not recommend it.

Before continuing I suggest you remove all packages that you have previously installed, just to be sure that there are no conflicts. Start from a clean slate.

Installing the conda packages is pretty straightforward. Basically, you follow the instructions [here](https://meep.readthedocs.io/en/latest/Installation/#conda-packages) and start using Meep. You do *not* need to install anything before or after this - it really is all you need to do.
The only thing you should (probably) change is this line:
`conda create -n mp -c chogan -c conda-forge pymeep
`
to this:
`conda create -n mp -c chogan -c conda-forge nomkl pymeep
`
This step might not be necessary, but I remember running into problems with BLAS/MKL.
You can then activate your PyMeep environment by typing `conda activate mp`. When your environment is activated you can run `python`, then `import meep` and it *should* work.
I don't use PyCharm so I don't know how to make it use the correct Python environment (the one with Meep installed), but since it's a very popular IDE I assume it has decent support for different environments.

**Comment by ChristopherHogan** [comment]
To add to @mrbaozi's excellent answer, the recommended way to install Meep is the conda package. After you've run the commands linked above, you will have a Meep conda environment located at `/path/to/miniconda/envs/mp`. To get things working with PyCharm, you just need to tell PyCharm to use the python interpreter from the Meep environment. Instructions can be found [here](https://www.jetbrains.com/help/pycharm/conda-support-creating-conda-virtual-environment.html).

**Comment by ChristopherHogan** [comment]
If it's not clear from the instructions, the interpreter you want to select is `/path/to/miniconda/envs/mp/bin/python`.

**Comment by DiegoGuisasola** [comment]
Thank you very much!
I've installed the Conda packages but know I'm having troubles trying to use pycharm.
Note: I made a mistake and didn't add the `nomkl` in the line `conda create -n mp -c chogan -c conda-forge pymeep`. I hope it won't cause troubles.
1. The path to miniconda for me is: `/home/diego/.conda/envs/Meep`
2. I created the folder Meep inside envs because the link shared by ChristopherHogan states that the folder must be empty so I created a new one. Am I right?
3. The python version I want to use is 3.6.
4. The file I choose for the conda executable is: `/home/diego/desired_prefix/envs/mp/bin/python3.6`.
I choose this one because I want to use Python 3.6 but I also tried the one recommended by Christopher  and none worked, I keep getting the next error: 
`/home/diego/desired_prefix/envs/mp/bin/python3.6: can't open file 'create': [Errno 2] No such file or directory`

![2](https://user-images.githubusercontent.com/44145128/46964888-e6164800-d06e-11e8-84a7-30a6197e0656.png)
![1](https://user-images.githubusercontent.com/44145128/46964889-e6aede80-d06e-11e8-8961-1acdb5cd1213.png)

What can I do in order to fix this?
Thanks in advance!

**Comment by ChristopherHogan** [comment]
Since you're already created an environment, you should use the "Existing environment" option. Click the "Existing environment" bullet and set the interpreter to `/home/diego/desired_prefix/envs/mp/bin/python`.

**Comment by soamaven** [comment]
@DiegoGuisasola you can safely ignore the `canberra-gtk-module` error; it is unrelated to `meep`, only the GUI graphics display libraries of Ubuntu and certain GUIs. You can install it if you want, a quick search on stackexchange will tell you how.

**Comment by DiegoGuisasola** [comment]
Thank you veru much to all of you!
I'm now able to run all my scripts and fixed tha `canberra-gtk-module`.
You can't imagine how thankful I am.

Have an awesome day!

**Comment by ElboxD** [comment]
Hello everyone

**Comment by DiegoGuisasola** [comment]
Hello everyone! 
I apologize for reopening this thread but I'm having troubles trying to use meep in the terminal without python, that is, to use bash and scheme.
Meep is install because I can use it within PyCharm (this is the result of having followed the instructions above) but when I type Meep in the terminal, it says the following:
![1](https://user-images.githubusercontent.com/44145128/52486398-01aade80-2b89-11e9-879d-b173aee66015.png)

As you can see, I have the Meep's folders, hence, it's installed.
What I want to do is to run bash codes which call .ctl files.

Thank you very much!

**Comment by ChristopherHogan** [comment]
The conda packages only include the Python interface. If you want to use Scheme, you have to either
1. Use the [ubuntu package](https://meep.readthedocs.io/en/latest/Installation/#installation-on-linux), which is quite outdated.
2. [Build from source](https://meep.readthedocs.io/en/latest/Build_From_Source/). Just follow the script [here](https://meep.readthedocs.io/en/latest/Build_From_Source/#building-from-source). You don't need to install the dependencies that include `python` in the name, and you can add the `--without-python` flag  to the `sh autogen.sh` command for Meep.

**Comment by DiegoGuisasola** [comment]
Thank you very much for the fast response!!!!
I'll do it right away and come back.

Thanks!

**Comment by stevengj** [comment]
@DiegoGuisasola, the end of your screenshot gives the answer: your script terminated early with the error `pip3: command not found`, so it never got to the point of compiling and installing `meep`.   You need to install `pip3` (`sudo apt-get -y install python3-pip`) if you want to use it for the installation steps. 

In general, error messages are helpful to read!   But I would also say that installing software from source on Unix systems is something that takes getting used to, and I would recommend finding a local expert at your institution or company to help.

@oskooi, if `python3-pip` is not installed by default on Ubuntu these days, it should probably be added to the list of packages for the `sudo apt-get -y install` command in the documentation.

**Comment by DiegoGuisasola** [comment]
Thank you very much!
I was able to do it and now it's working perfectly. Thank you so much!

**Comment by DiegoGuisasola** [comment]
Hello everyone!
I'm sorry for opening this issue again is just that I've encountered a problem when building from source in another computer.
There were some problems while installing:

`sudo pip3 install --upgrade pip
# If pip3 doesn't work on ubuntu 18.04, just use pip
pip3 install --user --no-cache-dir mpi4py
export HDF5_MPI="ON"
pip3 install --user --no-binary=h5py h5py`

But I was able to make it work.
Now when I run the `meep` command in the terminal, it says:

![image](https://user-images.githubusercontent.com/44145128/52872142-bf9a1380-3119-11e9-9e0c-ade4453882cf.png)

What can I do in order to fix this?

Thank you very much!
