### ISSUE TITLE
bug in vertices property of prism objects in Scheme interface

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#608]
The [prism](https://meep.readthedocs.io/en/latest/Scheme_User_Interface/#prism) object in the Scheme interface defines the `vertices` property as the *bottom* of the `prism` with the `center` property being unused. However, the *z* coordinate of the `vertices` seems to be ignored and the `prism` centroid is always at the origin. This is demonstrated in the following script where the `height` and *z* coordinate of the `vertices` are parameters.

```scm
(set! geometry-lattice (make lattice (size 5 5 5)))

(set! eps-averaging? false)

(set-param! resolution 50)

(define-param pz 0)   ; prism bottom z coordinate                                                                                                                    
(define-param ph 1.0) ; prism height                                                                                                                                 

(set! geometry
      (list
       (make prism
         (vertices
          (list (vector3 -1 0 pz)
                (vector3 -0.5 (/ (sqrt 3) 2) pz)
                (vector3 0.5 (/ (sqrt 3) 2) pz)
                (vector3 1 0 pz)
                (vector3 0.5 (/ (sqrt 3) -2) pz)
                (vector3 -0.5 (/ (sqrt 3) -2) pz)))
         (height ph)
         (center (vector3 0 0 0))
         (material (make medium (epsilon 12))))))

(run-until 0 (at-beginning output-epsilon))
```
The four figures below show the *yz* cross section through the middle of the `prism` for cases involving heights (`ph`) of `1.0` and `3.0` and *z* coordinates (`pz`) of `0` and `-2.5`. The figures were generated using `h5topng` of [h5utils](https://github.com/stevengj/h5utils/blob/master/README.md) via the commands:

```
meep pz=-2.5 pz=1.0 prism.ctl;
h5topng -x 125 prism-eps-000000.00.h5;
```
![prism_bug_scheme](https://user-images.githubusercontent.com/7152530/48589315-db5e0580-e8ef-11e8-9855-d1a7df3ea8d2.png)

In all four cases, the centroid of the `prism` is at the origin which is incorrect. For `pz=-2.5`, the bottom of the prism should be at the bottom of the cell. The `height` of each prism is correct.

This bug was originally reported by Alexander Davis on the [mailing list](https://www.mail-archive.com/meep-discuss@ab-initio.mit.edu/msg06167.html).

**Comment by stevengj** [comment]
I thought the `center` was ignored in the Scheme interface?   (We should fix libctl so that `center` is no longer a required property for prisms in Scheme.)

**Comment by stevengj** [comment]
Actually, it looks like `center` is not ignored in Scheme; it shifts the centroid by the `center`.

**Comment by stevengj** [comment]
Actually, it looks like prism objects are just broken in Scheme; a lot of the fields are not getting initialized properly.
