### ISSUE TITLE
turn off subpixel averaging or print warning message if epsilon < 1

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#615]
A common cause of instability which leads to fields blowing up is when subpixel averaging is applied to pixels which have ε < 1.  This occurs either at boundary pixels or for dispersive materials (particularly metals in the [materials library](https://meep.readthedocs.io/en/latest/Materials/#materials-library)) involving [Lorentzian susceptibilities](https://meep.readthedocs.io/en/latest/Python_User_Interface/#lorentziansusceptibility). The suggested workaround has always been to turn off subpixel averaging (see this [FAQ](https://meep.readthedocs.io/en/latest/FAQ/#why-are-the-fields-blowing-up-in-my-simulation)). To simplify this further, it might be useful during the grid initialization whenever an  ε < 1 pixel is detected to either (1) print a message warning that the fields may become unstable or (2) automatically turn off subpixel averaging altogether.

**Comment by stevengj** [comment]
There is no subpixel averaging of Lorentzian susceptibilities, however.

For a nondispersive 0 < ε < 1, subpixel averaging shouldn't be a problem.

**Comment by oskooi** [comment]
This issue was addressed by adding a separate clause (5) in an [FAQ](https://meep.readthedocs.io/en/latest/FAQ/#why-are-the-fields-blowing-up-in-my-simulation).
