### ISSUE TITLE
 GDS tutorial needs fix

### ISSUE THREAD

**Issue by joamatab** [NanoComp/meep#621]
in the GDS tutorial
https://meep.readthedocs.io/en/latest/Python_Tutorials/GDSII_Import/

mp.GDSII_vol, function is not available

needs to be replaced by

mp.get_GDSII_volume

however the example does not run

**Comment by oskooi** [comment]
`GDS_volume` is indeed included in the Python module and [python/examples/coupler.py](https://github.com/stevengj/meep/blob/master/python/examples/coupler.py) should run without any errors. Perhaps your installation is out of date or the SWIG headers have not been properly re-built after an update? The discussion in #613 may be relevant.

**Comment by kod4** [comment]
Probably It's because GDS module is not included in official release. With nightly builds example works fine, but with official release it isn't working.

**Comment by ChristopherHogan** [comment]
A conda package for the 1.7.0 release will be available very soon.
