### ISSUE TITLE
Missing '...duplicate' functions in the user reference

### ISSUE THREAD

**Issue by scimax** [NanoComp/meep#632]
While browsing through the Python based User reference for MPB I realized that the ...duplicate functions , like geometric_object_duplicates(...), of MEEP are all listed there only. In case of the Scheme Interface they are listed under "Geometry Utilities" in both MEEP and MPB. I would suggest to do the same for the Python interface, as they are part of the MEEP package. Or is there a clear decision against having it in both places? Otherwise I would copy it over from the [MPB docs](https://github.com/stevengj/mpb/blob/master/doc/docs/Python_User_Interface.md#geometry-utilities) to the [MEEP docs](https://github.com/stevengj/meep/blob/master/doc/docs/Python_User_Interface.md#miscellaneous-functions) and submit a PR.

Probably it might be better to have the description of the function only at one place and reference it from the other. But at least it would be good to have that reference, e.g. from the MEEP docs to the MPB docs.

**Comment by stevengj** [comment]
I agree that it would be better to just document them in one place and link them from the other place.
