### ISSUE TITLE
hidden feature to initialize fields using Bessel functions

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#645]
There is a hidden feature [`fields::initialize_field`](https://github.com/stevengj/meep/blob/master/src/initialize.cpp#L126-L139) for initializing fields using [Bessel functions](https://en.wikipedia.org/wiki/Bessel_function) via the [GNU Scientific Library](https://www.gnu.org/software/gsl/) (GSL). This would be useful for launching guided modes in [optical fibers](https://en.wikipedia.org/wiki/Optical_fiber). However, it is missing a Python SWIG wrapper as well as documentation in the manual (and possibly a tutorial example) even though it is available by default in the [C++ interface](https://meep.readthedocs.io/en/latest/Build_From_Source/#building-from-source).

**Comment by stevengj** [comment]
This is something that Mihai implemented years ago and and only computes the modes of hollow metal cylinders, and is only for cylindrical coordinates, so it's not that generally useful.

**Comment by stevengj** [comment]
We could probably just remove it.

**Comment by oskooi** [comment]
Since `initialize_field` is used by three different tests &mdash; [python/tests/multilevel_atom.py](https://github.com/NanoComp/meep/blob/master/python/tests/multilevel_atom.py#L65), [tests/cylindrical.cpp](https://github.com/NanoComp/meep/blob/master/tests/cylindrical.cpp#L290-L291), and [tests/one_dimensional.cpp](https://github.com/NanoComp/meep/blob/master/tests/one_dimensional.cpp#L134-L135) &mdash; it's best to leave it as is (including the unused Bessel functions), for now.
