### ISSUE TITLE
make distclean removes two HDF5 files required by tests

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#648]
Running `make distclean` in the parent directory causes `cyl-ellipsoid-eps-ref.h5` and `array-slice-ll-ref.h5` to be removed from the `tests/` subdirectory. However, these two files are used by three tests &mdash; `cyl-ellipsoid-ll.cpp`, `user-defined-material.cpp`, `array-slice-ll.cpp` &mdash; and thus should be excluded from the file purge.

**Comment by ChristopherHogan** [comment]
I can't reproduce this

```bash
$ ls tests/ | grep ref
array-slice-ll-ref.h5
cyl-ellipsoid-eps-ref.h5
$ make distclean
$ ls tests/ | grep ref
array-slice-ll-ref.h5
cyl-ellipsoid-eps-ref.h5
```

**Comment by oskooi** [comment]
You are right; the two HDF5 files are indeed being automatically excluded from the purge. I must have removed them manually during testing.

However, there is a single Scheme file `cyl-ellipsoid.ctl` in the `tests/` directory which does not appear to be actually being used for anything?

**Comment by ChristopherHogan** [comment]
Maybe `cyl-ellipsoid.ctl` is what @HomerReid used to create `cyl-ellipsoid-eps-ref.h5`?
