### ISSUE TITLE
collapse=False parameter is ignored in slicing routines

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#661]
The recently added `get_dft_array_metadata` routine accepts four parameters: `dft_cell=None, vol=None, center=None, size=None`. However, it seems that the three geometric parameters &mdash; `vol`, `center`, and `size` &mdash; are never used. This is actually consistent with `get_dft_array` which also does not provide for the slicing of its `dft` object (unlike `get_array`). Thus, unless (or until) we provide this additional functionality for both `get_dft_array` and `get_dft_array_metadata`, we should remove the three unused parameters from `get_dft_array_metadata`.

As a demonstration, the following script extracts two different slices using `get_dft_array_metadata` by specifying unique values of `center` and `size`.

```py
import meep as mp
import numpy as np

resolution = 20

n = 3.4
w = 1
r = 1
pad = 4
dpml = 2

sxy = 2*(r+w+pad+dpml)
vol = mp.Volume(mp.Vector3(), size=mp.Vector3(sxy,sxy))

c1 = mp.Cylinder(radius=r+w, material=mp.Medium(index=n))
c2 = mp.Cylinder(radius=r)

fcen = 0.118
df = 0.08

src = mp.Source(mp.GaussianSource(fcen,fwidth=df), mp.Ez, mp.Vector3(r+0.1))

sim = mp.Simulation(cell_size=mp.Vector3(sxy,sxy),
                    geometry=[c1,c2],
                    sources=[src],
                    resolution=resolution,
                    boundary_layers=[mp.PML(dpml)])

dfts = sim.add_dft_fields([mp.Ez], fcen, fcen, 1, where=vol)
sim.run(until_after_sources=100)

(x1,y1,z1,w1) = sim.get_dft_array_metadata(dft_cell=dfts,center=mp.Vector3(0.5*sxy-dpml-2.3),size=mp.Vector3(0,sxy-2*dpml,0))
(x2,y2,z2,w2) = sim.get_dft_array_metadata(dft_cell=dfts,center=mp.Vector3(),size=mp.Vector3(2.3,2.3,0))
```
(note: due to #658, symmetries have been omitted)

The two sets of parameters (`x1`,`y1`,`z1`,`w1`) and (`x2`,`y2`,`z2`,`w2`) should be different but turn out to be in fact equal:
```
>>> w1.shape
(320, 320)
>>> w2.shape
(320, 320)
>>> np.where(w1!=w2)
(array([], dtype=int64), array([], dtype=int64))
```
Rather unexpectedly, if the `dft_cell` parameter is removed, the two slices turn out to be different.
```py
(x1,y1,z1,w1) = sim.get_dft_array_metadata(center=mp.Vector3(0.5*sxy-dpml-2.3),size=mp.Vector3(0,sxy-2*dpml,0))
(x2,y2,z2,w2) = sim.get_dft_array_metadata(center=mp.Vector3(),size=mp.Vector3(2.3,2.3,0))
```
```
>>> w1.shape
(242,)
>>> w2.shape
(48, 48)
```

**Comment by HomerReid** [comment]
All of this is intentional behavior, though perhaps this is not clear from the documentation, and perhaps a different calling convention would be optimal from the user's perspective. 

In the current implementation, the parameters are processed according to the following order of precedence to determine the region for which metadata is returned:

-- If `dft_cell` is present, we use the region covered by the specified cell, and all other parameters (`vol`, `center`, `size`) are **ignored.**
 
-- If `dft_cell` is absent and `size` is present, we construct a region from `size` and `center` (with the latter defaulting to the origin if not specified) and `vol` is **ignored.** 

-- If `dft_cell` and `size` are absent and `vol` is present, we use `vol`.

-- If *no* parameters are specified we use the entire computational cell. 

The latter three rungs of this hierarchy mimic what is already done for `get_array`, and the only addition is the option to pass a `dft_cell` as a convenience.

**Comment by oskooi** [comment]
Thanks for the clarification. I will update the docs for `get_array_dft_metadata` to include this additional detail.

A separate but related issue is the cubature weights returned by `get_dft_array_metadata` (and also perhaps `get_array_metadata`). Since every slice consists of uniformly-spaced points, I would expect all weights to be identical (or very nearly so) and simply equal to the size of the point spacing: 1/resolution. However, this doesn't seem to be the case as demonstrated below for two slices (1d and 2d).
```
>>> (x,y,z,w) = sim.get_dft_array_metadata(center=mp.Vector3(1.3),size=mp.Vector3(0,2.4,0))
>>> x.shape
(1,)
>>> x
array([1.3])
>>> y.shape
(50,)
>>> y
array([-1.225, -1.175, -1.125, -1.075, -1.025, -0.975, -0.925, -0.875,
       -0.825, -0.775, -0.725, -0.675, -0.625, -0.575, -0.525, -0.475,
       -0.425, -0.375, -0.325, -0.275, -0.225, -0.175, -0.125, -0.075,
       -0.025,  0.025,  0.075,  0.125,  0.175,  0.225,  0.275,  0.325,
        0.375,  0.425,  0.475,  0.525,  0.575,  0.625,  0.675,  0.725,
        0.775,  0.825,  0.875,  0.925,  0.975,  1.025,  1.075,  1.125,
        1.175,  1.225])
>>> w.shape
(50,)
>>> w
array([0.00625, 0.04375, 0.05   , 0.05   , 0.05   , 0.05   , 0.05   ,
       0.05   , 0.05   , 0.05   , 0.05   , 0.05   , 0.05   , 0.05   ,
       0.05   , 0.05   , 0.05   , 0.05   , 0.05   , 0.05   , 0.05   ,
       0.05   , 0.05   , 0.05   , 0.05   , 0.05   , 0.05   , 0.05   ,
       0.05   , 0.05   , 0.05   , 0.05   , 0.05   , 0.05   , 0.05   ,
       0.05   , 0.05   , 0.05   , 0.05   , 0.05   , 0.05   , 0.05   ,
       0.05   , 0.05   , 0.05   , 0.05   , 0.05   , 0.05   , 0.04375,
       0.00625])
```
The weights near the edge of the slice (i.e., 0.00625) are not 0.05. I suspect what is going on here is that the weights are being computed by how much of a full pixel centered at each point in the slice lies within the slice area/volume. Points in the interior are fully contained in the slice area and thus have the full weight of 0.05 while those on the boundary have smaller values.

```
>>> (x,y,z,w) = sim.get_dft_array_metadata(center=mp.Vector3(),size=mp.Vector3(0.7,0.4,0))
>>> x.shape
(16,)
>>> x
array([-0.375, -0.325, -0.275, -0.225, -0.175, -0.125, -0.075, -0.025,
        0.025,  0.075,  0.125,  0.175,  0.225,  0.275,  0.325,  0.375])
>>> y.shape
(10,)
>>> y
array([-0.225, -0.175, -0.125, -0.075, -0.025,  0.025,  0.075,  0.125,
        0.175,  0.225])
>>> w.shape
(16, 10)
>>> w
array([[3.9062500e-05, 2.7343750e-04, 3.1250000e-04, 3.1250000e-04,
        3.1250000e-04, 3.1250000e-04, 3.1250000e-04, 3.1250000e-04,
        2.7343750e-04, 3.9062500e-05],
       [2.7343750e-04, 1.9140625e-03, 2.1875000e-03, 2.1875000e-03,
        2.1875000e-03, 2.1875000e-03, 2.1875000e-03, 2.1875000e-03,
        1.9140625e-03, 2.7343750e-04],
       [3.1250000e-04, 2.1875000e-03, 2.5000000e-03, 2.5000000e-03,
        2.5000000e-03, 2.5000000e-03, 2.5000000e-03, 2.5000000e-03,
        2.1875000e-03, 3.1250000e-04],
       [3.1250000e-04, 2.1875000e-03, 2.5000000e-03, 2.5000000e-03,
        2.5000000e-03, 2.5000000e-03, 2.5000000e-03, 2.5000000e-03,
        2.1875000e-03, 3.1250000e-04],
       [3.1250000e-04, 2.1875000e-03, 2.5000000e-03, 2.5000000e-03,
        2.5000000e-03, 2.5000000e-03, 2.5000000e-03, 2.5000000e-03,
        2.1875000e-03, 3.1250000e-04],
       [3.1250000e-04, 2.1875000e-03, 2.5000000e-03, 2.5000000e-03,
        2.5000000e-03, 2.5000000e-03, 2.5000000e-03, 2.5000000e-03,
        2.1875000e-03, 3.1250000e-04],
       [3.1250000e-04, 2.1875000e-03, 2.5000000e-03, 2.5000000e-03,
        2.5000000e-03, 2.5000000e-03, 2.5000000e-03, 2.5000000e-03,
        2.1875000e-03, 3.1250000e-04],
       [3.1250000e-04, 2.1875000e-03, 2.5000000e-03, 2.5000000e-03,
        2.5000000e-03, 2.5000000e-03, 2.5000000e-03, 2.5000000e-03,
        2.1875000e-03, 3.1250000e-04],
       [3.1250000e-04, 2.1875000e-03, 2.5000000e-03, 2.5000000e-03,
        2.5000000e-03, 2.5000000e-03, 2.5000000e-03, 2.5000000e-03,
        2.1875000e-03, 3.1250000e-04],
       [3.1250000e-04, 2.1875000e-03, 2.5000000e-03, 2.5000000e-03,
        2.5000000e-03, 2.5000000e-03, 2.5000000e-03, 2.5000000e-03,
        2.1875000e-03, 3.1250000e-04],
       [3.1250000e-04, 2.1875000e-03, 2.5000000e-03, 2.5000000e-03,
        2.5000000e-03, 2.5000000e-03, 2.5000000e-03, 2.5000000e-03,
        2.1875000e-03, 3.1250000e-04],
       [3.1250000e-04, 2.1875000e-03, 2.5000000e-03, 2.5000000e-03,
        2.5000000e-03, 2.5000000e-03, 2.5000000e-03, 2.5000000e-03,
        2.1875000e-03, 3.1250000e-04],
       [3.1250000e-04, 2.1875000e-03, 2.5000000e-03, 2.5000000e-03,
        2.5000000e-03, 2.5000000e-03, 2.5000000e-03, 2.5000000e-03,
        2.1875000e-03, 3.1250000e-04],
       [3.1250000e-04, 2.1875000e-03, 2.5000000e-03, 2.5000000e-03,
        2.5000000e-03, 2.5000000e-03, 2.5000000e-03, 2.5000000e-03,
        2.1875000e-03, 3.1250000e-04],
       [2.7343750e-04, 1.9140625e-03, 2.1875000e-03, 2.1875000e-03,
        2.1875000e-03, 2.1875000e-03, 2.1875000e-03, 2.1875000e-03,
        1.9140625e-03, 2.7343750e-04],
       [3.9062500e-05, 2.7343750e-04, 3.1250000e-04, 3.1250000e-04,
        3.1250000e-04, 3.1250000e-04, 3.1250000e-04, 3.1250000e-04,
        2.7343750e-04, 3.9062500e-05]])
```
In this 2d example, none of the weights are 0.05 which is unexpected. Similar to the first example, the boundary points have smaller values than interior points.

**Comment by HomerReid** [comment]
> The weights near the edge of the slice (i.e., 0.00625) are not 0.05. I suspect what is going on here is that the weights are being computed by how much of a full pixel centered at each point in the slice lies within the slice area/volume.

Yes, the weights reflect information about the interpolation needed to estimate field values at points in interstitial regions between grid points. This can be explored in further detail by looking at the output of `get_array_metadata` (instead of `get_dft_array_metadata`) for array slices in which one dimension has zero thickness---the array will contain two points for each grid point in that dimension, whose weights *sum* to 0.05 (at least for grid points away from boundaries) but with a distribution that will vary as the coordinate of the array slice moves from being closer to one grid point to being closer to the other one. In `get_dft_array_metadata` these expanded dimensions are collapsed into a single dimension by simply summing the cubature weights for each point. 

> In this 2d example, none of the weights are 0.05 which is unexpected.

Actually, this is expected. The weighting scheme reflects the dimension of the slice region (1D, 2D, or 3D) and adjusts the weights appropriately to ensure that the sum of the cubature weights has dimensions of length, area, or volume respectively. For this case, with `resolution=20`, the grid-point spacing is 0.05 and the array slice is two-dimensional, so interior grid points have weights of (0.05)^2^ = 0.025.

**Comment by oskooi** [comment]
As a test of the interpolation properties of `get_array_metadata`, based on the previous example involving a 2d cell the following are 1d slices along the y-direction of fixed length with slight variations (subpixel, <0.05) in the x coordinate.

```
>>> (x,y,z,w) = sim.get_array_metadata(center=mp.Vector3(5.42),size=mp.Vector3(0,2.1,0),collapse=False); w.shape
(38,)
>>> (x,y,z,w) = sim.get_array_metadata(center=mp.Vector3(5.43),size=mp.Vector3(0,2.1,0),collapse=False); w.shape
(38,)
>>> (x,y,z,w) = sim.get_array_metadata(center=mp.Vector3(5.437),size=mp.Vector3(0,2.1,0),collapse=False); w.shape
(38,)
>>> (x,y,z,w) = sim.get_array_metadata(center=mp.Vector3(5.45),size=mp.Vector3(0,2.1,0),collapse=False); w.shape
(38,)
>>> (x,y,z,w) = sim.get_array_metadata(center=mp.Vector3(5.479),size=mp.Vector3(0,2.1,0),collapse=False); w.shape
(38,)
>>> (x,y,z,w) = sim.get_array_metadata(center=mp.Vector3(-5.32),size=mp.Vector3(0,2.1,0),collapse=False); w.shape
(38,)
>>> (x,y,z,w) = sim.get_array_metadata(center=mp.Vector3(-5.39),size=mp.Vector3(0,2.1,0),collapse=False); w.shape
(38,)
>>> (x,y,z,w) = sim.get_array_metadata(center=mp.Vector3(-5.4923851),size=mp.Vector3(0,2.1,0),collapse=False); w.shape
(38,)
```
For some reason, `get_array_metadata` seems to always return a collapsed 1d array even though its `collapse` parameter is `False`. I would have expected that a few of these slices would be 2d (i.e., those slices in which the x-coordinate lies between two grid points).

Is it possible that the `collapse` parameter is being ignored and that the arrays are being collapsed by default?

As an additional observation, `get_array` also always returns a collapsed 1d array independent of the x-coordinate of the slice even though the documentations states that "in arrays of time-domain field components (as returned by `get_array`), empty dimensions are not collapsed;".

```
>>> Ex_slice = sim.get_array(center=mp.Vector3(5.42),size=mp.Vector3(0,2.1,0),component=mp.Ex); Ex_slice.shape
(38,)
>>> Ex_slice = sim.get_array(center=mp.Vector3(5.43),size=mp.Vector3(0,2.1,0),component=mp.Ex); Ex_slice.shape
(38,)
>>> Ex_slice = sim.get_array(center=mp.Vector3(5.437),size=mp.Vector3(0,2.1,0),component=mp.Ex); Ex_slice.shape
(38,)
>>> Ex_slice = sim.get_array(center=mp.Vector3(5.45),size=mp.Vector3(0,2.1,0),component=mp.Ex); Ex_slice.shape
(38,)
>>> Ex_slice = sim.get_array(center=mp.Vector3(5.479),size=mp.Vector3(0,2.1,0),component=mp.Ex); Ex_slice.shape
(38,)
>>> Ex_slice = sim.get_array(center=mp.Vector3(-5.32),size=mp.Vector3(0,2.1,0),component=mp.Ex); Ex_slice.shape
(38,)
>>> Ex_slice = sim.get_array(center=mp.Vector3(-5.39),size=mp.Vector3(0,2.1,0),component=mp.Ex); Ex_slice.shape
(38,)
>>> Ex_slice = sim.get_array(center=mp.Vector3(-5.4923851),size=mp.Vector3(0,2.1,0),component=mp.Ex); Ex_slice.shape
(38,)
```

**Comment by stevengj** [comment]
Looking at the source code to refresh my memory, it seems that the DFT slice routines [*always* collapse](https://github.com/NanoComp/meep/blob/d4bb82f6d6ff0fe6f7ad5ddd3b1dc37bf1c049a0/src/dft.cpp#L1028) empty dimensions (see also #330), whereas the time-domain array-slice routines [*never* collapse](https://github.com/NanoComp/meep/blob/d4bb82f6d6ff0fe6f7ad5ddd3b1dc37bf1c049a0/src/array_slice.cpp#L403) empty dimensions.

**Comment by oskooi** [comment]
The time-domain array-slice routine `get_array` *always* returns a collapsed array as demonstrated in the following script which takes 10 1d slices (in both the *x* and *y* directions) at random positions in a 2d cell and outputs their `shape` (since each is a NumPy array).

```py
import meep as mp
import numpy as np

resolution = 20

n = 3.4
w = 1
r = 1
pad = 4
dpml = 2

sxy = 2*(r+w+pad+dpml)
vol = mp.Volume(mp.Vector3(), size=mp.Vector3(sxy,sxy))

c1 = mp.Cylinder(radius=r+w, material=mp.Medium(index=n))
c2 = mp.Cylinder(radius=r)

fcen = 0.118
df = 0.08

src = mp.Source(mp.GaussianSource(fcen,fwidth=df), mp.Ez, mp.Vector3(r+0.1))

sim = mp.Simulation(cell_size=mp.Vector3(sxy,sxy),
                    geometry=[c1,c2],
                    sources=[src],
                    resolution=resolution,
                    boundary_layers=[mp.PML(dpml)])

sim.run(until_after_sources=100)

for r in 0.5*sxy*np.random.random(10):
    Ez1 = sim.get_array(center=mp.Vector3(x=r),size=mp.Vector3(y=sxy-2*dpml))
    Ez2 = sim.get_array(center=mp.Vector3(y=r),size=mp.Vector3(x=sxy-2*dpml))
    print(r, Ez1.shape, Ez2.shape)
```

**output**
```
----------
Initializing structure...
Working in 2D dimensions.
Computational cell is 16 x 16 x 0 with resolution 20
     cylinder, center = (0,0,0)
          radius 2, height 1e+20, axis (0, 0, 1)
          dielectric constant epsilon diagonal = (11.56,11.56,11.56)
     cylinder, center = (0,0,0)
          radius 1, height 1e+20, axis (0, 0, 1)
          dielectric constant epsilon diagonal = (1,1,1)
time for set_epsilon = 0.163936 s
-----------
run 0 finished at t = 225.0 (9000 timesteps)
0.44519706056432007 (242,) (242,)
0.41628548414366406 (242,) (242,)
0.5384956219996111 (242,) (242,)
3.5351235254307136 (242,) (242,)
7.510235465190334 (242,) (242,)
4.092435002342075 (242,) (242,)
7.298266532207943 (242,) (242,)
6.816475002152994 (242,) (242,)
0.4363109795928679 (242,) (242,)
5.212467274823124 (242,) (242,)

Elapsed run time = 3.1826 s
```
The 1d slices are all returned as 1d arrays which indicates that they are collapsed. Since `collapse=False` is the default, some of these slices which happen to lie *between* two pixels are expected to be 2d.

**Comment by stevengj** [comment]
Ah, now I understand what is happening — the array slice routines are passing `snap_empty_dims=true` to `loop_in_chunks`.  This means that it is not doing interpolation of empty dimensions — it just "rounds" to the nearest pixel.

I think we made this choice because it has the convenient property that taking a 2d slice yields a 2d array, with no need for a collapsing post-processing step.   But it does make array slicing not continuous (in the sense that if you move the slice continuously the result will "jump" from one pixel to the next).  In the long run it would be nice to turn interpolation on for array slicing and implement collapsing, as we do for DFT slices (which *are* interpolated).
