### ISSUE TITLE
output_epsilon shows discretization artifacts when k_point is set

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#668]
The [`output_epsilon`](https://meep.readthedocs.io/en/latest/Python_User_Interface/#output-functions) routine which generates an HDF5 file of the permittivity profile over the entire computational cell shows discretization artifacts when periodic boundaries are used. This is demonstrated in the following example of a 2d cell consisting of a 1d lattice of slanted blocks.The output is shown for two cases: with a `k_point` of `mp.Vector3(0,0,0)` and without.

```py
import meep as mp
import math

resolution = 100

cell_size = mp.Vector3(5,2,0)

k_point = mp.Vector3(0,0,0)

rot_angle = 30

geometry = []
for j in range(5):
    geometry.append(mp.Block(material=mp.Medium(index=1.5),
                             center=mp.Vector3(-2+j,0,0),
                             size=mp.Vector3(0.5,3,0),
                             e1 = mp.Vector3(1,0,0).rotate(mp.Vector3(0,0,1), math.radians(rot_angle)),
                             e2 = mp.Vector3(0,1,0).rotate(mp.Vector3(0,0,1), math.radians(rot_angle))))

sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size,
                    k_point=k_point,
                    filename_prefix='with_kpoint',
                    geometry=geometry,
                    ensure_periodicity=False)

sim.run(mp.at_beginning(mp.output_epsilon),until=0)

sim.reset_meep()

sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size,
                    filename_prefix='without_kpoint',
                    geometry=geometry,
                    ensure_periodicity=False)

sim.run(mp.at_beginning(mp.output_epsilon),until=0)
```

Note that `ensure_periodicity` is set to `False` so that geometric objects which extend outside of the cell are not translated back in. The permittivity profile should be the same in both cases but is not.

![output_epsilon_kpoint](https://user-images.githubusercontent.com/7152530/51076881-596e2c80-1653-11e9-9710-6cd221fc3a0c.png)

The figure on the left includes artifacts of the discretization at the edges of the cell which are highlighted.

(the images were created using [h5utils](https://github.com/NanoComp/h5utils/blob/master/README.md): `h5topng epsilon.h5`.)

**Comment by stevengj** [comment]
The results seem correct to me.   With `k_point` set, the boundaries are periodic, and you will see a little of the cell from one edge "leaking" over to the other edge.  This accurately reflects the computation that Meep is doing.  Why is this a problem?

(Of course, you wouldn't see any artifacts if your ε function were actually perodic.)

**Comment by oskooi** [comment]
If this is indeed the intended behavior for `output_epsilon` then we should do two things: (1) mention this in the documentation since otherwise some users may regard this as some kind of bug, and (2) for consistency (and once #667 is resolved), ensure that `get_epsilon` (which is based on `get_array`) has the same properties.

**Comment by stevengj** [comment]
In particular, `get_epsilon` averages ε from the Yee grid to the center of the pixel, so for pixels at the edge of the computational cell it picks up some effect from the other side.  (This will happen regardless of how you create the computational cell, e.g. via geometric objects or by a material function.

**Comment by soamaven** [comment]
I would advocate including a few words on this detail in the [FAQ](https://meep.readthedocs.io/en/latest/FAQ/#why-doesnt-turning-off-subpixel-averaging-work). Upon first using MEEP it was non-obvious, when simulating PML along one axis and periodic BCs in the others, why the epsilon in the PML region was showing "wrap-around" dielectric pixels. It was very confusing. A paradigm change was required coming from Lumerical etc. to I fully internalized the `get_epsilon` internal algorithm, MEEP's implementation of the different BCs, and why the epsilon artifacts were showing up in the `get_epsilon` output. Thanks!

**Comment by oskooi** [comment]
For reference as part of this discussion, replacing the geometric objects with a material function which constructs a periodic ε based on the grating example from above produces the same discretization artifacts.

```py
import meep as mp
import math

resolution = 100

cell_size = mp.Vector3(5.3,2,0)

k_point = mp.Vector3(0,0,0)

rot_angle = 60

w = 0.5  # width of grating                                                                                                                                                  

def slanted_grating(p):
    m = -math.tan(math.radians(rot_angle))
    b = -m*0.5*w
    x2 = (p.y-b)/m
    x1 = (p.y+b)/m
    xx = p.x
    if (xx < x2) and (xx > x1):
        return mp.Medium(index=1.5)
    elif (xx >= x2):
        while (xx >= x2):
            xx -= 1
            if (xx < x2) and (xx > x1):
                return mp.Medium(index=1.5)
    elif (xx <= x1):
        while (xx <= x1):
            xx += 1
            if (xx < x2) and (xx > x1):
                return mp.Medium(index=1.5)
    return mp.air

geometry = [mp.Block(center=mp.Vector3(), size=cell_size, material=slanted_grating)]

sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size,
                    k_point=k_point,
                    filename_prefix='with_kpoint',
                    geometry=geometry,
                    ensure_periodicity=False)

sim.run(mp.at_beginning(mp.output_epsilon),until=0)

sim.reset_meep()

sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size,
                    filename_prefix='without_kpoint',
                    geometry=geometry,
                    ensure_periodicity=False)

sim.run(mp.at_beginning(mp.output_epsilon),until=0)
```

![output_epsilon_matfunc_kpoint](https://user-images.githubusercontent.com/7152530/51353222-d7bc3b80-1a64-11e9-92da-01e2fefa34de.png)

**Comment by oskooi** [comment]
Also for reference, the following is the result from `get_epsilon` for just the case of no `k_point` (again because of #667, the case involving `k_point` is omitted). The result is identical to that of `output_epsilon` shown in the figure above right.

```py
import numpy as np
import matplotlib.pyplot as plt

sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size,
                    geometry=geometry,
                    ensure_periodicity=False)

sim.init_sim()

eps_data = sim.get_epsilon() # identical to sim.get_array(component=mp.Dielectric, center=mp.Vector3(), size=cell_size)
(x,y,z,w) = sim.get_array_metadata(center=mp.Vector3(), size=cell_size)
plt.figure(dpi=100)
plt.pcolormesh(x,y,np.transpose(eps_data), cmap='gist_gray_r', shading='gouraud')
plt.title('without k_point')
plt.axis('scaled')
plt.show()
```

![test_get_epsilon_matfunc_withoutkpoint2](https://user-images.githubusercontent.com/7152530/51366459-8038c280-1a9a-11e9-9681-19403848afae.png)

**Comment by oskooi** [comment]
This issue was addressed by updates to an [FAQ}(https://meep.readthedocs.io/en/latest/FAQ/#why-doesnt-turning-off-subpixel-averaging-work) in #679.
