### ISSUE TITLE
streamlining interface to slicing routines

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#670]
Four suggestions for creating a more streamlined interface to the slicing routines:

1. change the interface of `get_array(vol=None, center=None, size=None, component=mp.Ez, ...)` to `get_array(component, vol=None, center=None, size=None, ...)` (i.e., `component` is the first argument) in order to be consistent with `get_source_slice`

2. rename `get_source_slice` to `get_source` to be consistent with `get_array`

3. remove `get_dft_array_metadata` and have just a single `get_array_metadata` which accepts a `dft_cell` keyword argument and set `collapse=True` by default for everything

4. `get_array` should have `collapse=True` by default (currently it is false)

**Comment by ChristopherHogan** [comment]
For number 4, do you mean `get_array_metadata`? Or should `get_array` also have a `collapse` argument that defaults to `False` (it currently doesn't)?

**Comment by oskooi** [comment]
Both would be preferable: `get_array_metadata` should have `collapse=True` as its default *and* `get_array` should have a separate `collapse` argument (which is `True` by default). For the second option, it might require some work to support `collapse=False` for  `get_array` and this can be left out for the time being.

**Comment by oskooi** [comment]
Note that `get_array` has `collapse=False` set implicitly by default as described by @HomerReid in the [documentation](https://meep.readthedocs.io/en/latest/Python_User_Interface/#array-metadata): "in arrays of time-domain field components (as returned by `get_array`), empty dimensions are not collapsed;". Thus, number 4 should perhaps be omitted until `get_array` has been reworked to include an explicit `collapse` argument.

**Comment by stevengj** [comment]
For backwards compatibility, do `get_array(component=None, vol=None, center=None, size=None, ...)`, and:

* if a volume is passed for the `component` object, print out a deprecation warning, or at least a helpful error message.

* `component` is a required argument, so give an error if it is `None`.
