### ISSUE TITLE
pymeep cannot be installed in Anaconda 2018.12

### ISSUE THREAD

**Issue by drinkwell** [NanoComp/meep#688]
I've just downloaded the latest version of Anaconda (2018.12) and found after doing a `conda install pymeep` that I get the following error:
```
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda==2018.12=py37_0 -> cython==0.29.2=py37he6710b0_0
  - anaconda==2018.12=py37_0 -> mkl-service==1.1.2=py37he904b0f_5
  - anaconda==2018.12=py37_0 -> numexpr==2.6.8=py37h9e4a6bb_0
  - anaconda==2018.12=py37_0 -> scikit-learn==0.20.1=py37hd81dba3_0
  - pymeep
Use "conda info <package>" to see the dependencies for each package.
```
Given this is the preferred way of installing pymeep according to the documentation, I thought it warranted a bug report

**Comment by ChristopherHogan** [comment]
The preferred way is to use a conda environment. Please try the command exactly as it appears in the documentation:
```
$ conda create -n mp -c chogan -c conda-forge pymeep
$ source activate pymeep
```

**Comment by drinkwell** [comment]
Brilliant, that's sorted it.  I was worried I might have to resort to compiling from source.  In my ignorance I believed that the conflicts were fundamental to the version of Anaconda, however this is apparently not the case when building a separate environment.

Couple of minor things: I think you meant `source activate mp` (I've just checked the documentation and it's correct, so there no need to do anything).  Also, apparently the preferred way to activate an environment in conda now is `conda activate mp`, however the old sourcing method still works.  I believe the main reason for this is to make it consistent between operating systems

Thanks for the assistance

**Comment by ChristopherHogan** [comment]
> I think you meant `source activate mp`

Yes, sorry about that.

> Also, apparently the preferred way to activate an environment in conda now is conda activate mp

Right, I'll update the docs. Thanks!
