### ISSUE TITLE
Problem with pmp_test environment

### ISSUE THREAD

**Issue by JohnWeiner** [NanoComp/meep#702]

**Comment by JohnWeiner** [comment]
I have a python script that runs without problems on the latest stable meep release (using pmp environment) but shows errors when using pmp_test environment or pmp_7.1 environment.  Without going into the details of the python script, here is a sampling of the error messages:

HDF5-DIAG: Error detected in HDF5 (1.10.2) thread 0:
  #000: H5F.c line 445 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1519 in H5F_open(): unable to lock the file
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 1650 in H5FD_lock(): driver lock request failed
    major: Virtual File Layer
    minor: Can't update object
  #003: H5FDsec2.c line 941 in H5FD_sec2_lock(): unable to lock file, errno = 35, error message = 'Resource temporarily unavailable'
    major: File accessibilty
    minor: Bad file ID accessed

Was there a change in hdf5 ?

**Comment by ChristopherHogan** [comment]
I tried installing the Mac nightly `pymeep-parallel` package and hdf5 seems to work as expected. However, the latest builds should be using hdf5 `1.10.4`, but your error message indicates version `1.10.2`. That implies that something isn't right with your environment. Can you make sure `PYTHONPATH` is unset. Also, you might scan your environment variables with the `env` command and make sure there's nothing pointing to a different hdf5 installation.

**Comment by JohnWeiner** [comment]
Hi Chris,

PYTHONPATH is unset and I didn’t see anything suspicious in the environmental variables (env command).  Should I simply remove the pmp_test environment and recreate it?  If so, can you remind me of the all the command line options are?

By the way I see the same behaviour in your 7.1 environment.

Thanks,

John

**Comment by ChristopherHogan** [comment]
Yes, I would try recreating the environment.
```sh
# Start with the root environment
$ conda activate root
# Create an environment called "mp_dev" (or named however you wish) using the nightly parallel package
$ conda create -n mp_dev -c chogan/label/dev -c chogan -c conda-forge pymeep-parallel
# Activate the environment
$ conda activate mp_dev
```
> By the way I see the same behaviour in your 7.1 environment.

I'm not sure which environment you're referring to. It's probably best to refer to the Meep version, which is obtained from the command
```sh
$ python -c "import meep; print(meep.__version__)"
```

**Comment by JohnWeiner** [comment]
There seems to be a problem with downloading three packages after the conda create command

Downloading and Extracting Packages
h5utils-parallel-1.1 |   66 KB |                                                                                 |   0% 
mpb-1.7.1.dev        |   86 KB |                                                                                 |   0% 
pymeep-parallel-1.7. |  3.2 MB |                                                                                 |   0% 

I tried it twice since there was a message saying that HTTP errors were intermittent.

Not sure what to do now…

John

**Comment by JohnWeiner** [comment]
Here is a sample error from the failed connection:

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/chogan/label/dev/osx-64/mpb-1.7.1.dev-nomklhdc02c5d_13.tar.bz2>

**Comment by ChristopherHogan** [comment]
Yes, that happens with conda occasionally, but the errors really are intermittent so I would just keep trying every 5 or 10 minutes.

**Comment by JohnWeiner** [comment]
OK, got the errant packages downloaded and the parallel pymeep (pmp_dev) seems to be working just fine.  Must have been the version of HDF5 that caused the problem.

John

**Comment by ChristopherHogan** [comment]
Great!
