### ISSUE TITLE
Meta-data not unfolded

### ISSUE THREAD

**Issue by soamaven** [NanoComp/meep#704]
I am in a bit of a hurry, just wanted to throw this onto the board before I forget. I'll try to post a simplified example later:

I am seeing that using `get_array_metadata` on a geometry defined by `center` and `size` when using mirror symmetries (currently using two mirrors, X and Y) returns an array of only the negative values for `x`, `y`, in the first half a a `numpy` array and the second half of the array is all zeros. `z` is returned as the expected filled array. I am throwing out the `w` meta data, so I haven't examined it yet, but this might also be happening there. 

Based on the fact that all unfolding is supposed to be transparent to the user, this is unexpected behavior.

**Comment by oskooi** [comment]
This is a known bug; see #658.

**Comment by soamaven** [comment]
Ah thanks! I'll close this out then.
