### ISSUE TITLE
Multiple copies of plots when calling matplotlib routines in parallel pymeep

### ISSUE THREAD

**Issue by JohnWeiner** [NanoComp/meep#710]
I am working on a code that seeks to compute the net transmission through a subwavelength slit over a range of frequencies (wavelengths).  The python script runs in parallel meep and calculates the results correctly, but plot routines show plots for every processor in the mpirun -np command.  Is there some way to tell mpi or python to produce just one plot?  I didn't find any doc or faq that addresses this issue in meep readthedocs

**Comment by ChristopherHogan** [comment]
Just call your plotting code in the master process. E.g.,
```py
if mp.am_master():
    plt.show()

```

**Comment by JohnWeiner** [comment]
OK…did find some discussion of this in Technical Details under Parallel Meep in meep.readthedocs.

**Comment by JohnWeiner** [comment]
Yes! It works as advertised…thanks.
