### ISSUE TITLE
Suggestion: change norm() for complex Vector3

### ISSUE THREAD

**Issue by 98md21** [NanoComp/meep#722]
While this is not necessarily a bug, it would be useful if `norm()` function for `Vector3` were changed so that `norm()` gives the expected answer for complex vectors, since `Vector3` is allowed to be real or complex. As written in [https://meep.readthedocs.io/en/latest/Python_User_Interface/#vector3](url), `norm()` currently equals `math.sqrt(abs(v1.dot(v1)))`. This means, for example, that `Vector3(1, 1j, 0).norm()` equals 0.

**Comment by stevengj** [comment]
Just change [this line](https://github.com/NanoComp/meep/blob/78fbe1dc531cc409714fb8541cc56f1f0dc9880c/python/geom.py#L112) to call `real(self.cdot(self)))`, I think?  A PR with a test would be welcome.
