### ISSUE TITLE
make fails in scheme directory

### ISSUE THREAD

**Issue by ChristopherHogan** [NanoComp/meep#723]
Dear Steven,
Thank for your meep updating.
For meep-1.8.0, the configure process goes smoothly, but the make appears error:
meep-1.8.0/scheme
error1
meep-1.8.0/scheme
error2

How to resolve the problem, your suggestion is appreciated.

Nengyi2019

**Comment by ChristopherHogan** [comment]
@nengyi2019, This isn't enough output for me to diagnose the problem. Can you try building via the instructions [here](https://meep.readthedocs.io/en/latest/Build_From_Source/#building-from-source) and post the full output if something goes wrong? Thanks.

**Comment by stevengj** [comment]
Closing as not reproducible.

**Comment by nengyi2019** [comment]
Dear Christopher,

I have run a simulation about 1d photonic crystal with defect and calculate its flux:
(define (display-flux-in-box dir box)
(print "flux:, " (meep-time) ", " (flux-in-box dir box) "\n"))
and at the last
(run-sources+ 2000
(at-beginning output-epsilon)
(at-end output-efield-z)
(at-every 0.2 (display-flux-in-box Y (volume (center 0 (+ (* -0.5 sy) dpml 0.5) 0) (size (* 2 d) 0 0))))
when I run this ,there is a error
"core dumped"
I don't know why this error comes up?
Your suggestion is greatly appreciated. 

Best regards,

Nengyi2010




nengyi2010@163.com
 
From: Christopher Hogan
Date: 2019-02-18 22:18
To: NanoComp/meep
CC: nengyi2019; Mention
Subject: Re: [NanoComp/meep] make fails in scheme directory (#723)
@nengyi2019, This isn't enough output for me to diagnose the problem. Can you try building via the instructions here and post the full output if something goes wrong? Thanks.
