### ISSUE TITLE
init_sim hangs for some cell sizes

### ISSUE THREAD

**Issue by osepsi** [NanoComp/meep#736]
All,

I have run into a strange problem. Using the python interface (1.8.0 using anaconda) the program hangs for certain cell size parameters. Here is the most minimalistic code that produces the problem for me:

`import meep as mp`
`sim = mp.Simulation(resolution=100,
                    cell_size=mp.Vector3(1.50, 0.1, 0))`
`sim.init_sim()`

In case the cell_size is different (i.e. (1.501, 0.1, 0)) the program just runs fine. Modifying the resolution, adding sources, or geometry does not help either. I have traced it down until the mp._compute_fragment_stats function call, but could not continue finding the bug.

**Comment by ChristopherHogan** [comment]
Thanks for the minimal reproducer. That really helps speed up debugging. Fixed by #737.
