### ISSUE TITLE
improve performance of writing HDF5 files in parallel simulations 

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#738]
A previous [post from the mailing list](https://www.mail-archive.com/meep-discuss@ab-initio.mit.edu/msg02230.html) by @stevengj, reproduced below, described an approach to improve the performance of [`h5file::write`](https://github.com/NanoComp/meep/blob/master/src/h5file.cpp#L706-L730) which has yet to be implemented. 

```
I believe the correct code in h5file::write(const char *dataname, const char *data) should be:

  if (IF_EXCLUSIVE(am_master(), 1)) {
    hid_t file_id = HID(get_id()), type_id, data_id, space_id;

    CHECK(file_id >= 0, "error opening HDF5 output file");

    remove_data(dataname); // HDF5 gives error if we H5Dcreate existing dataset

    type_id = H5Tcopy(H5T_C_S1);;
    H5Tset_size(type_id, strlen(data) + 1);
    space_id = H5Screate(H5S_SCALAR);

    data_id = H5Dcreate(file_id, dataname, type_id, space_id, H5P_DEFAULT);
    if (am_master())
      H5Dwrite(data_id, type_id, H5S_ALL, H5S_ALL, H5P_DEFAULT, data);

    H5Sclose(space_id);
    H5Tclose(type_id);
    H5Dclose(data_id);
  }

The first am_master() check is only for non-parallel HDF5 versions.  The second am_master check is because only one process needs to write the data, even for parallel HDF5.  (The dataset by default is opened in independent-access mode.)

Can you confirm that the test passes on your machine with this modification?

Steven

PS. Reading the PHDF5 documentation again, I notice that we also really should be calling H5Pset_dxpl_mpio to do collective I/O for the field datasets, for better performance.  Another thing for the TODO list...
```

**Comment by RobinD42** [comment]
Unless I'm missing something, it looks like the code above (plus an additional change mentioned in  a reply to the message on the mailing list) has already been applied to the source.

**Comment by stevengj** [comment]
(We aren't calling `H5Pset_dxpl_mpio` yet.  Not sure if this actually improves things, however.)

**Comment by RobinD42** [comment]
https://github.com/NanoComp/meep/pull/1285/files#diff-9799130269c0345f8b6f8287b1cdb810

**Comment by RobinD42** [comment]
https://github.com/NanoComp/meep/commit/559b85b02c19c7b9163fa40dd2fe51e29b64e2a6

**Comment by stevengj** [comment]
Reviewing the code, it looks like we call `H5Dwrite` independently on different processes — that is, it is not necessarily called from all processes the same number of times.   So I don't think we can use `H5FD_MPIO_COLLECTIVE` and hence there is no need to call `H5Pset_dxpl_mpio`.
