### ISSUE TITLE
Cannot convert h5 to png "h5topng error: invalid colormap file"

### ISSUE THREAD

**Issue by wenzao** [NanoComp/meep#739]
I am following this [tutorial](https://meep.readthedocs.io/en/latest/Python_Tutorials/Basics/#a-90-bend) and I'm having trouble generating PNG files from the h5 file. 
```
$ h5ls ez.h5
ez                       Dataset {160, 160, 333/Inf}
$ h5topng -t 0:332 -R -Zc dkbluered -a yarg -A eps-000000.00.h5 ez.h5
h5topng error: invalid colormap file
```
Where is this colormap file? What is `-Zc dkbluered -a yarg -A eps-000000.00.h5` anyway? I have read the h5 file as a 3-D array, is there a way to convert it to images or a gif using Pillow or something else?

**Comment by ChristopherHogan** [comment]
I assume you are using the conda package? I just updated the `h5utils` package an hour ago. Can you try `conda update -c chogan h5utils`. The new version should work.

**Comment by wenzao** [comment]
Thanks! It works now after the update. The version number is still the same only the conda channel has changed. 
```
  h5utils            conda-forge::h5utils-1.13.1-nompi_hfd~ --> chogan::h5utils-1.13.1-nompi_h04274fc_101
```
But still, is there any explanation what does `-Zc dkbluered -a yarg -A eps-000000.00.h5` do?

**Comment by ChristopherHogan** [comment]
I don't know the details, but they can probably be found in `man h5topng` or `h5topng --help`.

**Comment by parimalsah04** [comment]
Dear Sir
When I run:
h5topng holey-wvg-cavity-eps-000000.00.h5
I am getting the following error:
h5topng error: invalid colormap file

Please help me to solve this error.

**Comment by fr0ger** [comment]
This is not a big problem for beginners. It is just h5topng does not work. You can still use data processing software to make animations.
