### ISSUE TITLE
How to define the transmission direction of the source ?

### ISSUE THREAD

**Issue by sjtuhyj** [NanoComp/meep#750]
I want to let the source transmit only in one specific direction( e.g. 45 degree). How can I achieve this?
Thank you very much.

Hou

**Comment by oskooi** [comment]
There are two different approaches for generating an oblique planewave in homogeneous media:
1. using the amplitude function `amp_func` as described in this [FAQ](https://meep.readthedocs.io/en/latest/FAQ/#how-do-i-create-an-oblique-planewave-source) which includes links to several tutorials and examples
2. using the [eigenmode source](https://meep.readthedocs.io/en/latest/Python_User_Interface/#eigenmodesource) as demonstrated in #751 which will soon be added to the [documentation](https://meep.readthedocs.io/en/latest/Python_Tutorials/Eigenmode_Source/)
