### ISSUE TITLE
On cygwin, make meep got multi "definition of some " error, and make stop, how to fix it?

### ISSUE THREAD

**Issue by genlintan** [NanoComp/meep#760]
On cywin, make meep, got "multiple definition of xxxx" errors, the patial error information as follows:
```
 /usr/local/lib/libctlgeom.a(libctlgeom_la-geom.o): In function `make_block':
/home/Genlin/libctl-4.2.0/utils/geom.c:2065: multiple definition of `make_block
meep-geom.o:geom.cpp:(.text+0xf260): first defined here
/usr/local/lib/libctlgeom.a(libctlgeom_la-geom.o): In function `make_ellipsoid'
/home/Genlin/libctl-4.2.0/utils/geom.c:2082: multiple definition of `make_ellipoid'
meep-geom.o:geom.cpp:(.text+0xf380): first defined here
/usr/local/lib/libctlgeom.a(libctlgeom_la-geom.o): In function `make_prism_withcenter':
/home/Genlin/libctl-4.2.0/utils/geom.c:2702: multiple definition of `make_prismwith_center'
meep-geom.o:geom.cpp:(.text+0x1dea0): first defined here
/usr/local/lib/libctlgeom.a(libctlgeom_la-geom.o): In function `make_prism':
/home/Genlin/libctl-4.2.0/utils/geom.c:2696: multiple definition of `make_prism
meep-geom.o:geom.cpp:(.text+0x1dd60): first defined here
/usr/local/lib/libctlgeom.a(libctlgeom_la-geom.o):/home/Genlin/libctl-4.2.0/utis/geom.c:2587: multiple definition of `auto_center'
meep-geom.o:geom.cpp:(.data+0x0): first defined here
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:522: meep.exe] Error 1
make[3]: Leaving directory '/home/Genlin/meep-1.8.0_1/scheme'
make[2]: *** [Makefile:435: all] Error 2
make[2]: Leaving directory '/home/Genlin/meep-1.8.0_1/scheme'
make[1]: *** [Makefile:505: all-recursive] Error 1
make[1]: Leaving directory '/home/Genlin/meep-1.8.0_1'
make: *** [Makefile:414: all] Error 2
```
I removed /home/genlin/libctl-4.2-0, re-cofigure meep, and re make meep, still get these errors, I do not know what is problem.
Help wanted, Thanks for your help.

**Comment by ChristopherHogan** [comment]
It looks like you're trying to link with the static `libctlgeom.a`. Make sure you compile libctl with `--enable-shared` so that you get a dynamic library `libctlgeom.so`.

**Comment by genlintan** [comment]
Thanks for your reply.
I made  dynamical library of libctl, but still got the same errors (multiple definition).
Any further suggestions?
Thanks

**Comment by ChristopherHogan** [comment]
Do you want to use the python or scheme interface?

**Comment by stevengj** [comment]
This may be a consequence of merging libctlgeom into libmeep.  It consequence, the Scheme interface should really import `geom.c` into its own namespace, or define things statically.

**Comment by genlintan** [comment]
How to use Scheme interface or define thing statically to solve this problem, Please give the details.
Thanks

**Comment by stevengj** [comment]
Try passing `--without-scheme` to the Meep `configure` script to disable the Scheme interface and only build Python.

**Comment by genlintan** [comment]
I use ./configure --without-scheme, 
but got error : 
c++ compiler cannot create executables
see config.log for motr details

**Comment by genlintan** [comment]
Sorry, ignore above comment(by accident)
./configure --without-scheme 
 got error is as follows:
checking for libctl dir... /usr/local/share/libctl
checking for gen-ctl-io... gen-ctl-io
checking for ctl_get_vector3 in -lctl... yes
checking ctl.h usability... no
checking ctl.h presence... no
checking for ctl.h... no
checking for alternate ctl.h location...
configure: error: Couldn't find the ctl.h header file for libctl.
**********
In fact, ctl.h  is  in /usr/local/include/ctl.h
previous configure  could find it.
How to fix it?

**Comment by stevengj** [comment]
See the Installation Paths section of the manual to tell the configure script where to find ctl.h etcetera.

**Comment by lxuechao** [comment]
请问您解决了这个问题吗？
我也有同样的问题
