### ISSUE TITLE
pw-source.ctl

### ISSUE THREAD

**Issue by sjtuhyj** [NanoComp/meep#762]
Hello, I find the example of pw-source propagating at a 45-degree angle in vacuum. But how to change it to propagate in materials with n != 1. Because when I change n in the example, it can't propagate at 45-degree angle.
Thanks a lot!

**Comment by stevengj** [comment]
I assume you are referring to https://github.com/NanoComp/meep/blob/master/python/examples/pw-source.py … changing the `n=1` line only changes the source, it doesn't change the material.

You have to also change the material in the simulation to correspond to that line.  For example, pass `default_material = mp.Medium(index=n)` to the `Simulation` constructor.

@oskooi, we might want to update the tutorial example to do this.
