### ISSUE TITLE
near to far field transformation with Bloch-periodic boundaries

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#763]
The [`near to far field transformation`](https://meep.readthedocs.io/en/latest/Python_User_Interface/#near-to-far-field-spectra) feature only works with [non-periodic regions](https://www.mail-archive.com/meep-discuss@ab-initio.mit.edu/msg06261.html) in free space. It would be useful to also support Bloch-periodic boundaries via the `k_point` for e.g. computing the focal length and other imaging properties of a metasurface lens directly from its far-field intensity profile. This type of calculation is also possible using [mode decomposition](https://meep.readthedocs.io/en/latest/Python_User_Interface/#mode-decomposition) but requires additional post-processing for the user which may be cumbersome.

The challenge is implementing the periodic Green's functions. Naively, you just sum periodic copies of the Green's function but that converges very slowly. @HomerReid has implemented a much more sophisticated technique based on [Ewald summation](https://en.wikipedia.org/wiki/Ewald_summation) in [SCUFF-EM](http://homerreid.github.io/scuff-em-documentation/) which perhaps can be adapted for use in Meep. Homer's code is for 3d but we would also need the 2d case.

**Comment by stevengj** [comment]
Also commented on in #18.
