### ISSUE TITLE
Openmpi process terminated

### ISSUE THREAD

**Issue by vinneko** [NanoComp/meep#765]
Dear all,

We encountered some issues when we ran meep on openmpi. The error message is the following:

```
Currently Loaded Modulefiles:
  1) /home/chang95/own.modules

	This module will set up environment variables for anaconda3.

	This module will set up environment variables for gcc/7.2.0.

	This module will set up environment variables
	for the Message-Passing Interface environment openmpi/2.1.2.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

We contacted the manager of the cluster, and he suggested that we should report the issue on the forum. His actual quote is, 

"From the cluster environment perspective, everything is working correctly. The job starts and it is able to run. The crash is caused by the meep software itself and I would suggest to try to get support from the meep community". 

We can share the python code and the execute bash code if necessary. Any help would be greatly appreciated. 

Thank you so much!

**Comment by henrikschulz** [comment]
Well, our cluster nodes have 256 GB of memory. I don´t know the example, but we will monitor the memory usage first. Thanks @ChristopherHogan for this hint!

**Comment by henrikschulz** [comment]
We didn´t build meep from source. We just installed the conda package.

**Comment by vinneko** [comment]
The grid size of this particular run was 2706 x 2706 x 564, and we used 16 cores to run the procedure. I suppose each core requires at least ~ 2G (please correct me if I'm wrong).

**Comment by ChristopherHogan** [comment]
If memory looks good, then it may be an issue with the conda package. I'm not sure which version you installed, but most of the Meep conda packages are built with mpich. You can see the MPI version by running `conda list`. All of the MPI libraries are contained within the conda environment, so if you load the openmpi module Meep might link with the wrong MPI libraries at runtime. This could also be the case for the gcc/7.2.0 module that's loaded. I would unload gcc/7.2.0 and openmpi/2.1.2.

**Comment by henrikschulz** [comment]
![graph php](https://user-images.githubusercontent.com/7815299/54210946-b87be080-44e0-11e9-9ef4-59b1da931e77.png)

The job crashed after around 50 minutes when it allocated more memory than physically available. Maybe @vinneko can mention the grid parameters here. I just think that memory allocation of the current calculation went wrong.

**Comment by henrikschulz** [comment]
Without loading gcc/7.2.0 and openmpi/2.1.2 the behavior is the same.

**Comment by vinneko** [comment]
This time the grid size we used was 3480x1680x720. I believe this setting shouldn't need more than 200 GB.

**Comment by stevengj** [comment]
In 3d assuming you have dielectric materials and interfaces, then you need to store E, H, and D for each grid point — 9 field components — plus a 3x3 dielectric tensor (since isotropic ε becomes anisotropic when you do subpixel averaging).   This is 18 double-precision numbers (8 bytes each) per pixel.  For a 3480x1680x720 grid this comes out to 560GiB.    Potentially somewhat less if some of the chunks have simpler materials (e.g. if a chunk has only vacuum in it then it won't need to store ε). Then you add in more memory for PML regions, for Fourier-transformed fluxes, dispersive materials, and so on.

**Comment by henrikschulz** [comment]
The calculation does not crash anymore when a smaller grid (and thus less memory) is being used. Thank You all for Your hints!
