### ISSUE TITLE
Resolution of Apparent Problem #757-Tri_Rods_Tutorial

### ISSUE THREAD

**Issue by JohnWeiner** [NanoComp/meep#766]
This "issue" is really a comment on #757 which was closed (somewhat prematurely in my respectful opinion) by stevengj yesterday.  The issue I had with the MPB_tri_rods.py tutorial was the list of k-points for the triangular lattice.  The list is simply given as Γ=(0,0); M=(0,1/2); K=(-⅓,⅓) for the k-points of the irreducible Brillouin zone with little indication as to where these pairs of coordinates come from.  If one uses the irreducible BZ indicated in the book, (Fig. 10, p. 76), it is impossible to verify the coordinates of K.  The figure below shows how the problem is resolved:

![Tri_rods_IrredBZ](https://user-images.githubusercontent.com/7879288/54296150-a66b7200-45b4-11e9-85ce-cb07633df82a.png)

The first step is to rotate the two basis vectors, (b1,b2), shown in light blue on the right, by 120 deg (cow) to the two red basis vectors (b1',b2').  Their expansion in x,y Cartesian basis vectors of (b1',b2') is shown on the Fig. above.

The second, critical step is to realise that the irreducible BZ indicated in the book (Fig. 10, p.76) and indicated by diagonal lines in the Fig above, is NOT the one that is used in the tutorial!  The one used in the tutorial is indicated by the  blue-lined triangle.  The Γ,M,K points are consistent with this irreducible BZ.  This choice of irreducible BZ is far from obvious, and I respectfully submit that the tutorial could use some supplementary explanation to make it comprehensible.

**Comment by stevengj** [comment]
If you understand what an irreducible BZ is, you know that the choice is not unique. I don’t think the tutorial should try to be a textbook on Bloch theory, but it wouldn’t hurt to add a sentence on this I suppose.

**Comment by stevengj** [comment]
And your blue lined triangle is not correct. As I explained in the other issue, you are forgetting that the book uses a different choice of primitive lattice vectors.

**Comment by JohnWeiner** [comment]
With all due respect Steven, I am not forgetting anything about the choice of basis vectors.  I am well aware that the basis vectors in the Appendix B are not the same as those used in the tutorial and pointed out the difference in an earlier comment. They differ in the choice of basis vector length. I am using the choice of lattice vectors (b1,b2 in the Fig. above) that is in the tutorial, and the blue-lined triangle is consistent with the coefficients that are stated (without explanation) in the tutorial as it is presently written.  The problem is with the K k-point (-⅓,⅓) as I have tried to explain a number of times in earlier comments.  The IRBZ that is cited in the book is not the one that is chosen in the tutorial that leads to the stated list of k-points.  The tutorial makes frequent references to the book, and it is natural and reasonable for one who is studying the MPB_tri_rods tutorial (and related tutorials on MPB Data Analysis) and trying to understand the choice of k-points to assume that IRBZ is the same as the one shown in the book.  It would improve the tutorial to add some supplementary explanation.

**Comment by stevengj** [comment]
No, they don't differ in the length of basis vectors — the length is the same, it is the nearest-neighbor distance.  They differ in the *angle* between the basis vectors.

It should be obvious that you made a mistake here because the blue triangle you outlined in the diagram is not an irreducible Brillouin zone.

I closed the issue because it was not an MPB issue — there is no error in the tutorial, just an error in your understanding.

**Comment by stevengj** [comment]
In particular, this is the coordinate choice that the tutorial is using:

![image](https://user-images.githubusercontent.com/2913679/54443800-c36c8600-4717-11e9-9388-b73620e688d8.png)

**Comment by stevengj** [comment]
I added this diagram to the MPB manual along with a few words of explanation.
