### ISSUE TITLE
On cygwin, make meep got error when make scheme : #error need --with-maintainer-mode to generate this file

### ISSUE THREAD

**Issue by genlintan** [NanoComp/meep#767]
meep-1.8.0.tar.gz missing configure, and src/sphere-quade.h, I used autoconfig generate a configure, and got sphere-quade.h from your source(tar.gz) release.
configure is OK, make : libctl multipe definition erro disapealred. finally fail and stop at make scheme, The error infomation is as follows: 
```
make[2]: Entering directory '/home/Genlin/meep-1.8.0/scheme'
gen-ctl-io --cxx --header -o ctl-io.h meep.scm /usr/local/share/libctl
cp -f /usr/local/share/libctl/base/main.c main.cpp
cp -f /usr/local/share/libctl/utils/geom.c geom.cpp
gen-ctl-io --cxx --code -o ctl-io.cpp meep.scm /usr/local/share/libctl
gen-ctl-io --cxx --swig -o ctl-io.i meep.scm /usr/local/share/libctl
(echo "// AUTOMATICALLY GENERATED -- DO NOT EDIT"; perl -pe 's/^ *class +([A-Za-z_0-9:]*)( *| *:[^{]*){.*$/%rename(meep_\1) meep::\1;/' ../src/meep.hpp ../src/meep/vec.hpp ../src/meep/mympi.hpp | grep "%rename" | sort -u; echo; grep -hv typedef ../src/meep.hpp ../src/meep/vec.hpp ../src/meep/mympi.hpp | perl -pe 's/(inline|const|extern|static) +//g' | perl -pe 's/^[A-Za-z_0-9:<>]+[* ]+([A-Za-z_0-9:]*) *\(.*$/%rename(meep_\1) meep::\1;/' | grep "%rename" | sort -u; ) > meep_renames.i
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/^ *class +([A-Za-z_0-9:]*)( *| *:[^{]*){ <-- HERE .*$/ at -e line 1.
(echo "// AUTOMATICALLY GENERATED -- DO NOT EDIT"; for f in ../src/meep.hpp ../src/meep/vec.hpp ../src/meep/mympi.hpp; do egrep "^enum" $f | perl -pe 's/enum +([A-Za-z_0-9:]+).*$/\1/g' | while read enum; do cat $f | tr -d '\n' | perl -pe 's/.*enum +'${enum}' *{([^}]*)}.*/\1/g' | perl -pe 's/= *[0-9]+//g' |tr -d ' \t' | tr ',' '\n' | perl -pe 's/^(.*)$/'"%rename(meep_${enum}_\1) meep::\1;/g"; echo; done; done;) > meep_enum_renames.i
(echo "// AUTOMATICALLY GENERATED -- DO NOT EDIT"; grep -h friend ../src/meep.hpp ../src/meep/vec.hpp ../src/meep/mympi.hpp | perl -pe 's/^ *friend +[A-Za-z_0-9:<>]+[* ]+([A-Za-z_0-9:]*) *\(.*$/%ignore \1;/' | grep "%ignore" | sort -u;) > meep_swig_bug_workaround.i
(perl -pe 's/%rename\(([A-Za-z0-9_]*)\) *([A-Za-z0-9:_]*);$/(define \2 (\1))/' meep_enum_renames.i | perl -pe 's/[A-Za-z0-9:_]*:://g' | perl -pe 's/_/-/g' | perl -pe 's,//,;,'; echo "(define Centered Dielectric)") > meep-enums.scm
echo "#error need --with-maintainer-mode to generate this file" 1>&2
#error need --with-maintainer-mode to generate this file
exit 1
make[2]: *** [Makefile:915: meep_wrap.cxx] Error 1
make[2]: Leaving directory '/home/Genlin/meep-1.8.0/scheme'
make[1]: *** [Makefile:506: all-recursive] Error 1
make[1]: Leaving directory '/home/Genlin/meep-1.8.0'
make: *** [Makefile:415: all] Error 2
```
How to fix it?

**Comment by ChristopherHogan** [comment]
Add the flag `--enable-maintainer-mode` when running `./configure`. 

> meep-1.8.0.tar.gz missing configure, and src/sphere-quade.h, I used autoconfig generate a configure, and got sphere-quade.h from your source(tar.gz) release.

I just checked, and both`configure` and `sphere-quad.h` are contained in `meep-1.8.0.tar.gz`.

```sh
$ wget https://github.com/NanoComp/meep/releases/download/v1.8.0/meep-1.8.0.tar.gz
$ tar xf meep-1.8.0.tar.gz
$ cd meep-1.8.0
$ ls | grep configure
configure
configure.ac
$ ls src/ | grep shere
sphere-quad.cpp
sphere-quad.h
```
Maybe you ran `make distclean` at some point, which would have deleted them.

**Comment by genlintan** [comment]
I re-download meep-1.8.0.tar.gz ( use wget) and configure, but get following error:
make  all-recursive
make[1]: Entering directory '/home/Genlin/meep-1.8.0'
Making all in src
make[2]: Entering directory '/home/Genlin/meep-1.8.0/src'
make  all-am
make[3]: Entering directory '/home/Genlin/meep-1.8.0/src'
  CXX      sphere-quad.o
  CXXLD    sphere_quad.exe
  CXX      array_slice.lo
In file included from /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/include/c++/x86_64-pc-cygwin/bits/gthr.h:148:0,
                 from /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/include/c++/ext/atomicity.h:35,
                 from /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/include/c++/bits/ios_base.h:39,
                 from /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/include/c++/ios:42,
                 from /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/include/c++/istream:38,
                 from /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/include/c++/sstream:38,
                 from /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/include/c++/complex:45,
                 from meep/vec.hpp:22,
                 from meep.hpp:24,
                 from meep_internals.hpp:19,
                 from array_slice.cpp:27:
/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/include/c++/x86_64-pc-cygwin/bits/gthr-default.h: In function ‘int __gthread_mutex_lock(__pthread_mutex_t**)’:
/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/include/c++/x86_64-pc-cygwin/bits/gthr-default.h:748:21: error: ‘mutex_lock’ was not declared in this scope
     return __gthrw_(pthread_mutex_lock) (__mutex);
                     ^
/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/include/c++/x86_64-pc-cygwin/bits/gthr-default.h:748:21: note: suggested alternative: ‘mutex_t’
/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/include/c++/x86_64-pc-cygwin/bits/gthr-default.h: In function ‘int __gthread_mutex_unlock(__pthread_mutex_t**)’:
/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/include/c++/x86_64-pc-cygwin/bits/gthr-default.h:778:21: error: ‘mutex_unlock’ was not declared in this scope
     return __gthrw_(pthread_mutex_unlock) (__mutex);
                     ^
/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/include/c++/x86_64-pc-cygwin/bits/gthr-default.h:778:21: note: suggested alternative: ‘putc_unlocked’
make[3]: *** [Makefile:610: array_slice.lo] Error 1
make[3]: Leaving directory '/home/Genlin/meep-1.8.0/src'
make[2]: *** [Makefile:456: all] Error 2
make[2]: Leaving directory '/home/Genlin/meep-1.8.0/src'
make[1]: *** [Makefile:505: all-recursive] Error 1
make[1]: Leaving directory '/home/Genlin/meep-1.8.0'
make: *** [Makefile:414: all] Error 2
-------------------
How to fix it?

**Comment by genlintan** [comment]
I re-install gcc, above error disappeard.
The problems are:
(1) configure is OK, but make is fail, libctl has mutilple definition (when compile scheme)
(2) change to configure --without-scheme, configure got fail : can not find ctl.h.
     configule has found /usr/local/share/libctl, but could not find ctl.h
     I find at /usr/include/CTL directory, there are all relevant ctlxxx x.h, but no ctl.h.
     I find ~/libctl-1.4.0/src/ctl.h, and I send this ctl.h to /usr/include/CTL, but configure could not find ctl.h still. I suspext it do not recognize CTL, I use ctl directory synble link to CTL. the erro is there still.
I suspect --without-scheme did not avoid scheme, because libctl use scheme as well.
Do you know anybidy port meep to cygwin system and got success?

Thanks for youe help.

**Comment by stevengj** [comment]
See the *Installation Paths* section of the manual to tell the configure script where to find ctl.h etcetera.
