### ISSUE TITLE
python2 compatibility of MPB tests?

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#772]
@ChristopherHogan, I notice that several of the MPB examples and tests have [lines like](https://github.com/NanoComp/meep/blob/47204b5365c65d92d39362df4a61ee186205e754/python/tests/mpb.py#L536) `mp.Vector3(-1 / 3, 1 / 3)`.

In Python 2, however, isn't this wrong because it does truncated integer division?  It seems like all of these tests and examples should use `mp.Vector3(-1./3, 1./3)` and similar.

(It surprises me that the MPB tests pass in Python 2.)

**Comment by ChristopherHogan** [comment]
The statement `from __future__ import division` makes the Python 2 division operator behave like Python 3's. It looks like all the relevant files contain that import.

**Comment by stevengj** [comment]
Ah, good. In the manual’s examples we probably don’t want to assume that, however, since people may cut and paste snippets from the manual.
