### ISSUE TITLE
ERROR in scheme 

### ISSUE THREAD

**Issue by Hoochan** [NanoComp/meep#773]
After running a simulation in scheme, this happened:
ERROR: In procedure %run-finalizers:
ERROR: In procedure delete-meep-volume: Wrong type argument in position 1: #<finalized smob 55e039bf7640>
      Why?

**Comment by ChristopherHogan** [comment]
This was fixed in Meep 1.6. Prior to 1.6, this error was caused by using a version of Guile >= 2.0.12. What version of Meep are you running (or how did you install it)?

**Comment by Hoochan** [comment]
The version of Meep installed now is Meep 1.3, and the version of Guile is 2.0.13. So it means that I need to update Meep or use the older version of Guile?

**Comment by ChristopherHogan** [comment]
Correct. Either use Meep >= 1.6, or Guile < 2.0.12.

**Comment by Hoochan** [comment]
I used Precompiled packages of Meep version 1.3 to install, Guile 2.0.13 was installed and used by default. And I failed to eliminate the error even the lower version of Guile was installed. Are the calculation results right if the error is not eliminated?

**Comment by ChristopherHogan** [comment]
Depending on the package manager you're using, the precompiled meep is likely tied to a certain version of Guile, so to downgrade Guile you would need to compile Meep yourself.

Anyway, the error only happens at the end of a simulation when trying to free memory, so it shouldn't interfere with results. See this [comment](https://github.com/NanoComp/meep/issues/35#issuecomment-334642158).
