### ISSUE TITLE
On cygwin, make meep met "swig : command not found" at scheme

### ISSUE THREAD

**Issue by genlintan** [NanoComp/meep#778]
The error is as follows:
***************
make[2]: Entering directory '/home/Genlin/meep-1.8.0_2/scheme'
gen-ctl-io --cxx --header -o ctl-io.h meep.scm /usr/local/share/libctl
;;; note: source file /usr/local/share/libctl/base/include.scm
;;;       newer than compiled /home/Genlin/.cache/guile/ccache/2.2-LE-8-3.A/usr/local/share/libctl/base/include.scm.go
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /usr/local/share/libctl/base/include.scm
;;; compiled /home/Genlin/.cache/guile/ccache/2.2-LE-8-3.A/usr/local/share/libctl/base/include.scm.go
cp -f /usr/local/share/libctl/base/main.c main.cpp
cp -f /usr/local/share/libctl/utils/geom.c geom.cpp
gen-ctl-io --cxx --code -o ctl-io.cpp meep.scm /usr/local/share/libctl
gen-ctl-io --cxx --swig -o ctl-io.i meep.scm /usr/local/share/libctl
swig -I../src -c++ -guile -o meep_wrap.cxx ./meep.i
make[2]: swig: Command not found
make[2]: *** [Makefile:910: meep_wrap.cxx] Error 127
make[2]: Leaving directory '/home/Genlin/meep-1.8.0_2/scheme'
make[1]: *** [Makefile:506: all-recursive] Error 1
make[1]: Leaving directory '/home/Genlin/meep-1.8.0_2'
make: *** [Makefile:415: all] Error 2
****************
How to fix it?

**Comment by ChristopherHogan** [comment]
You need to install SWIG in your cygwin setup. I would really recommend installing Ubuntu through the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) instead of using Cygwin. That way, the build script in the documentation will just work.

**Comment by stevengj** [comment]
Or you can download the .tar.gz release file, which doesn’t require swig (or autotools).
