### ISSUE TITLE
On Cygwin, mpb installed success, meep make got error: ctl mutiple definition

### ISSUE THREAD

**Issue by genlintan** [NanoComp/meep#798]
I think we should not give up to install meep on cygwin, maybe this is final one issue.
When make meep, got errors are as follows:
```
make[3]: Entering directory '/home/Genlin/meep-1.8.0_2/scheme'
  CXXLD    meep.exe
/usr/local/lib/libctlgeom.a(libctlgeom_la-geom.o): In function `geom_fix_lattice0':
/home/Genlin/libctl-4.2.0/utils/geom.c:195: multiple definition of `geom_fix_lattice0'
meep-geom.o:geom.cpp:(.text+0x3290): first defined here
/usr/local/lib/libctlgeom.a(libctlgeom_la-geom.o): In function `geom_fix_lattice':
/home/Genlin/libctl-4.2.0/utils/geom.c:210: multiple definition of `geom_fix_lattice'
meep-geom.o:geom.cpp:(.text+0x3740): first defined here
/usr/local/lib/libctlgeom.a(libctlgeom_la-geom.o): In function `geom_cartesian_lattice0':
/home/Genlin/libctl-4.2.0/utils/geom.c:215: multiple definition of `geom_cartesian_lattice0'
meep-geom.o:geom.cpp:(.text+0x3c10): first defined here
/usr/local/lib/libctlgeom.a(libctlgeom_la-geom.o): In function `geom_cartesian_lattice0':
/home/Genlin/libctl-4.2.0/utils/geom.c:215: multiple definition of `geom_cartesian_lattice'
meep-geom.o:geom.cpp:(.text+0x4110): first defined here

/usr/local/lib/libctlgeom.a(libctlgeom_la-geom.o): In function `make_prism_with_center':
/home/Genlin/libctl-4.2.0/utils/geom.c:2702: multiple definition of `make_prism_with_center'
meep-geom.o:geom.cpp:(.text+0x1dea0): first defined here
/usr/local/lib/libctlgeom.a(libctlgeom_la-geom.o): In function `make_prism':
/home/Genlin/libctl-4.2.0/utils/geom.c:2696: multiple definition of `make_prism'
meep-geom.o:geom.cpp:(.text+0x1dd60): first defined here
/usr/local/lib/libctlgeom.a(libctlgeom_la-geom.o):/home/Genlin/libctl-4.2.0/utils/geom.c:2587: multiple definition of `auto_center'
meep-geom.o:geom.cpp:(.data+0x0): first defined here
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:519: meep.exe] Error 1
make[3]: Leaving directory '/home/Genlin/meep-1.8.0_2/scheme'
make[2]: *** [Makefile:432: all] Error 2
make[2]: Leaving directory '/home/Genlin/meep-1.8.0_2/scheme'
make[1]: *** [Makefile:506: all-recursive] Error 1
make[1]: Leaving directory '/home/Genlin/meep-1.8.0_2'
make: *** [Makefile:415: all] Error 2
```
How to fix it from modify meep a little maybe
Thank you for your help

**Comment by ChristopherHogan** [comment]
When building `libctl`, `mpb`, and `meep`, pass the `-no-undefined` flag to `make`. Without this flag, gcc will not create shared libraries and will try to use static linkage.

**Comment by genlintan** [comment]
Thanks for your reply. After add -no-undefined, ctl multiple definition error disapeared. scheme compile passed.
But now there is a new problem: no rule to make target 'meep-python,cxx' needed by all stop.
****************
make[2]: Leaving directory '/home/Genlin/meep-1.8.0_2/libpympb'
Making all in python
make[2]: Entering directory '/home/Genlin/meep-1.8.0_2/python'
make[2]: *** No rule to make target 'meep-python.cxx', needed by 'all'.  Stop.
make[2]: Leaving directory '/home/Genlin/meep-1.8.0_2/python'
make[1]: *** [Makefile:506: all-recursive] Error 1
make[1]: Leaving directory '/home/Genlin/meep-1.8.0_2'
make: *** [Makefile:415: all] Error 2
**********************
How to fix it.

**Comment by ChristopherHogan** [comment]
If you want to work in Scheme (Guile) then you don't need the Python interface. If you want to work in Python though I can't help any further. I was unable to get pymeep running on Cygwin. I would suggest the Windows Subsystem for Linux. You might try the [conda package](https://meep.readthedocs.io/en/latest/Installation/#conda-packages). It doesn't require building anything from source.

**Comment by genlintan** [comment]
Thank you for your help. If I I do not use python and only use Scheme, then how to do, add -no-python, for make, isn't OK?
BTW, I browserd conda package, and found WSL(Ubuntu) has meep, and mpb, and I have install them success. Thinks.

**Comment by genlintan** [comment]
Could the Conda pakage works on cygwin?
I tried download conda and install, got the error:

 bash miniconda.sh -b -p '/usr/local'
PREFIX=/home/Genlin/miniconda3
installing: python-3.7.1-h0371630_7 ...
miniconda.sh: line 370: /home/Genlin/miniconda3/pkgs/python-3.7.1-h0371630_7/bin/python: cannot execute binary file: Exec format error
How to fix it?

**Comment by stevengj** [comment]
Please don't file duplicates for the same issue.  Cygwin is currently unsupported.
