### ISSUE TITLE
On WSL(Ubuntu), run python straight-waveguide.py,got error: no module named meep

### ISSUE THREAD

**Issue by genlintan** [NanoComp/meep#803]
I install precompiled binary meep and mpb on WSL(Ubuntu), then tried an example
python straight-waveguide.py
Got th error:
gltan@Genlin2015-PC:~/meep-1.8.0/python/examples$ python straight-waveguide.py
Traceback (most recent call last):
  File "straight-waveguide.py", line 6, in <module>
    import meep as mp
ImportError: No module named meep

But we have /usr/bin/meep, /usr/bin/mpb, /usr/bin/python,  on my WSL
How to fix it?

**Comment by ChristopherHogan** [comment]
When you say "precompiled binary" do you mean the conda package or the package installed with "apt-get"?

**Comment by stevengj** [comment]
The Ubuntu Meep package doesn't include Python.
