### ISSUE TITLE
Bug on transmission when cell_size ends in 0.05 dimensionless units?

### ISSUE THREAD

**Issue by azdagkas** [NanoComp/meep#809]
In the  example bellow you can see that the transmission spectra change significantly when the cell_size in the x dimension ends in 0.05 (dimensinless units).
Simulations with Comsol and Lumerical give the correct result which meep gives only when sx does not end in 0.05.

``` python
import meep as mp
import meep.materials as mp_mat
import numpy as np
import matplotlib.pyplot as plt

def plot_TRA(freqs, t_flux, r_flux, input_flux, wv=True):
    reflectance = -r_flux/input_flux
    transmitance = t_flux/input_flux
    absorptance = 1-reflectance-transmitance
    c = 299792458
    plt.figure()
    if wv:
        plt.plot(1e-6/freqs, transmitance, label='T')
        plt.plot(1e-6/freqs, reflectance, label='R')
        plt.plot(1e-6/freqs, absorptance, label='A')
        plt.xlabel(r'$\lambda$ (m)')
    else:
        plt.plot(freqs*c/1e-6*1e-12, transmitance, label='T')
        plt.plot(freqs*c/1e-6*1e-12, reflectance, label='R')
        plt.plot(freqs*c/1e-6*1e-12, absorptance, label='A')
        plt.xlabel(r'$\nu$ (THz)')
    plt.ticklabel_format(style='sci', scilimits=(0, 0))
    plt.legend()
    plt.tight_layout()


# =============================================================================
# === script ==================================================================
# =============================================================================
resolution = 100  # pixels/μm
sim_time = 100  # the simulation time
decay_ratio = 1e-6  # the decay ratio for the simulation to stop

Au = mp_mat.Au
#Si3N4 = mp_mat.Si3N4_VISNIR  # do not use this in version 1.7, it is wrong

um_scale = 1.0/1.23984193
mp_mat.Si3N4_VISNIR_susc = [mp.LorentzianSusceptibility(frequency=1/(0.13967*um_scale), gamma=0, sigma=2.8939)]
Si3N4_VISNIR = mp_mat.Si3N4_VISNIR

mat_grating = Au
mat_sub = Si3N4_VISNIR

'''Repropduction of the problem'''
'''sx must not end in 0.05.
1) Use sx = dpml+dair+dslab+dair2+dpml
   Use sx = dpml+dair+hg+dslab+dair2+dpml
   Use sx = dpml+dair+2*hg+dslab+dair2+dpml
   The second does not agree with the rest.
2) Change hg to hg = 0.1
   repeat:
   Use sx = dpml+dair+dslab+dair2+dpml
   Use sx = dpml+dair+hg+dslab+dair2+dpml
   Use sx = dpml+dair+2*hg+dslab+dair2+dpml
   All agree.
3)  Use:
    dpml = 0.2
    dair = 1.0
    dair2 = 0.6
    dslab = 0.1
    hg = 0.05
    sx = dpml+dair+hg+dslab+dair2+dpml
    change dair2 to 0.59 and 0.61.
    They agree but they disagree with dair2 = 0.6.
Conclussion: sx must not end in 0.05.
Simulations with Comsol and Lumerical show that the above simulation
converges to the correct when sx does not end to 0.05.'''
dpml = 0.2
dair = 1.0
dair2 = 0.6
dslab = 0.1
hg = 0.05
sx = dpml+dair+hg+dslab+dair2+dpml  # must not end in 0.05, gives different spectra
'''################################'''
uc = 0.5
wg = 0.4
sy = uc
cell_size = mp.Vector3(sx, sy, 0)

pml_layers = [mp.PML(thickness=dpml,direction=mp.X,side=mp.High),
              mp.PML(thickness=dpml,direction=mp.X,side=mp.Low)]

wvl_min = 0.60
wvl_max = 1.0
fmin = 1/wvl_max
fmax = 1/wvl_min
fcen = 0.5*(fmax+fmin)
df = fmax-fmin
nfreq = 200

symmetries = [mp.Mirror(mp.Y, phase=-1)]
src_cmpt = mp.Hz
k_point = mp.Vector3(0, 0, 0)

src_pt = mp.Vector3(-0.5*sx+dpml+0.2*dair, 0, 0)
sources = [mp.Source(mp.GaussianSource(fcen, fwidth=df),
                     component=src_cmpt,
                     center=src_pt,
                     size=mp.Vector3(0, sy, 0))]

sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size,
                    boundary_layers=pml_layers,
                    symmetries=symmetries,
                    k_point=k_point,
                    sources=sources)

refl_pt = mp.Vector3(-0.5*sx+dpml+0.5*dair, 0, 0)
refl_flux = sim.add_flux(fcen, df, nfreq, mp.FluxRegion(center=refl_pt, size=mp.Vector3(0,sy,0)))

#sim.run(until=sim_time)
sim.run(until_after_sources=mp.stop_when_fields_decayed(20, src_cmpt, mp.Vector3(), decay_ratio))

input_flux = np.array(mp.get_fluxes(refl_flux))
input_flux_data = sim.get_flux_data(refl_flux)

sim.reset_meep()

# =========================================================================
# run with the structure
# =========================================================================
geometry = [mp.Block(mp.Vector3(dslab, mp.inf, mp.inf), center=mp.Vector3(-0.5*sx+dpml+dair+hg+0.5*dslab,0,0), material=mat_sub),
            mp.Block(mp.Vector3(hg, wg, mp.inf), center=mp.Vector3(-0.5*sx+dpml+dair+0.5*hg,0,0), material=mat_grating)]

sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size,
                    geometry=geometry,
                    symmetries=symmetries,
                    boundary_layers=pml_layers,
                    k_point=k_point,
                    sources=sources)

refl_flux = sim.add_flux(fcen, df, nfreq, mp.FluxRegion(center=refl_pt, size=mp.Vector3(0,sy,0)))
sim.load_minus_flux_data(refl_flux, input_flux_data)

tran_pt = mp.Vector3(0.5*sx-dpml-0.1*dair2, 0, 0)
tran_flux = sim.add_flux(fcen, df, nfreq, mp.FluxRegion(center=tran_pt, size=mp.Vector3(0,sy,0)))

#sim.run(until=sim_time)
sim.run(until_after_sources=mp.stop_when_fields_decayed(20, src_cmpt, mp.Vector3(), decay_ratio))


tran_fl = np.array(mp.get_fluxes(tran_flux))
refl_fl = np.array(mp.get_fluxes(refl_flux))
freqs = np.array(mp.get_flux_freqs(refl_flux))

mp.all_wait()
# === various plots ===
if mp.am_master():
    plot_TRA(freqs, tran_fl, refl_fl, input_flux, wv=True)

plt.show()

```

**Comment by ChristopherHogan** [comment]
For reference, here are the results.

### hg = 0.0
![sx-2 1](https://user-images.githubusercontent.com/14114829/55884326-80160380-5b6d-11e9-8811-0bff54762b5c.png)

### hg = 0.05
![sx-2 1500000000000004](https://user-images.githubusercontent.com/14114829/55884334-84dab780-5b6d-11e9-9fa5-b4588918757e.png)

### hg = 0.1
![sx-2 2](https://user-images.githubusercontent.com/14114829/55884344-899f6b80-5b6d-11e9-8a8e-8a005ef70a3b.png)

**Comment by oskooi** [comment]
`hg` defines not just the cell size but the thickness of your `Au` block and so different values should produce very different spectra. In fact, this is exactly what happens when I run your script using the latest master.

**hg=0**

![foo_hg0](https://user-images.githubusercontent.com/7152530/55920210-d99e2280-5bad-11e9-8804-2875e5560ada.png)

**hg=0.05**

![foo_hg0 05](https://user-images.githubusercontent.com/7152530/55920216-e0c53080-5bad-11e9-9b46-f42d8dfc39a5.png)

**hg=0.1**

![foo_hg0 1](https://user-images.githubusercontent.com/7152530/55920227-eae72f00-5bad-11e9-9b67-7ee641d5bbb0.png)

**Comment by azdagkas** [comment]
In my example I do not change the thickness of the gold. I only change the thickness of the cell in terms of hg. That was a confusing example so please do the following:
Keep the gold thickness at hg=0.05 and sx = dpml+dair+hg+dslab+dair2+dpml.
To be sure that we mitigate numerical and physics related problems use :
resolution = 300
dpml = 1.0
dair = 1.2
dair2 = 1.2
Now the spectrum looks correct.
Now change the thicknsess of the air behind the grating, dair2, and look at the spectrum. 
dair2 = 1.20 correct
dair2 = 1.21 correct
dair2 = 1.22 wrong
dair2 = 1.23 correct
dair2 = 1.24 correct
dair2 = 1.25 wrong
Correct means that it converges to what Comsol and Lumerical converge.

The correct spectrum for dair2 = 1.24
![correct](https://user-images.githubusercontent.com/49478566/55943621-d141f800-5c3e-11e9-9e03-3157e9e9c502.png)

The wrong spectrum for dair2 = 1.25
![wrong](https://user-images.githubusercontent.com/49478566/55943655-e6b72200-5c3e-11e9-9854-f70c1813bec6.png)

**Comment by azdagkas** [comment]
I have run the code posted in the begining with increasing resolution and I have seen that it is kinda 
converging to the correct spectrum. According to some papers, DOI:10.1364/OE.23.010481, FDTD needs a mesh with 0.25nm
resolution to properly resolve the plasmon resonanes in gold. I run it with resolution= 300(3.3nm), 1000(1nm), 2000(0.5nm).
It seems better with better resolution but it is still a bit different.
I suspect that some cell sizes create a mesh in positions that happen to describe better
the problem and hence reduce the error and that was the reason of different spectra with 
very slight changes of the surrounding air size.
I don't think that there is something wrong with meep.
Sorry for your time.
PS It would be great to see non-uniform discretization of the mesh implemented in meep.

The result of the initially posted script with different resolutions.

resolution = 300 (3.3nm mesh)
![wrong_300](https://user-images.githubusercontent.com/49478566/55973896-61ebf880-5c7e-11e9-91fe-2f1c5785fea4.png)

resolution = 1000 (1nm mesh)
![wrong_1000](https://user-images.githubusercontent.com/49478566/55973902-66181600-5c7e-11e9-84d5-736bf6ef5036.png)

resolution = 2000 (2nm mesh)
![wrong_2000](https://user-images.githubusercontent.com/49478566/55973908-6a443380-5c7e-11e9-8249-1436ddb05ee7.png)
