### ISSUE TITLE
Geometric Object '+' functionality

### ISSUE THREAD

**Issue by JamesWhitehead5** [NanoComp/meep#815]
This might be a bug.

I would expect using '+' would return a new object with a displaced center and not modify the input arguments.

Example of existing functionality:
```
>>>import meep as mp
>>> geo_ob = mp.Block(mp.Vector3(1., 1., 1.))
>>> geo_ob.center
Vector3<0.0, 0.0, 0.0>
>>> print(geo_ob + mp.Vector3(0.1))
None
>>>geo_ob.center
Vector3<0.1, 0.0, 0.0>
```

Maybe remove this functionality since it is ambiguous which object (the Geometric Object or the Vector3) the '+' is modifying. The 'shift' method should be sufficient and clear.

Also, I would expect the '+' operation to commute. This 
```
>>> geo_ob = mp.Block(mp.Vector3(1., 1., 1.))
>>> print(mp.Vector3(0.1) + geo_ob)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/anaconda2/envs/mp/lib/python3.6/site-packages/meep/geom.py", line 37, in __add__
    x = self.x + other.x
AttributeError: 'Block' object has no attribute 'x'

```

**Comment by stevengj** [comment]
I agree.  `object += vector` should be in-place, and `+` should be out-of-place
