### ISSUE TITLE
module 'meep' has no attribute 'EnergyRegion'

### ISSUE THREAD

**Issue by tsehso** [NanoComp/meep#816]
Hello,

I encountered the below error when I tried to use EnergyRegion to define where to calculate the energy density. 

AttributeError: module 'meep' has no attribute 'EnergyRegion'

Besides, not only the above command, it seems like add_energy, get_electric_energy, load_minus_energy, and get_energy_freqs also having the same issue. (These commands are highlighted in my editor)

Does anyone meet this issue and successfully solve it?

Thank you very much.

**Comment by ChristopherHogan** [comment]
The `EnergyRegion` features were added on March 8, 2019. You are likely using the 1.8.0 release (or earlier), which came out on February 13, 2019. To access the `EnergyRegion` features, you either need to build the latest master branch from source, or install the [nightly build](https://meep.readthedocs.io/en/latest/Installation/#nightly-builds) of the conda package.
