### ISSUE TITLE
discrepancy in array size for get_array, get_efield_z, and get_epsilon when using k_point

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#818]
As a follow up to @stevengj's recent comment on the [mailing list](https://www.mail-archive.com/meep-discuss@ab-initio.mit.edu/msg06313.html), the example below demonstrates that there is a discrepancy in the array sizes for `get_array` and `get_efield_z`/`get_epsilon` when Bloch-periodic boundaries (`k_point`) and `symmetries` are used. The 2d example outputs the array sizes for the E<sub>z</sub> and permittivity arrays over the entire cell for two cases involving with/out `k_point`.

```py
import meep as mp
import numpy as np

resolution = 20

n = 3.4
w = 1
r = 1
pad = 4
dpml = 2

sxy = 2*(r+w+pad+dpml)
cell = mp.Vector3(sxy,sxy)

c1 = mp.Cylinder(radius=r+w, material=mp.Medium(index=n))
c2 = mp.Cylinder(radius=r)

fcen = 0.118
df = 0.08

# pulsed source                                                                                                                                                  
src = mp.Source(mp.GaussianSource(fcen,fwidth=df), mp.Ez, mp.Vector3(r+0.1))

sim = mp.Simulation(cell_size=cell,
                    geometry=[c1,c2],
                    sources=[src],
                    resolution=resolution,
                    symmetries=[mp.Mirror(mp.Y)],
                    boundary_layers=[mp.PML(dpml)])

sim.init_sim()

ez1 = sim.get_array(center=mp.Vector3(),size=cell,component=mp.Ez)
ez2 = sim.get_efield_z()
print('Ez [no k_point]:     ',ez1.shape,ez2.shape)

eps1 = sim.get_array(center=mp.Vector3(),size=cell,component=mp.Dielectric)
eps2 = sim.get_epsilon()
print('epsilon [no k_point]:',eps1.shape,eps2.shape)

sim.reset_meep()

k_point = mp.Vector3(0,0,0)

sim = mp.Simulation(cell_size=cell,
                    geometry=[c1,c2],
                    sources=[src],
                    resolution=resolution,
                    k_point=k_point,
                    symmetries=[mp.Mirror(mp.Y)],
                    boundary_layers=[mp.PML(dpml)])

sim.init_sim()

ez1 = sim.get_array(center=mp.Vector3(),size=cell,component=mp.Ez)
ez2 = sim.get_efield_z()
print('Ez [k_point]:     ',ez1.shape,ez2.shape)

eps1 = sim.get_array(center=mp.Vector3(),size=cell,component=mp.Dielectric)
eps2 = sim.get_epsilon()
print('epsilon [k_point]:',eps1.shape,eps2.shape)
```

For the first case involving no `k_point`, the results are as expected (i.e., a `16 x 16` grid at a resolution of `20` pixels yields a cell of `320x320` pixels):

```
Ez [no k_point]:      (320, 320) (320, 320)
epsilon [no k_point]: (320, 320) (320, 320)
```
However, when `k_point` is used, a discrepancy appears in the array sizes for the two methods:

```
Ez [k_point]:      (322, 322) (321, 324)
epsilon [k_point]: (322, 322) (321, 324)
```
It is unclear which of the two sets of values is correct. Naively, one would have expected the array size to increase by *one* in each direction because of the "ghost" pixels (i.e., `(321, 321)`). Matters seem to be more complicated, however.

Additionally, the size of the array in the *y*-direction changes for `get_efield_z`/`get_epsilon` for `k_point` if the `symmetries` (also in *y*) is *removed*:

```
Ez [k_point]:      (322, 322) (321, 321)
epsilon [k_point]: (322, 322) (321, 321)
```

Note that the results for `get_array` (first column) are *unchanged*.

There are two separate issues that need to be addressed:
1. discrepancy between `get_array` and `get_efield_z`/`get_epsilon` when `k_point` is used (both with and without `symmetries`)
2. discrepancy among `get_efield_z`/`get_epsilon` when `symmetries` is used (only for `k_point`)

**Comment by stevengj** [comment]
Maybe look at the `_get_array_slice_dimensions` call – how is this returning something different in the two cases?

**Comment by stevengj** [comment]
Oh, `_get_array_slice_dimensions` is fine.  Ez and Dielectric are giving the same size, as is `get_eps` and get_efield_z.   The difference is that in one case you are passing `size=cell` and in the other case you are using the default `size=sim.fields.total_volume()`, and these are not the same thing in the periodic case.

**Comment by stevengj** [comment]
The `total_volume` is the *interior* volume (`fields.gv.interior()`) unioned with its Y mirror flip.   The latter is why it is longer in one direction, because the periodicity adds an extra pixel in one direction that gets mirrored.

When you  pass `size=cell`, it gets expanded by an extra pixel in each direction by the interpolation with the periodic boundary conditions.

Neither of these is "wrong", they are just slightly different methods of fetching the boundaries.

**Comment by stevengj** [comment]
The key point is that if you pass the same value for the the `size=` parameter, or use the default, it will always give you the same-size array for all components.  This is happening correctly.

However, users shouldn't generally try to predict the exact size they get out, they should rely on Meep's output — in the same way that you shouldn't try to predict exactly how Meep will discretize any given structure or input.
