### ISSUE TITLE
discrepancy in grid between integrate_field_function and get_array_metadata

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#831]
Following @stevengj's [suggestion](https://github.com/NanoComp/meep/pull/830#discussion_r276886269) in #830 of including the position vectors (in addition to the weights) in the test for `get_array_metadata`, the following script computes the integral of the position vector in a 2d cell using two different methods: (1) `integrate_field_function` and (2) `get_array_metadata`. The results are expected to be nearly *identical* but they are not which might indicate a bug in `get_array_metadata`.

```py
import meep as mp
import numpy as np

resolution = 25

cell_size = mp.Vector3(10,10)

sim = mp.Simulation(cell_size=cell_size,
                    resolution=resolution)

sim.init_sim()

def vec_norm(r):
    return r.norm()

vec_norm_integral = sim.integrate_field_function([],vec_norm)

(X,Y,Z,W) = sim.get_array_metadata()
vec_norm_grid = np.sqrt(np.power(X,2)+np.power(Y,2))
vec_norm_sum = np.sum(W*vec_norm_grid)

print(np.real(vec_norm_integral),
      vec_norm_sum,
      (np.real(vec_norm_integral)-vec_norm_sum)/np.real(vec_norm_integral))
```

Note the absence of `symmetries` and `k_point` which seemed to have been fixed in #811. Also, there are no fields involved in the integration; just the points on the grid. The output indicates a relative difference in the results of 7.6%.

```
Using MPI version 3.1, 1 processes
-----------
Initializing structure...
Working in 2D dimensions.
Computational cell is 10 x 10 x 0 with resolution 25
time for set_epsilon = 0.0929166 s
-----------
377.4640768427174 348.81022507819836 0.07591146687174317
```
The relative difference is practically unchanged when the resolution is increased.

**resolution=50**
```
380.02315375296246 351.1743652716992 0.07591323896021532
```
**resolution=100**
```
381.30854930621626 352.36201401005985 0.07591368026975552
```
This may indicate there is a slight offset in the grid used in `get_array_metadata` relative to that in `integrate_field_function` (i.e., the true grid from `LOOP_OVER_CHUNKS`).

**Comment by stevengj** [comment]
> `vec_norm_grid = np.sqrt(np.power(X,2)+np.power(Y,2))`

I thought `X` and `Y` were 1d arrays along each axis, so you need to use broadcasting to combine them into a 2d array of the right shape here?   With broadcasting:

```py
np.sqrt(X**2 + (X**2).reshape(len(X), 1))
```
or with meshgrid do
```py
X, Y = np.meshgrid(x, y)
```
first.

(I'm not a 100% sure the above code isn't tranposed — you might have to swap X and Y?   That's one of the reasons I suggested computing `X**2 + 2Y**2` or similar, to break the symmetry and make sure that both X and Y are in the correct order.)

**Comment by oskooi** [comment]
Broadcasting the 1d arrays into 2d does indeed fix the issue. The results from `integrate_field_function` and `get_array_metadata` are now identical.

```py
import numpy as np

resolution = 25

cell_size = mp.Vector3(10,10)

sim = mp.Simulation(cell_size=cell_size,
                    resolution=resolution)

sim.init_sim()

def vec_norm(r):
    return r.norm()

vec_norm_integral = sim.integrate_field_function([],vec_norm)

(X,Y,Z,W) = sim.get_array_metadata()

xm, ym = np.meshgrid(X,Y)
vec_norm_grid = np.sqrt(xm**2+ym**2)
vec_norm_sum = np.sum(W*vec_norm_grid)

print(np.real(vec_norm_integral),
      vec_norm_sum,
      (np.real(vec_norm_integral)-vec_norm_sum)/np.real(vec_norm_integral))
```
Replacing `vec_norm_grid = np.sqrt(xm**2+ym**2)` with `vec_norm_grid = np.sqrt(np.power(X,2) + np.power(Y,2).reshape(len(Y),1))` produces the same result as shown below.
```
Using MPI version 3.1, 1 processes
-----------
Initializing structure...
Working in 2D dimensions.
Computational cell is 10 x 10 x 0 with resolution 25
time for set_epsilon = 0.0950409 s
-----------
377.4640768427174 377.4640768427175 -1.5059292353400203e-16
```
Additionally, choosing an integrand which breaks the symmetry as you suggested produces identical results.

```py
import meep as mp
import numpy as np

resolution = 25

cell_size = mp.Vector3(10,10)

sim = mp.Simulation(cell_size=cell_size,
                    resolution=resolution)

sim.init_sim()

def vec_norm(r):
    return r.x**2 + 2*r.y**2

vec_norm_integral = sim.integrate_field_function([],vec_norm)

(X,Y,Z,W) = sim.get_array_metadata()

xm, ym = np.meshgrid(X,Y)
vec_norm_grid = xm**2 + 2*ym**2
vec_norm_sum = np.sum(W*vec_norm_grid)

print(np.real(vec_norm_integral),
      vec_norm_sum,
      (np.real(vec_norm_integral)-vec_norm_sum)/np.real(vec_norm_integral))
```

```
Using MPI version 3.1, 1 processes
-----------
Initializing structure...
Working in 2D dimensions.
Computational cell is 10 x 10 x 0 with resolution 25
time for set_epsilon = 0.0854402 s
-----------
2455.43955459 2455.43955459 0.0
```

There is no bug and `get_array_metadata` works as expected.
