### ISSUE TITLE
get_array_metadata produces segmentation fault for a single point

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#838]
The routine [`get_array_metadata`](https://meep.readthedocs.io/en/latest/Python_User_Interface/#array-metadata) returns coordinate arrays with *uncollapsed* empty dimensions at a single point only when the `size` parameter is *non-zero*. A `size` of `mp.Vector3()` produces a segmentation fault as demonstrated below.

```py
import meep as mp

resolution = 10

cell_size = mp.Vector3(5,5)

sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size)

sim.init_sim()

slice_vol1 = mp.Volume(center=mp.Vector3(1.651,-1.095), size=mp.Vector3(1e-15))
(x,y,z,w) = sim.get_array_metadata(vol=slice_vol1)
print(x,y)

slice_vol2 = mp.Volume(center=mp.Vector3(1.651,-1.095), size=mp.Vector3())
(x,y,z,w) = sim.get_array_metadata(vol=slice_vol2)
print(x,y)
```

**output**
```
Using MPI version 3.1, 1 processes
-----------
Initializing structure...
Working in 2D dimensions.
Computational cell is 5 x 5 x 0 with resolution 10
time for set_epsilon = 0.0138906 s
-----------
(1.6500000000000001, 1.7500000000000002) (-1.1500000000000001, -1.05)
[simpetus:04936] *** Process received signal ***
[simpetus:04936] Signal: Segmentation fault (11)
[simpetus:04936] Signal code: Address not mapped (1)
```
Note that in the first case, the *x* and *y* coordinate arrays both have dimension 2 and are thus uncollapsed. The two points &mdash; `(1.6500000000000001, 1.7500000000000002)` and `(-1.1500000000000001, -1.05)` &mdash; correspond to the nearest grid points and have a single-pixel separation which is expected.

The results for the two cases should be identical (i.e., `size` of `mp.Vector3()` is equivalent to `mp.Vector3(1e-15)`).

**Comment by oskooi** [comment]
The output of the above script using `master` shows that the 0- and 1-dimensional array slices are identical:
```
(1.6500000000000001, 1.7500000000000002) (-1.1500000000000001, -1.05)
(1.6500000000000001, 1.7500000000000002) (-1.1500000000000001, -1.05)
```
While the original segmentation fault has been fixed, the output seems incorrect because the 0-dimensional array slice should return just a single point: the closest grid point `(1.65) (-1.15)` (i.e., it collapses to the grid point which minimizes the Euclidean distance).

**Comment by stevengj** [comment]
Yes, I think so; I don't immediately see the problem, so someone probably needs to step through or insert some printf statements to see why the resulting array is not `rank = 0` (0 dimensional = 1 point).

**Comment by oskooi** [comment]
It seems the bug fix involves changing a single line in the definition of  `fields::get_array_metadata` in [`src/array_slice.cpp:719`](https://github.com/NanoComp/meep/blob/master/src/array_slice.cpp#L719):
```c++
   if (where.in_direction(d) == 0.0 && collapse_empty_dimensions) {
      xyzmin[nd] = xyzmax[nd] = where.in_direction_min(d);
      nxyz[nd] = 1;
    } else {
    ...
```
to
```c++
   if (where.in_direction(d) == 0.0) {
```
This if clause was never being executed because the parameter `collapse_empty_dimensions` is `false` due to the [Python wrapper](https://github.com/NanoComp/meep/blob/master/python/simulation.py#L1836-L1837) which is overriding the default `true` in the [C++ function header](https://github.com/NanoComp/meep/blob/master/src/meep.hpp#L1566-L1567).

Probably the correct approach is to pass `collapse_empty_dimensions=true` but this will require additional changes `get_array_metadata`.

**Comment by stevengj** [comment]
Try passing `snap=True` to `get_array_metadata`, to match what `get_array` does.

**Comment by oskooi** [comment]
```py
import meep as mp

resolution = 10

cell_size = mp.Vector3(5,5)

sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size)

sim.init_sim()

slice_vol1 = mp.Volume(center=mp.Vector3(1.651,-1.095), size=mp.Vector3(1e-15))
(x,y,z,w) = sim.get_array_metadata(vol=slice_vol1,snap=True)
print(x,y)

slice_vol2 = mp.Volume(center=mp.Vector3(1.651,-1.095), size=mp.Vector3())
(x,y,z,w) = sim.get_array_metadata(vol=slice_vol2,snap=True)
print(x,y)
```
**output**
```
Using MPI version 3.1, 1 processes
-----------
Initializing structure...
Working in 2D dimensions.
Computational cell is 5 x 5 x 0 with resolution 10
time for set_epsilon = 0.0130307 s
-----------
(1.6500000000000001, 1.7500000000000002) (0.0,)
(0.0,) (0.0,)

Elapsed run time = 0.0170 s
```

**Comment by oskooi** [comment]
```py
import meep as mp

resolution = 10

cell_size = mp.Vector3(5,5)

sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size)

sim.init_sim()

slice_vol1 = mp.Volume(center=mp.Vector3(1.651,-1.095), size=mp.Vector3(1e-15))
(x,y,z,w) = sim.get_array_metadata(vol=slice_vol1,snap=True)
print(w,x,y)

slice_vol2 = mp.Volume(center=mp.Vector3(1.651,-1.095), size=mp.Vector3())
(x,y,z,w) = sim.get_array_metadata(vol=slice_vol2,snap=True)
print(w,x,y)
```

```
Using MPI version 3.1, 1 processes
-----------
Initializing structure...
Working in 2D dimensions.
Computational cell is 5 x 5 x 0 with resolution 10
time for set_epsilon = 0.0121522 s
-----------
[1.05471187e-15 1.06577074e-17] (1.6500000000000001, 1.7500000000000002) (0.0,)
1.0 (0.0,) (0.0,)

Elapsed run time = 0.0167 s
```

**Comment by stevengj** [comment]
For DFT slices (which do interpolation), the correct thing is `collapse=True, snap=False`, but for `get_array` slices (which don't do interpolation), the correct thing is `collapse=False, snap=True`.  Since `get_array_metadata` doesn't know what kind of slice you are asking about, it is hard for it to do the right thing.

Ideally, `get_array` will be changed to do interpolation, and collapse empty dimensions, in which case `collapse=True, snap=False` will be the right thing for all slices.

**Comment by stevengj** [comment]
Separately, however, we should fix the `snap=True` output … not sure why it is giving (0,0).
