### ISSUE TITLE
Unable to reproduce Adjoint Meep results

### ISSUE THREAD

**Issue by audupa2** [NanoComp/meep#839]
Hello,

Could you please tell me the exact settings you used to produce this plot:
![HoleyWaveguide_AdjointVsFD](https://user-images.githubusercontent.com/46763276/56762930-b1462480-6766-11e9-816d-f73528875fd1.png)
I tried to run it with the same file given here https://homerreid.github.io/, and I end up getting very different values for df/db0 and df/db0__01__. Sometimes I even get 'nan' for these quantities. Changing the fd_order also seems to be changing df/db0 which it shouldn't because it is the adjoint calculation and not the finite difference calculation. 

Thanks,
Aditi

**Comment by smartalecH** [comment]
Closing as this corresponds to the old version of the adjoint solver.
