### ISSUE TITLE
On cygwin, make meep-1.9.0 got error on mympi.cpp : 576 compiling in src

### ISSUE THREAD

**Issue by genlintan** [NanoComp/meep#848]
On cgywin, I tried make meep-1.9.0, when compiled mympi.cpp in src got yjr error:
 CXX      mympi.lo
mympi.cpp: In function ‘void meep::master_printf(const char*, ...)’:
mympi.cpp:576:7: error: ‘vasprintf’ was not declared in this scope
       vasprintf(&s, fmt, ap);
       ^~~~~~~~~
mympi.cpp:576:7: note: suggested alternative: ‘vasnprintf’
       vasprintf(&s, fmt, ap);
       ^~~~~~~~~
       vasnprintf
make[3]: *** [Makefile:609: mympi.lo] Error 1
make[3]: Leaving directory '/home/Genlin/meep-1.9.0/src'
make[2]: *** [Makefile:455: all] Error 2
make[2]: Leaving directory '/home/Genlin/meep-1.9.0/src'
make[1]: *** [Makefile:504: all-recursive] Error 1
make[1]: Leaving directory '/home/Genlin/meep-1.9.0'
make: *** [Makefile:413: all] Error 2
*************
if change vasprintf to vasnprintf, got the error:
  CXX      mympi.lo
mympi.cpp: In function ‘void meep::master_printf(const char*, ...)’:
mympi.cpp:576:29: error: cannot convert ‘char**’ to ‘char*’ for argument ‘1’ to ‘char* vasnprintf(char*, size_t*, const char*, __gnuc_va_list)’
       vasnprintf(&s, fmt, ap);
                             ^
make[3]: *** [Makefile:609: mympi.lo] Error 1
make[3]: Leaving directory '/home/Genlin/meep-1.9.0/src'
make[2]: *** [Makefile:455: all] Error 2
make[2]: Leaving directory '/home/Genlin/meep-1.9.0/src'
make[1]: *** [Makefile:504: all-recursive] Error 1
make[1]: Leaving directory '/home/Genlin/meep-1.9.0'
make: *** [Makefile:413: all] Error 2
How to fix it?
Thamks

**Comment by ChristopherHogan** [comment]
Try inserting `#define _GNU_SOURCE` at the top of `meep/src/meep/mympi.hpp`.

**Comment by genlintan** [comment]
I inseted #define _GNU_SOURCE at the top of meep/src/meep/mympi.hpp, but got the same error:
  CXX      mympi.lo
mympi.cpp: In function ‘void meep::master_printf(const char*, ...)’:
mympi.cpp:576:7: error: ‘vasprintf’ was not declared in this scope
       vasprintf(&s, fmt, ap);
       ^~~~~~~~~
mympi.cpp:576:7: note: suggested alternative: ‘vasnprintf’
       vasprintf(&s, fmt, ap);
       ^~~~~~~~~
       vasnprintf
make[3]: *** [Makefile:609: mympi.lo] Error 1
make[3]: Leaving directory '/home/Genlin/meep-1.9.0/src'
make[2]: *** [Makefile:455: all] Error 2
make[2]: Leaving directory '/home/Genlin/meep-1.9.0/src'
make[1]: *** [Makefile:504: all-recursive] Error 1
make[1]: Leaving directory '/home/Genlin/meep-1.9.0'
make: *** [Makefile:413: all] Error 2
How to fix it?

**Comment by ChristopherHogan** [comment]
I guess `_GNU_SOURCE` has to be defined before including `stdio.h`, so you should put the `#define` at the beginning of `meep.hpp`, before the `#include <stdio.h>` line.

**Comment by genlintan** [comment]
Yes, I put _GNU_SOURCE before include, as follows:
#ifndef MEEP_MY_MPI_H
#define MEEP_MY_MPI_H
#define _GNU_SOURCE

#include <complex>
#include <stddef.h>

namespace meep {

**Comment by genlintan** [comment]
#ifndef MEEP_MY_MPI_H
#define MEEP_MY_MPI_H
#define _GNU_SOURCE

#include <complex>
#include <stddef.h>

**Comment by ChristopherHogan** [comment]
Please reread my comment carefully:

> so you should put the #define at the beginning of meep.hpp, before the #include <stdio.h> line.

**Comment by genlintan** [comment]
In fact, mympi.hpp only has two include statements:
#include <complex>
#include <stddef.h>
no #include <stdio.h>
Do I need to put  #define _GNU_SOURCE between two include atatements?

**Comment by ChristopherHogan** [comment]
I said `meep.hpp`, not `mympi.hpp`.

**Comment by genlintan** [comment]
I just put #define _GNU_SOURCE before #include <stddef.h> line, re-make and got the same error.

**Comment by genlintan** [comment]
on meep/src/meep, there are only two ,hpp files mympi.hpp and vec.hpp.
no meep.hpp

**Comment by ChristopherHogan** [comment]
I said to put it before the `<stdio.h>` include, not the `<stddef.h>` include. 

The first several lines of `meep.hpp` look like this:
```cpp
#ifndef MEEP_H
#define MEEP_H

#include <stdio.h>
#include <stddef.h>
#include <math.h>

#include "meep/vec.hpp"
#include "meep/mympi.hpp"

#include <vector>

namespace meep {

```
You should changed them to look like this:
```cpp
#ifndef MEEP_H
#define MEEP_H
#define _GNU_SOURCE
#include <stdio.h>
#include <stddef.h>
#include <math.h>

#include "meep/vec.hpp"
#include "meep/mympi.hpp"

#include <vector>

namespace meep {

```

**Comment by ChristopherHogan** [comment]
`meep.hpp` is at `meep/src/meep.hpp`.

**Comment by genlintan** [comment]
meep.hpp in meep/src dir, I put #define _GNU_SOURCE before #include <stdio.h>, and re make, got the same error.

**Comment by ChristopherHogan** [comment]
In that case, I'm sorry, but I can't help you.

**Comment by stevengj** [comment]
Closing since Cygwin is not a supported environment.

**Comment by lxuechao** [comment]
请问您解决了吗？
