### ISSUE TITLE
displaying the progress status and total time of near2far calculations in output

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#849]
In certain situations involving a large number of far-field points, the [`near2far`](https://meep.readthedocs.io/en/latest/Python_User_Interface/#near-to-far-field-spectra) routines `get_farfields` and `output_farfields` can comprise the majority of the wall-clock time (e.g., the tutorial example in #845). Currently, the progress status of the `near2far` calculation is *not* included in the output. Unlike the progress status for the time-stepping (i.e., `on time step 4467 (time=55.8375), 0.0549067 s/step`) which provides an approximate insight into its expected completion, no such information is available for `near2far` calculations. In fact, there is *no* mention at all in the output that the far-fields are being computed. It would be useful to include some indication of the `near2far` progress in the output. This information could also facilitate with debugging to improve performance.

**Comment by stevengj** [comment]
i.e. we'd add something like https://github.com/NanoComp/meep/blob/a06587cf4bd633ce9e8febe8171d711fa7f71bbb/src/step.cpp#L43-L54 on every call to `farfield_lowlevel` [here](https://github.com/NanoComp/meep/blob/master/src/near2far.cpp#L323)

**Comment by stevengj** [comment]
One thing we might think about is having a callback function for progress instead of a hard-coded printf.    That is, you would call something like `progress_update(label_string, fraction)` and it would default to a printf.

This would allow us to potentially call something like the [progressbar2](https://pypi.org/project/progressbar2/) package in Python (or [tqdm](https://github.com/tqdm/tqdm) or similar).

**Comment by oskooi** [comment]
The total time spent computing the far fields during the call to `get_farfields` or `output_farfields` is also missing from the "Field time usage" statistics info appearing at the end of the time stepping when `Simulation.run` has completed.

For example, [python/examples/binary_grating_n2f.py](https://github.com/NanoComp/meep/blob/master/python/examples/binary_grating_n2f.py) has three separate calls to `run` and `get_farfields` but the near-to-far field transformation portion of the runtime (which comprises the majority) is not included in any of its three output statistics. This is the output from the final run:
```
Field time usage:
        connecting chunks: 0.0613327 s
            time stepping: 37.194 s
            communicating: 1.59942 s
     Fourier transforming: 8.40363 s
          everything else: 0.60348 s
```
