### ISSUE TITLE
Feature request: simulation timeout run function

### ISSUE THREAD

**Issue by smartalecH** [NanoComp/meep#850]
It would be nice to incorporate a `run` function that stops the simulation after a specified time interval (actual time, not MEEP time) has passed. 

This would be especially useful for jobs that are submitted to clusters with designated walltimes. The user could pass the walltime to the MEEP solver so that any progress could be saved before the job scheduler kills the job.

I'm thinking of something similar to the `opt.set_maxtime(maxtime)` within [nlopt's](https://meep.readthedocs.io/en/latest/Python_User_Interface/#run-functions) API.

**Comment by stevengj** [comment]
It would certainly be possible to have a `stop_after_walltime(t)` function that you could pass to `run`.  (You could even write such a run function yourself — it doesn't require any Meep internals.)

Another possibility is to have a `stop_on_interrupt` function that you can pass to `run`, which will catch SIGTERM or SIGINT (ctrl-c) and stop the simulation, executing any code that you have following the `run` (e.g. code to output fields or whatever).
