### ISSUE TITLE
find_k only stores single eigenmode field info

### ISSUE THREAD

**Issue by smartalecH** [NanoComp/meep#851]
It seems that the `find_k` function only records the first eigenmode's field into the ModeSolver object, even when it solves for multiple bands. Consequently, functions like `ModeSolver.get_efield()` can't access the different bands (or modes).

When trying to access multiple modes after a simulation, it throws the warning:
`Must have 1 <= band index <= num_bands (1)`

Here's a MWE:
```python
import meep as mp
from meep import mpb
import numpy as np
from matplotlib import pyplot as plt


Si   = mp.Medium(index=3.45)
SiO2 = mp.Medium(index=1.45)
wavelength = 1.55
omega      = 1/wavelength
w = 1    # Si width (um)
h = 0.5  # Si height (um)
geometry = [mp.Block(size=mp.Vector3(mp.inf, w, h), material=Si)]
resolution = 32  # pixels/um
sc_y = 2  # supercell width (um)
sc_z = 2  # supercell height (um)
geometry_lattice = mp.Lattice(size=mp.Vector3(0, sc_y, sc_z))

num_modes = 4
# Setup a simulation object
ms = mpb.ModeSolver(
    geometry_lattice = geometry_lattice,
    geometry         = geometry,
    resolution       = resolution,
    num_bands        = num_modes
)

# ------------------------------------------------- #
# Solve for all the modes at once, then plot
# ------------------------------------------------- #

k = ms.find_k(
    p              = mp.EVEN_Z,
    omega          = omega,
    band_min       = 1,
    band_max       = num_modes,
    korig_and_kdir = mp.Vector3(1,0,0),
    tol            = 1e-4,
    kmag_guess     = omega * 3.45,
    kmag_min       = omega * 0.1,
    kmag_max       = omega * 4
)
print(wavelength * np.array(k))
eps = ms.get_epsilon()
plt.figure(figsize=(8,4))
# Plot the E fields
for mode in range(num_modes):
    print('Current band: {}'.format(mode+1))
    E   = ms.get_efield(which_band=mode+1,bloch_phase=False)
    plt.subplot(1,num_modes,mode+1)
    plt.imshow(eps.transpose(), interpolation='spline36', cmap='binary')
    plt.imshow(np.abs(np.squeeze(E[:,:,0,1]).transpose())**2, cmap='RdBu', alpha=0.9)
    plt.axis('off')
    plt.title('$E_{{y{}}}$'.format(mode))
plt.tight_layout()
plt.savefig('errorFields.png')

# ------------------------------------------------- #
# Solve for all the modes one by one
# ------------------------------------------------- #

plt.figure(figsize=(8,4))
for mode in range(num_modes):
    k = ms.find_k(
        p              = mp.EVEN_Z,
        omega          = omega,
        band_min       = mode+1,
        band_max       = mode+1,
        korig_and_kdir = mp.Vector3(1,0,0),
        tol            = 1e-4,
        kmag_guess     = omega * 3.45,
        kmag_min       = omega * 0.1,
        kmag_max       = omega * 4
    )
    E   = ms.get_efield(which_band=mode+1,bloch_phase=False)
    plt.subplot(1,num_modes,mode+1)
    plt.imshow(eps.transpose(), interpolation='spline36', cmap='binary')
    plt.imshow(np.abs(np.squeeze(E[:,:,0,1]).transpose())**2, cmap='RdBu', alpha=0.9)
    plt.axis('off')
    plt.title('$E_{{y{}}}$'.format(mode))
plt.tight_layout()
plt.savefig('correctFields.png')

plt.show()
```

The problematic routine simply routines the fundamental mode after each call:

![errorFields](https://user-images.githubusercontent.com/24902086/57091321-244f1e00-6cc6-11e9-934b-dd59335af00e.png)

I can get the correct field profile if I iterate through the solver mode by mode (and only solve for that particular band):

![correctFields](https://user-images.githubusercontent.com/24902086/57091366-3fba2900-6cc6-11e9-94ec-e410bd364eed.png)

Hopefully this is just a small tweak in the python interface. I can look into it.

**Comment by stevengj** [comment]
In Scheme, you pass band functions to `find-k` that are called after each band is computed.  You can't wait until after all the bands are computed because they are computed at different k's.  It looks like you can do the same thing [in Python](https://github.com/NanoComp/meep/blob/master/python/solver.py#L978-L979).

You can't wait until after `find_k` runs because the different bands are solved for independently, and one is discarded when the next is computed at a different k.

There's not much advantage in passing a range of bands to `find_k`, since they are computed separately anyway.  I wonder if we should just change the API to take a single band instead of a range — you can always use a loop to compute multiple bands, as in your code above.

**Comment by stevengj** [comment]
Oh, actually there is a benefit in computing the bands together, because it caches a table of the (k,ω) found for each band as it computes the others.

**Comment by stevengj** [comment]
So, in your code above, I would say that you should really be doing your `ms.get_efield` as a band function passed to `find_k` so that you grab the fields when they are computed.

**Comment by smartalecH** [comment]
I can pass the `output_hfield()` or `output_efield()` band functions, and they store the field profiles in an h5 file. Is there a more elegant band function for caching the profiles in memory, and then pulling them after `find_k()` runs using the same 
```python
E   = ms.get_efield(which_band=mode+1,bloch_phase=False)
```

as before?

**Comment by stevengj** [comment]
Can't you write a band function that grabs the fields as a numpy array and stores it somewhere?

**Comment by smartalecH** [comment]
I tried implementing a band function like so:

```python
E = []
store_fields = lambda ms_temp, mode: E.append(ms_temp.get_efield(which_band=mode,bloch_phase=False))
```

and subsequently passed it to `find_k`. Interestingly, It computes all of the bands in _reverse_ order:

![errorFields](https://user-images.githubusercontent.com/24902086/61391936-0b90e600-a87b-11e9-8a3f-aad180768069.png)

when it should be:

![correctFields](https://user-images.githubusercontent.com/24902086/61391956-12b7f400-a87b-11e9-8d75-ccf261de37c3.png)

Note that the 4th mode profile is also off.

The code obviously agrees with this observation. It also shows that the `band_funcs` are computed _after_ all of the modes are calculated. Is there a reason for this?

https://github.com/NanoComp/meep/blob/e9251c32bef33eee05994872b07803b159e9f8b6/python/solver.py#L1038-L1052

**Comment by stevengj** [comment]
It is important to run the root-finding on the bands in reverse order, because that way while it is computing a higher band it is able to cache results for the lower bands and use them to accelerate subsequent calculations.

Once that is done, however, we can call the `band_funcs` in whatever order we want, so I think it would be fine to change it to call them for the bands in increasing order.

**Comment by smartalecH** [comment]
After #968, the example works just as expected:

```python
import meep as mp
from meep import mpb
import numpy as np
from matplotlib import pyplot as plt


Si   = mp.Medium(index=3.45)
SiO2 = mp.Medium(index=1.45)
wavelength = 1.55
omega      = 1/wavelength
w = 1    # Si width (um)
h = 0.5  # Si height (um)
geometry = [mp.Block(size=mp.Vector3(mp.inf, w, h), material=Si)]
resolution = 32  # pixels/um
sc_y = 2  # supercell width (um)
sc_z = 2  # supercell height (um)
geometry_lattice = mp.Lattice(size=mp.Vector3(0, sc_y, sc_z))

num_modes = 4
# Setup a simulation object
ms = mpb.ModeSolver(
    geometry_lattice = geometry_lattice,
    geometry         = geometry,
    resolution       = resolution,
    num_bands        = num_modes
)

# ------------------------------------------------- #
# Solve for all the modes at once, then plot
# ------------------------------------------------- #
E = []
store_fields = lambda ms_temp, mode: E.append(ms_temp.get_efield(which_band=mode,bloch_phase=False))    

k = ms.find_k(
    mp.EVEN_Z, # p
    omega, # omega
    1, # band_min
    num_modes, # band_max
    mp.Vector3(1,0,0), # korig_and_kdir
    1e-4, # tol
    omega * 3.45, # kmag_guess
    omega * 0.1, # kmag_min
    omega * 4, # kmag_max
    store_fields # band_funcs
)

eps = ms.get_epsilon()
plt.figure(figsize=(8,4))
# Plot the E fields
for mode in range(num_modes):
    print('Current band: {}'.format(mode+1))
    plt.subplot(1,num_modes,mode+1)
    plt.imshow(eps.transpose(), interpolation='spline36', cmap='binary')
    plt.imshow(np.abs(np.squeeze(E[mode][:,:,0,1]).transpose())**2, cmap='RdBu', alpha=0.9)
    plt.axis('off')
    plt.title('$E_{{y{}}}$'.format(mode))
plt.tight_layout()
plt.savefig('errorFields.png')

# ------------------------------------------------- #
# Solve for all the modes one by one
# ------------------------------------------------- #

plt.figure(figsize=(8,4))
for mode in range(num_modes):
    k = ms.find_k(
        p              = mp.EVEN_Z,
        omega          = omega,
        band_min       = mode+1,
        band_max       = mode+1,
        korig_and_kdir = mp.Vector3(1,0,0),
        tol            = 1e-4,
        kmag_guess     = omega * 3.45,
        kmag_min       = omega * 0.1,
        kmag_max       = omega * 4
    )
    E   = ms.get_efield(which_band=mode+1,bloch_phase=False)
    plt.subplot(1,num_modes,mode+1)
    plt.imshow(eps.transpose(), interpolation='spline36', cmap='binary')
    plt.imshow(np.abs(np.squeeze(E[:,:,0,1]).transpose())**2, cmap='RdBu', alpha=0.9)
    plt.axis('off')
    plt.title('$E_{{y{}}}$'.format(mode))
plt.tight_layout()
plt.savefig('correctFields.png')

plt.show()
```

Using band functions:

![errorFields](https://user-images.githubusercontent.com/24902086/61414536-73f7bb80-a8ab-11e9-9f42-aa3d3a3bad2d.png)

Manually iterating:

![correctFields](https://user-images.githubusercontent.com/24902086/61414556-7d812380-a8ab-11e9-9917-f69c51d0a704.png)

They agree!
