### ISSUE TITLE
module 'meep' has no attribute 'output_dft'

### ISSUE THREAD

**Issue by qngu** [NanoComp/meep#852]
All of the output functions under
https://meep.readthedocs.io/en/latest/Python_User_Interface/#predefined-step-functions
can be called as mp.output_* except for output_dft, which returns the error "module 'meep' has no attribute 'output_dft'" when you try to call mp.output_dft(...).

**Comment by ChristopherHogan** [comment]
`output_dft` is a method of the `Simulation` class. Fixed in #853.
