### ISSUE TITLE
Installation error in centos 7.4/7.5 (module 'meep' has no attribute 'Vetcor3'  )

### ISSUE THREAD

**Issue by houge9089** [NanoComp/meep#884]
I have installed meep in centos 7.4/7.5 using installation script on Centos7 as follow: https://meep.readthedocs.io/en/latest/Build_From_Source/

The error reports are as follows:
```
Libraries have been installed in:
   /usr/local/lib/python3.6/site-packages/meep

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /usr/bin/mkdir -p '/usr/local/lib/python3.6/site-packages/meep/adjoint'
 /usr/bin/install -c -m 644 ./adjoint/__init__.py ./adjoint/Basis.py ./adjoint/Objective.py ./adjoint/OptimizationProblem.py ./adjoint/ParallelDesignTester.py ./adjoint/Visualization.py '/usr/local/lib/python3.6/site-packages/meep/adjoint'
../py-compile: line 118: python3: command not found
make[3]: *** [install-adjointPYTHON] Error 127
make[3]: Leaving directory `/root/install/meep/python'
make[2]: *** [install-am] Error 2
make[2]: Leaving directory `/root/install/meep/python'
make[1]: *** [install] Error 2
make[1]: Leaving directory `/root/install/meep/python'
make: *** [install-recursive] Error 1
[root@iZbp13vvxm0y2qcbnp2n4qZ ~]# python3
Python 3.6.5 (default, May 17 2019, 09:29:38) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import meep
>>> x=meep.Vetcor3(2,2,2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'meep' has no attribute 'Vetcor3'  
```
The other attributes are in the same status.

**Comment by ChristopherHogan** [comment]
Vector3 is spelled as "Vetcor3"  in the snippet above. It looks like `meep` imported successfully though. Can you try with the correct spelling?

**Comment by emma-branigan** [comment]
Hi Christopher, I've just installed meep on Windows through WSL (following the Conda packages tutorial [here](https://meep.readthedocs.io/en/latest/Installation/#conda-packages)) and am seeing the same issue when I try to run the first tutorial. I've attempted to setup an environment for running meep on my machine. I've attached a snippet of what I'm seeing when I try to search for my meep module (in case I've installed it in the wrong place!) 
<img width="608" alt="meep" src="https://user-images.githubusercontent.com/29775585/58170090-6bf41480-7c8a-11e9-8f23-7c89b527eed5.PNG">

Thanks!
Emma

**Comment by ChristopherHogan** [comment]
Hi Emma. I've just tried the following commands on Windows (Ubuntu 18.04 through WSL) and everything is working correctly.
```bash
$ conda create -n mp -c conda-forge pymeep
$ source activate mp
$ git clone https://github.com/NanoComp/meep.git
$ cd meep/python/examples
$ python straight-waveguide.py
```
Can you detail the steps you took so I can reproduce the error?

**Comment by emma-branigan** [comment]
Hi Christopher, thanks for taking a look at that for me. In the mean time I actually started fresh with a new miniconda installation and I can run this fine from the command line now. (I was originally trying to run it in Jupyter notebook, however I'm having some trouble with permissions getting the notebook to open now so I can't check that the error is being reproduced). Thanks!

**Comment by houge9089** [comment]
Thanks! I've changed the installation script as follows:

cd ~/install
wget https://ftp.gnu.org/gnu/guile/guile-2.2.4.tar.gz
tar xvf guile-2.2.4.tar.gz
cd guile-2.2.4
./configure
make 
sudo make  install

cd ~/install
wget https://github.com/h5py/h5py/archive/2.8.0.tar.gz
tar xvf 2.8.0.tar.gz
cd h5py-2.8.0/
python3 setup.py configure --mpi
python3 setup.py build
sudo /usr/local/bin/python3 setup.py install

cd ~/install
git clone https://github.com/NanoComp/meep.git
cd meep/
sh autogen.sh --enable-shared --with-mpi PYTHON=python3 MPICC=/usr/local/bin/mpicc MPICXX=/usr/local/bin/mpic++ LDFLAGS="${MY_LDFLAGS}" CPPFLAGS="${MY_CPPFLAGS}"
make -j
make install

**Comment by stevengj** [comment]
Sounds like the original problem here is fixed.
