### ISSUE TITLE
time-varying permitivity

### ISSUE THREAD

**Issue by arezoozarif** [NanoComp/meep#895]
I wanted to know if in Meep software, one can simulate photonic structures with time-varying permitivity, as in the other FDTD simulators like LUMERICAL there is not such a feature. Since this subject has become so popular recently, If the feature of having time-varying permitivity can be developed in the software it'll become so useful and more convenient than writing FDTD code.

**Comment by oskooi** [comment]
See this [FAQ](https://meep.readthedocs.io/en/latest/FAQ/#can-meep-simulate-time-varying-structures) as well as #207.
