### ISSUE TITLE
Derived tensor from MPB doesn't match expected results

### ISSUE THREAD

**Issue by smartalecH** [NanoComp/meep#933]
If I define an anisotropic material, I should be able to pull the corresponding tensor using MPB. For example, I should be able to use the `get_eigenmode()` routine to pull the different k vectors and build the tensor with the simulated `omega`:

```python
import meep as mp
import numpy as np

omega = 1


FR = mp.FreqRange
FR.min = 0.5
FR.max = 1.5
material = mp.Medium(epsilon_diag=mp.Vector3(2**2,3**2,4**2),valid_freq_range=FR)


sim = mp.Simulation(cell_size=mp.Vector3(2,2,2),
                            default_material=material,
                            resolution=50
                            )

band_num = 1
sim.init_sim()

# Pull the x direction
direction = mp.X
where = mp.Volume(center=mp.Vector3(0,0,0),size=mp.Vector3(0,0,0))
kpoint = mp.Vector3(1,0,0)
emx = sim.get_eigenmode(omega,direction,where,band_num,kpoint)

# Pull the y direction
direction = mp.Y
where = mp.Volume(center=mp.Vector3(0,0,0),size=mp.Vector3(0,0,0))
kpoint = mp.Vector3(0,1,0)
emy = sim.get_eigenmode(omega,direction,where,band_num,kpoint)

# Pull the z direction
direction = mp.Z
where = mp.Volume(center=mp.Vector3(0,0,0),size=mp.Vector3(0,0,0))
kpoint = mp.Vector3(0,0,1)
emz = sim.get_eigenmode(omega,direction,where,band_num,kpoint)

# combine and return
k = np.array(mp.Matrix(emx.k,emy.k,emz.k))
neff_meep = np.squeeze(k) / omega

n = np.real(np.sqrt(material.epsilon(omega).astype(np.complex128)))

#np.testing.assert_allclose(n,neff_meep)
print("Meeps solution:")
print(neff_meep)
print("Correct Solution")
print(n)
```

Unfortunately, the results don't match:

```
Meeps solution:
[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 3.]]
Correct Solution
[[2. 0. 0.]
 [0. 3. 0.]
 [0. 0. 4.]]
```

Any ideas?

**Comment by stevengj** [comment]
Meep's solution looks correct … I think you are misunderstanding the math for transverse waves here.

For example, if you are propagating along the x direction, then there are two linearly-polarized planewave solutions: one polarized along y (index of 3) and one polarized along z (index of 4).  You are computing the first band = lowest frequency = largest effective index.  So Meep correctly gives you the z-polarized planewave, with an index of 4.

Your "correct" solution for propagating along the x direction is an index of 2 — I guess you are thinking about longitudinal waves?

**Comment by smartalecH** [comment]
Yup, you're right -- I was thinking about longitudinal waves.
