### ISSUE TITLE
Jupyter Diff

### ISSUE THREAD

**Issue by smartalecH** [NanoComp/meep#936]
As we start to revamp the Jupyter notebooks, we may want to use a better diff visualization tool. The JSON version control is pretty opaque and practically impossible to use in this context.

Here's a good GitHub app that I know several people use to better visualize their Jupyter notebook changes across PRs (free for open source projects):

https://www.reviewnb.com/

**Comment by stevengj** [comment]
Should be installed now?  e.g. https://app.reviewnb.com/NanoComp/meep/commit/bf7aff44d22c96c62d72ac0a0814cc4d405b2340/
