### ISSUE TITLE
What is the minimum GUILE version required by meep/1.10.0

### ISSUE THREAD

**Issue by einzigsue** [NanoComp/meep#948]
What is the minimum GUILE version required by meep/1.10.0

Hi All,

When compile from source, the make stopped at the error 
"""
gen-ctl-io --cxx --header -o ctl-io.h meep.scm /apps/libctl/4.3.0/share/libctl
ERROR: Unbound variable: define*
"""
in the directory ./scheme/. It seems like this line in meep.scm 
"""
$ grep "define\*" meep.scm
(define* (add-near2far fcen df nfreq #:key (nperiods 1) . near2fars)
"""
disappointed the make process.

Does it mean my system GUILE is too old? It is 1.8.7 on a old cluster running CentOS 6.10.

Cheers
Yue

**Comment by stevengj** [comment]
You're write that this code requires Guile 2.

A workaround would be to add:
```scm
(if (< (string->number (major-version)) 2)
    (use-modules (ice-9 optargs)))
```
at the top of `meep.scm` … does that fix the problem for you?  If that is the only fix to make things work for Guile 1.8 again, we can incorporate it.

Alternatively, you can `./configure --without-scheme` to build only the Python interface and omit the Scheme interface.

**Comment by einzigsue** [comment]
Hi Steve,
Thank you for the prompt reply. It nails down the cause of the problem and fix it immediately. But another one comes up in creating the python interface at the step
"""
  CXX      _meep_la-meep-python.lo
"""
The error message says 
"""
meep-python.cxx(97925): error: identifier "maxwell_data" is undefined
    maxwell_data *arg2 = (maxwell_data *) 0 ;
    ^
"""
I think it is about missing a line
"""
#include "mpb_mpi.h" 
"""
in the file python/meep-python.cxx for MPB built with MPI enabled as there is no file called mpb.h in the installation folder of MPB if it is built with the option `--with-mpi`. There is only the header file mpb_mpi.h which in turn includes the header file mpb/maxwell.h in which the data type maxwell_data is defined. 

However, when I replaced the line 3258 and 3259 in python/meep-python.cxx simply with
"""
#ifdef HAVE_MPB
#include "mpb_mpi.h"
""" 
it failed at the same point with the same error. I then realised that HAVE_MPB is not defiled in the config.h file and it is most likely triggered by the same missing mpi.h in MPB's installation folder. Is it the line 24093 in the file configure
"""
ac_fn_cxx_check_header_mongrel "$LINENO" "mpb.h" "ac_cv_header_mpb_h" "$ac_includes_default"
""" 
need to consider mpb_mpi.h as well?

I am pretty sure I have included the MPB installation folder both into the LIBRARY and INCLUDE paths.
"""
$ env | grep "LIBRARY\|INCLUDE"
CPLUS_INCLUDE_PATH=/apps/gdsii/0.21/include:**/apps/mpb/1.9.0/include**:/apps/harminv/1.4.1/include:/apps/libctl/4.3.0/include:/apps/python3/3.6.7/lib/python3.6/site-packages/numpy/core/include:/apps/python3/3.6.7/include/python3.6m:/apps/hdf5/1.10.2p/include:/apps/openmpi/3.0.1/include:/apps/gsl/2.5/include:/apps/fftw3/3.3.7/include:/apps/intel-ct/2018.2.199/mkl/include
LIBRARY_PATH=/apps/gdsii/0.21/lib:**/apps/mpb/1.9.0/lib**:/apps/harminv/1.4.1/lib:/apps/libctl/4.3.0/lib:/apps/python3/3.6.7/lib:/apps/hdf5/1.10.2p/lib:/apps/openmpi/3.0.1/lib:/apps/openmpi/3.0.1/lib/profilers:/apps/gsl/2.5/lib:/apps/fftw3/3.3.7/lib:/apps/intel-ct/2018.2.199/mkl/lib/intel64:/apps/intel-ct/2018.2.199/fc/../common/lib:/apps/intel-ct/2018.2.199/cc/../common/lib
LD_LIBRARY_PATH=/apps/gdsii/0.21/lib:**/apps/mpb/1.9.0/lib**:/apps/harminv/1.4.1/lib:/apps/libctl/4.3.0/lib:/apps/python3/3.6.7/lib:/apps/hdf5/1.10.2p/lib:/apps/openmpi/3.0.1/lib:/apps/openmpi/3.0.1/lib/profilers:/apps/gsl/2.5/lib:/apps/fftw3/3.3.7/lib:/apps/intel-ct/2018.2.199/mkl/lib/intel64:/apps/intel-ct/2018.2.199/fc/../common/lib:/apps/intel-ct/2018.2.199/cc/../common/lib:/apps/ffmpeg/4.1.3/lib
C_INCLUDE_PATH=/apps/gdsii/0.21/include:**/apps/mpb/1.9.0/include**:/apps/harminv/1.4.1/include:/apps/libctl/4.3.0/include:/apps/python3/3.6.7/lib/python3.6/site-packages/numpy/core/include:/apps/python3/3.6.7/include/python3.6m:/apps/hdf5/1.10.2p/include:/apps/openmpi/3.0.1/include:/apps/gsl/2.5/include:/apps/fftw3/3.3.7/include:/apps/intel-ct/2018.2.199/mkl/include
"""
 
Should I open another issue for it?

Cheers
Yue

**Comment by stevengj** [comment]
Meep needs the serial version of MPB.  You can't use mpb-mpi.
