### ISSUE TITLE
Account for anisotropic pixels on interfaces in fragment stats

### ISSUE THREAD

**Issue by ChristopherHogan** [NanoComp/meep#959]
> Moreover, right now our fragment statistics don't take into account the fact that anisotropic pixels are created everywhere you have interfaces. To handle this, if any object interface intercepts a fragment box, the entire box should be treated as anisotropic. -Steven

@stevengj, can you elaborate on this?
1. What do you mean by "object interface?"
2. To "treat a box as anisotropic", I assume I would do something like:
```
if (object interface intercepts)
  num_anisotropic_eps_pixels += num_pixels_in_box
  if (has_mu)
    num_anisotropic_mu_pixels += num_pixels_in_box
```

**Comment by stevengj** [comment]
(1.) I mean the surface of any geometric object.  i.e. does the surface of a sphere, cylinder, etcetera intersect the box?

(2.) yes.
